Azure Security Center - Adaptive Application Control - Rename 'whitelist'
Azure/azure-rest-api-specs pull request #10100
Opened 2020-07-12 12:27 UTC by erelh

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

2020-07-12 12:27 UTC, AutorestCI commented
You don't have permission to trigger SDK Automation.
Please add yourself to ***Azure*** group from opensource portal if you are MSFT employee,
or please ask reviewer to add comment *** /openapibot sdkautomation ***.
Please ask tih@microsoft.com (or NullMDR in github) for additional help.

2020-07-12 12:27 UTC, erelh commented
Hi,
We renamed some of the descriptions & models that had the word "whitelist".
That is why there's a breaking change - some of the models were renamed.

2020-07-12 12:40 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-07-14 05:34 UTC, erelh commented
@markcowl ?

2020-07-15 05:37 UTC, erelh commented
@ChenTanyi @xccc-msft @raych1 @tjprescott @MyronFanQiu can somebody please review ? note that tests fail (only) on "breaking change" because some of the internal models were renamed (no API change)

2020-07-17 02:35 UTC, markcowl requested changes

2020-07-17 02:35 UTC, markcowl commented on specification/security/resource-manager/Microsoft.Security/stable/2020-01-01/applicationWhitelistings.json
> +    "AdaptiveApplicationControlIssue": {
These name changes in your schemas will create breaking changes in all generated SDKs.  Please revert.

2020-07-17 16:44 UTC, markcowl commented
@azuresdkci test this please

2020-07-17 16:45 UTC, markcowl commented
@azuresdkci add to whtelist

2020-07-17 16:46 UTC, markcowl commented
@azuresdkci *** /openapibot sdkautomation ***

2020-07-17 16:46 UTC, markcowl commented
/openapibot sdkautomation

2020-07-17 16:47 UTC, AutorestCI commented
/azp run automation - sdk

2020-07-17 16:47 UTC, AutorestCI commented
/azp run automation - sdk

2020-07-17 16:47 UTC, AutorestCI commented
/azp run automation - sdk

2020-07-17 16:48 UTC, markcowl approved these changes
After discussion, the breaking changes are desirable to remove an offensive term.

2020-07-17 20:53 UTC, merged