Mofnmodel
Azure/azure-rest-api-specs pull request #10195
Opened 2020-07-17 23:37 UTC by vasanthrajams

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

2020-07-17 23:38 UTC, AutorestCI commented
/azp run automation - sdk

2020-07-18 00:01 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-07-23 00:02 UTC, AutorestCI commented
/azp run automation - sdk

2020-07-23 00:22 UTC, AutorestCI commented
/azp run automation - sdk

2020-07-23 22:23 UTC, heaths approved these changes

2020-07-23 22:23 UTC, heaths commented on specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/securitydomain.json
> +    "MofNCertificateInfoObject": {
If we ever did generate a model, we don't use abbreviations in class names. You could either rename this to something more human readable, or leave the model name, but add an `x-ms-client-name`: https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-client-name

2020-07-23 22:23 UTC, heaths commented on specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/securitydomain.json
> +        "Certificates": {
Property names are generally camelCase.

2020-07-23 22:23 UTC, heaths commented on specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/securitydomain.json
> +          "description": "Security domain"
You should add `"format": "base64"` (or "base64url" for consistency with rest of KV, but either is fine) to clients know how to encode the data, if this is indeed the encoded data we discussed in our meeting.

2020-07-30 02:36 UTC, AutorestCI commented
/azp run automation - sdk

2020-07-31 01:04 UTC, AutorestCI commented
/azp run automation - sdk

2020-07-31 01:20 UTC, AutorestCI commented
/azp run automation - sdk

2020-07-31 02:01 UTC, AutorestCI commented
/azp run automation - sdk

2020-07-31 02:14 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-07 20:51 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-08 04:59 UTC, heaths approved these changes

2020-08-27 20:00 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-27 20:05 UTC, dcleblanc reviewed
There would never be 2 pstore elements, there would be one pstore, and one for the partition backup.

2020-08-27 20:09 UTC, amitbapat requested changes
Please include min and max limits in the description, so that auto-generated REST API doc looks good.

2020-08-27 20:09 UTC, amitbapat commented on specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/securitydomain.json
> +            "description": "Security domain download operation requires customer to provide N certificates containing public key in JWK format."
Please specify minimum and maximum values of N - minimum 3, maximum 10.

2020-08-27 20:09 UTC, amitbapat commented on specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/securitydomain.json
> +                  "description": "Number of keys required for security domain"
Please specify minimum and maximum values - minimum 2, maximum 10.

2020-08-27 20:09 UTC, amitbapat commented on specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/securitydomain.json
> +          "description": "Customer to specify the quorum number of certificates to restore security domain",
Add min and max values to description. Min=2, Max=10.

2020-08-28 03:13 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-28 03:23 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-28 03:25 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-28 18:02 UTC, dcleblanc reviewed
This sample is incorrect, not the same as the actual JSON

2020-08-29 01:18 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-29 01:21 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-29 01:48 UTC, dcleblanc approved these changes

2020-08-31 18:41 UTC, anuchandy approved these changes

2020-08-31 18:51 UTC, heaths approved these changes

2020-08-31 18:51 UTC, heaths commented on specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/securitydomain.json
> +          "description": "Specifies the format of the transfer key"
Should this be an enum, even if a value of only "jwk"? How do the customers know what to put here (especially as newer versions maybe support newer formats), or was this part of the opaque data that they shouldn't neeed to know about?

2020-08-31 18:51 UTC, heaths commented on specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/securitydomain.json
> +                  "description": "The number of keys (minimum 2 and maximum 10) required for security domain. "
Wasn't the minimum 3 as mentioned above? Or is that different in this case (in which case, shouldn't the maximum be 9 then)?

2020-09-01 17:32 UTC, merged