[Checklist] Add an example for M1000
Azure/azure-rest-api-specs pull request #1029
Opened 2017-03-13 22:06 UTC by RobDolinMS

Adds an example
Links to the original file
NOTE: Removes the "tags": ["Profiles"], object from the original JSON without "..." for readability in the checklist

Signed-off-by: Rob Dolin <robdolin@microsoft.com>

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [ ] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

2017-03-13 22:06 UTC, msftclas commented
@RobDolinMS,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-03-14 01:29 UTC, veronicagg approved these changes

2017-03-16 00:00 UTC, salameer requested changes
Hi Rob,

This looks good, however the team is currently working at more rules and the ARM has recently added more rules. my concerns here is if we dont find a way to have this collapsible then the checklist would become humongous .

Also I think we need to show what's a "Bad example" to give the full picture :)

2017-03-16 00:20 UTC, RobDolinMS commented
Thanks @salameer.  I'll look into how to do collapsing.

2017-04-03 22:32 UTC, salameer commented
@kirthik  and @RobDolinMS 

I think we might wanna hold on on this until we have all the content available in the Checklist thoguhts?

2017-04-03 22:34 UTC, RobDolinMS commented
>I [@salameer] think we might wanna hold on on this until we have all the content available in the Checklist thoguhts?

@salameer Would you please clarify what you mean by "all the content?"

2017-04-04 18:24 UTC, salameer commented
HI @RobDolinMS 

I was  reffering to the rest of the rules that are currently not  documented or listed into the checklist

2017-04-11 21:04 UTC, kirthik commented on documentation/swagger-checklist.md
> +    "/subscriptions/{subscriptionId}/providers/Microsoft.Cdn/profiles": {
@RobDolinMS : Example here does not point to plural names. Am i confused here? Could you please point me to the parameters/model properties which are collections?

2017-04-13 22:21 UTC, RobDolinMS commented
Closing this as I understand the checklist format is getting a big update soon.

2017-04-13 22:21 UTC, closed without merging