[Hub Generated] Review request for Microsoft.AppPlatform to add version stable/2020-07-01
Azure/azure-rest-api-specs pull request #10320
Opened 2020-08-02 15:54 UTC by bowen5

This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/bowen5/azure-rest-api-specs/dev-appplatform-Microsoft.AppPlatform-2020-07-01...master/).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for AME onboarding.
- [ ] [Validation tools](https://aka.ms/swaggertools) have been run on swagger spec(s) updated and errors have all been fixed with this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, [please view the FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories.
*	adding/removing APIs.
* adding/removing properties.
* adding/removing API-version.
* adding a new service in Azure.

*Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.*

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them.

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

2020-08-02 15:54 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-02 16:01 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-08-02 16:07 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-02 16:10 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-03 06:29 UTC, bowen5 commented
@majastrz , would you please help to sign off this PR? The content of this PR actually has been already signed off in private repo here https://github.com/Azure/azure-rest-api-specs-pr/pull/1627. Thank you!

2020-08-03 19:13 UTC, majastrz approved these changes
Thanks for making the first commit the original API version. It makes it much easier to review. The delta looks good. Signed off from ARM side.

2020-08-04 02:13 UTC, njuCZ approved these changes

2020-08-07 06:54 UTC, ArcturusZhang requested changes
Could you please also add a new tag entry in the readme.go.md since you are requesting this package to be released in go SDK?

2020-08-11 06:32 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-11 07:05 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-11 07:25 UTC, yuwzho commented
> Could you please also add a new tag entry in the readme.go.md since you are requesting this package to be released in go SDK?

@ArcturusZhang Thanks, just updated.

2020-08-11 08:02 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-17 05:01 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-17 05:28 UTC, ArcturusZhang requested changes
Your new api-version should be stable, but the output-folder is accidentally in preview sub-directory

2020-08-17 05:28 UTC, ArcturusZhang commented on specification/appplatform/resource-manager/readme.go.md
> +output-folder: $(go-sdk-folder)/services/preview/$(namespace)/mgmt/2020-07-01/$(namespace)
```suggestion
output-folder: $(go-sdk-folder)/services/$(namespace)/mgmt/2020-07-01/$(namespace)
```

2020-08-17 05:30 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-17 05:43 UTC, ArcturusZhang approved these changes

2020-08-17 06:03 UTC, merged