[Azure Automation] Swagger json files for rest of 15 resources and and changes to
Azure/azure-rest-api-specs pull request #1045
Opened 2017-03-17 17:12 UTC by fearthecowboy

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [ ] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

2017-03-18 22:41 UTC, vishrutshah requested changes
I've only reviewed `arm-automation/2015-10-31/swagger/account.json` from the PR so far

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "operationId": "Statistics_List",
Seems like this is `ListByAutomationAccounts` 

Rule M1004: https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +	"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccount}/statistics": {
Does this API accept $top and $max OData filter?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +	"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccount}/usages": {
indentation

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +	"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccount}/usages": {
Is this really a `usage` of `automationAccount` or `usages`? - naming

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "operationId": "Usages_List",
`ListByAutomationAccount`?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets the SKU name of the account.",
`Gets or sets` MUST not appear in the swagger description

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "enum": [
What is the default here? 

Rule M2027: https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +            "name": "SkuNameEnum",
You don't need to suffix `Enum` in the name

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets the SKU family."
`Gets or sets` MUST not appear in the swagger description

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets the SKU capacity."
`Gets or sets` MUST not appear in the swagger description

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +    "Sku": {
Are there any required properties of `Sku`?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets account SKU."
`Gets or sets`

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +	"AutomationAccountUpdateProperties": {
indentation

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "name": {
is this updatable or readOnly?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "location": {
is this updatable or readOnly?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets the location of the resource."
`Gets or sets`

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets account update properties."
`Gets or sets`

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "name": {
How does this `name` differ from `automationAccountName` from `PATCH` on `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}` ? It think should not exists here

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets the tags attached to the resource."
`Gets or sets`

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets the SKU of account."
`Gets or sets`

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "lastModifiedBy": {
readOnly candidate. Is this time in ISO8601 format?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets the status of account.",
`Get or Sets`

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +            "Ok",
Is this a readOnly candidate?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "type": "string",
Is this time in ISO8601 format?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "type": "string",
readOnly?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "lastModifiedTime": {
Is this time in ISO8601 format?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "lastModifiedTime": {
readOnly?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "name": {
Is this updatable?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "location": {
Is this updatable?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets list of accounts."
`Gets or sets`?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets the property value of the statistic."
`Gets or sets`?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "type": "string",
what are the example `value of the statistic`?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "startTime": {
readOnly?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "endTime": {
readOnly?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "id": {
readOnly?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "id": {
`readOnly`?

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets the usage unit name."
please provide descriptive description so that users can understand this property. Applies for entire document.

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +          "type": "integer",
you should use  `Minimum` and `Maximum` constrains here

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +      "description": "Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call."
`Gets ` ??

2017-03-18 22:41 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +	  "pattern": "^[-\\w\\._]+$",
Indentation

2017-03-18 22:44 UTC, vishrutshah commented
I'd request you please provide x-ms-example for your APIs. https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/x-ms-examples.md

2017-03-20 19:18 UTC, vivlingaiah commented
Hi Vishrut,
   We have received exceptions for the below issues:
[Azure Automation] validations (size, range, regexes) on properties and parameters missing  #1020 
https://github.com/Azure/azure-rest-api-specs/issues/1020
[Azure Automation] Descriptions need to be corrected in all Azure Automation resources  #1021
https://github.com/Azure/azure-rest-api-specs/issues/1021

Samer is aware of above issues. The two issues above will be revisited. These descriptions were inherited from Hyak specs and we won't be changing descriptions or validation regex at the moment

2017-03-20 19:54 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +      "description": "Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call."
Hi Vishrut,
 We have received exceptions for the below issues:
 [Azure Automation] validations (size, range, regexes) on properties and parameters missing  #1020
#1020
 [Azure Automation] Descriptions need to be corrected in all Azure Automation resources  #1021
#1021

Samer is aware of above issues. The two issues above will be revisited. These descriptions were inherited from Hyak specs and we won't be changing descriptions or validation regex at the moment

2017-03-20 19:54 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +          "type": "integer",
Leave a commentHi Vishrut,
 We have received exceptions for the below issues:
 [Azure Automation] validations (size, range, regexes) on properties and parameters missing  #1020
#1020
 [Azure Automation] Descriptions need to be corrected in all Azure Automation resources  #1021
#1021

Samer is aware of above issues. The two issues above will be revisited. These descriptions were inherited from Hyak specs and we won't be changing descriptions or validation regex at the moment

2017-03-20 19:54 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets the usage unit name."
Leave a commentHi Vishrut,
 We have received exceptions for the below issues:
 [Azure Automation] validations (size, range, regexes) on properties and parameters missing  #1020
#1020
 [Azure Automation] Descriptions need to be corrected in all Azure Automation resources  #1021
#1021

Samer is aware of above issues. The two issues above will be revisited. These descriptions were inherited from Hyak specs and we won't be changing descriptions or validation regex at the moment

2017-03-20 19:55 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets the property value of the statistic."
Leave a commentHi Vishrut,
 We have received exceptions for the below issues:
 [Azure Automation] validations (size, range, regexes) on properties and parameters missing  #1020
#1020
 [Azure Automation] Descriptions need to be corrected in all Azure Automation resources  #1021
#1021

Samer is aware of above issues. The two issues above will be revisited. These descriptions were inherited from Hyak specs and we won't be changing descriptions or validation regex at the moment

2017-03-20 19:55 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets list of accounts."
Leave a coHi Vishrut,
 We have received exceptions for the below issues:
 [Azure Automation] validations (size, range, regexes) on properties and parameters missing  #1020
#1020
 [Azure Automation] Descriptions need to be corrected in all Azure Automation resources  #1021
#1021

Samer is aware of above issues. The two issues above will be revisited. These descriptions were inherited from Hyak specs and we won't be changing descriptions or validation regex at the moment
mment

2017-03-20 19:55 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +          "description": "Gets or sets the status of account.",
Hi Vishrut,
 We have received exceptions for the below issues:
 [Azure Automation] validations (size, range, regexes) on properties and parameters missing  #1020
#1020
 [Azure Automation] Descriptions need to be corrected in all Azure Automation resources  #1021
#1021

Samer is aware of above issues. The two issues above will be revisited. These descriptions were inherited from Hyak specs and we won't be changing descriptions or validation regex at the moment
Leave a comment

2017-03-20 19:55 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +            "description": "OK",
Hi Vishrut,
 We have received exceptions for the below issues:
 [Azure Automation] validations (size, range, regexes) on properties and parameters missing  #1020
#1020
 [Azure Automation] Descriptions need to be corrected in all Azure Automation resources  #1021
#1021

Samer is aware of above issues. The two issues above will be revisited. These descriptions were inherited from Hyak specs and we won't be changing descriptions or validation regex at the moment
Leave a comment

2017-03-20 20:13 UTC, vivlingaiah commented
More importantly, I need help your help with below issues.
Issue 1: 
couple of operations need to automatically generate new Guid each time.  Is there a way to do it in Swagger ? This swagger was auto-generated using Hyak specs. Could you confirm this is correct way to auto-generate new guid on each invocation of operation ?
![uuid](https://cloud.githubusercontent.com/assets/25780318/24119582/00eac116-0d6f-11e7-8203-6aa84e3f2c16.JPG)

2017-03-20 20:19 UTC, vivlingaiah commented
Issue 2: The issue is AutoRest command that generates “Generated” files adds member Credentials (Credentials needed for the client to connect to Azure.) Co-Incidentally, we also have an API “Credentials” due to which two members have name conflicts. Could you let us know how to resolve this issue? I’ve attached the concerned files for your reference. (Forwarded the .cs files in reference to Vishrut). There is a name conflict. Two "Credentials" can be found

![credentialspath](https://cloud.githubusercontent.com/assets/25780318/24119828/b247e8bc-0d6f-11e7-90b5-b42af9d66279.JPG)

2017-03-20 20:35 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +        "operationId": "AutomationAccounts_ListBySubscriptionId",
this is a tracked resource. Errors prompted me to rename it as ListBySubscriptionId

2017-03-20 22:15 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +        "operationId": "AutomationAccounts_ListBySubscriptionId",
We are sorry for that. Actually that's a bug in the linter. Could you please name it as "List" even though linter is complaining. We are fixing it in linter.

2017-03-20 22:43 UTC, vishrutshah commented
#Issue 2 is coming from https://github.com/Azure/azure-rest-api-specs/pull/1045/files#diff-bf0e1b6e54180951dd6138234a55f3c4R239 : `operationId` should be PsCredentials_List.

2017-03-20 22:47 UTC, vishrutshah commented
Issue 1: Yes AutoRest should generate guid for you. Ref: https://github.com/Azure/autorest/pull/784

2017-03-20 23:02 UTC, salameer commented on arm-automation/2015-10-31/swagger/account.json
> +      "description": "Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call."
Yes @vishrutshah they have exceptions for fixing descriptions

2017-03-20 23:04 UTC, salameer commented
@vivlingaiah just to be clear xms-examples are not covered in the exceptions, just wanted to make sure that we're on the same page here

2017-03-20 23:07 UTC, vishrutshah requested changes
Reviewed `arm-automation/2015-10-31/swagger/certificate.json`. Please fix indentation across the swagger files

2017-03-20 23:07 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/certificate.json
> +        "isExportable": {
Is this readOnly?

2017-03-20 23:07 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/certificate.json
> +        "thumbprint": {
Is this readOnly?

2017-03-20 23:07 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/certificate.json
> +        "expiryTime": {
Is this updatable?

2017-03-20 23:07 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/certificate.json
> +        "creationTime": {
readOnly?

2017-03-20 23:07 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/certificate.json
> +        "lastModifiedTime": {
readOnly?

2017-03-20 23:07 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/certificate.json
> +          "format": "date-time",
What is the date-time format? ISO8601?

2017-03-20 23:07 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/certificate.json
> +    "Certificate": {
Is this a tracked resource?

2017-03-20 23:44 UTC, vishrutshah requested changes
Reviewed `arm-automation/2015-10-31/swagger/connection.json`. Please update indentation and provide accurate descriptions.

Also please provide `x-ms-example` for each of the operation

2017-03-20 23:44 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/connection.json
> +            "description": "OK"
`Patch` MUST return `#/definitions/Connection` schema

2017-03-20 23:44 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/connection.json
> +        "operationId": "Connections_List",
`_ListByAutomationAccounts`

2017-03-20 23:44 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/connection.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccount}/connections": {
Don't you have 

`List` - BySubscription &
`ListByResourceGroup` for this tracked resource?

2017-03-20 23:44 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/connection.json
> +          "description": "Gets or sets the connectionType of the connection."
`Gets or Sets` MUST not appear in the swagger. Documentation will not be good.

2017-03-20 23:44 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/connection.json
> +          "type": "string",
readOnly?

2017-03-20 23:44 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/connection.json
> +        "lastModifiedTime": {
readOnly?

2017-03-20 23:44 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/connection.json
> +    "Connection": {
Is this a tracked/Proxy Resource? Should it inherit from the common `Resource` model having `id`, `name`, `type` as readOnly?

2017-03-20 23:44 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/connection.json
> +          "type": "string",
readOnly?

2017-03-21 01:09 UTC, vishrutshah submitted a review, later dismissed

2017-03-21 01:09 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/account.json
> +	"/{subscriptionId}/operations/{requestId}": {
Is this the API supported & maintained by your team?

2017-03-21 01:09 UTC, vishrutshah commented on arm-automation/2015-10-31/swagger/certificate.json
> +          "201": {
when do you return 201 v/s 200? Seems like both return the same model?

2017-03-21 16:44 UTC, vishrutshah commented
Assigning it to @sarangan12 to help out Automation team and re-balance on our side. Thanks

2017-03-27 23:17 UTC, vivlingaiah commented
Hi @sarangan12, I've sent out another iteration ? could you check ? It has x-ms-examples for few resources.

2017-03-27 23:19 UTC, vivlingaiah commented
Changes made:
- I have moved all definitions and parameters to one file and refer them in others
- Added examples to 5 resources ( 3 more to come). Please check 
- I will address the rest of feedback above in next iteration

2017-03-28 15:35 UTC, vivlingaiah commented
please note I have not addressed all the feedback mentioned before. They will all be addressed in next PR I'll send. I sent the latest PR to show you examples.

2017-03-31 23:14 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +      "put": {
No

2017-03-31 23:14 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +		  "default": {
all indentations are corrected now.

2017-03-31 23:15 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +		  "default": {
all indentations are corrected now.

2017-03-31 23:15 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +          "nextLinkName": null
corrected

2017-03-31 23:16 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +        "operationId": "Statistics_List",
corrected

2017-03-31 23:17 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +	"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccount}/statistics": {
no

2017-03-31 23:18 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +	"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccount}/usages": {
It's usages of automation account. It returns many usages

2017-03-31 23:18 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +        "operationId": "Usages_List",
corrected

2017-03-31 23:19 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +    "Sku": {
added "name" as required

2017-03-31 23:19 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +          "enum": [
added default

2017-03-31 23:22 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +        "name": {
corrected

2017-03-31 23:22 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +        "lastModifiedBy": {
corrected

2017-03-31 23:22 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +          "type": "string",
correctted

2017-03-31 23:22 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +          "type": "string",
added example

2017-03-31 23:24 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/certificate.json
> +            "description": "OK"
corrected

2017-03-31 23:24 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/certificate.json
> +        "operationId": "Certificates_List",
corrected

2017-03-31 23:24 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/certificate.json
> +    "Certificate": {
no

2017-03-31 23:24 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/connection.json
> +            "description": "OK"
corrected

2017-03-31 23:25 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/connection.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccount}/connections": {
this is not a tracked resource. corrected naming of methods

2017-03-31 23:25 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/connection.json
> +        "operationId": "Connections_List",
corrected

2017-03-31 23:25 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/connection.json
> +    "Connection": {
this is not a tracked resource

2017-03-31 23:26 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +	"/{subscriptionId}/operations/{requestId}": {
it's not supported. I removed it

2017-03-31 23:26 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/certificate.json
> +          "201": {
corrected

2017-03-31 23:37 UTC, viveklingaiah approved these changes

2017-03-31 23:54 UTC, vivlingaiah commented
Notes:
1) We have an issue with on of the API calls where we are not able pass string in request body. Raised an issue with Autorest team https://github.com/Azure/autorest/issues/2095 
2) For 8 resources, few API calls return null values due to which validation of x-ms-examples fail.
[Azure Automation] Service returns null values for few resources. validation of x-ms-examples fails. #1091
https://github.com/Azure/azure-rest-api-specs/issues/1091
Samer has advised we can raise an issue. Non blocker for Swagger specs to be released
![sameronserverreturnednulls](https://cloud.githubusercontent.com/assets/25780318/24572986/a5fe9c4c-1632-11e7-92de-02060c434273.JPG)

3) We have exceptions with updating meaningful descriptions and adding validations (regex, max, min )
[Azure Automation] validations (size, range, regexes) on properties and parameters missing  #1020 
https://github.com/Azure/azure-rest-api-specs/issues/1020
[Azure Automation] Descriptions need to be corrected in all Azure Automation resources  #1021
https://github.com/Azure/azure-rest-api-specs/issues/1021

2017-04-01 03:15 UTC, sarangan12 commented on arm-automation/2015-10-31/swagger/webhook.json
> +              "$ref": "./definitions.json#/definitions/WebhookCreateOrUpdateParameters"
Our recommendation is that for a put operation, the body parameter and the response should match. It does not. Could you check for this one and other put operations in the PR

2017-04-01 03:15 UTC, sarangan12 commented on arm-automation/2015-10-31/swagger/webhook.json
> +              "$ref": "./definitions.json#/definitions/Webhook"
201 means accepted status. It is not a valid termination of the whole process. So, how is it returning a Webhook?

2017-04-01 03:15 UTC, sarangan12 commented on arm-automation/2015-10-31/swagger/webhook.json
> +            "in": "body",
The comment that I added for post applies to patch operation also. Why is the body parameter and response different?

2017-04-01 03:15 UTC, sarangan12 commented on arm-automation/2015-10-31/swagger/account.json
>          "responses": {
What is the schema for 200 response?

2017-04-03 16:39 UTC, sarangan12 commented
The following operation names are violating the rules:

1. Statistics_ListByAutomationAccount
2. Usages_ListByAutomationAccount
3. Certificates_ListByAutomationAccount
4. Connections_ListByAutomationAccount
5. ConnectionTypes_ListByAutomationAccount
6. PsCredentials_ListByAutomationAccount
7. Jobs_ListByAutomationAccount
8. JobStreams_ListByJob
9. Activities_ListByModule
10. Modules_ListByAutomationAccount
11. Fields_ListByType
12. Runbooks_ListByAutomationAccount
13. TestJobStreams_ListByTestJob
14. Schedules_ListByAutomationAccount
15. JobSchedules_ListByAutomationAccount
16. Variables_ListByAutomationAccount
17. Webhooks_ListByAutomationAccount
18. CompilationJobs_ListByAutomationAccount
19. Configurations_ListByAutomationAccount
20. Nodes_ListByAutomationAccount
21. NodeReports_ListByNode
22. NodeConfigurations_ListByAutomationAccount
23. HybridRunbookWorkerGroups_ListByAutomationAccount

@vivlingaiah Can you confirm if you have exceptions approved for all of these?

2017-04-03 16:48 UTC, sarangan12 commented
A body parameter must be named 'parameters'. The following paths are violating the rule:

1. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/patch/parameters[3]
2. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/put/parameters[3]
3. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/certificates/{certificateName}/put/parameters[4]
4. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/connections/{connectionName}/put/parameters[4]
5. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/connections/{connectionName}/patch/parameters[4]
6. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/connectionTypes/{connectionTypeName}/put/parameters[4]
7. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/modules/{moduleName}/put/parameters[4]
8. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/modules/{moduleName}/patch/parameters[4]
9. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/runbooks/{runbookName}/draft/content/put/parameters[4]
10. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/runbooks/{runbookName}/put/parameters[4]
11. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/runbooks/{runbookName}/draft/testJob/put/parameters[4]
12. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/schedules/{scheduleName}/put/parameters[4]
13. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/schedules/{scheduleName}/patch/parameters[4]
14. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/jobSchedules/{jobScheduleId}/put/parameters[4]
15. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/variables/{variableName}/put/parameters[4]
16. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/variables/{variableName}/patch/parameters[4]
17. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/webhooks/{webhookName}/put/parameters[4]
18. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/webhooks/{webhookName}/patch/parameters[4]
19. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/compilationjobs/{compilationJobId}/put/parameters[4]
20. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/agentRegistrationInformation/regenerateKey/post/parameters[3]
21. Path: #/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/nodeConfigurations/{nodeConfigurationName}/put/parameters[4]

2017-04-03 16:56 UTC, sarangan12 commented
One of the rule is that "Parameters "subscriptionId" and "api-version" are not allowed in the operations section, define these in the global parameters section instead". There are several paths which violate the rule: https://gist.github.com/sarangan12/e5ffe03d76cbaccbcceba2060c2dec8d#file-gistfile1-txt

2017-04-03 16:57 UTC, sarangan12 commented
ERROR: A 'POST' operation 'RunbookDraft_Publish' with x-ms-long-running-operation extension must have a valid terminal success status code 200 or 201 or 204.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-automation/compositeAutomation.json#/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/runbooks/{runbookName}/draft/publish/post/extensions/x-ms-long-running-operation

2017-04-03 16:57 UTC, sarangan12 commented
ERROR: The property 'odata.nextLink' specified by nextLinkName does not exist in the 200 response schema.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-automation/compositeAutomation.json#/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/hybridRunbookWorkerGroups/get/extensions/x-ms-pageable

2017-04-03 16:57 UTC, sarangan12 commented
ERROR: Tracked Resource failing validation is: "DscConfiguration". Validation Failed: 2.
    A Tracked Resource must have:
    1. A Get Operation
    2. A ListByResourceGroup operation with x-ms-pageable extension and
    3. A ListBySubscriptionId operation with x-ms-pageable extension.
    4. "type","location","tags" should not be used in the RP property bag named "properties".
        Path: file:///C:/workspace/azure-rest-api-specs/arm-automation/compositeAutomation.json#/definitions
ERROR: Tracked resource 'DscConfiguration' must have patch operation that at least supports the update of tags.
        Path: file:///C:/workspace/azure-rest-api-specs/arm-automation/compositeAutomation.json#/definitions

2017-04-03 20:31 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/webhook.json
> +              "$ref": "./definitions.json#/definitions/Webhook"
201 is created

2017-04-03 20:31 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/webhook.json
> +          "url": "http://aka.ms/azureautomationsdk/webhookoperations"
yes, that's right

2017-04-03 20:32 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/webhook.json
> +              "$ref": "./definitions.json#/definitions/WebhookCreateOrUpdateParameters"
this is a won't fix. Im just describing the specs on how service behaves

2017-04-03 20:33 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/webhook.json
> +            "in": "body",
this is a won't fix. Im just describing the specs on how service behavesent

2017-04-03 23:20 UTC, vivlingaiah commented
Hi Sarangan,
- Addressed your feedback
- Changed plural name to singular. AutomationAccounts_ to AutomationAccount_ for all resources
- renamed all parameters to "parameters"
- For 9 resources, please note validation of x-ms-examples will have errors such as (returned null) for which I have created an issue https://github.com/Azure/azure-rest-api-specs/issues/1091 Samer advised to create an issue at this point to unblock us

2017-04-03 23:50 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
>          "responses": {
delete does not send an object

2017-04-04 03:37 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +				"$ref": "#/definitions/AutomationAccountCreateOrUpdateParameters"
corrected

2017-04-04 03:37 UTC, vivlingaiah commented on arm-automation/2015-10-31/swagger/account.json
> +		  "default": {
corrected

2017-04-04 21:49 UTC, sarangan12 approved these changes

2017-04-05 17:45 UTC, sarangan12 approved these changes

2017-04-06 21:58 UTC, sarangan12 approved these changes

2017-04-06 21:59 UTC, merged

2017-04-06 22:04 UTC, AutorestCI commented
No modification for Ruby

2017-04-06 22:04 UTC, AutorestCI commented
No modification for Ruby

2017-04-06 22:04 UTC, AutorestCI commented
No modification for Python

2017-04-06 22:04 UTC, AutorestCI commented
No modification for NodeJS