[Hub Generated] Review request for Microsoft.HybridCompute to add version stable/2020-08-15
Azure/azure-rest-api-specs pull request #10496
Opened 2020-08-18 00:00 UTC by Atchub

This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/Atchub/azure-rest-api-specs/atchub-hybridcompute-Microsoft.HybridCompute-2020-08-15...master/).

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “**WaitForARMFeedback**” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

2020-08-18 00:00 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-18 00:30 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-08-18 00:40 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-18 01:31 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-18 02:16 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-18 07:31 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-18 07:45 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-18 08:24 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-18 17:25 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-18 18:31 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-18 18:55 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-18 21:17 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-18 21:36 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-18 22:35 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-19 01:17 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-19 01:33 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-19 01:42 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-20 00:45 UTC, Atchub commented
@xccc-msft , can you please review the PR?

2020-08-20 02:17 UTC, xccc-msft commented
@Atchub I'm from SDK team. `WaitForARMFeedback` requires ARM team to review for your new APIs.

2020-08-21 08:05 UTC, ravbhatnagar reviewed
Signing off from ARM side.

2020-08-21 08:09 UTC, xseeseesee approved these changes

2020-08-21 08:10 UTC, xccc-msft commented
@Atchub I cannot find hybridCompute in [CODEOWNERS](https://github.com/Azure/azure-rest-api-specs/blob/master/CODEOWNERS). Do you know who can help review from service end?

2020-08-24 20:44 UTC, TylerLeonhardt commented on specification/hybridcompute/resource-manager/readme.md
> +```
please put this in the readme.go.md

2020-08-24 20:44 UTC, TylerLeonhardt commented on specification/hybridcompute/resource-manager/readme.md
> +## Python
please put this in the readme.python.md

2020-08-24 20:44 UTC, TylerLeonhardt commented on specification/hybridcompute/resource-manager/readme.md
> +## PowerShell
please remove this section and do what was already there.

2020-08-24 20:45 UTC, TylerLeonhardt commented on specification/hybridcompute/resource-manager/readme.md
> +## C#
please put this in the readme.csharp.md

2020-08-25 16:35 UTC, TylerLeonhardt requested changes
Please take a look at the README files in master

2020-10-28 04:23 UTC, xccc-msft commented
Close this as changes merged in another PR. Please feel free to reopen if you still need to work on this one. Thanks.

2020-10-28 04:23 UTC, closed without merging