added files for new api version 2017-03-31 (#1)
Azure/azure-rest-api-specs pull request #1054
Opened 2017-03-21 21:22 UTC by kejiun

* added files for new api version 2017-03-31

2017-03-21 21:23 UTC, msftclas commented
@kejiun,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-03-22 18:26 UTC, sarangan12 requested changes

2017-03-22 18:26 UTC, sarangan12 commented on arm-advisor/2017-03-31/swagger/advisor.json
> +					"202": {
Here you are giving the status 202 which is accepted. But what is the final status? 200? If so, please include it

2017-03-22 18:26 UTC, sarangan12 commented on arm-advisor/2017-03-31/swagger/advisor.json
> +				"operationId": "Recommendations_GetGenerateRecommendationsStatus",
Are you particular in this name? Can it be names GenerateRecommendationsStatus_Get which is what we usually recommend

2017-03-22 18:26 UTC, sarangan12 commented on arm-advisor/2017-03-31/swagger/advisor.json
> +					"202": {
Here you mention 202 which is accepted. Now, how will I poll back to get the response? Which URI to hit? Usually it is obtained from the response of the 202. But there is no response here.

2017-03-22 18:26 UTC, sarangan12 commented on arm-advisor/2017-03-31/swagger/advisor.json
> +				"operationId": "Suppressions_Get",
Does this operation provide a list of suppressions for one recommendations? In that case, the recommendation is to use the id Suppressions_ListByRecommendations

2017-03-22 18:26 UTC, sarangan12 commented on arm-advisor/2017-03-31/swagger/advisor.json
> +						"description": "OK.",
Provide a valid description

2017-03-22 18:26 UTC, sarangan12 commented on arm-advisor/2017-03-31/swagger/advisor.json
> +						"description": "OK.",
Provide a vaid description

2017-03-22 18:26 UTC, sarangan12 commented on arm-advisor/2017-03-31/swagger/advisor.json
> +						"format": "uuid",
Is it possible to avoid usage of uuids?

2017-03-22 18:26 UTC, sarangan12 commented on arm-advisor/2017-03-31/swagger/advisor.json
> +		"ResourceRecommendationBase": {
Can you confirm if this is a resource? If so, it should have an allOf of a resource.

2017-03-22 18:35 UTC, sarangan12 commented
Running the swagger against linter, I get the following errors:

ERROR: Per the Noun_Verb convention for Operation Ids, the noun 'Recommendations' should not appear after the underscore.
        Path: ..\advisor.json#/paths/subscriptions/{subscriptionId}/providers/Microsoft.Advisor/generateRecommendations/{operationId}/get/operationId
ERROR: Top level properties should be one of name, type, id, location, properties, tags, plan, sku, etag, managedBy, identity. Extra properties found: "SuppressionContract/suppressionId, SuppressionContract/ttl".
        Path: ..\advisor.json#/paths/{resourceUri}/providers/Microsoft.Advisor/recommendations/{recommendationId}/suppressions/{name}
ERROR: Tracked Resource failing validation is: "SuppressionContract". Validation Failed: 2.
    A Tracked Resource must have:
    1. A Get Operation
    2. A ListByResourceGroup operation with x-ms-pageable extension and
    3. A ListBySubscriptionId operation with x-ms-pageable extension.
    4. "type","location","tags" should not be used in the RP property bag named "properties".
        Path: ..\advisor.json#/definitions
ERROR: Tracked resource 'SuppressionContract' must have patch operation that at least supports the update of tags.
        Path: ..\advisor.json#/definitions


Please fix them

2017-03-22 23:11 UTC, kejiun commented on arm-advisor/2017-03-31/swagger/advisor.json
> +				"operationId": "Suppressions_Get",
this one returns only one suppression

2017-03-22 23:18 UTC, kejiun commented on arm-advisor/2017-03-31/swagger/advisor.json
> +						"format": "uuid",
may I have the reason

2017-03-22 23:19 UTC, kejiun commented on arm-advisor/2017-03-31/swagger/advisor.json
> +		"ResourceRecommendationBase": {
this is a extension resource, does it count?

2017-03-22 23:20 UTC, kejiun commented on arm-advisor/2017-03-31/swagger/advisor.json
> +				"operationId": "Suppressions_Get",
this one return single suppressions

2017-03-24 20:48 UTC, ravbhatnagar commented on arm-advisor/2017-03-31/swagger/advisor.json
> +						"format": "uuid",
Hank and I had a conversation on this. The design of this API will be revisited after GA. There may not be a need for suppressionIds. But lets not block GA due to this. This is read-only for now and service generates it. So user does not have to pass in the GUID.

2017-03-24 23:07 UTC, kejiun commented on arm-advisor/2017-03-31/swagger/advisor.json
> +					"202": {
The design of this API will be revisited after GA.

2017-03-24 23:07 UTC, kejiun commented on arm-advisor/2017-03-31/swagger/advisor.json
> +					"202": {
The design of this API will be revisited after GA.

2017-03-24 23:07 UTC, kejiun commented on arm-advisor/2017-03-31/swagger/advisor.json
> +		"ResourceRecommendationBase": {
done

2017-03-27 20:54 UTC, sarangan12 commented
Based on the offline communications, I see some of the API design issues will be handled after GA release. The documentation issues seem to be resolved now. Approving these

2017-03-27 20:54 UTC, azuresdkci commented
Can one of the admins verify this patch?

2017-03-27 20:54 UTC, sarangan12 approved these changes

2017-03-27 20:54 UTC, merged