Updating readme.md files for SDK generation (multi-api, new api version already checked in)
Azure/azure-rest-api-specs pull request #10567
Opened 2020-08-24 17:20 UTC by mjain2

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

This PR is to update MD files for azure.mgmt.rdbms namespace, which includes mysql and postgresql.

Overview of changes:
1. Adding new API version (already checked in) for both MySQL and PostgreSQL to the .md files
2. Updates and adding md files for SDKs for Go, .NET and Python (includes multi-api changes)

### Contribution checklist:
- [x] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [x] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [n/a ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

2020-08-24 17:20 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-25 05:42 UTC, ArcturusZhang requested changes
Hi @mjain2 I left one comment for the go SDK generation configuration, please have a look

2020-08-25 05:42 UTC, ArcturusZhang commented on specification/mysql/resource-manager/readme.go.md
> +output-folder: $(go-sdk-folder)/services/preview/$(namespace)/mgmt/flexible-servers/2020-07-01-privatepreview/$(namespace)
```suggestion
output-folder: $(go-sdk-folder)/services/preview/$(namespace)/mgmt/2020-07-01-preview/$(namespace)
```

2020-08-26 01:26 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-27 16:57 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-27 23:10 UTC, AutorestCI commented
/azp run automation - sdk

2020-09-03 19:08 UTC, AutorestCI commented
/azp run automation - sdk

2020-09-03 23:52 UTC, AutorestCI commented
/azp run automation - sdk

2020-09-04 21:22 UTC, mjain2 commented
Abandoning this PR. Changes should only include readme.md files.  Will recreate PR and activate it once the new swagger spec is checked in.

2020-09-04 21:28 UTC, closed without merging