Add Azure SQL Database Failover Group REST API specs
Azure/azure-rest-api-specs pull request #1079
Opened 2017-03-29 04:58 UTC by btasdoven

Adding Azure SQL Database Failover Group REST API specifications as the feature will be in public preview soon.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-03-29 04:58 UTC, msftclas commented
@btasdoven,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-03-29 19:02 UTC, jaredmoo requested changes

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                            "$ref": "#/definitions/ArmErrorResponseMessage"
Remove this

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                "description": "Creates or updates the failover group with the given name.",
Creates or updates a failover group .

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                "description": "Deletes the failover group with the given name.",
Deletes a failover group.

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                            "$ref": "#/definitions/ArmErrorResponseMessage"
Remove

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                "description": "Gets the failover group with the given name.",
Gets a failover group.

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                            "$ref": "#/definitions/ArmErrorResponseMessage"
Remove

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                "description": "Partially updates the failover group with the given name.",
Updates a failover group.

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                            "$ref": "#/definitions/ArmErrorResponseMessage"
Remove

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                "operationId": "FailoverGroups_List",
FailoverGroups_ListByServer

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                "description": "Lists the failover groups on the given server.",
Lists the failover groups in a server.

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                "description": "Starts planned failover operation for the failover group.",
I assume that like replicationLinks/failover this is called on the new primary, is this correct? If so, please describe. Below is what I wrote in Azure CLI for this operation, consider something similar. 

Command
    az sql db replica set-primary: Sets which replica database is primary by failing over from the
    current primary replica database.

The swagger doc for replicationLinks/failover probably needs to be improved as well.

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                            "$ref": "#/definitions/ArmErrorResponseMessage"
This should be removed everywhere, I will stop commenting on the later ones :)

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                        "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource I
Remove all these

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                        "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource I
please remove all these and use "allOf" to include properties from ProxyResource or TrackedResource. You can see examples of this in other sql swagger files. You will need to copy Resource and ProxyResource/TrackedResource definitions into this file.

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                        "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource I
This should just be called 'FailoverGroupProperties'. 'Resource' is redundant.

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                        "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource I
What are possible values? Describe with enum. Is it readonly?

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                        "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource I
Readonly?

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                        "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource I
Readonly?

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                        "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource I
Needs x-ms-enum. See https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#Enum-x-ms-enum

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                        "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource I
Need x-ms-enum

2017-03-29 19:02 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +                        "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource I
FailoverGroupList

2017-03-29 22:36 UTC, dsgouda commented
I shall take a look at this soon

2017-03-29 23:38 UTC, dsgouda requested changes

2017-03-29 23:38 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +  "paths": {
Please expose an ```/operations``` API for this spec

2017-03-29 23:38 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "$ref": "#/parameters/SubscriptionIdParameter"
nit: For consistency, put ```SubscriptionId``` and ```ApiVersion``` together at the beginning or at the end of the parameters section

2017-03-29 23:38 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "$ref": "#/parameters/SubscriptionIdParameter"
nit: parameter ordering

2017-03-29 23:38 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "$ref": "#/parameters/SubscriptionIdParameter"
nit: parameter ordering

2017-03-29 23:38 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
Consider marking this as ```"modelAsString": true``` if the enum is expected to change in the future, not doing so causes breaking changes

2017-03-29 23:38 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
Same comment as above for enums

2017-03-29 23:38 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
This also seems like something that the server is setting and should not be a part of the request. Could this be marked as readonly

2017-03-29 23:38 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
Same comment as above for enums

2017-03-29 23:38 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
Some properties here look like candidates for readonly properties, please verify if you have all properties correctly marked as readonly

2017-03-29 23:38 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
nit: If you're not using this, you can remove it

2017-03-29 23:41 UTC, dsgouda requested changes

2017-03-29 23:41 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
Consider using ```x-ms-client-flatten``` here for the nested properties for better user experience

2017-03-29 23:44 UTC, jaredmoo commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +  "paths": {
Hey @dsgouda , I was told by @veronicagg that /operations isn't needed in each swagger file - it's just needed once per RP. https://github.com/Azure/azure-rest-api-specs/pull/1005#issuecomment-285826237

2017-03-29 23:45 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +  "paths": {
That's correct, if there is an operations API already existing which returns the operations mentioned in this spec, you can disregard this comment

2017-03-30 18:04 UTC, btasdoven commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
I can't correctly see which lines you comment on @dsgouda . This and all of the next comments are for the line 321. Any ideas to view them?

2017-03-30 18:06 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
Weird, I might have to try this manually, let me get back in a while

2017-03-30 18:22 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "$ref": "#/parameters/SubscriptionIdParameter"
Also applies [here](https://github.com/Azure/azure-rest-api-specs/pull/1079/files#diff-090eb226c435d8d8ba061faca6869009R72), [here](https://github.com/Azure/azure-rest-api-specs/pull/1079/files#diff-090eb226c435d8d8ba061faca6869009R72), [here](https://github.com/Azure/azure-rest-api-specs/pull/1079/files#diff-090eb226c435d8d8ba061faca6869009R123), [here](https://github.com/Azure/azure-rest-api-specs/pull/1079/files#diff-090eb226c435d8d8ba061faca6869009R165), [here](https://github.com/Azure/azure-rest-api-specs/pull/1079/files#diff-090eb226c435d8d8ba061faca6869009R212), [here](https://github.com/Azure/azure-rest-api-specs/pull/1079/files#diff-090eb226c435d8d8ba061faca6869009R252) and [here](https://github.com/Azure/azure-rest-api-specs/pull/1079/files#diff-090eb226c435d8d8ba061faca6869009R296)

2017-03-30 18:23 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
Linked [here ](https://github.com/Azure/azure-rest-api-specs/pull/1079/files#diff-090eb226c435d8d8ba061faca6869009R351)

2017-03-30 18:28 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
Linked [here](https://github.com/Azure/azure-rest-api-specs/pull/1079/files#diff-090eb226c435d8d8ba061faca6869009R471) and [here](https://github.com/Azure/azure-rest-api-specs/pull/1079/files#diff-090eb226c435d8d8ba061faca6869009R492)

2017-03-30 18:30 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
Linked [here](https://github.com/Azure/azure-rest-api-specs/pull/1079/files#diff-090eb226c435d8d8ba061faca6869009R476), [here](https://github.com/Azure/azure-rest-api-specs/pull/1079/files#diff-090eb226c435d8d8ba061faca6869009R523) and [here](https://github.com/Azure/azure-rest-api-specs/pull/1079/files#diff-090eb226c435d8d8ba061faca6869009R497)

2017-03-30 18:32 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
Linked [here](https://github.com/Azure/azure-rest-api-specs/pull/1079/files#diff-090eb226c435d8d8ba061faca6869009R416)

2017-03-30 18:33 UTC, dsgouda commented
Github is probably acting up because of the super long description for one of the operation responses, I've tried my best to link my comments to the line numbers, hope that helps

2017-03-30 19:00 UTC, btasdoven commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
We allow customers to update those fields. I made a second pass on them to make sure all the read-only properties are marked as read only.

2017-03-30 19:01 UTC, btasdoven commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
Thanks!

2017-03-30 20:03 UTC, dsgouda commented on arm-sql/2015-05-01-preview/swagger/failoverGroups.json
> +            "description": "*** Error Responses: ***\n\n * 400 FailoverGroupCreateOrUpdateRequestInvalidDatabases - The provided databases in the request are not valid database resource IDs.\n\n * 40
Just curious, is FailoverGroupReadWriteEndpoint some sort of a url?

2017-03-30 20:19 UTC, dsgouda approved these changes

2017-03-30 20:19 UTC, dsgouda commented
Linter rules look good, generated C# code seems to compile too. LGTM

2017-03-30 20:20 UTC, merged

2017-03-30 20:24 UTC, AutorestCI commented
No modification for NodeJS

2017-03-30 20:24 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1079)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1058

2017-03-30 20:25 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1079)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/738