Update compute.json
Azure/azure-rest-api-specs pull request #11055
Opened 2020-10-06 19:32 UTC by grizzlytheodore

from API owner: @shpa-microsoft

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of “no breaking changes
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  - Adding a new service

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from API Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable version with Breaking Change Validation errors
- [ ] Updating API(s) in preview over 1 year

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

2020-10-06 19:32 UTC, AutorestCI commented
/azp run automation - sdk

2020-10-06 19:33 UTC, grizzlytheodore commented
added 'DoNotMerge' label to follow new API version PR process for Cplat

2020-10-06 19:57 UTC, markcowl requested changes

2020-10-06 19:57 UTC, markcowl commented on specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json
> +        "platformFaultDomain": {
Can we add this to existing examples?

2020-10-06 19:58 UTC, markcowl commented
@grizzlytheodore You will need to fix the LintDiff error above (see https://aka.ms/ci-fix) when this is ready to merge

2020-10-07 15:47 UTC, AutorestCI commented
/azp run automation - sdk

2020-10-07 17:50 UTC, grizzlytheodore commented on specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/compute.json
> +        "platformFaultDomain": {
@shpa-microsoft

2020-10-07 22:17 UTC, markcowl requested changes

2020-10-07 22:17 UTC, markcowl commented on specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/runCommands.json
> +    "RunCommandDocumentBase": {
Is this a resource?

2020-10-20 03:18 UTC, AutorestCI commented
/azp run automation - sdk

2020-10-22 22:53 UTC, pilor approved these changes

2020-10-27 22:05 UTC, shpa-microsoft commented
Based on private chat; Abandoning this with new PR https://github.com/Azure/azure-rest-api-specs/pull/11409

2020-10-29 13:33 UTC, Sandido commented
Closing as per above comment. New PR 11409.

2020-10-29 13:33 UTC, closed without merging