Update WebApps swagger - Antares 62.1
Azure/azure-rest-api-specs pull request #1112
Opened 2017-04-11 22:57 UTC by Nking92

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-04-20 23:14 UTC, jianghaolu requested changes
Thanks for the Swagger changes with good quality! Just a couple nits and a few `x-ms-examples` and we are good to go!

2017-04-20 23:14 UTC, jianghaolu commented on arm-web/2016-03-01/swagger/Provider.json
> +        "operationId": "Provider_GetAvailableStacks",
Please provide a summary / description.

2017-04-20 23:14 UTC, jianghaolu commented on arm-web/2016-08-01/swagger/WebApps.json
> +        "operationId": "WebApps_ListConfigurations",
Please provide `x-ms-examples` section according to https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/x-ms-examples.md.

2017-04-20 23:14 UTC, jianghaolu commented on arm-web/2016-08-01/swagger/WebApps.json
> +        "operationId": "WebApps_GetResourceHealthMetadata",
Please provide x-ms-examples section according to https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/x-ms-examples.md.

2017-04-20 23:14 UTC, jianghaolu commented on arm-web/2016-08-01/swagger/WebApps.json
> +        "operationId": "WebApps_ListConfigurationsSlot",
Please provide x-ms-examples section according to https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/x-ms-examples.md.

2017-04-20 23:14 UTC, jianghaolu commented on arm-web/2016-08-01/swagger/WebApps.json
> +        "operationId": "WebApps_GetResourceHealthMetadataSlot",
Please provide x-ms-examples section according to https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/x-ms-examples.md.

2017-04-20 23:14 UTC, jianghaolu commented on arm-web/2016-08-01/swagger/WebApps.json
> +        "operationId": "WebApps_SyncFunctionTriggersSlot",
Please provide x-ms-examples section according to https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/x-ms-examples.md.

2017-04-20 23:14 UTC, jianghaolu commented on arm-web/2016-08-01/swagger/WebApps.json
> +        "summary": "this is to allow calling via powershell and ARM template",
Please provide a more descriptive summary / description.

2017-04-20 23:14 UTC, jianghaolu commented on arm-web/2016-08-01/swagger/WebApps.json
> +        "summary": "this is to allow calling via powershell and ARM template",
Please provide a more descriptive summary / description.

2017-04-20 23:14 UTC, jianghaolu commented on arm-web/2016-08-01/swagger/WebApps.json
> +        "operationId": "WebApps_SyncFunctionTriggers",
Please provide x-ms-examples section according to https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/x-ms-examples.md.

2017-04-21 18:14 UTC, Nking92 commented
Thank you for the review @jianghaolu. Most of these should be easy fixes. However, I'm not sure what I should do about x-ms-examples. We use Swashbuckle to generate the Swagger files, and I'm afraid that if I manually added  x-ms-examples  properties, they would be overwritten later on. Do you have any advice?

2017-04-21 21:53 UTC, jianghaolu commented
Hi @Nking92 

Thanks! I'm looking forward to the easy fixes :)

For `x-ms-examples`, if you have .NET test recordings for these routes in your RP, we have a tool (not in production yet, but few service teams have tested) that help you get `x-ms-examples` contents. 
Clone the repo through `git clone -b readrecordings git@github.com:veronicagg/openapi-validation-tools.git` and run `node scripts/readrecording.js`.
Do you think you can try this out by early next week?

2017-04-21 21:54 UTC, jianghaolu reviewed
One more nit-picking: Please add `providers.json` to `compositeWebAppClient.json`.

2017-04-25 18:51 UTC, jianghaolu commented
Hi @Nking92 
Thanks for addressing the review feedback! Did you get a chance to look at the example generator?

2017-04-25 20:14 UTC, Nking92 commented
Hi @jianghaolu 
We'd like to delay the examples for the next update if that's acceptable. The tooling we use to generate the swagger isn't set up to handle the examples yet, and the FTE who owns that tooling is out until May 8. In the interest of getting this new API spec published to unblock other teams for //Build work, it will be best for us to delay the examples for now. Yugang Wang has more specifics if you'd like to discuss.

2017-04-26 19:05 UTC, jianghaolu approved these changes

2017-04-26 19:51 UTC, jianghaolu commented
Hi @Nking92 @naveedaz
We will merge this for now but the `x-ms-examples` requirement is still valid and will be recorded as an action item on Service 360, which will be part of the monthly report. Please let us know when you plan to work on them so that we can provide the tools/resources to help you.

2017-04-26 19:51 UTC, merged

2017-04-26 19:55 UTC, AutorestCI commented
No modification for NodeJS

2017-04-26 19:55 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1112)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/766

2017-04-26 19:56 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1112)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1114