Bruceper work
Azure/azure-rest-api-specs pull request #1114
Opened 2017-04-12 18:55 UTC by BrucePerlerMS

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-04-12 18:57 UTC, BrucePerlerMS commented
comment updates for most/all API descriptions. Please review

2017-04-12 22:26 UTC, dsgouda requested changes
Operation descriptions should be provided and some nit comments

2017-04-12 22:26 UTC, dsgouda commented on keyvault/2016-10-01/swagger/keyvault.json
> +        "description": "The cryptographic material of a key itself cannot be changed. In order to perform this operation, the key must already exist in the Key Vault.",
nit: doesn't really describe the operation itself

2017-04-12 22:26 UTC, dsgouda commented on keyvault/2016-10-01/swagger/keyvault.json
> +        "description": "SIGN is applicable to asymmetric and symmetric keys stored in Azure Key Vault since this operation uses the private portion of the key.",
nit: You could say "The SIGN operation is applicable..." just like all other operations to maintain consistency and provide better description.

2017-04-12 22:26 UTC, dsgouda commented on keyvault/2016-10-01/swagger/keyvault.json
> +        "description": "VERIFY is applicable to symmetric keys stored in Azure Key Vault. VERIFY is not strictly necessary for asymmetric keys stored in Azure Key Vault since signature verification c
nit: "VERIFY operation"

2017-04-12 22:26 UTC, dsgouda commented on keyvault/2016-10-01/swagger/keyvault.json
> +        "description": " ",
No description?

2017-04-12 22:26 UTC, dsgouda commented on keyvault/2016-10-01/swagger/keyvault.json
> +        "description": " ",
Empty description

2017-04-12 22:34 UTC, BrucePerlerMS commented
@Pooneh Mortazavi - Please have a look at these documentation updates to the swagger file and accept or offer feedback. Thanks, Bruce

2017-04-12 22:38 UTC, BrucePerlerMS commented on keyvault/2016-10-01/swagger/keyvault.json
> +        "description": " ",
I'm in touch with the dev and will be updating this.

2017-04-12 22:38 UTC, BrucePerlerMS commented on keyvault/2016-10-01/swagger/keyvault.json
> +        "description": " ",
I'm in touch with the dev and will be updating this.

2017-04-12 22:39 UTC, dsgouda commented on keyvault/2016-10-01/swagger/keyvault.json
> +        "description": " ",
FYI there are multiple occurrences I have pointed out just a couple.

2017-04-12 22:41 UTC, BrucePerlerMS commented on keyvault/2016-10-01/swagger/keyvault.json
> +        "description": "The cryptographic material of a key itself cannot be changed. In order to perform this operation, the key must already exist in the Key Vault.",
Its an Key update operation that takes the specified attributes as arguments and sets those attrs. What more would you like to see?

2017-04-12 22:41 UTC, BrucePerlerMS commented on keyvault/2016-10-01/swagger/keyvault.json
> +        "description": "SIGN is applicable to asymmetric and symmetric keys stored in Azure Key Vault since this operation uses the private portion of the key.",
will do

2017-04-12 22:41 UTC, BrucePerlerMS commented on keyvault/2016-10-01/swagger/keyvault.json
> +        "description": "VERIFY is applicable to symmetric keys stored in Azure Key Vault. VERIFY is not strictly necessary for asymmetric keys stored in Azure Key Vault since signature verification c
will do

2017-04-12 22:42 UTC, dsgouda commented on keyvault/2016-10-01/swagger/keyvault.json
> +        "description": "The cryptographic material of a key itself cannot be changed. In order to perform this operation, the key must already exist in the Key Vault.",
I probably should have worded it as this comment https://github.com/Azure/azure-rest-api-specs/pull/1114/files/08da994f2d15e01c3d1c9d54c64fe172857dc15d#diff-778ad7ebcca7d8ff16a50b1ef232a622

2017-04-12 23:00 UTC, BrucePerlerMS commented
Hi @pomortaz, 
Please have a look at the swagger updates here. I'm also about to sync with some placeholder descriptions for the Certificate operations, which are thin on detail. 
Thanks,
Bruce

2017-04-13 16:09 UTC, BrucePerlerMS commented on keyvault/2016-10-01/swagger/keyvault.json
> +        "description": " ",
I've gone through the entire file and filled in placeholders, per the note below. Working with @pomortaz to get fuller descriptions as the responsibility for this is with the dev team.

2017-04-13 16:12 UTC, BrucePerlerMS commented
@pomortaz - when I began editing the swagger file I found most of the description content was in the "description" field on the operation and there was no "summary" field. I've edited the descriptions, created summaries for all and have placeholder descriptions for many of the CERT resource ops due to lack of details. 

The swagger file is to contain only language neutral descriptions. This way the language specific info can be added in a downstream step using overwrites. For instance, for REST, the guidance about using nextLink is contained in the overwrite for ops that return lists / sets.

2017-04-18 16:37 UTC, pomortaz commented
@BrucePerlerMS the changes look good. Thanks!
However, please do not check in the changes without filling in the cert descriptions.

2017-04-18 16:48 UTC, BrucePerlerMS commented
Hi Pooneh,
The content for the cert descriptions need to come from your team. I'd fill them in if I had the details.
😊 Bruce

Sent from my Windows Phone
________________________________
From: Pooneh Mortazavi<mailto:notifications@github.com>
Sent: ‎4/‎18/‎2017 9:37 AM
To: Azure/azure-rest-api-specs<mailto:azure-rest-api-specs@noreply.github.com>
Cc: Bruce Perler<mailto:Bruce.Perler@microsoft.com>; Mention<mailto:mention@noreply.github.com>
Subject: Re: [Azure/azure-rest-api-specs] Bruceper work (#1114)


@BrucePerlerMS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBrucePerlerMS&data=02%7C01%7CBruce.Perler%40microsoft.com%7Cfd1fae139dff4850968808d48679391c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636281302584405381&sdata=ONe9SDPhGfiPoe%2BS%2FNSPnuLQzrWOes4TPtAvNW3gC5c%3D&reserved=0> the changes look good. Thanks!
However, please do not check in the changes without filling in the cert descriptions.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F1114%23issuecomment-294903785&data=02%7C01%7CBruce.Perler%40microsoft.com%7Cfd1fae139dff4850968808d48679391c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636281302584405381&sdata=NpkF0FoQrgnsbyRbczQT0WGmNBlyLPd6T8XFN4cAvB8%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALf7kBxyPqEot3f2mJQ52wTQxejsMY1pks5rxObQgaJpZM4M71Iy&data=02%7C01%7CBruce.Perler%40microsoft.com%7Cfd1fae139dff4850968808d48679391c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636281302584405381&sdata=GkLX72REERYhiFANZC%2BsH28gTUfmaojKgRmtvtcADQc%3D&reserved=0>.

2017-04-25 17:37 UTC, dsgouda commented
@BrucePerlerMS @pomortaz 
Do we have any updates here, please reply soon since the PR has been idle for almost a week now.

2017-04-25 19:40 UTC, BrucePerlerMS commented
This is an important PR that is being worked with by the Azure Key Vault team. Please be patient with the process.

Thank you,
Bruce

From: Deepak Shankargouda [mailto:notifications@github.com]
Sent: Tuesday, April 25, 2017 10:37 AM
To: Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com>
Cc: Bruce Perler <Bruce.Perler@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [Azure/azure-rest-api-specs] Bruceper work (#1114)


@BrucePerlerMS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBrucePerlerMS&data=02%7C01%7CBruce.Perler%40microsoft.com%7C2a5988c9df7341ab823408d48c01bc01%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636287386464533826&sdata=uFXJsAEQceFWVmb9Ck6PfnbBkaOzJvyAXGb4BPkDIRU%3D&reserved=0> @pomortaz<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpomortaz&data=02%7C01%7CBruce.Perler%40microsoft.com%7C2a5988c9df7341ab823408d48c01bc01%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636287386464533826&sdata=Phpwba19Hw7AfTT%2Fq07jrBlPZrd3GACaREA%2BY3AqD9E%3D&reserved=0>
Do we have any updates here, please reply soon since the PR has been idle for almost a week now.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F1114%23issuecomment-297107760&data=02%7C01%7CBruce.Perler%40microsoft.com%7C2a5988c9df7341ab823408d48c01bc01%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636287386464533826&sdata=g5dQOMGGxujSwiqHSHam1qp31HD%2BOPjmQzwVLiaAGQc%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALf7kMk6xnFUcZCQUYRQR9A-J8Mh9e1Cks5rzi9SgaJpZM4M71Iy&data=02%7C01%7CBruce.Perler%40microsoft.com%7C2a5988c9df7341ab823408d48c01bc01%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636287386464533826&sdata=5SPHhsi6ZrzoBvOgJ%2BVVU02bqApiuocMAuuBv3uoV%2Fk%3D&reserved=0>.

2017-04-26 22:06 UTC, BrucePerlerMS commented
@pomortaz - I've discussed this swagger file with the AKV prod team and we've determined that it should be merged as is. The less-than-complete Cert Resource descriptions will be addressed in a separate process. Please sign-off.

#sign-off

2017-04-26 22:34 UTC, dsgouda approved these changes

2017-04-26 22:35 UTC, merged

2017-04-26 22:38 UTC, AutorestCI commented
No modification for Ruby

2017-04-26 22:38 UTC, AutorestCI commented
No modification for NodeJS

2017-04-26 22:39 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1114)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1115