[Storage] Added support for https traffic only.
Azure/azure-rest-api-specs pull request #1120
Opened 2017-04-14 11:16 UTC by JasonYang-MSFT

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-04-18 01:21 UTC, vishrutshah requested changes
File is not semantically correct. Please review https://travis-ci.org/Azure/azure-rest-api-specs/jobs/222040448

2017-04-18 01:21 UTC, vishrutshah commented on arm-storage/2016-12-01/swagger/storage.json
> +          "default": "false",
Is this "false" a string false expected from service?

2017-04-18 01:21 UTC, vishrutshah commented on arm-storage/2016-12-01/swagger/storage.json
> +          "default": "false",
same as above

2017-04-19 03:42 UTC, JasonYang-MSFT commented on arm-storage/2016-12-01/swagger/storage.json
> +          "default": "false",
Changed to "default": false.

2017-04-19 21:51 UTC, vishrutshah commented
@JasonYang-MSFT This changes looks good to me. 

Although there are linter errors from the swagger not related to your changes, I have opened a bug https://github.com/Azure/azure-rest-api-specs/issues/1141 and assign to you or your team to triage and decide. Let us know if you need any more information. Thanks

2017-04-19 21:53 UTC, vishrutshah approved these changes
LGTM!

2017-04-19 21:54 UTC, merged

2017-04-19 21:58 UTC, AutorestCI commented
No modification for NodeJS

2017-04-19 21:58 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1120)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/761

2017-04-19 21:58 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1120)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1095