Update Sql capabilities API to include elastic pool edition capabilities
Azure/azure-rest-api-specs pull request #1127
Opened 2017-04-15 00:37 UTC by nathannfan

Elastic Pool edition capabilities were recently lit up in canary clusters, and will soon be in production.  Also, temporarily removing APIs that are not yet public in production from compositeSql.json.

### PR information
- [ x] The title of the PR is clear and informative.
- [x ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x ] If applicable, the PR references the bug/issue that it fixes.
- [x ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x ] My spec meets the review criteria:
  - [x ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-04-15 00:39 UTC, nathannfan commented
SDK Pull Request: https://github.com/Azure/azure-sdk-for-net/pull/3078

2017-04-17 16:55 UTC, dsgouda commented on arm-sql/compositeSql.json
> -    "./2015-05-01-preview/swagger/blobAuditingPolicies.json",
Are you merging these into a single swagger? If not, are ```failoverGroups.json``` or ```virtualNetworkRules.json``` going to be used anywhere?
@vishrutshah will this affect the Ruby builds?

2017-04-17 16:56 UTC, dsgouda requested changes
Just have a question, other than that looks very good!

2017-04-17 18:29 UTC, nathannfan commented on arm-sql/compositeSql.json
> -    "./2015-05-01-preview/swagger/blobAuditingPolicies.json",
So these APIs aren't yet live in production, so I want to remove them from the compositeSql.json file for now until we're ready to actually use the client they'll generate.  Is that okay?

2017-04-17 23:02 UTC, dsgouda commented on arm-sql/compositeSql.json
> -    "./2015-05-01-preview/swagger/blobAuditingPolicies.json",
In that case, consider deleting the unused files and revert whenever you need them.

2017-04-17 23:27 UTC, nathannfan commented on arm-sql/compositeSql.json
> -    "./2015-05-01-preview/swagger/blobAuditingPolicies.json",
Is that a blocker?  It's a reasonable thing to do, but I didn't check in these files, and they both already went through the Pull request review process, so I'd hate for anyone to have to review already-reviewed files.  

If there's a policy against having swagger files not referenced by the composite file, we may have an issue later on, as we have two versions of some APIs and I will be adding the new version and replacing the reference to the old version in the composite file, but not deleting the old file.

2017-04-18 21:29 UTC, dsgouda commented on arm-sql/compositeSql.json
> -    "./2015-05-01-preview/swagger/blobAuditingPolicies.json",
Had offline chat with reviewers and we think this should be okay. I need to point out however, that these would be breaking changes.

2017-04-18 21:29 UTC, dsgouda approved these changes

2017-04-18 21:29 UTC, merged

2017-04-18 21:33 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1127)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/757

2017-04-18 21:34 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1127)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1091

2017-04-18 21:34 UTC, AutorestCI commented
No modification for NodeJS