Suppression list paging
Azure/azure-rest-api-specs pull request #1144
Opened 2017-04-20 03:41 UTC by cohnmarc

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-04-20 03:41 UTC, msftclas commented
@cohnmarc,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-04-20 16:29 UTC, olydis commented
@cohnmarc Please complete the checklist. Note that there are CI errors that made me wonder: You updated the old Swagger (2017-03-31) to match the new one (2017-04-19) exactly (was that intended? You want to have a breaking change in an existing API version?). However, the examples for 2017-03-31 don't match the changes you did (paging), so our model validation fails.

2017-04-21 01:13 UTC, cohnmarc commented
Rolled back version 2017-03-31 swagger output. It was incorrectly commited

2017-04-21 16:47 UTC, vishrutshah requested changes
Changes look good. Just left few feedback. 

Also opened a bug in our tool that seems like not interpreting the type in query parameters. Ref: https://github.com/Azure/oav/issues/111

2017-04-21 16:47 UTC, vishrutshah commented on arm-advisor/2017-04-19/swagger/advisor.json
> +						"description": "The number of suppressions per page if a paged version of this API is being used.",
I believe the `$top` would be `The maximum number of suppression to return from the operation`. Now if your paging mechanism accommodates 50 iteams per page and user has asked for 55 then you do paging and if user has asked for 45 then you do not. Correct me if i am misunderstanding `$top` usage

2017-04-21 16:47 UTC, vishrutshah commented on arm-advisor/2017-04-19/swagger/advisor.json
> +						"type": "integer"
You should also add ` "format": "int32"`. That way typed languages can efficiently use the memory for this variable.

2017-04-21 16:47 UTC, vishrutshah commented on arm-advisor/2017-04-19/swagger/advisor.json
> +						"description": "The page-continuation token to use with a paged version of this API.",
I am not sure whether we want to say `with a paged version of this API`. I'd prefer only `The page-continuation token`

2017-04-21 17:12 UTC, cohnmarc commented on arm-advisor/2017-04-19/swagger/advisor.json
> +						"description": "The number of suppressions per page if a paged version of this API is being used.",
Users can use both paged and not paged 2017-04-19. If user do not specify top then all items will be retuned up to limit

2017-04-21 17:17 UTC, cohnmarc commented on arm-advisor/2017-04-19/swagger/advisor.json
> +						"description": "The number of suppressions per page if a paged version of this API is being used.",
top is the requested by user page size per subscription, so users can limit how many items returned

2017-04-21 21:20 UTC, vishrutshah commented on arm-advisor/2017-04-19/swagger/advisor.json
> +						"description": "The number of suppressions per page if a paged version of this API is being used.",
okay then

2017-04-21 21:21 UTC, vishrutshah commented on arm-advisor/2017-04-19/swagger/advisor.json
> +						"description": "The number of suppressions per page if a paged version of this API is being used.",
okay

2017-04-21 22:25 UTC, vishrutshah approved these changes
Changes LGTM! 

Waiting for CI to pass.

2017-04-21 22:31 UTC, cohnmarc commented on arm-advisor/2017-04-19/swagger/advisor.json
> +						"description": "The page-continuation token to use with a paged version of this API.",
It is aligned with our recommendation paging message we already give to our customers

2017-04-21 22:32 UTC, merged

2017-04-21 22:36 UTC, AutorestCI commented
No modification for Python

2017-04-21 22:36 UTC, AutorestCI commented
No modification for Ruby

2017-04-21 22:37 UTC, AutorestCI commented
No modification for NodeJS