Add ARM Managed Appliaction (aka Appliances) spec
Azure/azure-rest-api-specs pull request #1179
Opened 2017-05-01 20:50 UTC by vivsriaus

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-05-01 22:28 UTC, jianghaolu requested changes

2017-05-01 22:28 UTC, jianghaolu commented on arm-resources/appliances/2016-09-01-preview/swagger/appliances.json
> +              "$ref": "#/definitions/Appliance"
a PATCH operation's request body cannot have required properties.

2017-05-01 22:28 UTC, jianghaolu commented on arm-resources/appliances/2016-09-01-preview/swagger/appliances.json
> +              "$ref": "#/definitions/Appliance"
a PATCH operation's request body cannot have required properties.

2017-05-01 22:28 UTC, jianghaolu commented on arm-resources/appliances/2016-09-01-preview/swagger/appliances.json
> +        "properties": {
Consider using x-ms-client-flatten to provide a better end user experience

2017-05-01 22:28 UTC, jianghaolu commented on arm-resources/appliances/2016-09-01-preview/swagger/appliances.json
> +        "properties": {
Consider using x-ms-client-flatten to provide a better end user experience

2017-05-01 22:28 UTC, jianghaolu commented on arm-resources/appliances/2016-09-01-preview/swagger/appliances.json
> +    "Resource": {
Please add a class level description.

2017-05-01 22:28 UTC, jianghaolu commented on arm-resources/appliances/2016-09-01-preview/swagger/appliances.json
> +  "paths": {
Please add `x-ms-examples` to all the APIs: https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/x-ms-examples.md.

2017-05-01 22:59 UTC, vivsriaus commented on arm-resources/appliances/2016-09-01-preview/swagger/appliances.json
> +    "Resource": {
Done

2017-05-01 23:01 UTC, vivsriaus commented on arm-resources/appliances/2016-09-01-preview/swagger/appliances.json
> +        "properties": {
Thanks. Done

2017-05-01 23:02 UTC, vivsriaus commented on arm-resources/appliances/2016-09-01-preview/swagger/appliances.json
> +        "properties": {
Makes sense

2017-05-01 23:02 UTC, vivsriaus commented on arm-resources/appliances/2016-09-01-preview/swagger/appliances.json
> +              "$ref": "#/definitions/Appliance"
Thanks!

2017-05-01 23:02 UTC, vivsriaus commented on arm-resources/appliances/2016-09-01-preview/swagger/appliances.json
> +              "$ref": "#/definitions/Appliance"
Fixed

2017-05-01 23:09 UTC, jianghaolu requested changes

2017-05-01 23:09 UTC, jianghaolu commented on arm-resources/managedapplications/2016-09-01-preview/swagger/managedapplications.json
> -            "required": true,
The properties in the body should also be all optional.
Imagine someone trying to patch an `Appliance`, with this API, that person has to provide `properties` and `kind`, which shouldn't be the case.
Many RPs find adding a `BlahPatchable` class helpful.

2017-05-01 23:41 UTC, vivsriaus commented on arm-resources/managedapplications/2016-09-01-preview/swagger/managedapplications.json
> -            "required": true,
Makes sense. Fixed

2017-05-01 23:49 UTC, jianghaolu approved these changes

2017-05-01 23:52 UTC, jianghaolu commented
Good work! Please let me know when you are done adding examples!

2017-05-02 00:16 UTC, vivsriaus commented
@jianghaolu Done adding examples

2017-05-02 00:22 UTC, jianghaolu commented
Thanks! Merging.

2017-05-02 00:22 UTC, merged

2017-05-02 00:26 UTC, AutorestCI commented
No modification for NodeJS

2017-05-02 00:26 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1179)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1132

2017-05-02 00:26 UTC, AutorestCI commented
No modification for Ruby