User Access Token resource
Azure/azure-rest-api-specs pull request #1213
Opened 2017-05-10 16:56 UTC by solankisamir

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-05-10 22:39 UTC, vishrutshah requested changes
@solankisamir Changes LGTM overall. Just left few comments to be addressed. Thanks!

2017-05-10 22:39 UTC, vishrutshah commented on arm-apimanagement/2016-10-10/swagger/apimusers.json
> +        "operationId": "Users_GetSharedAccessToken",
`Noun` part of `operationId` should match tags by conventions. Please update `operationId` to `UserToken_GetSharedAccessToken` or change the `tags` to `Users`. Former on will create operation group name as `UserToken` while later one creates operation group name as `Users`. So make sure sure which one you prefer in SDK

2017-05-10 22:39 UTC, vishrutshah commented on arm-apimanagement/2016-10-10/swagger/apimusers.json
> +     	  },
please format the json file

2017-05-10 22:39 UTC, vishrutshah commented on arm-apimanagement/2016-10-10/swagger/apimusers.json
> +        "description": "Gets the Shared Access Authorization Token for the User.",
please use keywords consitantly either "SharedAccessAuthorization" or "Shared Access Authorization"

Example: here v/s line 735

2017-05-10 22:39 UTC, vishrutshah commented on arm-apimanagement/2016-10-10/examples/ApiManagementUsersGetToken.json
> +         "expiry": "2017-05-09 18:20:08.7803554"
Does this follow the ISO8601 format of `yyyy-MM-ddTHH:mm:ssZ`?

2017-05-10 22:39 UTC, vishrutshah commented on arm-apimanagement/2016-10-10/examples/ApiManagementUsersGetToken.json
> +         "expiry": "2017-05-09 18:20:08.7803554"
Please see CI failure https://travis-ci.org/Azure/azure-rest-api-specs/jobs/230842021#L1107

2017-05-11 18:21 UTC, solankisamir commented
@vishrutshah can you take a look at the changes?

2017-05-11 20:33 UTC, vishrutshah commented
Changes looks good to me.

@ravbhatnagar Just wanted to make sure that "_Adding new operations into existing RP's existing api-version is considered to be an additive change from API Review Board perspective._" Please confirm. Thanks!

2017-05-12 21:10 UTC, vishrutshah commented
Verified with @ravbhatnagar offline that adding new operations is not a breaking change in the RPC perspective. 

Thanks @solankisamir for addressing the comments. LGTM!

2017-05-12 21:10 UTC, vishrutshah approved these changes

2017-05-12 21:11 UTC, merged

2017-05-12 21:15 UTC, AutorestCI commented
No modification for NodeJS

2017-05-12 21:15 UTC, AutorestCI commented
No modification for Ruby

2017-05-12 21:15 UTC, AutorestCI commented
No modification for Python