Job Relationship functionality for ADLA
Azure/azure-rest-api-specs pull request #1272
Opened 2017-06-01 17:39 UTC by begoldsm

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-06-01 19:01 UTC, veronicagg requested changes
Generally looks good! Few comments/questions inline. Thanks!
We're looking into the CI failure, expecting it to be fixed soon.

2017-06-01 19:01 UTC, veronicagg commented on arm-datalake-analytics/job/2016-11-01/swagger/job.json
> +        "related": {
is this changed considered a breaking change on the service side?

2017-06-01 19:01 UTC, veronicagg commented on arm-datalake-analytics/job/2016-11-01/examples/AdlPipelineGet.json
> +    "pipelineId": "076713da-9018-41ae-a3bd-9eab14e54d09",
this parameter is called pipelineIdentity in the spec file https://github.com/Azure/azure-rest-api-specs/pull/1272/files#diff-c3357f2ab384c3b8ab52d353d8b2724eR94 (https://travis-ci.org/Azure/azure-rest-api-specs/jobs/238436043#L1113)

2017-06-01 19:01 UTC, veronicagg commented on arm-datalake-analytics/job/2016-11-01/examples/AdlRecurrenceGet.json
> +    "recurrenceId": "8b3e4d71-022d-4cf4-91af-703b954d7b95"
this parameter is called recurrenceIdentity in the spec https://github.com/Azure/azure-rest-api-specs/pull/1272/files#diff-c3357f2ab384c3b8ab52d353d8b2724eR187 (error https://travis-ci.org/Azure/azure-rest-api-specs/jobs/238436043#L1120)

2017-06-01 19:01 UTC, veronicagg commented on arm-datalake-analytics/job/2016-11-01/swagger/job.json
> +    "JobRecurrenceInformation": {
Warning: Description is missing for this model,

2017-06-01 19:01 UTC, veronicagg commented on arm-datalake-analytics/job/2016-11-01/swagger/job.json
> +          "format": "uuid",
Has the usage of GUIDs for the properties where you're using them been review by the Azure API review board? Just want to make sure it's intentional and wanted.

2017-06-01 20:17 UTC, begoldsm commented on arm-datalake-analytics/job/2016-11-01/swagger/job.json
> +          "format": "uuid",
It hasn't been reviewed, I don't think, but these are Guids. Should they instead just be defined as strings even though they are in a GUID format?

2017-06-01 20:20 UTC, begoldsm commented on arm-datalake-analytics/job/2016-11-01/swagger/job.json
> +        "related": {
No because we are adding a new property, which is optional.

2017-06-01 20:20 UTC, begoldsm commented on arm-datalake-analytics/job/2016-11-01/examples/AdlRecurrenceGet.json
> +    "recurrenceId": "8b3e4d71-022d-4cf4-91af-703b954d7b95"
oops! good catch!

2017-06-01 20:23 UTC, begoldsm commented on arm-datalake-analytics/job/2016-11-01/examples/AdlPipelineGet.json
> +    "pipelineId": "076713da-9018-41ae-a3bd-9eab14e54d09",
Good catch!

2017-06-01 20:57 UTC, veronicagg commented on arm-datalake-analytics/job/2016-11-01/swagger/job.json
> +          "format": "uuid",
ok, if they are GUIDs and should be so, then it's good.

2017-06-01 21:02 UTC, veronicagg approved these changes
Changes look good, I'll wait on successful CI to merge. Thanks!

2017-06-01 21:05 UTC, begoldsm commented
@veronicagg thanks! Let me know if there is a CI failure that I need to look at once the infrastructure is fixed!

2017-06-02 19:11 UTC, begoldsm commented
@veronicagg CI is passing! woohoo! Merge away!

2017-06-05 17:15 UTC, merged

2017-06-05 17:18 UTC, AutorestCI commented
No modification for Ruby

2017-06-05 17:18 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1272)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1204

2017-06-05 17:18 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-node.svg?branch=RestAPI-PR1272)](https://travis-ci.org/AutorestCI/azure-sdk-for-node) https://github.com/Azure/azure-sdk-for-node/pull/2188