Swagger spec for Azure SQL restore
Azure/azure-rest-api-specs pull request #1279
Opened 2017-06-02 22:50 UTC by pixia

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-06-02 22:50 UTC, msftclas commented
@pixia,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-06-02 22:55 UTC, jaredmoo commented
@nathannfan FYI

We will likely have several validation warnings, I will look at these.

2017-06-05 17:08 UTC, sergey-shandar requested changes
There are syntax errors in this PS https://travis-ci.org/Azure/azure-rest-api-specs/jobs/238944872. @pixie could you fix them?
```
  2) External file or url references ("$ref") in a swagger spec: /home/travis/build/Azure/azure-rest-api-specs/arm-sql/2014-04-01/swagger/backupLongTermRetentionPolicies.json should be completely resolvable.:
     Uncaught Error: /home/travis/build/Azure/azure-rest-api-specs/arm-sql/2014-04-01/swagger/backupLongTermRetentionPolicies.json has references that cannot be resolved. They are as follows: 
'Error parsing /home/travis/build/Azure/azure-rest-api-specs/arm-sql/2014-04-01/swagger/backupLongTermRetentionPolicies.json \nmissed comma between flow collection entries at line 186, column 21:\n                        "enum": [\n                        ^'
      at test/syntax.js:142:17
      at node_modules/call-me-maybe/index.js:13:28
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  3) External file or url references ("$ref") in a swagger spec: /home/travis/build/Azure/azure-rest-api-specs/arm-sql/2014-04-01/swagger/sql.core.json should be completely resolvable.:
     Uncaught Error: /home/travis/build/Azure/azure-rest-api-specs/arm-sql/2014-04-01/swagger/sql.core.json has references that cannot be resolved. They are as follows: 
'Error opening file "/home/travis/build/Azure/azure-rest-api-specs/arm-sql/2014-04-01/examples/DatabaseCreateLongTermRetentionRestore.json" \nENOENT: no such file or directory, open \'/home/travis/build/Azure/azure-rest-api-specs/arm-sql/2014-04-01/examples/DatabaseCreateLongTermRetentionRestore.json\''
```

2017-06-07 18:31 UTC, sergey-shandar commented
@pixie Could resolve merge conflicts?

2017-06-07 21:08 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionPolicies.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionVaults.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backups.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/sql.core.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **2**


Thanks for your co-operation.

2017-06-07 22:26 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionPolicies.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionVaults.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backups.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/sql.core.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


Thanks for your co-operation.

2017-06-07 22:29 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionPolicies.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionVaults.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backups.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/sql.core.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


Thanks for your co-operation.

2017-06-07 23:18 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionPolicies.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionVaults.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backups.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/sql.core.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


Thanks for your co-operation.

2017-06-07 23:55 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionPolicies.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionVaults.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backups.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/sql.core.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


Thanks for your co-operation.

2017-06-08 00:38 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionPolicies.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionVaults.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backups.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/sql.core.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


Thanks for your co-operation.

2017-06-08 00:38 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionPolicies.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionVaults.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backups.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/sql.core.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


Thanks for your co-operation.

2017-06-08 00:44 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionPolicies.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionVaults.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/backups.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


File: `arm-sql/2014-04-01/swagger/sql.core.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


Thanks for your co-operation.

2017-06-13 18:46 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionPolicies.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **1**


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionVaults.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **1**


File: `arm-sql/2014-04-01/swagger/backups.json`
Number of linter errors/warnings _before_ the PR: **2**
Number of linter errors/warnings _after_ the PR: **2**


File: `arm-sql/2014-04-01/swagger/sql.core.json`
Number of linter errors/warnings _before_ the PR: **24**
Number of linter errors/warnings _after_ the PR: **24**


Thanks for your co-operation.

2017-06-13 19:22 UTC, sergey-shandar commented
I'm still trying to find out why build failing https://travis-ci.org/Azure/azure-rest-api-specs/builds/240606820?utm_source=github_status&utm_medium=notification

2017-06-14 22:39 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionPolicies.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **1**


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionVaults.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **1**


File: `arm-sql/2014-04-01/swagger/backups.json`
Number of linter errors/warnings _before_ the PR: **2**
Number of linter errors/warnings _after_ the PR: **2**


File: `arm-sql/2014-04-01/swagger/sql.core.json`
Number of linter errors/warnings _before_ the PR: **24**
Number of linter errors/warnings _after_ the PR: **24**


Thanks for your co-operation.

2017-06-15 22:16 UTC, sergey-shandar approved these changes

2017-06-15 22:17 UTC, jaredmoo commented
Let me review again before merge. Thx

2017-06-15 22:20 UTC, jaredmoo requested changes
Just 1 error to fix.

2017-06-15 22:20 UTC, jaredmoo commented on arm-sql/2014-04-01/swagger/backups.json
> +                    "type": "integer",
This should be "string" instead. (And remove format int64 below).

2017-06-15 22:33 UTC, sergey-shandar approved these changes

2017-06-15 22:40 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionPolicies.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **1**


File: `arm-sql/2014-04-01/swagger/backupLongTermRetentionVaults.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **1**


File: `arm-sql/2014-04-01/swagger/backups.json`
Number of linter errors/warnings _before_ the PR: **2**
Number of linter errors/warnings _after_ the PR: **2**


File: `arm-sql/2014-04-01/swagger/sql.core.json`
Number of linter errors/warnings _before_ the PR: **24**
Number of linter errors/warnings _after_ the PR: **24**


Thanks for your co-operation.

2017-06-15 22:42 UTC, jaredmoo approved these changes

2017-06-15 23:28 UTC, merged