[Azure Analysis Services] Replace backup from configuration object to container Uri string
Azure/azure-rest-api-specs pull request #1287
Opened 2017-06-07 20:24 UTC by taiwu

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-06-07 20:24 UTC, msftclas commented
@__taiwu__,
Thanks for your contribution. It looks like you are a Microsoft vendor. To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

The agreement will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-06-07 20:37 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-analysisservices/2016-05-16/swagger/analysisservices.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **0**


Thanks for your co-operation.

2017-06-07 22:49 UTC, vishrutshah requested changes

2017-06-07 22:49 UTC, vishrutshah commented on arm-analysisservices/2016-05-16/swagger/analysisservices.json
> -        "backupConfiguration": {
I see the you are removing the existing property. This potentially will be a breaking change in the generated SDK. 

Breaking changes are not recommended without updating the api-version.

2017-06-08 22:57 UTC, taiwu commented on arm-analysisservices/2016-05-16/swagger/analysisservices.json
> -        "backupConfiguration": {
So should I create another json file under the new version folder or directly update the version in this file?

2017-06-08 23:53 UTC, vishrutshah commented on arm-analysisservices/2016-05-16/swagger/analysisservices.json
> -        "backupConfiguration": {
@taiwu Yes please. Follow the guidelines outlined https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md#filenames-and-folder-structure .

Please make sure you create 2 commits. One with just copy of the old swagger into the new folder and second with the changes to help us review the changes only. Thanks.

2017-06-12 23:03 UTC, taiwu commented on arm-analysisservices/2016-05-16/swagger/analysisservices.json
> -        "backupConfiguration": {
@vishrutshah could you please take a look at the pull request?
https://github.com/Azure/azure-rest-api-specs/pull/1296

2017-06-12 23:27 UTC, vishrutshah commented on arm-analysisservices/2016-05-16/swagger/analysisservices.json
> -        "backupConfiguration": {
@taiwu I'd like to close this PR in favor of #1296.

2017-06-12 23:27 UTC, closed without merging