This is for adding swagger for OperationsManagement RP.
Azure/azure-rest-api-specs pull request #1319
Opened 2017-06-16 19:30 UTC by dashimi16

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-06-16 19:30 UTC, msftclas commented
@__dashimi16__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

It will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-06-16 19:40 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-operationsmanagement/2015-11-01-preview/Swagger/OperationsManagement.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **18**


File: `arm-operationsmanagement/2017-03-03-preview/Swagger/OperationsManagement.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **18**


Thanks for your co-operation.

2017-06-19 19:36 UTC, vishrutshah requested changes

2017-06-19 19:36 UTC, vishrutshah commented on arm-operationsmanagement/compositeOperationsManagement.json
> +    "./2015-11-01-preview/swagger/OperationsManagement.json",
Why are you adding two api-version of same RP into composite swagger?

2017-06-19 19:36 UTC, vishrutshah commented on arm-operationsmanagement/2017-03-03-preview/Swagger/OperationsManagement.json
> +{
Could you please follow the guidelines outlined https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md#filenames-and-folder-structure .

Please make sure you create 3 commits. 
One with just api-version `2015-11-01-preview` 
Second with copy of `2015-11-01-preview` api-version into folder name `2017-03-03-preview`
Third with updating the only changes into the new api-version. We should only review the diffs between api-versions. 
Fourth with the adding [x-ms-examples](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/x-ms-examples.md#why-x-ms-examples). 

 That's greatly help us in reviewing the changes. Thanks.

2017-06-19 19:37 UTC, vishrutshah commented
Some general questions:

- [ ] Was this RP reviewed by One API & ARM Review team?
- [ ] Are both the version of api live i.e. deployed in production?

2017-06-19 19:39 UTC, vishrutshah commented
@dashimi16 Make sure to sign the cla if you haven't already.

2017-06-20 17:58 UTC, dashimi16 commented on arm-operationsmanagement/2017-03-03-preview/Swagger/OperationsManagement.json
> +{
I will cancel this pull request and then create one with at a time.

2017-06-20 17:59 UTC, closed without merging

2017-06-20 18:00 UTC, dashimi16 commented
Closing this pull request since got feedback for smaller commit. Will make that change and publish a new pull request. Thanks for your time in reviewing the pull request.