Add DataMasking swagger and examples
Azure/azure-rest-api-specs pull request #1321
Opened 2017-06-16 23:13 UTC by nathannfan

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-06-16 23:19 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/dataMasking.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **3**


Thanks for your co-operation.

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/examples/DataMaskingPolicyCreateOrUpdate.json
> +            "maskingLevel": null
no need, this parameter is deprecated

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/examples/DataMaskingPolicyCreateOrUpdate.json
> +            "applicationPrincipals": null,
no need, this parameter is deprecated

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/examples/DataMaskingPolicyCreateOrUpdate.json
> +    "api-version": "2014-04-01"
what about sending: dataMaskingState": "Enabled"?

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/examples/DataMaskingPolicyCreateOrUpdate.json
> +{
what is the difference  between this file and " arm-sql/2014-04-01/examples/DataMaskingPolicyCreateOrUpdate.json"?

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/examples/DataMaskingPolicyCreateOrUpdateMin.json
> +      "201": {
I don't think we return 201 in any case.

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/examples/DataMaskingRuleCreateOrUpdateDefaultMax.json
> +            "columnName": "test2",
I would change to:
   "columnName": "test1",

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/examples/DataMaskingRuleCreateOrUpdateDefaultMax.json
> +            "aliasName": "nickname",
please remove. it is deprecated.

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +        "description": "Provides create, read, update and delete functionality for Azure SQL Database datamasking policies.",
.. and rules

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +        "title": "Azure SQL Database Datamasking Policies",
.. and rules

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                "Create or update data masking policy max": { "$ref": "../examples/DataMaskingPolicyCreateOrUpdateMax.json" },
where do you reference DataMaskingPolicyCreateOrUpdate.json?

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                    "201": {
I'm not sure we ever return this response code.

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                        "description": "The name of the database."
.. on which the data masking policy is set

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                        "description": "The name of the database."
..... on which the data masking policy is set

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                "Create/Update data masking policy for text": { "$ref": "../examples/DataMaskingRuleCreateOrUpdateText.json" },
data masking rule.

here and below.

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                    "DataMaskingPolicies"
DataMaskingRules

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                "description": "Creates or updates an Azure SQL Server Firewall rule.",
database datamasking

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                        "type": "string",
can be enum from:
{Default , CCN, SSN, Email, Email, Text}

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                "applicationPrincipals": {
deprecated

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                "maskingLevel": {
deprecated

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                "aliasName": {
deprecated

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                    "description": "The numberFrom property of the masking rule. Required if maskingFunction is set to Number, otherwise ignored."
"this parameter will be ignored"?
here and below

2017-06-18 12:00 UTC, yaakoviyun commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +    "securityDefinitions": {
this is not related to Data masking. isn't is can be retrieved from some share location?

2017-06-18 15:41 UTC, jaredmoo commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +    "securityDefinitions": {
It's required in every file.

2017-06-19 17:53 UTC, nathannfan commented on arm-sql/2014-04-01/examples/DataMaskingPolicyCreateOrUpdate.json
> +    "api-version": "2014-04-01"
Examples don't need to cover every possible value of properties

2017-06-19 17:54 UTC, nathannfan commented on arm-sql/2014-04-01/examples/DataMaskingPolicyCreateOrUpdate.json
> +            "maskingLevel": null
Still needs to be documented if it's being returned by the API

2017-06-19 17:54 UTC, nathannfan commented on arm-sql/2014-04-01/examples/DataMaskingPolicyCreateOrUpdate.json
> +            "applicationPrincipals": null,
Still needs to be documented if it's being returned by the API

2017-06-19 17:56 UTC, nathannfan commented on arm-sql/2014-04-01/examples/DataMaskingPolicyCreateOrUpdateMin.json
> +      "201": {
Yeah, I had 201 in case it was likely to change, but looks like it's pretty solidified so I'll remove

2017-06-19 17:57 UTC, nathannfan commented on arm-sql/2014-04-01/examples/DataMaskingRuleCreateOrUpdateDefaultMax.json
> +            "aliasName": "nickname",
If it's being returned by the API, needs to be documented as a deprecated parameter.

2017-06-19 18:02 UTC, nathannfan commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                "description": "Creates or updates an Azure SQL Server Firewall rule.",
Thanks

2017-06-19 18:32 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/dataMasking.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **3**


Thanks for your co-operation.

2017-06-19 21:56 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/dataMasking.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **3**


Thanks for your co-operation.

2017-06-19 21:59 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


Thanks for your co-operation.

2017-06-19 23:41 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/dataMasking.json`
Number of linter errors/warnings _before_ the PR: **0**
Number of linter errors/warnings _after_ the PR: **3**


Thanks for your co-operation.

2017-06-19 23:49 UTC, jaredmoo approved these changes

2017-06-20 17:12 UTC, yaakoviyun approved these changes

2017-06-20 17:16 UTC, yaakoviyun approved these changes

2017-06-20 18:19 UTC, nathannfan commented
@jianghaolu we've completed our internal review and checks are passing - could you please have a look?  Thanks!

2017-06-20 22:38 UTC, vishrutshah requested changes
@nathannfan Left some comments and questions. Please let me know what do you think. Thanks!

2017-06-20 22:38 UTC, vishrutshah commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                "id": {
Is this readOnly i.e server populated property?

2017-06-20 22:38 UTC, vishrutshah commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                    "description": "The alias name.  This is a legacy parameter and is no longer used."
Do service still returns this property on `GET` call?

2017-06-20 22:38 UTC, vishrutshah commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                    "description": "The rule state.  Also used to delete a rule.  To delete an existing rule, specify the schemaName, tableName, columnName, maskingFunction, and specify ruleState as
minor: two spaces between `state.` and `Also`

2017-06-20 22:38 UTC, vishrutshah commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                    "enum": [
Do we have any default value for enum?

2017-06-20 22:38 UTC, vishrutshah commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                    "enum": [
Do we have any default value for enum?

2017-06-20 22:38 UTC, vishrutshah commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                    "description": "If maskingFunction is set to Text, the number of characters to show unmasked in the beginning of the string.  Otherwise, this parameter will be ignored."
minor: 2 spaces between `string.` & `Otherwise` is unnecessary. Please format the file with one space

2017-06-20 22:38 UTC, vishrutshah commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                    "type": "string",
should this be integer as description suggest a potential number

2017-06-20 22:38 UTC, vishrutshah commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                "prefixSize": {
why not integer/number?

2017-06-20 22:38 UTC, vishrutshah commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                "operationId": "Databases_ListDataMaskingRules",
Should this be named as `Databases_ListByDataMaskingPolicy` ?

2017-06-20 22:38 UTC, vishrutshah commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +            "put": {
Just making sure here: This is not a long running operation. Right?

2017-06-20 22:38 UTC, vishrutshah commented on arm-sql/2014-04-01/swagger/dataMasking.json
> +                    "200": {
why no `default` response? Ref: https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#DefaultResponse

2017-06-20 22:56 UTC, nathannfan commented
Test comment

2017-06-20 23:41 UTC, nathannfan commented
For some reason github is not letting me reply to comments right now.

I see the you also have api-version 2015-05-01-preview. Is this feature not available in that api-version ?
> Correct, it is not available on that version.

minor: Although we not using tags directly but we'd prefer to keep tag as the same as NOUN part of the operationId. like here Databases
> For singleton resources, the pattern we've been told to use has been to set tags to the singleton resource, but have the operation id use the ParentResource_ListSingletonResource pattern.
See https://github.com/Azure/azure-rest-api-specs/blob/master/arm-sql/2014-04-01/swagger/sql.core.json#L977 and https://github.com/Azure/azure-rest-api-specs/blob/master/arm-sql/2014-04-01/swagger/geoBackupPolicies.json#L24

Feel free to refactor this parameter to a global parameter section to avoid repetition.
>

Is there any reason for not including default response code for any operations here?
>Is this required now?  We have it auto-generated in 2015-05-01-preview to document our error values, but we're actually fine with just passing through the error message and code coming from the API directly.

Just making sure here: This is not a long running operation. Right?
>Right.

why no default response? Ref: https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#DefaultResponse
>Is this required now?  We have it auto-generated in 2015-05-01-preview to document our error values, but we're actually fine with just passing through the error message and code coming from the API directly.

Should this be named as Databases_ListByDataMaskingPolicy ?
>I don't think so.  That would imply we're listing databases by data masking policy.  There's only one policy, and this is a child resource of that singleton, so Databases_ListDataMaskingRules makes the most sense.  

Otherwise the client would look like this client.DataMaskingRules.ListByDataMaskingPolicy("myrg", "myserver", "mydb"), but with no policy name, because policy name is always "default."  That's a bit confusing.

Is this readOnly i.e server populated property?
>Yes.  Fixed.

Do service still returns this property on GET call?
>Yes, unfortunately.

minor: two spaces between state. and Also
> k

Do we have any default value for enum?
> Behavior of this property is in the description.

Do we have any default value for enum?
>No, and it is required on every PUT.

why not integer/number?
>It is returned as a string by the API.

minor: 2 spaces between string. & Otherwise is unnecessary. Please format the file with one space
> k

should this be integer as description suggest a potential number
> The description already says this property is a number

2017-06-20 23:49 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/dataMasking.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **2**  Error(s): **1**


Thanks for your co-operation.

2017-06-20 23:54 UTC, nathannfan commented
@vishrutshah 

Regarding this question:  Should this be named as Databases_ListByDataMaskingPolicy ?

What if we did DataMaskingRules_CreateOrUpdate and DataMaskingRules_ListByDatabase?  Again, since the dataMaskingPolicy is singleton, it might be confusing the client to make it ListByDataMaskingPolicy and not require a DataMaskingPolicy name in the client parameters.

2017-06-21 00:38 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-sql/2014-04-01/swagger/dataMasking.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **2**  Error(s): **1**


Thanks for your co-operation.

2017-06-21 21:35 UTC, vishrutshah approved these changes
@nathannfan Thanks a lot for the detailed answers and addressing appropriate comments. 

Regarding the `default` response code, we should be fine as other swaggers don't have them for this api-version. Regarding the names, we are good 👍

2017-06-21 21:35 UTC, merged

2017-06-21 21:38 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-06-21 21:38 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-python

2017-06-21 21:39 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1321)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/810

2017-06-21 22:23 UTC, nathannfan commented
@vishrutshah Thanks, Vishrut!