VirtualNetworkGateway.json QOL fixes
Azure/azure-rest-api-specs pull request #1331
Opened 2017-06-20 17:30 UTC by henry416

PR exclusively for general QOL fixes for VirtualNetworkGateway.json

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-06-20 17:44 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-network/2017-06-01/swagger/virtualNetworkGateway.json`
Before the PR: Warning(s): **22**  Error(s): **11**
After the PR: Warning(s): **22**  Error(s): **11**


Thanks for your co-operation.

2017-06-20 18:08 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-network/2017-06-01/swagger/virtualNetworkGateway.json`
Before the PR: Warning(s): **22**  Error(s): **11**
After the PR: Warning(s): **22**  Error(s): **11**


Thanks for your co-operation.

2017-06-20 19:17 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter** Azure bot. I am here to help. My task to analyze the situation from the AutoRest linter perspective. Please review the below analysis result:


File: `arm-network/2017-06-01/swagger/virtualNetworkGateway.json`
Before the PR: Warning(s): **22**  Error(s): **11**
After the PR: Warning(s): **22**  Error(s): **11**


Thanks for your co-operation.

2017-06-21 00:31 UTC, dsgouda commented on arm-network/2017-06-01/swagger/virtualNetworkGateway.json
> +            "Succeeded",
Potential breaking change, please verify if that's okay

2017-06-26 22:44 UTC, henry416 commented
@dsgouda Normalized provisioning state across entire JSON

2017-06-26 23:04 UTC, dsgouda approved these changes
LGTM

2017-06-26 23:05 UTC, dsgouda commented
@azuresdkci Test this please

2017-06-26 23:08 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter Azure bot**. I am here to help. My task is to analyze the situation from the [AutoRest linter](https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest) perspective. Please review the below analysis result:


File: `arm-network/2017-06-01/swagger/virtualNetworkGateway.json`
Before the PR: Warning(s): **22**  Error(s): **11**
After the PR: Warning(s): **22**  Error(s): **11**


Know more about [AutoRest Linter Guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md).

Send <a href='mailto:vissha@microsoft.com?subject=Feedback%20|%20AutoRest%20Linter%20Azure%20Bot'>feedback</a> and make **AutoRest Linter Azure Bot** smarter day by day!

Thanks for your co-operation.

2017-06-27 16:52 UTC, salameer commented
@dsgouda 
are we good t o merge here?

2017-06-27 17:06 UTC, dsgouda commented
We are good, but I need to check why the travis build is failing, will investigate now.

2017-06-27 17:14 UTC, dsgouda commented
CI is reporting a failure to generate sdk for ruby, get a feeling it may have to do with using old command line args for AutoRest, will post my findings soon.

2017-06-27 18:33 UTC, dsgouda commented
@henry416 looks like you are updating `provisioningState` enum only here and not in the other json files which are a part of the corresponding composite. When generating the SDK, AutoRest expects to have exactly one unique `x-ms-enum` extension or the exact same definition repeated (like you have in virtualNetworkGateway.json), either update all definitions for `ProvisioningState` or undo this particular change. FYI The definition for `ProvisioningState` in networkWatcher.json has an additional enum value.

2017-06-27 18:33 UTC, dsgouda requested changes
enums need to be updated.

2017-06-29 21:34 UTC, salameer commented
ping @henry416

2017-06-29 21:38 UTC, henry416 commented
@salameer I am aware of this, however I am busy with other issues at the moment, I will take time when it is finished to deal with this.

2017-07-02 06:50 UTC, salameer commented
Sounds Good @henry416 

But please note that we'll have to close this pr by end of the Next week July 7th if this is not updated. and please feel free to open a new PR after that if your unable to make these changes by that time.

Thanks,

Samer

2017-07-07 20:25 UTC, salameer commented
Closing due to no response.

2017-07-07 20:25 UTC, closed without merging