[DO-NOT-MERGE][ACR]Add registry usages API and SKU update
Azure/azure-rest-api-specs pull request #1359
Opened 2017-06-28 16:27 UTC by djyou

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-06-28 16:37 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter Azure bot**. I am here to help. My task is to analyze the situation from the [AutoRest linter](https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest) perspective. Please review the below analysis result:


File: `arm-containerregistry/2017-06-01-preview/swagger/containerregistry.json`
Before the PR: Warning(s): **11**  Error(s): **1**
After the PR: Warning(s): **13**  Error(s): **1**


Know more about [AutoRest Linter Guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md).

Send <a href='mailto:vissha@microsoft.com?subject=Feedback%20|%20AutoRest%20Linter%20Azure%20Bot'>feedback</a> and make **AutoRest Linter Azure Bot** smarter day by day!

Thanks for your co-operation.

2017-06-28 16:41 UTC, djyou commented
@dsgouda I noticed the warning on naming `usages` to `listUsages` because it returns a list. The exact name should be ok to us either way but many other services have used `usages`. What is the guideline for this? /cc @SajayAntony

2017-06-28 17:49 UTC, dsgouda commented
@djyou for list operations, it is recommended you name the operationId as \*_list\*

2017-06-28 17:54 UTC, dsgouda commented on arm-containerregistry/2017-06-01-preview/swagger/containerregistry.json
> +        "name": {
nit: Feel free to mark the readOnly properties wherever applicable

2017-06-28 17:56 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter Azure bot**. I am here to help. My task is to analyze the situation from the [AutoRest linter](https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest) perspective. Please review the below analysis result:


File: `arm-containerregistry/2017-06-01-preview/swagger/containerregistry.json`
Before the PR: Warning(s): **11**  Error(s): **1**
After the PR: Warning(s): **13**  Error(s): **1**


Know more about [AutoRest Linter Guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md).

Send <a href='mailto:vissha@microsoft.com?subject=Feedback%20|%20AutoRest%20Linter%20Azure%20Bot'>feedback</a> and make **AutoRest Linter Azure Bot** smarter day by day!

Thanks for your co-operation.

2017-06-28 19:38 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter Azure bot**. I am here to help. My task is to analyze the situation from the [AutoRest linter](https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest) perspective. Please review the below analysis result:


File: `arm-containerregistry/2017-06-01-preview/swagger/containerregistry.json`
Before the PR: Warning(s): **11**  Error(s): **1**
After the PR: Warning(s): **11**  Error(s): **1**


Know more about [AutoRest Linter Guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md).

Send <a href='mailto:vissha@microsoft.com?subject=Feedback%20|%20AutoRest%20Linter%20Azure%20Bot'>feedback</a> and make **AutoRest Linter Azure Bot** smarter day by day!

Thanks for your co-operation.

2017-06-28 20:04 UTC, dsgouda approved these changes
LGTM

2017-06-28 20:04 UTC, dsgouda commented
@djyou Please let me know when you would like me to merge this.

2017-06-29 18:44 UTC, salameer commented
@djyou what's the ETA for the Merge?

2017-06-29 18:55 UTC, djyou commented
Still waiting for ARM's response on this new API. We can merge as soon as it is approved.

2017-06-29 21:15 UTC, salameer commented
Great! please let us know, and sorry for pushing on this, but we try our best to avoid having open PRs too long on this Repo :)

2017-06-30 17:02 UTC, ravbhatnagar commented
Looks good. ARM sign off.

2017-06-30 17:17 UTC, djyou commented
Thank you @ravbhatnagar.
@salameer @dsgouda Please merge.
/cc @SajayAntony

2017-06-30 21:30 UTC, dsgouda commented on arm-containerregistry/2017-06-01-preview/swagger/containerregistry.json
> +    "RegistryUsageListResult": {
How large is this list? Consider using `x-ms-pageable` if the page is large enough (>50 entries)

2017-06-30 21:31 UTC, dsgouda requested changes
Have a minor doubt I need to clarify

2017-06-30 21:32 UTC, djyou commented on arm-containerregistry/2017-06-01-preview/swagger/containerregistry.json
> +    "RegistryUsageListResult": {
2 entries.

2017-06-30 21:34 UTC, dsgouda commented on arm-containerregistry/2017-06-01-preview/swagger/containerregistry.json
> +    "RegistryUsageListResult": {
Thanks, no issues here then.

2017-06-30 21:34 UTC, dsgouda approved these changes

2017-06-30 21:34 UTC, merged

2017-06-30 21:38 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-ruby

2017-06-30 21:38 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1359)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1276