Private access services implementation
Azure/azure-rest-api-specs pull request #1362
Opened 2017-06-29 17:29 UTC by EvgenyAgafonchikov

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-06-29 17:35 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter Azure bot**. I am here to help. My task is to analyze the situation from the [AutoRest linter](https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest) perspective. Please review the below analysis result:


File: `arm-network/2017-06-01/swagger/privateAccessServices.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **2**  Error(s): **2**


File: `arm-network/2017-06-01/swagger/virtualNetwork.json`
Before the PR: Warning(s): **45**  Error(s): **17**
After the PR: Warning(s): **46**  Error(s): **17**


Know more about [AutoRest Linter Guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md).

Send <a href='mailto:vissha@microsoft.com?subject=Feedback%20|%20AutoRest%20Linter%20Azure%20Bot'>feedback</a> and make **AutoRest Linter Azure Bot** smarter day by day!

Thanks for your co-operation.

2017-06-29 22:05 UTC, veronicagg requested changes
Is the privateAccessServices.json operation already deployed to ARM?
x-ms-examples are missing in the new spec for swagger model validation - https://travis-ci.org/Azure/azure-rest-api-specs/jobs/248463464#L1328 
will you be adding them? More info about this validation at https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist.
Adding @ravbhatnagar in the review, since you're adding a new file.

2017-06-29 22:05 UTC, veronicagg commented on arm-network/2017-06-01/swagger/privateAccessServices.json
> +    "PrivateAccessServiceResult": {
is this model an azure resource? should id, name and type be read only? (if it's an azure resource, you may want to tag it as x-ms-azure-resource.

2017-06-30 09:00 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter Azure bot**. I am here to help. My task is to analyze the situation from the [AutoRest linter](https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest) perspective. Please review the below analysis result:


File: `arm-network/2017-06-01/swagger/privateAccessServices.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **0**  Error(s): **1**


File: `arm-network/2017-06-01/swagger/virtualNetwork.json`
Before the PR: Warning(s): **45**  Error(s): **17**
After the PR: Warning(s): **45**  Error(s): **17**


Know more about [AutoRest Linter Guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md).

Send <a href='mailto:vissha@microsoft.com?subject=Feedback%20|%20AutoRest%20Linter%20Azure%20Bot'>feedback</a> and make **AutoRest Linter Azure Bot** smarter day by day!

Thanks for your co-operation.

2017-06-30 09:28 UTC, EvgenyAgafonchikov commented on arm-network/2017-06-01/swagger/virtualNetwork.json
> +    "PrivateAccessServicePropertiesFormat": {
updated

2017-06-30 09:46 UTC, EvgenyAgafonchikov commented on arm-network/2017-06-01/swagger/virtualNetwork.json
> +        "privateAccessServices": {
Yes, it was. I've added spec extractions to clarify the changes, please find them in the top PR's comment.

2017-06-30 18:09 UTC, ravbhatnagar commented
ACK - ARM sign off. This has been already reviewed and approved by ARM.

2017-06-30 18:18 UTC, veronicagg requested changes
couple more comments, to make review easier, please add commits on top of existing instead of removing old commits and commiting again. I'll squash for the final merge anyway. thanks.

2017-06-30 18:18 UTC, veronicagg commented on arm-network/2017-06-01/examples/SubnetCreate.json
> +  "parameters": {
parameters are not properly specified in the example, please add "subnetName" to the parameters and "subnetParameters" with its properties "name" and "addessPrefix" inside.

2017-06-30 18:18 UTC, veronicagg commented on arm-network/2017-06-01/examples/SubnetPrivateAccessServiceCreate.json
> +  "parameters": {
similar comment as in the other example, missing required parameters, "subnetName", "subnetParamaters" with its properties "name", "addressPrefix" and "privateAccessServices" inside.

2017-07-03 07:19 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter Azure bot**. I am here to help. My task is to analyze the situation from the [AutoRest linter](https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest) perspective. Please review the below analysis result:


File: `arm-network/2017-06-01/swagger/privateAccessServices.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **0**  Error(s): **1**


File: `arm-network/2017-06-01/swagger/virtualNetwork.json`
Before the PR: Warning(s): **45**  Error(s): **17**
After the PR: Warning(s): **45**  Error(s): **17**


Know more about [AutoRest Linter Guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md).

Send <a href='mailto:vissha@microsoft.com?subject=Feedback%20|%20AutoRest%20Linter%20Azure%20Bot'>feedback</a> and make **AutoRest Linter Azure Bot** smarter day by day!

Thanks for your co-operation.

2017-07-03 07:27 UTC, EvgenyAgafonchikov commented on arm-network/2017-06-01/examples/SubnetCreate.json
> +  "parameters": {
Updated, please have a look. I think there should be no "name" property under "subnetParameters" as it is placed one level above

2017-07-03 07:28 UTC, EvgenyAgafonchikov commented on arm-network/2017-06-01/swagger/privateAccessServices.json
> +    "PrivateAccessServiceResult": {
updated as inherited from SubResource

2017-07-03 07:31 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter Azure bot**. I am here to help. My task is to analyze the situation from the [AutoRest linter](https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest) perspective. Please review the below analysis result:


File: `arm-network/2017-06-01/swagger/privateAccessServices.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **1**  Error(s): **2**


File: `arm-network/2017-06-01/swagger/virtualNetwork.json`
Before the PR: Warning(s): **45**  Error(s): **17**
After the PR: Warning(s): **45**  Error(s): **17**


Know more about [AutoRest Linter Guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md).

Send <a href='mailto:vissha@microsoft.com?subject=Feedback%20|%20AutoRest%20Linter%20Azure%20Bot'>feedback</a> and make **AutoRest Linter Azure Bot** smarter day by day!

Thanks for your co-operation.

2017-07-05 18:28 UTC, DeepakRajendranMsft commented
@veronicagg could you please take a look and merge if all comments have been resolved?

2017-07-05 18:45 UTC, veronicagg requested changes
thanks for addressing the comments. One more question, other than that looks good.

2017-07-05 18:45 UTC, veronicagg commented on arm-network/2017-06-01/swagger/privateAccessServices.json
> +    "PrivateAccessServiceResult": {
ok, thanks, is here a reason for name and type to not be read-only? https://travis-ci.org/Azure/azure-rest-api-specs/jobs/249523709#L1307

2017-07-05 18:50 UTC, DeepakRajendranMsft commented
@veronicagg I am working on a PR that adds read only properties for all SDN resources (nics, vnet, nsg, routes, lb) i will add them as part of that PR. Currently, none of the SDN resources have readonly flags.

2017-07-05 20:59 UTC, veronicagg commented
@DeepakRajendranMsft ok, thanks.

2017-07-05 21:00 UTC, veronicagg approved these changes

2017-07-05 21:00 UTC, merged

2017-07-05 21:03 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-07-05 21:04 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1362)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/827

2017-07-05 21:04 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1362)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1284