Adding migrate to AAD API Spec.
Azure/azure-rest-api-specs pull request #1381
Opened 2017-07-06 08:08 UTC by ambhat

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-07-06 08:08 UTC, msftclas commented
@ambhat,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-07-06 08:24 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter Azure bot**. I am here to help. My task is to analyze the situation from the [AutoRest linter](https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest) perspective. Please review the below analysis result:


File: `arm-recoveryservicessiterecovery/2016-08-10/swagger/service.json`
Before the PR: Warning(s): **95**  Error(s): **15**
After the PR: Warning(s): **95**  Error(s): **15**


Know more about [AutoRest Linter Guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md).

Send <a href='mailto:azure-swag-tooling@microsoft.com?subject=Feedback%20|%20AutoRest%20Linter%20Azure%20Bot'>feedback</a> and make **AutoRest Linter Azure Bot** smarter day by day!

Thanks for your co-operation.

2017-07-06 17:09 UTC, anuchandy requested changes

2017-07-06 17:09 UTC, anuchandy commented on arm-recoveryservicessiterecovery/2016-08-10/swagger/service.json
> +        "x-ms-long-running-operation": true,
Just curious, i didn't see 204 begin declared as a response type for any of the other POST LRO in the same swagger? If not intended, please remove it.

2017-07-10 15:52 UTC, anuchandy commented on arm-recoveryservicessiterecovery/2016-08-10/swagger/service.json
> +        "x-ms-long-running-operation": true,
@ambhat please confirm

2017-07-10 20:20 UTC, fearthecowboy commented
ATTENTION REQUIRED.
-------------

We have changed the `default` branch in the `azure-rest-api-specs` repository to use the branch labeled `current`.

This PR is opened against the `master` branch.

You have two options: 
1. Keep this PR open, and complete the review process as normal, and once this PR is merged against the `master` branch, we (@olydis & @fearthecowboy)  will create a PR against the current branch and make any updates required to work in the newly reorganized default branch.  

2. Close this PR and create a new one. That would mean pulling in the changes from the new default branch `current` moving any files and switching to the configuration-based layout.  (You are more than welcome to choose option 2, but I don't expect anyone to do that)

Either way, the work you are currently doing against the previous default branch `master` will be the last PR against that branch that we will accept and all new PRs will go against the new default branch  `current`.

If you have any questions or concerns, ping @fearthecowboy or @olydis (or go ask on the `#swagger` channel in slack) ASAP and we can help you thru the process.

2017-07-11 21:42 UTC, salameer commented
@ambhat this PR has been inactive for a while, please respond ASAP to  avoid having this PR closed due to inactivity

2017-07-12 06:28 UTC, ambhat commented
Hi,
Sorry for the late reply. I was OOF for few days which caused the delay in response.

2017-07-12 06:29 UTC, ambhat commented
Also, if there are no more comments apart from the above one (204), I want to get this PR merged rather than create a new branch etc.

2017-07-13 00:14 UTC, anuchandy commented on arm-recoveryservicessiterecovery/2016-08-10/swagger/service.json
> +        "x-ms-long-running-operation": true,
thanks LGTM

2017-07-13 00:15 UTC, anuchandy approved these changes

2017-07-13 00:17 UTC, merged

2017-07-13 00:20 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-python

2017-07-13 00:20 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-ruby

2017-07-13 00:21 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node