2017-03-01 api version of apim spec
Azure/azure-rest-api-specs pull request #1390
Opened 2017-07-07 21:44 UTC by solankisamir

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-07-07 22:01 UTC, solankisamir commented
@fearthecowboy I have opened a new PR for the closed PR https://github.com/Azure/azure-rest-api-specs/pull/1286, which you had reviewed. This includes fixes after generating the .net client.

2017-07-07 22:25 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter Azure bot**. I am here to help. My task is to analyze the situation from the [AutoRest linter](https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest) perspective. Please review the below analysis result:


File: `arm-apimanagement/2017-03-01/swagger/apimanagement.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **2**  Error(s): **1**


File: `arm-apimanagement/2017-03-01/swagger/apimapis.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **12**  Error(s): **7**


File: `arm-apimanagement/2017-03-01/swagger/apimauthorizationservers.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **1**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimbackends.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **3**  Error(s): **3**


File: `arm-apimanagement/2017-03-01/swagger/apimcertificates.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **1**  Error(s): **1**


File: `arm-apimanagement/2017-03-01/swagger/apimdeployment.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **2**  Error(s): **1**


File: `arm-apimanagement/2017-03-01/swagger/apimemailtemplate.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **2**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimgroups.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **4**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimidentityprovider.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **0**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimloggers.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **2**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimnetworkstatus.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **0**  Error(s): **1**


File: `arm-apimanagement/2017-03-01/swagger/apimopenidconnectproviders.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **1**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimproducts.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **14**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimproperties.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **2**  Error(s): **1**


File: `arm-apimanagement/2017-03-01/swagger/apimquotas.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **0**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimreports.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **0**  Error(s): **1**


File: `arm-apimanagement/2017-03-01/swagger/apimsubscriptions.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **1**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimtenant.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **9**  Error(s): **4**


File: `arm-apimanagement/2017-03-01/swagger/apimusers.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **3**  Error(s): **2**


Know more about [AutoRest Linter Guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md).

Send <a href='mailto:azure-swag-tooling@microsoft.com?subject=Feedback%20|%20AutoRest%20Linter%20Azure%20Bot'>feedback</a> and make **AutoRest Linter Azure Bot** smarter day by day!

Thanks for your co-operation.

2017-07-07 23:05 UTC, salameer commented
Assigning to Garret since he already has context

2017-07-08 01:28 UTC, azuresdkci commented
Hi There,

I am the **AutoRest Linter Azure bot**. I am here to help. My task is to analyze the situation from the [AutoRest linter](https://marketplace.visualstudio.com/items?itemName=ms-vscode.autorest) perspective. Please review the below analysis result:


File: `arm-apimanagement/2017-03-01/swagger/apimanagement.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **2**  Error(s): **1**


File: `arm-apimanagement/2017-03-01/swagger/apimapis.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **12**  Error(s): **7**


File: `arm-apimanagement/2017-03-01/swagger/apimauthorizationservers.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **1**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimbackends.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **3**  Error(s): **3**


File: `arm-apimanagement/2017-03-01/swagger/apimcertificates.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **1**  Error(s): **1**


File: `arm-apimanagement/2017-03-01/swagger/apimdeployment.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **2**  Error(s): **1**


File: `arm-apimanagement/2017-03-01/swagger/apimemailtemplate.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **2**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimgroups.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **4**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimidentityprovider.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **0**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimloggers.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **2**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimnetworkstatus.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **0**  Error(s): **1**


File: `arm-apimanagement/2017-03-01/swagger/apimopenidconnectproviders.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **1**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimproducts.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **14**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimproperties.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **2**  Error(s): **1**


File: `arm-apimanagement/2017-03-01/swagger/apimquotas.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **0**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimreports.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **0**  Error(s): **1**


File: `arm-apimanagement/2017-03-01/swagger/apimsubscriptions.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **1**  Error(s): **2**


File: `arm-apimanagement/2017-03-01/swagger/apimtenant.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **9**  Error(s): **4**


File: `arm-apimanagement/2017-03-01/swagger/apimusers.json`
Before the PR: Warning(s): **0**  Error(s): **0**
After the PR: Warning(s): **3**  Error(s): **2**


Know more about [AutoRest Linter Guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md).

Send <a href='mailto:azure-swag-tooling@microsoft.com?subject=Feedback%20|%20AutoRest%20Linter%20Azure%20Bot'>feedback</a> and make **AutoRest Linter Azure Bot** smarter day by day!

Thanks for your co-operation.

2017-07-10 20:19 UTC, fearthecowboy commented
ATTENTION REQUIRED.
-------------

We have changed the `default` branch in the `azure-rest-api-specs` repository to use the branch labeled `current`.

This PR is opened against the `master` branch.

You have two options: 
1. Keep this PR open, and complete the review process as normal, and once this PR is merged against the `master` branch, we (@olydis & @fearthecowboy)  will create a PR against the current branch and make any updates required to work in the newly reorganized default branch.  

2. Close this PR and create a new one. That would mean pulling in the changes from the new default branch `current` moving any files and switching to the configuration-based layout.  (You are more than welcome to choose option 2, but I don't expect anyone to do that)

Either way, the work you are currently doing against the previous default branch `master` will be the last PR against that branch that we will accept and all new PRs will go against the new default branch  `current`.

If you have any questions or concerns, ping @fearthecowboy or @olydis (or go ask on the `#swagger` channel in slack) ASAP and we can help you thru the process.

2017-07-10 20:59 UTC, solankisamir commented
@fearthecowboy lets complete the review process in the master branch itself.

2017-07-11 18:29 UTC, fearthecowboy requested changes
I'm pretty sure we've talked about CreateOrUpdate before -- 

>  A PUT operation request body schema should be the same as its 200 response schema, to allow reusing the same entity between GET and PUT. 
> If the schema of the PUT request body is a superset of the GET response body, make sure you have a PATCH operation to make the resource updatable. 

In operations: 
``` 
    arm-apimanagement/2017-03-01/swagger/apimapis.json:149:6 
    arm-apimanagement/2017-03-01/swagger/apimcertificates.json:146:6
    arm-apimanagement/2017-03-01/swagger/apimemailtemplate.json:132:6
    arm-apimanagement/2017-03-01/swagger/apimgroups.json:143:6
    arm-apimanagement/2017-03-01/swagger/apimproducts.json:153:6 
    arm-apimanagement/2017-03-01/swagger/apimproperties.json:143:6
    arm-apimanagement/2017-03-01/swagger/apimsubscriptions.json:146:6
    arm-apimanagement/2017-03-01/swagger/apimusers.json:146:6
    arm-apimanagement/2017-03-01/swagger/apimopenidconnectproviders.json:140:6 
```    

You're not able to keep the models the same, because the creates have additional data? 

Does the API support round-tripping the GET entity with the PATCH operations?

-----

Operations missing `x-ms-examples` -- ( can these be added? ):

 'Api_Update'
 'Api_Delete'
 'ApiOperation_Update'
 'ApiOperationPolicy_CreateOrUpdate'
 'ApiPolicy_CreateOrUpdate'
 'ApiPolicy_Delete'
 'AuthorizationServer_Update'
 'Backend_Update'
 'Backend_Delete'
 'ApiManagementOperations_List'
 'EmailTemplate_Update'
 'Group_Update'
 'IdentityProvider_Update'
 'Logger_Update'
 'OpenIdConnectProvider_Update'
 'Product_Update'
 'Subscription_Update'
 'TenantConfiguration_Deploy'
 'TenantConfiguration_Save'
 'TenantConfiguration_Validate'
 'User_Update'


----

Other than that, I think this is pretty good. I've ignored the `R3018` , `R3010` and `R2061` linter errors, I don't think they are significant in this case.

2017-07-11 18:29 UTC, fearthecowboy commented on arm-apimanagement/2017-03-01/swagger/apimquotas.json
> +        "Value": {
`"Value"` should start with a lower-case  `v` to be camel-case consistent.

2017-07-11 18:29 UTC, fearthecowboy commented on arm-apimanagement/2017-03-01/swagger/apimtenant.json
> +            "description": "Parameters."
`"description" : "Parameters"` - Description must not match the name of the node it is supposed to describe.

2017-07-11 18:29 UTC, fearthecowboy commented on arm-apimanagement/2017-03-01/swagger/apimdeployment.json
> +          "description": "Hostname."
`"description" : "Hostname"` - Description must not match the name of the node it is supposed to describe.

2017-07-11 22:39 UTC, solankisamir commented on arm-apimanagement/2017-03-01/swagger/apimquotas.json
> +        "Value": {
Yes.. this is an issue in the API. We are planning to fix it in the next Api-Version.

2017-07-11 22:42 UTC, solankisamir commented on arm-apimanagement/2017-03-01/swagger/apimtenant.json
> +            "description": "Parameters."
Fixed

2017-07-11 22:43 UTC, solankisamir commented on arm-apimanagement/2017-03-01/swagger/apimdeployment.json
> +          "description": "Hostname."
Fixed

2017-07-12 01:33 UTC, solankisamir commented
arm-apimanagement/2017-03-01/swagger/apimapis.json:149:6 
>> Yes the create parameter has extra parameters like Content-Type, which is not part of the Get Contract
arm-apimanagement/2017-03-01/swagger/apimcertificates.json:146:6
>> The Create Contract has Base64 Certificate, not part of the get Contract
    arm-apimanagement/2017-03-01/swagger/apimemailtemplate.json:132:6
>> isDefault is a Property in GetContract, not present in CreateContract
    arm-apimanagement/2017-03-01/swagger/apimgroups.json:143:6
>> Property builtiin is GetContract is not valid in CreateContract, as it is ReadOnly.
    arm-apimanagement/2017-03-01/swagger/apimproducts.json:153:6 
>> I have made the GetContract and CreateContract same
    arm-apimanagement/2017-03-01/swagger/apimproperties.json:143:6
>>  I have made the GetContract and CreateContract same
    arm-apimanagement/2017-03-01/swagger/apimsubscriptions.json:146:6
>> state is a required parameter in GetContract and NotRequired in CreateContract
    arm-apimanagement/2017-03-01/swagger/apimusers.json:146:6
>> groups is a parameter in the GetContract, but not present in CreateContract
    arm-apimanagement/2017-03-01/swagger/apimopenidconnectproviders.json:140:6 
>>  I have made the GetContract and CreateContract same

2017-07-12 14:57 UTC, fearthecowboy approved these changes

2017-07-12 14:57 UTC, merged

2017-07-12 15:01 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-python

2017-07-12 15:01 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-ruby

2017-07-12 15:01 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node