Adding changes for v2 swagger
Azure/azure-rest-api-specs pull request #14427
Opened 2021-05-17 01:09 UTC by dukum

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Please ensure to add changelog with this PR by answering the following questions.
  1. What's the purpose of the update?    
      - [ ] new service onboarding 
      - [ ] new API version 
      - [ ] update existing version for new feature 
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify 
  2. When you are targeting to deploy new service/feature to public regions? Please provide date, or month to public if date is not available yet.
  3. When you expect to publish swagger? Please provide date, or month to public if date is not available yet.
  4. If it's an update to existing version,  please select SDKs of specific language and CLIs that require refresh after swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No, no need to refresh for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Ensure to check this box if one of the following scenarios meet updates in the PR, so that label “WaitForARMFeedback” will be added automatically to involve ARM API Review. Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs, all “removals” and “adding a new property” no more require ARM API review.
  - Adding new API(s)
  - Adding a new API version
  -  [ ] Ensure to copy the existing version into new directory structure for first commit (including refactoring) and then push new changes including version updates in separate commits. This is required to review the changes efficiently.
  - Adding a new service

- [ ] Please ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If there are following updates in the PR, ensure to request an approval from Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 

- [ ] Removing API(s) in stable version
- [ ] Removing properties in stable version
- [ ] Removing API version(s) in stable version
- [ ] Updating API in stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

2021-06-01 13:00 UTC, innosam commented on specification/resourcemover/resource-manager/Microsoft.Migrate/stable/2021-01-01/resourcemovercollection.json
> +          "MoveCollections_Prepare": {
fix?

2021-06-01 13:02 UTC, innosam commented on specification/resourcemover/resource-manager/Microsoft.Migrate/stable/2021-01-01/resourcemovercollection.json
> +    "/providers/Microsoft.Migrate/operations/supportedResourceTypesForResourceMover": {
Which RP will this API hit? This looks like an API that will hit global endpoint, as there is no idea of location associated here.

I see two options here:
a. If its a global endpoint, we can consider supporting this configuration across regional RP's, and use the azure traffic manager to route the traffic based on say "Geographic traffic-routing method".
https://docs.microsoft.com/en-us/azure/traffic-manager/traffic-manager-routing-methods#geographic-traffic-routing-method.
b. The other option is definitely, this to be an ARM api which is what our current proposal, however there might be a need for an wrapper if resource mover has to expose extra set of properties.

2021-06-01 13:05 UTC, innosam commented on specification/resourcemover/resource-manager/Microsoft.Migrate/stable/2021-01-01/resourcemovercollection.json
> +		  "type": "array",
identation.

2021-06-01 13:06 UTC, innosam commented on specification/resourcemover/resource-manager/Microsoft.Migrate/stable/2021-01-01/resourcemovercollection.json
> +          "description": "Gets or sets a value indicating whether the operation needs to add dependency automatically.",
should this be a query parameter?

2021-06-01 13:08 UTC, innosam commented on specification/resourcemover/resource-manager/Microsoft.Migrate/stable/2021-01-01/resourcemovercollection.json
> +        "targetResourceName": {
this is optional here, will RMO assume the source resource and target resource name to be same if not provided?

2021-06-01 13:11 UTC, innosam commented on specification/resourcemover/resource-manager/Microsoft.Migrate/stable/2021-01-01/resourcemovercollection.json
> -    "VirtualMachineResourceSettings": {
1. Shouldn't these stay to support inter operability? 
2. Considering above, should we introduce a new derived class called GenericResourceSettings?

2021-06-01 13:13 UTC, innosam requested changes
provided comments, check and get back if there are any questions.

2026-09-16 15:57 UTC, closed without merging

2026-09-16 15:57 UTC, timotheeguerin commented
This PR has been closed because it has had no activity for more than a year. If this change is still needed, please reopen the PR.

<!-- inactive-pr-cleanup:2026-09-16 -->