Add Express Route Connector json and examples.
Azure/azure-rest-api-specs pull request #1449
Opened 2017-07-20 18:48 UTC by dedhar

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-07-20 18:48 UTC, msftclas commented
@__dedhar__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

It will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-07-20 21:57 UTC, olydis commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +			"location": {
Properties `location`, `tags` and `name` are inherited by `Resource`! Don't specify those here.

2017-07-20 21:58 UTC, fearthecowboy commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +            "tags": {
You've duplicated 'tags' from Resource

2017-07-20 22:09 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +			"location": {
Moving to using subresource. Is there any advantage or disadvantage in using resource vs subresource

2017-07-20 22:09 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +			"location": {
I modelled this new json on RouteFilter.json which uses subresource

2017-07-20 22:10 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +            "tags": {
I am moving to using SubResource in allOf. That should also resolve the build errors

2017-07-20 22:56 UTC, dedhar commented
Resolved olydis and fearthecowboy comments to move to using Resource and remove redundant fields : tags etc. Vishrut mentioned the build failure is due to Mode being Ruby. He kicked off another build

2017-07-20 23:34 UTC, dedhar commented
I have linked my Microsoft account to azure GitHub. How do I get rid of cla required label? @olydis / @fearthecowboy : any suggestions on how to resolve this?

2017-07-21 00:15 UTC, dedhar commented
Also in the first phase of this project we are planning to make authorizations optional parameter. If all circuits are in same subscription we don't need authorization.

2017-07-21 16:18 UTC, fearthecowboy commented
Adding @dsgouda  as reviewer (this is reopened from #1430 on wrong branch)

2017-07-21 16:44 UTC, dedhar commented
@fearthecowboy  : From the old PR : 

we've reorganized this repository a bit -- can I get you to make a clean fork of the repository, and base your PR off the current branch instead of `master, and then issue a new PR?

So I got a clean fork from current :
D:\One\Networking\azure-rest-api-specs>git remote -v
Azure   https://github.com/Azure/azure-rest-api-specs.git (fetch)
Azure   https://github.com/Azure/azure-rest-api-specs.git (push)
origin  https://github.com/dedhar/azure-rest-api-specs.git (fetch)
origin  https://github.com/dedhar/azure-rest-api-specs.git (push)

D:\One\Networking\azure-rest-api-specs>git branch
* current

Do I need new PR?

2017-07-21 16:47 UTC, fearthecowboy commented
@dedhar  I think this PR is OK -- it's running thru the CI checks and it's based against `current` and the files are in the right spots.

2017-07-21 16:50 UTC, dedhar commented
Thanks @fearthecowboy !  Let me know if there are additional comments.

2017-07-21 17:55 UTC, dsgouda commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteCircuit.json
> +	    "Transport"
nit: formatting

2017-07-21 17:57 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteCircuit.json
> +	    "Transport"
addressed in latest commit

2017-07-21 17:58 UTC, dsgouda commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"x-ms-long-running-operation": false
you don't need to explicitly define this

2017-07-21 17:58 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"x-ms-long-running-operation": false
you mean x-ms-long-running-operation? Will address

2017-07-21 18:08 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"x-ms-long-running-operation": false
addressed

2017-07-21 18:13 UTC, dsgouda requested changes

2017-07-21 18:13 UTC, dsgouda commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +					"404": {
4XX status codes are not supported by autorest, please use default instead. You can do this however 
https://github.com/Azure/azure-rest-api-specs/blob/2fb9a0b3b902335ff0b0033711c234431931ec9d/specification/sql/resource-manager/Microsoft.Sql/2015-05-01-preview/virtualNetworkRules.json#L55

2017-07-21 18:13 UTC, dsgouda commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +					"description": "Resource does not pass pre condition"
same comment as before for 4xx status codes

2017-07-21 18:13 UTC, dsgouda commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"operationId": "expressRouteConnectors_CreateOrUpdate",
If you already have a separate _Update operation please make this _Create

2017-07-21 18:13 UTC, dsgouda commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +					"description": "Bad Request"
same comment as above for 4xx codes.

2017-07-21 18:13 UTC, dsgouda commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +			"nextLink": {
Please mark this as readonly

2017-07-21 18:22 UTC, dsgouda commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +			"description": "Gets all express route Connector resources in a given subscrption.",
please provide ```x-ms-examples``` for this operation

2017-07-21 18:37 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +			"description": "Gets all express route Connector resources in a given subscrption.",
addressed in latest commit

2017-07-21 18:37 UTC, dedhar commented
Addressed following comments in latest commit : 
- Example for list by subscription
- Remove 4xx error codes

2017-07-21 18:42 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +			"description": "Gets all express route Connector resources in a given subscrption.",
addressed in latest commit

2017-07-21 20:03 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +					"404": {
addressed in latest commit

2017-07-21 20:04 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"operationId": "expressRouteConnectors_CreateOrUpdate",
addressed

2017-07-21 20:14 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +			"nextLink": {
addressed

2017-07-21 20:14 UTC, dedhar commented
Addressed latest comments from Deepak

2017-07-21 20:28 UTC, dsgouda commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +					"403": {
still needs fixing

2017-07-21 20:43 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +					"403": {
sorry about that

2017-07-21 20:45 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +					"403": {
addressed and checked examples as well

2017-07-21 20:46 UTC, dedhar commented
addressed latest comments from Deepak

2017-07-21 20:50 UTC, dsgouda reviewed
Looks good for the most part, per @dedhar this needs ARM approval. @ravbhatnagar ?

2017-07-24 21:44 UTC, ravbhatnagar requested changes

2017-07-24 21:44 UTC, ravbhatnagar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"responses": {
Please model the default error response.

2017-07-24 21:44 UTC, ravbhatnagar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +						}
Error response missing.

2017-07-24 21:44 UTC, ravbhatnagar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"authorizations": {
This looks like it contains secret information. It should not be returned in the response of GET/PUT. Expose this using the POST api.

2017-07-24 21:44 UTC, ravbhatnagar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"connectionStatus": {
Looks like the intended use of this property is different from provisioningState. Please make this an enum. Also add "provisioningState" property

2017-07-25 00:02 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +						}
SDK Team requested me to remove 4xx Error codes.
@fearthecowboy / @olydis / @dsgouda  : Can you comment if we need to add back error codes?

2017-07-25 00:02 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"responses": {
SDK Team requested me to remove 4xx Error codes.
@fearthecowboy / @olydis / @dsgouda  : Can you comment if we need to add back error codes?

2017-07-25 00:05 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"authorizations": {
The customer specifies authorization Key as part of PUT API Call and we just intend to return whatever customer specified in ExpressRouteConnector object. Authorization Key is also returned as part of VirtualNetworkGatewayConnectionObject : Reference : virtualNetworkGateway.json

2017-07-25 00:06 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"connectionStatus": {
I checked with team internally here and for now we just need provisioningState. When we expand the API to accept list of circuits we would consider exposing connectionStatus for each link between a pair of circuits

2017-07-25 00:08 UTC, dsgouda commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"responses": {
The error response is denoted by ```"default"```. please [refer](https://github.com/Azure/azure-rest-api-specs/blob/2fb9a0b3b902335ff0b0033711c234431931ec9d/specification/apimanagement/resource-manager/Microsoft.ApiManagement/2016-10-10/apimapis.json#L81)
@ravbhatnagar please confirm

2017-07-25 00:08 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"connectionStatus": {
Renamed connectionStatus to provisioningState in latest commit

2017-07-25 16:47 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"responses": {
addressed in latest commit

2017-07-25 16:48 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +				"authorizations": {
removed authorization keys from GET / LIST calls

2017-07-25 16:48 UTC, dedhar commented
Addressed Gaurav's comments to remove authorization keys from GET / LIST calls and added 4xx error codes to default error response

2017-07-25 22:37 UTC, dedhar commented
Addressed following comments from Gaurav : Remove authorizations from PUT / PATCH Call and default error responses

2017-07-25 22:38 UTC, dedhar commented
@ravbhatnagar / @dsgouda  : Can you take a look? Once I have approval, I would then move the code to https://github.com/Azure/azure-rest-api-specs-pr

2017-07-26 01:31 UTC, dedhar commented
Sample ARM Deployment Template : 
ExpressRouteConnector.json

{
    "$schema": "https://schema.management.azure.com/schemas/2017-08-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "expressRouteConnectorName": {
            "type": "string",
            "metadata": {
                "description": "This is the name of the Express Route Connector Resource"
            }
        },
        "location": {
            "type": "string",
            "defaultValue": "West US",
            "metadata": {
                "description": "Azure Region where Express Route Connector resource be deployed."
            }
        },
        “circuits”: {
            “type”:”array”,
“defaultValue”:[       "/subscriptions/CustomerSubscriptionUS/resourceGroups/ExpressRouteResourceGroupUS/providers/Microsoft.Network/expressRouteCircuits/ExpressRouteARMCircuitA",
	"/subscriptions/CustomerSubscriptionAus/resourceGroups/ExpressRouteResourceGroupAus/providers/Microsoft.Network/expressRouteCircuits/ExpressRouteARMCircuitB"
              ],
	“metadata”:”List of Express Route Circuits with complete URI. Not needed if all circuits are in same subscription.”
         },
        “authorizations”: {
“type”:”array”,
“defaultValue”:[     
     "abcdefgh^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
	      "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
              ],
	“metadata”:”List of Authorization Keys on all express route circuits being peered”
        },
        “addressPrefix”: {
               “type”:”string”
                “defaultValue”:”10.0.0.0/24”.
                 “metadata”:”/24 subnet to be used for iBGP Peering.”
         }
    },
    "resources": [
      {
        "apiVersion": "2017-08-01",
        "location": "[parameters('location')]",
        "name": "[parameters('filterName')]",
        "properties": {
        },
        "tags": {
          "key1": "value1",
          "key2": "value2"
        },
        "type": "Microsoft.Network/expressRouteConnectors"
      }
    ]
}

2017-07-26 17:11 UTC, salameer commented
Hi @ravbhatnagar 

Please review from ARMs side

2017-07-26 17:50 UTC, dedhar commented
I see that Tracis CI build passed. @dsgouda / @ravbhatnagar   : Were there more comments to address? Not seeing any new comments. :)

2017-07-27 00:46 UTC, ravbhatnagar commented
There is just one outstanding issue around returning secrets in the response of PUT/PATCH that is currently being discussed.

2017-07-27 19:13 UTC, dsgouda requested changes

2017-07-27 19:13 UTC, dsgouda commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +	    "SubResource": {
Please add description here

2017-07-27 19:27 UTC, dsgouda reviewed
The 2 new errors introduced are due to models inheriting from ```Resource``` model defined in network.json which is incorrectly modeled.
The warnings can be ignored as discussed offline. 
Pending the minor requested change, LGTM subject to ARM approval.

2017-07-27 19:30 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +	    "SubResource": {
addressed in latest commit

2017-07-27 19:30 UTC, dedhar commented
addressed latest comment from Deepak

2017-07-27 20:57 UTC, dsgouda commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +		  "definition":"Subresource modelled from network.json/SubResource without x-ms-azure-resource since that introduces lint error."
Did you mean ```description```?

2017-07-27 21:00 UTC, dedhar commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteConnector.json
> +		  "definition":"Subresource modelled from network.json/SubResource without x-ms-azure-resource since that introduces lint error."
oh yes since you had recommended to add description in previous comment

2017-07-27 21:41 UTC, dsgouda approved these changes
LGTM pending ARM approval.

2017-07-27 22:56 UTC, ravbhatnagar commented
#ARM sign off

2017-07-31 20:27 UTC, salameer commented
What's the deal here folks, is this the one where a Private PR was created instead?

2017-07-31 20:29 UTC, dsgouda commented
@salameer yes there is a PR on the private repo which is under review.

2017-08-08 17:07 UTC, dsgouda commented
@dedhar please close this PR if you plan to implement the service and open a new PR in the future.

2017-08-08 20:36 UTC, salameer commented
@dsgouda what's the status here?

2017-08-08 20:39 UTC, dsgouda commented
PR on the private repo is merged, I believe @dedhar and her team is now working on implementing the APIs, per my last comment, I am awaiting to know if they'd like to create a new public PR in the future.

2017-08-11 22:40 UTC, salameer commented
Hi  @dsgouda, I guess my question here is, is there any reason for this to stay open?

2017-08-11 22:41 UTC, dsgouda commented
Not at my end no.

2017-08-11 22:41 UTC, closed without merging