Added examples for Network items
Azure/azure-rest-api-specs pull request #1455
Opened 2017-07-21 13:22 UTC by EvgenyAgafonchikov

- Added examples for PublicIPAddress, VirtualNetworks, Subnets,
Peerings, RouteTables, Routes, Usage, NetworkSecurityGroups,
SecurityRules, VMSSS NetworkInterfaces, checkDnsNameAvailability,
LoadBalancer, NetworkInterface;
- Added descriptions to reduce warnings number
- Fixed protocol range in NIC effective security rule

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-07-21 22:57 UTC, jianghaolu requested changes

2017-07-21 22:57 UTC, jianghaolu commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/networkInterface.json
> +            "All"
this conflicts with the `SecurityRuleProtocol` definition here: https://github.com/EvgenyAgafonchikov/azure-rest-api-specs/blob/43acc9dd8542870186bfbd91e8980aaf7f227bf4/specification/network/resource-manager/Microsoft.Network/2017-06-01/networkSecurityGroup.json#L477

2017-07-24 07:10 UTC, EvgenyAgafonchikov commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/networkInterface.json
> +            "All"
@jianghaolu, I think these should be independent types. I've checked both and [this](https://github.com/EvgenyAgafonchikov/azure-rest-api-specs/blob/43acc9dd8542870186bfbd91e8980aaf7f227bf4/specification/network/resource-manager/Microsoft.Network/2017-06-01/networkSecurityGroup.json#L477) returns "*" as protocol of `SecurityRule` in server response while `EffectiveNetworkSecurityRule` has "All" in response

2017-07-24 17:43 UTC, jianghaolu commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/networkInterface.json
> +            "All"
Okay. They should have different names then because when we generate network client in AutoRest, these models will end up in the same folder.

2017-07-25 10:49 UTC, EvgenyAgafonchikov commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/networkInterface.json
> +            "All"
Could you please clarify what names do you imply? Root objects have different names: EffectiveNetworkSecurityRule and SecurityRule

2017-07-25 18:38 UTC, jianghaolu commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/networkInterface.json
> +            "All"
Please note that this is a breaking change - if you have dependent code in PowerShell or CLI please also update them.

2017-07-25 18:40 UTC, jianghaolu approved these changes

2017-07-27 14:30 UTC, EvgenyAgafonchikov commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/networkInterface.json
> +            "All"
Got it, thanks for notifying.
However, EffectiveSecurityRules have only GET operation, so there are no input parameters in PS/CLI that use this enum as validation set.

2017-07-27 19:31 UTC, merged

2017-07-27 19:34 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-07-27 19:35 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1455)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/865

2017-07-27 19:36 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1455)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1329