Add sql top queries spec
Azure/azure-rest-api-specs pull request #1469
Opened 2017-07-26 16:28 UTC by jaredmoo

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-07-26 16:29 UTC, jaredmoo commented
Please don't merge until I get signoff from SQL DB query store team. Thx

2017-07-26 21:33 UTC, veronicagg commented
@ravbhatnagar new spec being added, please take a look.

2017-07-26 21:41 UTC, veronicagg requested changes
should the new spec be added to any of the packages in the "readme.md" file at azure-rest-api-specs/specification/sql/resource-manager/ ?

2017-07-26 21:41 UTC, veronicagg commented on specification/sql/resource-manager/Microsoft.Sql/2014-04-01/queries.json
> +            "name": "queryId",
"type" missing for this parameter - causing CI to fail with syntax failure (not a valid swagger document) https://travis-ci.org/Azure/azure-rest-api-specs/jobs/257801073#L3217

2017-07-26 23:53 UTC, jaredmoo commented on specification/sql/resource-manager/Microsoft.Sql/2014-04-01/queries.json
> +            "name": "queryId",
Oops. Fixed.

2017-07-26 23:55 UTC, jaredmoo commented
The spec will be added to "schema-2014-04" tag when #1474 is merged, and will be added to "package-2015-05-preview" concurrently with .net sdk code and tests are submitted for review.

2017-07-27 22:29 UTC, veronicagg requested changes

2017-07-27 22:29 UTC, veronicagg commented on specification/sql/resource-manager/Microsoft.Sql/2014-04-01/queries.json
> +            "required": "true",
looks like "required" value is in quotes, but should be a boolean - "required": true
CI still fails due to this, you can use the schema at https://raw.githubusercontent.com/Azure/autorest/master/schema/swagger-extensions.json to validate the file before submission.

2017-07-28 18:51 UTC, veronicagg commented on specification/sql/resource-manager/readme.md
> + - ./Microsoft.Sql/2014-04-01/queries.json
just wondering should 'schema-2014-04' be the new default tag?  - see line 31 in this file.

2017-07-28 18:53 UTC, veronicagg commented
@jaredmoo thanks, added one more question inline. Waiting on review from @ravbhatnagar since it's a new file. 
Please let us know when you get signoff from SQL DB query store team

2017-07-28 18:59 UTC, ravbhatnagar requested changes

2017-07-28 18:59 UTC, ravbhatnagar commented on specification/sql/resource-manager/Microsoft.Sql/2014-04-01/queries.json
> +    "TopQueries": {
@jaredmoo - Please add the id, name, type top level properties in the response. Id example below
id: "/subscriptions/{subid}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/topQueries/{queryNameOrId}"

2017-07-28 18:59 UTC, ravbhatnagar commented on specification/sql/resource-manager/Microsoft.Sql/2014-04-01/queries.json
> +        "aggregationFunction": {
And then all these properties should move under the properties bag.

2017-07-28 18:59 UTC, ravbhatnagar commented on specification/sql/resource-manager/Microsoft.Sql/2014-04-01/queries.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/topQueries/{queryId}/statistics": {
IMO, you don't need a "statistics" type, a GET on a query returns the statistics information as well. So the API signature will be like - "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/topQueries/{queryId}

2017-07-28 18:59 UTC, ravbhatnagar commented on specification/sql/resource-manager/Microsoft.Sql/2014-04-01/queries.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/topQueries": {
A few Naïve questions to help my understanding - What categorizes a query into top queries? Is it the number of executions? Do you already have an API for listing all queries under a database? 
If yes, you can consider adding a property to response of /queries to indicate whether a query is a top query or not. And then to just list top queries, customers can use $filter on that property? 
All this is based on my limited knowledge of the scenario.

2017-07-28 19:04 UTC, jaredmoo commented
@veronicagg no, schema-2014-04 is what I'm using for conveniently generating RP schema and running --azure-validator until https://github.com/Azure/autorest/issues/2470 is fixed.

@ravbhatnagar this is all good feedback, but it's an old API that I can't change. Just adding missing swagger.

2017-07-28 19:15 UTC, ravbhatnagar commented
@jaredmoo - ok :). One thing I would still like to point out - If a customer has defined a custom role where in NotActions he has explicitly added /servers/databases/topqueries/read, he will be able to still see all the top queries since you dont have ID in the response payload. Thus potentially breaking RBAC? Please ACK if you are fine with this.

2017-07-28 19:21 UTC, jaredmoo commented
ACK - this API is a little weird by modern ARM standards, if/when we make a new api-version of this API it will be differently designed.

2017-07-31 17:39 UTC, veronicagg commented
@jaredmoo ok, let me know when you get sign off from SQL DB query store team, so I can approve & merge. thanks!

2017-08-01 13:50 UTC, sasapopo commented on specification/sql/resource-manager/Microsoft.Sql/2014-04-01/examples/QueriesList.json
> +          "numberOfTopQueries":5,
Example is not correct. If numberOfTopQueries is 5 "queries" list below must have 5 items and it has only one.

2017-08-01 13:54 UTC, sasapopo commented on specification/sql/resource-manager/Microsoft.Sql/2014-04-01/queries.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/topQueries": {
DTU usage % corresponding to query categorizes it into top queries. We calculate DTU usage based on real resource usage recorded by Query Store.
We don't have api for listing all queries.

2017-08-01 14:00 UTC, sasapopo approved these changes

2017-08-01 16:59 UTC, veronicagg commented
@jaredmoo do you want to update your example based on feedback from @sasapopo ?

2017-08-01 20:26 UTC, veronicagg approved these changes

2017-08-01 20:26 UTC, merged

2017-08-01 20:30 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-08-01 20:30 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1469)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1342

2017-08-01 20:32 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1469)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/874