Catching up with missing commits (not moved to the new branch), Fixing issue #1475: incorrect example in LogProfiles API documentation for CreateOrUpdate, fixing incorrect logProfiles example names.
Azure/azure-rest-api-specs pull request #1481
Opened 2017-07-27 20:11 UTC by gucalder

Catching up with missing commits (not moved to the new branch), Fixing issue #1475: incorrect example in LogProfiles API documentation for CreateOrUpdate, fixing incorrect logProfiles example names.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-07-27 20:12 UTC, gucalder commented
Retry of closed PR #1476.

2017-07-28 23:01 UTC, vishrutshah requested changes
@gucalder Change looks good but I noticed that there was already existing error in of the swagger. It'd great if we can address it in this PR itself. Thanks!

2017-07-28 23:01 UTC, vishrutshah commented on specification/monitor/resource-manager/microsoft.insights/2016-03-01/logProfiles_API.json
> +            "Delete log profile": { "$ref": "./examples/deleteLogProfile.json" }
seems like this example contains an additional response code that has not been modeled in swagger. Could you please verify? 

https://travis-ci.org/Azure/azure-rest-api-specs/jobs/258292847#L657

2017-08-02 20:57 UTC, vishrutshah commented
@gucalder ping! Could you please see whether we can fix this as part of this PR. Thanks!

2017-08-03 00:11 UTC, gucalder commented on specification/monitor/resource-manager/microsoft.insights/2016-03-01/logProfiles_API.json
> +            "Delete log profile": { "$ref": "./examples/deleteLogProfile.json" }
Fixed

2017-08-03 16:26 UTC, vishrutshah commented
@gucalder Thanks for fixing the example. I see that there is still one more invalid example/swagger model for operation `LogProfiles_CreateOrUpdate`. Could you please have a look?

https://travis-ci.org/Azure/azure-rest-api-specs/jobs/260424100#L663

2017-08-04 00:04 UTC, gucalder commented
I do not know how to fix this error reported by Linter:   "code": "DefinitionsPropertiesNamesCamelCase",
  "message": "Property named: '**odata.type**', for definition: 'RuleCondition' must follow camelCase style. Example: 
'**odata.type**'.",

2017-08-04 00:05 UTC, gucalder commented
Those are 6 of the 10 errors.

2017-08-04 16:19 UTC, vishrutshah commented
@gucalder Looks like the rule should not have triggered when there is a odata int eh property name. 

Would you please open an issue at https://github.com/Azure/azure-openapi-validator/issues and link to https://github.com/Azure/autorest/issues/2064 so that we can get it taken care. Thanks! 

Secondly, Please also have a look at the build `MODE:model PR_ONLY=true` [here](https://travis-ci.org/Azure/azure-rest-api-specs/builds/260730812?utm_source=github_status&utm_medium=notification). That build ensures that provided examples are matching the swagger models. Let me know if you need any help. Thanks!

2017-08-07 16:41 UTC, gucalder commented
Issues with the MODE:model PR_ONLY=true fixed. Waiting for the result of the validations.

2017-08-08 18:41 UTC, vishrutshah requested changes
Thanks for fixing the errors. I left one question for you. Let me know what you think.

2017-08-08 18:41 UTC, vishrutshah commented on specification/monitor/resource-manager/microsoft.insights/2016-09-01/serviceDiagnosticsSettings_API.json
> +                "name": "parameters",
@gucalder May I ask the reason for this change i.e renaming the parameter. Seems like generating new SDK from this swagger would not be backward compatible as parameter name has changed. Can you please provide your thoughts.

2017-08-08 20:19 UTC, gucalder commented on specification/monitor/resource-manager/microsoft.insights/2016-09-01/serviceDiagnosticsSettings_API.json
> +                "name": "parameters",
That is because I changed the wrong file... I need to change the example file, not the spec file.
I am on this.

2017-08-08 21:17 UTC, vishrutshah commented
Thanks @gucalder for incorporating the feedback.

2017-08-08 21:17 UTC, vishrutshah approved these changes

2017-08-08 21:18 UTC, merged

2017-08-08 21:22 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-08-08 21:22 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1481)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/878

2017-08-08 21:22 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1481)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1353

2017-08-08 22:19 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-ruby

2017-08-08 22:19 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node