[Azure Analysis Services] Add gateway info to version 0714 and version 0801
Azure/azure-rest-api-specs pull request #1526
Opened 2017-08-09 22:36 UTC by taiwu

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-08-09 22:36 UTC, msftclas commented
@__taiwu__,
Thanks for your contribution. It looks like you are a Microsoft vendor. To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

The agreement will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-08-09 22:39 UTC, taiwu commented
Sync and add older version as requested in
https://github.com/Azure/azure-rest-api-specs/pull/1518

2017-08-09 22:46 UTC, taiwu commented
I am not a vendor.

From: Microsoft Contribution License Agreements [mailto:notifications@github.com]
Sent: Wednesday, August 9, 2017 3:37 PM
To: Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com>
Cc: Tai-Yi Wu <taiwu@microsoft.com>; Author <author@noreply.github.com>
Subject: Re: [Azure/azure-rest-api-specs] [Azure Analysis Services] Add gateway info to version 0714 and version 0801 (#1526)


@taiwu,
Thanks for your contribution. It looks like you are a Microsoft vendor. To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcla.microsoft.com&data=02%7C01%7Ctaiwu%40microsoft.com%7C60569b31b01e407796af08d4df77278d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636379150236297505&sdata=jUpH%2B7AGS95H%2FGBQVu3yE7Qph%2Bdc6HbQ8HMcf9Ii71A%3D&reserved=0>.

The agreement will cover your contributions to all Microsoft-managed open source projects.
Thanks,
Microsoft Pull Request Bot

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F1526%23issuecomment-321400383&data=02%7C01%7Ctaiwu%40microsoft.com%7C60569b31b01e407796af08d4df77278d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636379150236297505&sdata=3iQUOFf0asUphLCzXoxUSI5tVQkUafjZDEc9qU2rCwM%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAb50Q6PZyKHkZyOXJXch8yPr8qeX0qZ2ks5sWjSNgaJpZM4Oyuio&data=02%7C01%7Ctaiwu%40microsoft.com%7C60569b31b01e407796af08d4df77278d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636379150236297505&sdata=yBOOpACe7QtRg%2FlBFbwO9iRYhgkdTEm9abFzbKQ3Ypg%3D&reserved=0>.

2017-08-10 00:38 UTC, olydis commented
@taiwu Please complete the checklist. Regarding vendor message: Seems like the PR was still tagged as "cla-not-required", so you can ignore that. (classification is flaky sometimes)

2017-08-10 02:24 UTC, taiwu commented
@olydis thanks for your reply, could you please take a look at the change?

2017-08-10 03:49 UTC, sergey-shandar commented
@ravbhatnagar New API version for Analysis Services.

2017-08-10 07:39 UTC, ravbhatnagar commented
@sergey-shandar @taiwu  This is difficult to review. Can you please make a commit using the contents from the existing API-version. And then add the changes? Is it possible to do it now?

2017-08-10 07:52 UTC, ravbhatnagar requested changes

2017-08-10 07:52 UTC, ravbhatnagar commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-08-01-beta/analysisservices.json
> +        "gatewayResourceId": {
Is gateway resource exposed through ARM?

2017-08-10 07:52 UTC, ravbhatnagar commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-08-01-beta/analysisservices.json
> +  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AnalysisServices/servers/{serverName}/listGatewayStatus": {
Why do you need a  separate POST API to get the gateway status? Cant it be obtained by GET /servers/{servername}?

2017-08-10 07:52 UTC, ravbhatnagar commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-08-01-beta/analysisservices.json
> +        "status": {
What are the valid values for the status property? Can this be an enum?

2017-08-10 07:52 UTC, ravbhatnagar commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-08-01-beta/analysisservices.json
> +          "404": {
There could be other error codes that this API returns. So its best to capture the error conditions by defining a "default" response and including the error object definition in that.

2017-08-10 07:54 UTC, ravbhatnagar commented
@sergey-shandar  - SDK can start reviewing.

2017-08-10 16:27 UTC, taiwu commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-08-01-beta/analysisservices.json
> +  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AnalysisServices/servers/{serverName}/listGatewayStatus": {
By design, the spec can be found at section 3.9 of http://aka.ms/asarm/
Get /servers/{servername} only contains the gateway configuration info.

2017-08-10 16:28 UTC, taiwu commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-08-01-beta/analysisservices.json
> +          "404": {
sure, will add default.

2017-08-10 16:37 UTC, taiwu commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-08-01-beta/analysisservices.json
> +        "gatewayResourceId": {
Yes

2017-08-10 17:08 UTC, olydis commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-08-01-beta/analysisservices.json
> +          "400": {
If 4xx responses are supposed to throw an exception in generated code (it looks like that was the intention), they can unfortunately not be modeled like that but have to go into a `default` response. See https://github.com/Azure/azure-rest-api-specs/blob/current/documentation/creating-swagger.md#negative-responses for details. I'd recommend documenting status codes and their corresponding description in the description of the default response.

2017-08-10 17:13 UTC, olydis commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-08-01-beta/analysisservices.json
> +          "description": "Gateway resource to be associated with the server. Only supported with api versions 2017-07-14 or higher."
Not sure whether it makes sense to document "Only supported with api versions 2017-07-14 or higher." - this very Swagger is tied to an API version, so it's kind of redundant information. On the other hand, you may have thought about what people read in docs generated from this Swagger (and I'm not sure how explicit API versions are called out in our auto-gened docs). But generally, I haven't seen this pattern before! @ravbhatnagar Guidance?

2017-08-10 17:13 UTC, olydis commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-08-01-beta/analysisservices.json
> +        "status": {
+1

2017-08-10 17:14 UTC, olydis commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-08-01-beta/analysisservices.json
> +    "GatewayErrors": {
Why is this called `GatewayErrors`? It's used in a property called `error` and also by itself looks like it represents a single error.

2017-08-10 17:17 UTC, olydis commented on specification/analysisservices/resource-manager/readme.md
>  - Microsoft.AnalysisServices/2016-05-16/analysisservices.json
Please flip order (most recent first). This has no influence on behavior, but makes it consistent with the other RP's configuration in this repo 🙂

2017-08-10 17:17 UTC, olydis requested changes
see comments

2017-08-10 19:14 UTC, taiwu commented
Fixed, please take a look.
Small adjustment, the v714 was a copy of v801, which is now based on v516.

2017-08-11 17:57 UTC, olydis commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-08-01-beta/analysisservices.json
> +          "description": "Live message of list gateway."
add `x-ms-enum` part (set model as string to `true`)

2017-08-11 18:04 UTC, olydis requested changes
Minor comment, but please take a look at the validation tool outputs: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/263248184#L665
Is there anything you can resolve? Note that the `x-ms-enum` comment is one of the issues flagged by the validator, please review these issues.

2017-08-14 19:35 UTC, taiwu commented
Updated, the rest are all examples and operation list.
The latest build failure is not related to my latest commit.
@olydis could you please take a look?

2017-08-15 20:22 UTC, michael-falk commented on specification/analysisservices/resource-manager/readme.md
> +tag: package-2017-07
Could you change package-2017-07 to package-2017-08-beta so it refers to latest and #1542 can be closed.

2017-08-15 21:12 UTC, michael-falk commented on specification/analysisservices/resource-manager/readme.md
> +tag: package-2017-07-08-beta
tag: package-2017-07-08-beta?
do you mean:
tag: package-2017-08-beta

2017-08-15 22:00 UTC, olydis approved these changes
LGTM, descriptions of model types can be made consistently end with `.`

2017-08-15 22:01 UTC, olydis commented
@ravbhatnagar All your concerns addressed?

2017-08-16 16:13 UTC, olydis commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-08-01-beta/analysisservices.json
> +            "description": "The name of the Analysis Services server. It must be at least 3 characters in length, and no more than 63."
Please remove ` It must be at least 3 characters in length, and no more than 63.`, don't restate constraints expressed in Swagger by other means.

2017-08-16 17:18 UTC, taiwu commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-08-01-beta/analysisservices.json
> +            "description": "The name of the Analysis Services server. It must be at least 3 characters in length, and no more than 63."
Sure, will do, but I just copy paste from previous one....
Can you just merge?

2017-08-16 18:43 UTC, ravbhatnagar approved these changes

2017-08-17 16:00 UTC, merged

2017-08-17 16:03 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-python

2017-08-17 16:04 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-08-17 16:04 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1526)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/901