[Reopen to 'current' branch] Make location parameter inline to fix issue 1508
Azure/azure-rest-api-specs pull request #1532
Opened 2017-08-11 04:15 UTC by felixwa

Make location parameter inline, so that AutoRest will generate it as a
parameter of the method instead of a property of Client class.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-08-11 04:22 UTC, felixwa commented
Previous PR was opened to 'master' now open it to 'current' as @dsgouda suggested.

2017-08-11 04:22 UTC, felixwa commented
To fix Issue #1508

2017-08-11 16:29 UTC, dsgouda approved these changes
Thanks, LGTM

2017-08-11 16:32 UTC, olydis commented
This fix could have been way simpler! Just add `"x-ms-parameter-location": "method"` (see https://github.com/Azure/azure-rest-api-specs/blob/current/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/2016-06-01/registeredIdentities.json#L73) to the parameter declaration - it's no big deal here since you only used the parameter once, but before unrolling *multiple* referenced to the same parameter, definitely use `x-ms-parameter-location`.

2017-08-11 16:37 UTC, dsgouda commented
On second thoughts I agree with @olydis , if you do ever need to use `resourceGroupNameParamater` in some other operation, you can simply reference this global definition (something we'd recommend anyway)

2017-08-11 16:38 UTC, dsgouda commented on specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/2017-04-18/cognitiveservices.json
> -      "type": "string"
set `x-ms-parameter-location` here instead, should be a one line change

2017-08-11 16:39 UTC, dsgouda requested changes
Requesting a minor change

2017-08-14 03:44 UTC, felixwa commented
Okay, now use "x-ms-parameter-location": "method" to decorate the parameter.

2017-08-14 16:12 UTC, olydis approved these changes

2017-08-14 16:19 UTC, dsgouda approved these changes

2017-08-14 16:19 UTC, merged

2017-08-14 16:22 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1532)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/891

2017-08-14 16:22 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1532)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1363

2017-08-14 16:22 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-08-14 16:23 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node