Added service endpoints APIs
Azure/azure-rest-api-specs pull request #1533
Opened 2017-08-11 09:37 UTC by EvgenyAgafonchikov

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-08-11 18:19 UTC, sergey-shandar commented
@ravbhatnagar New swagger file.

2017-08-14 17:34 UTC, sergey-shandar requested changes
Waiting for ARM feedback.

2017-08-15 21:52 UTC, DeepakRajendranMsft commented
Ping....Why does this need ARM review again? this has already been reviewed by them. we are renaming this property. so we had to remove and replace it back. @sergey-shandar  @ravbhatnagar

2017-08-15 22:08 UTC, sergey-shandar commented
@DeepakRajendranMsft I see a new file Microsoft.Network/2017-06-01/endpointService.json. Could you send a link to the ARM review for this file?

2017-08-15 22:11 UTC, DeepakRajendranMsft commented
this is the PR where we dropped it https://github.com/Azure/azure-rest-api-specs/pull/1486. we wouldnt have put in there if we didnt get ARM approval :)

2017-08-15 22:17 UTC, sergey-shandar commented
@ravbhatnagar could you confirm ARM review? I still can't see a ARM review confirmation for the new file.

2017-08-15 22:28 UTC, ravbhatnagar commented
@sergey-shandar - looks good.

2017-08-15 22:53 UTC, DeepakRajendranMsft commented
@sergey-shandar can this be merged please

2017-08-15 22:57 UTC, sergey-shandar commented
@DeepakRajendranMsft I'm working on a review. I'll post it today.

2017-08-15 23:24 UTC, sergey-shandar requested changes

2017-08-16 00:16 UTC, DeepakRajendranMsft commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/virtualNetwork.json
> +        "serviceEndpoints": {
@amarzavery  @salameer this is well documented and we are okay with the breaking change.
it is read-write property.

2017-08-16 00:28 UTC, DeepakRajendranMsft commented on specification/network/resource-manager/Microsoft.Network/2017-06-01/virtualNetwork.json
> +        "serviceEndpoints": {
@ravbhatnagar can you sign off on this new additional property.

2017-08-16 00:54 UTC, ravbhatnagar commented
@DeepakRajendranMsft - Is this again the same case where it has already been added on the service side for this api-version and swagger update is happening now?

2017-08-16 01:45 UTC, DeepakRajendranMsft commented
@ravbhatnagar yes. because we did a rename of the property.

2017-08-16 01:46 UTC, ravbhatnagar commented
@sergey-shandar - ARM signs off.

2017-08-16 06:11 UTC, sergey-shandar approved these changes

2017-08-16 06:11 UTC, merged

2017-08-16 06:14 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-08-16 06:15 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1533)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/896

2017-08-16 06:16 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1533)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1369