Current1
Azure/azure-rest-api-specs pull request #1540
Opened 2017-08-14 20:45 UTC by alvadb

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-08-14 20:45 UTC, msftclas commented
@alvadb,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-08-15 16:31 UTC, vishrutshah requested changes
@alvadb Let's make sure that [CI](https://travis-ci.org/Azure/azure-rest-api-specs/builds/264511255?utm_source=github_status&utm_medium=notification) is green first and also let me know if you have any questions. 

Also, curious to know whether you are doing this on behalf of service team?

Thanks!

2017-08-16 17:19 UTC, vishrutshah requested changes

2017-08-16 17:19 UTC, vishrutshah commented on specification/cognitiveservices/data-plane/Content Moderator/v1.0/contentmoderatorImageText.swagger.json
> +            "$ref": "#/parameters/ocpApimSubscriptionKeyParameter"
CI seems to be failing due to the duplicate parameters. 

https://travis-ci.org/Azure/azure-rest-api-specs/jobs/264921311#L3501

2017-08-18 21:17 UTC, vishrutshah requested changes

2017-08-18 21:17 UTC, vishrutshah commented on specification/cognitiveservices/data-plane/Content Moderator/v1.0/contentmoderatorImageText.swagger.json
> +              "type": "file"
This seems to be non-confimant to the swagger 2.0 schema. Please use 

```json5
"schema" : {
  "type": "object",
  "format": "file"
}
```

Reference: https://github.com/Azure/azure-rest-api-specs/pull/1544

2017-08-18 21:17 UTC, vishrutshah commented on specification/cognitiveservices/data-plane/Content Moderator/v1.0/contentmoderatorImageText.swagger.json
> +              "type": "file"
Here as well

2017-08-18 21:17 UTC, vishrutshah commented on specification/cognitiveservices/data-plane/Content Moderator/v1.0/contentmoderatorImageText.swagger.json
> +              "type": "file"
here as well

2017-08-18 21:17 UTC, vishrutshah commented on specification/cognitiveservices/data-plane/Content Moderator/v1.0/contentmoderatorImageText.swagger.json
> +              "type": "file"
here as well

2017-08-22 23:21 UTC, vishrutshah requested changes
Please review the syntax failures on CI https://travis-ci.org/Azure/azure-rest-api-specs/jobs/267346600#L3521 Thanks!

2017-09-05 21:46 UTC, veronicagg commented
@alvadb are there updates on this one?

2017-09-15 19:47 UTC, salameer commented
@alvab what are the next steps here on this PR?

2017-09-25 17:39 UTC, vishrutshah commented
Closing this as service team is working on improvements in their fork. Once completed, they'll send a new PR for review. Thanks@

2017-09-25 17:39 UTC, closed without merging