Add extended operations for ADF V1 multi-nodes Gateway
Azure/azure-rest-api-specs pull request #1577
Opened 2017-08-23 02:44 UTC by nicolaszhang

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-08-23 02:44 UTC, msftclas commented
@nicolaszhang,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-08-24 20:20 UTC, jianghaolu requested changes
The CI is not running properly without the files in the correct location - please address it and I'll take a further look.

2017-08-24 20:20 UTC, jianghaolu commented on specification/datafactory/resource-manager/Microsoft.DataFactoryV1Extended/2017-08-10-preview/swagger/datafactory.json
> +{
This file should appear one level up. We shouldn't have an extra folder `swagger`.

2017-08-24 20:20 UTC, jianghaolu commented on specification/datafactory/resource-manager/Microsoft.DataFactoryV1Extended/2017-08-10-preview/swagger/datafactory.json
> +              "$ref": "../examples/GatewaysExtended_Get.json"
When you move it up, remember to fix these example paths.

2017-09-05 21:49 UTC, veronicagg commented
@nicolaszhang any updates?

2017-09-15 20:00 UTC, salameer commented
@nicolaszhang  we will close this PR due to lack of response, plz reachout out if you want it to be re-opened

2017-09-15 20:00 UTC, closed without merging