Admin Swagger Specs for Commerce, Fabric, and Infrastructure Insights
Azure/azure-rest-api-specs pull request #1592
Opened 2017-08-25 22:50 UTC by deathly809

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR. 

---
## Known validation issues

### Commerce

Not implemented yet.  When I try to access this I get an exception.
```
ERROR (OperationsAPIImplementation/R3023/RPCViolation): Operations API must be implemented for '/providers/Microsoft.Commerce/operations'.
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/commerce/resource-manager/Microsoft.Commerce.Admin/2015-06-01-preview/swagger/commerceAdmin.json:16:1 ($.paths)
```

### Fabric

Not implemented yet.  When I try to access this I get an exception.
```
ERROR (OperationsAPIImplementation/R3023/RPCViolation): Operations API must be implemented for '/providers/Microsoft.Fabric.Admin/operations'.
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/SlbMuxInstance.json:17:4 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/ScaleUnitNode.json:17:4 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/ScaleUnit.json:17:2 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/Operations.json:11:4 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/MacAddressPool.json:17:4 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/LogicalSubnet.json:17:2 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/Volume.json:17:2 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/StorageSystem.json:17:4 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/StoragePool.json:17:4 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/LogicalNetwork.json:17:4 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/IpPool.json:17:4 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/InfraRoleInstance.json:17:4 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/InfraRole.json:17:4 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/FileShare.json:17:4 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/FabricLocation.json:17:4 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/EdgeGatewayPool.json:17:4 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/EdgeGateway.json:17:2 ($.paths)
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/Fabric.json:17:1 ($.paths)
```

```
WARNING (EnumInsteadOfBoolean/R3018/RPCViolation): Booleans are not descriptive and make them hard to use. Consider using string enums with allowed set of values defined. Property: networkVirtualizationEnabled
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/LogicalNetwork.json:123:16 ($.definitions.LogicalNetworkModel.properties.networkVirtualizationEnabled)
WARNING (EnumInsteadOfBoolean/R3018/RPCViolation): Booleans are not descriptive and make them hard to use. Consider using string enums with allowed set of values defined. Property: isPublic
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/LogicalSubnet.json:129:8 ($.definitions.LogicalSubnetModel.properties.isPublic)
```

This is to fix a naming issue.  Without this Autorest appends Property (I think) to the end of the name and cannot deserialize the results from the RP.
```
ERROR (XmsClientNameProperty/R2013/SDKViolation): Value of 'x-ms-client-name' cannot be the same as 'provisioningState' Property/Model.
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/Operations.json:112:12 ($.definitions.ProvisioningState.properties)
```

It is either true or false.
```
WARNING (EnumInsteadOfBoolean/R3018/RPCViolation): Booleans are not descriptive and make them hard to use. Consider using string enums with allowed set of values defined. Property: canPowerOff
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/ScaleUnitNode.json:299:16 ($.definitions.ScaleUnitNodeModel.properties.canPowerOff)
```

This only works on a multi-node environment and I don't have one. 
```
ERROR (XmsExamplesRequired/R2022/SDKViolation): Please provide x-ms-examples describing minimum/maximum property set for response/request payloads for operations. Operation: 'InfraRoles_ScaleUp'
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/InfraRole.json:19:12 ($.paths["/subscriptions/{subscriptionId}/resourceGroups/System.{location}/providers/Microsoft.Fabric.Admin/fabricLocations/{location}/infraRoles/{infraRole}/ScaleUp"].post)
```

This only works on a multi-node environment and I don't have one. 
```
ERROR (XmsExamplesRequired/R2022/SDKViolation): Please provide x-ms-examples describing minimum/maximum property set for response/request payloads for operations. Operation: 'ScaleUnits_ScaleOut'
    - file:///C:/temp/azure-rest-api-specs/specification/azsadmin/fabric/resource-manager/Microsoft.Fabric.Admin/2016-05-01/swagger/ScaleUnit.json:19:6 ($.paths["/subscriptions/{subscriptionId}/resourceGroups/System.{location}/providers/Microsoft.Fabric.Admin/fabricLocations/{location}/sca [...]

2017-08-25 22:50 UTC, msftclas commented
@deathly809,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-08-25 23:37 UTC, sarangan12 commented
@deathly809 Please take a look at the build jobs here: https://travis-ci.org/Azure/azure-rest-api-specs/builds/268547010?utm_source=github_status&utm_medium=notification 

There are 2 sets of jobs: Regular & Allowed Failure Jobs. Here Regular Jobs must be completed successfully for approval. In this case, one of the regular jobs failed. Take a look at: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/268547011 

There are 25 errors which are listed at https://travis-ci.org/Azure/azure-rest-api-specs/jobs/268547011#L3678. I have looked at these errors and the messages seem to be self explanatory. Please fix them and update the PR

2017-08-26 00:14 UTC, deathly809 commented
@sarangan12 

I have gone through and fixed all the issues except one specific error..  It says I cannot use x-ms-headers but the RP team returns the location to an operation status in the headers.

2017-08-30 20:32 UTC, sarangan12 requested changes

2017-08-30 20:32 UTC, sarangan12 commented on specification/azsadmin/resource-manager/fabric/readme.md
> +    - "Microsoft.Fabric.Admin/2016-05-01/Operations.json"
The name of the file is oncorrect. operations.json vs Operations.json. Please fix

2017-08-30 23:35 UTC, sarangan12 approved these changes

2017-08-30 23:35 UTC, merged

2017-08-30 23:47 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-08-30 23:47 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-ruby

2017-08-30 23:49 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-python