Add 2015-05-01 capabilities swagger
Azure/azure-rest-api-specs pull request #1600
Opened 2017-08-29 02:57 UTC by gaagra

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-08-29 02:57 UTC, msftclas commented
@__gaagra__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

It will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-08-29 19:18 UTC, anuchandy commented
continuous-integration/travis-ci/pr The Travis CI build [failed](https://travis-ci.org/Azure/azure-rest-api-specs/builds/269428052?utm_source=github_status&utm_medium=notification)

@gaagra please fix the linter, sematic and model validations - 

https://travis-ci.org/Azure/azure-rest-api-specs/jobs/269428059
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/269428060
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/269428061

2017-08-29 19:49 UTC, anuchandy commented
This is a new swagger targeting API version `2015-05-01` so adding `WaitForARMFeedBack` label.

2017-08-29 19:51 UTC, anuchandy requested changes
Please fix the CI failures as pointed. Also provide examples for capabilities operations.

2017-08-30 17:53 UTC, anuchandy commented
@gaagra it looks like swagger reference examples which does not exist.

You can repro this locally by running:

```
autorest --validation --azure-validator --message-format=json --input-file=./specification/sql/resource-manager/Microsoft.Sql/2015-05-01/capabilities.json
```

```
oav validate-spec ./specification/sql/resource-manager/Microsoft.Sql/2015-05-01/capabilities.json
oav validate-example ./specification/sql/resource-manager/Microsoft.Sql/2015-05-01/capabilities.json 
```

2017-09-01 05:20 UTC, anuchandy commented
@ravbhatnagar please sign-off.

2017-09-01 05:21 UTC, anuchandy approved these changes
looks good from SDK side.

2017-09-01 05:21 UTC, anuchandy commented on specification/sql/resource-manager/Microsoft.Sql/2015-05-01/capabilities.json
> +        "reason": {
Does service populate `reason` field only if `status` has a value other than `Available` (i.e. `Visible`, `Default `, `Disabled `)?

2017-09-01 22:05 UTC, gaagra commented on specification/sql/resource-manager/Microsoft.Sql/2015-05-01/capabilities.json
> +        "reason": {
yes

2017-09-01 22:47 UTC, jaredmoo commented on specification/sql/resource-manager/readme.md
> +- Microsoft.Sql/2015-05-01/capabilities.json
please add 2015-05-01-preview capabilities and use that one here.

2017-09-12 01:11 UTC, ravbhatnagar commented
Signed off!

2017-09-15 23:17 UTC, salameer commented
@anuchandy 

its seems to me that this is ready for merging right :)

2017-09-18 20:08 UTC, merged

2017-09-18 20:12 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-09-18 20:13 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1600)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1449

2017-09-18 20:13 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1600)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/981