add the list and cancel database operations
Azure/azure-rest-api-specs pull request #1605
Opened 2017-08-29 16:54 UTC by jiawang003

add the list and cancel database operations under 2017-03-01-preview, there's no issue in autorest validation

2017-08-29 16:54 UTC, msftclas commented
@jiawang003,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-08-29 19:25 UTC, olydis commented
@ravbhatnagar new APIs

2017-08-31 01:33 UTC, ravbhatnagar commented
Other than that it looks fine.

2017-08-31 17:57 UTC, jiawang003 commented on specification/sql/resource-manager/Microsoft.Sql/2017-03-01-preview/cancelOperations.json
> +            "responses": {
yes it'll be updated as CANCELLED

2017-08-31 22:44 UTC, jaredmoo requested changes

2017-08-31 22:44 UTC, jaredmoo commented on specification/sql/resource-manager/Microsoft.Sql/2017-03-01-preview/cancelOperations.json
> +            "operationId": "Databases_Cancel",
DatabaseOperations_Cancel

2017-08-31 22:44 UTC, jaredmoo commented on specification/sql/resource-manager/Microsoft.Sql/2017-03-01-preview/cancelOperations.json
> +        "operationId": "Databases_ListOperations",
DatabaseOperations_ListByDatabase

2017-09-01 14:16 UTC, olydis commented
@sergey-shandar Swapping this with you since I took the other one, let me know if that doesn't work for you 😉

2017-09-05 17:37 UTC, closed without merging