[Azure Analysis Services] Add dissociate gateway operation
Azure/azure-rest-api-specs pull request #1625
Opened 2017-08-31 22:52 UTC by taiwu

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-08-31 22:52 UTC, msftclas commented
@__taiwu__,
Thanks for your contribution. It looks like you are a Microsoft vendor. To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

The agreement will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-09-01 14:03 UTC, olydis commented
@ravbhatnagar new operation

2017-09-06 02:14 UTC, ravbhatnagar requested changes
@taiwu - Need to understand the intent of this API little more.

2017-09-06 02:14 UTC, ravbhatnagar commented on specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-07-14/analysisservices.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AnalysisServices/servers/{serverName}/dissociateGateway": {
how will calling this API change the payload of the GET /servers/{serverName} existing API that you have? THat has a gatewayResourceId which is associated with the server. What does disassociating that gateway mean?

2017-09-06 19:33 UTC, taiwu commented
I am oof this week, the gateway object is part of mutable property in AS. We can talk next Wednesday when I am back to office.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Gaurav Bhatnagar <notifications@github.com>
Sent: Tuesday, September 5, 2017 7:14:28 PM
To: Azure/azure-rest-api-specs
Cc: Tai-Yi Wu; Mention
Subject: Re: [Azure/azure-rest-api-specs] [Azure Analysis Services] Add dissociate gateway operation (#1625)


@ravbhatnagar requested changes on this pull request.

@taiwu<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftaiwu&data=02%7C01%7Ctaiwu%40microsoft.com%7Cc113f31d96184977fee808d4f4cd00d1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636402608692468614&sdata=B4eKJ9GEClhwuNOKsq9jO47NwK%2FDyE9JCh8DMKQEack%3D&reserved=0> - Need to understand the intent of this API little more.

________________________________

In specification/analysisservices/resource-manager/Microsoft.AnalysisServices/2017-07-14/analysisservices.json<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F1625%23discussion_r137157500&data=02%7C01%7Ctaiwu%40microsoft.com%7Cc113f31d96184977fee808d4f4cd00d1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636402608692468614&sdata=QHP7NNqqnEsDiwMp144BiQyMEvCXMxw%2Fk%2BWMyvGDdp4%3D&reserved=0>:

> @@ -417,6 +417,39 @@
           }
         }
       }
+    },
+    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AnalysisServices/servers/{serverName}/dissociateGateway": {


how will calling this API change the payload of the GET /servers/{serverName} existing API that you have? THat has a gatewayResourceId which is associated with the server. What does disassociating that gateway mean?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F1625%23pullrequestreview-60788068&data=02%7C01%7Ctaiwu%40microsoft.com%7Cc113f31d96184977fee808d4f4cd00d1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636402608692468614&sdata=q%2FN7C25%2FUGE%2BjExqyfiWgGt%2BCKuti2UHxympEwBeY7U%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAb50QwzUw2q-Ol2S36HlfU5fFE1T-Yesks5sfgADgaJpZM4PJgYx&data=02%7C01%7Ctaiwu%40microsoft.com%7Cc113f31d96184977fee808d4f4cd00d1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636402608692468614&sdata=%2BSbs1ieGjyGzr1gUlMq1S5qXUpgBhihDHip6pCXM11M%3D&reserved=0>.

2017-09-15 20:02 UTC, salameer commented
@taiwu and @ravbhatnagar any updates on this PR?

2017-09-15 20:30 UTC, taiwu commented
@ravbhatnagar as mentioned, the gatewayDetails object in get is mutable property.
If the AS instance dissociate the gateway, the AS instance will not have gatewayDetails object.

2017-09-20 17:49 UTC, olydis commented
@ravbhatnagar ping

2017-09-21 00:43 UTC, ravbhatnagar commented
@olydis - Following up with @taiwu on IM. This ideally should be modelled through a PUT and a new POST API should not be needed.

2017-09-21 01:54 UTC, ravbhatnagar commented
As per email conversation and ACK from AS team, we will let this PR in with the understanding that the team will fix this in the new API-version revision. This behavior is already implemented in the service side.
@johanste @salameer  as FYI.
@olydis - Good to merge the PR,

2017-09-21 01:55 UTC, ravbhatnagar commented
@veronicagg  - we need a new label to mark such PRs which we have conditionally merged. It will help in pulling them later and following up with the teams.

2017-09-21 01:55 UTC, ravbhatnagar approved these changes

2017-09-21 17:38 UTC, olydis approved these changes

2017-09-21 17:38 UTC, merged

2017-09-21 17:41 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-09-21 17:42 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1625)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/990

2017-09-21 17:45 UTC, veronicagg commented
@ravbhatnagar sure, I didn't know we were doing conditional merges. How will this work from the point of view of generating SDKs and breaking changes? Label is not a problem, I can create "Conditionally-Merged" label, feel free to use it, but I'm curious on how we're dealing with these after the conditional merge.