[ADLA] - [BUGFIX] - Adding an innerError field to JobInnerError object
Azure/azure-rest-api-specs pull request #1627
Opened 2017-09-01 02:21 UTC by ro-joowan

* There can be more levels of the innerError field in a JobInnerError object.  There is currently only one level of nesting of innerError. Practically, however, the service returns up to two levels.  Theoretically, this nesting can go on forever.  Hence, the recursive definition.  

* I made the change below:

Before:
* JobErrorDetails
  * JobInnerError

After:
* JobErrorDetails
  * JobInnerError
    * JobInnerError
      * ... More JobInnerErrors theoretically forever

* I passed on a private build to the IDE team for testing.  They did not run into any issues with the recursive definition.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-09-01 02:21 UTC, msftclas commented
@ro-joowan,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-09-05 19:31 UTC, veronicagg requested changes
@ro-joowan just one question, have you generated private code with AutoRest and made sure it looks the way you want? and that at least on the .Net SDK side the code works properly with this change?

2017-09-05 19:53 UTC, ro-joowan commented
@veronicagg, Yes I generated the private code and another team member made sure that it works with the .NET SDK

2017-09-05 20:23 UTC, veronicagg approved these changes

2017-09-05 20:23 UTC, merged

2017-09-05 20:28 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1627)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1412

2017-09-05 20:28 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-09-05 20:29 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-ruby