Update Anomaly Detection API
Azure/azure-rest-api-specs pull request #16543
Opened 2021-10-26 04:25 UTC by juaduan

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [x] SDK of .NET (need service team to ensure code readiness)
      - [x] SDK of Python
      - [x] SDK of Java
      - [x] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label “WaitForARMFeedback” will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

2021-11-08 20:08 UTC, heaths commented
Could you please rebase your changes atop main to avoid showing so many unrelated commits requiring review from many different people. It's also difficult to tell which of the 712 files you need reviewed.

Assuming you're on your topic branch (note: best practice is to always create a branch - not work directly in main, even if pushing to your fork), upstream is Azure/azure-rest-api-specs, and origin is juaduan/azure-rest-api-specs:

```bash
git fetch upstream main
git rebase upstream/main
#resolve any merge conflicts
git push -u --force origin main
```

This will make the PR much cleaner to review.

2021-11-11 00:57 UTC, markweitzel commented
@juaduan -- We've been experimenting with the [Spectral Linter](https://aka.ms/azapi/style) which has a nice VSCode plugin. We've used this to update have a quick look at the OpenAPI doc and apply the recently updated [REST API Guidelines](https://aka.ms/azapi/guidelines). We've identified a few things that would be good to look at and/or talk through...

There are a number of guidelines spread throughout your document that are easy to address, for example:
* Your Error response should contain a `x-ms-error-code` header.
* All success responses except 202 & 204 should define a response body.
* Property name should be camel case.

2021-11-11 04:08 UTC, juaduan commented
@markweitzel thanks for your recommendation. We are walking through the REST API guidelines to modify our documents.

2021-11-12 01:21 UTC, markweitzel requested changes
Based on the Stewardship board meeting, some ideas are captured in the issue.

2021-11-25 13:34 UTC, juaduan commented
Hi @markweitzel, we have updated our PR based on your suggestions. Please take a review. Thank you.

2021-12-01 15:22 UTC, mikekistler reviewed
I left a few quetions/comments I hope you can address.

2021-12-03 03:36 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.1-preview.1/AnomalyDetector.json
> +      "x-nullable": false,
Removed all the `x-nullable: false`

2021-12-03 03:38 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.1-preview.1/AnomalyDetector.json
> +        "modelAsString": false,
Good point. Do make this `modelAsString` as `true`.

2021-12-03 03:38 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.1-preview.1/AnomalyDetector.json
> +      "x-nullable": false,
Removed all the `x-nullable: false`

2021-12-03 03:57 UTC, moreOver0 commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.1-preview.1/AnomalyDetector.json
> +      "x-nullable": true,
Removed the `x-nullable`. I double confirmed with the team, this was be modified mistakenly.

2021-12-03 04:00 UTC, moreOver0 commented
@mikekistler Thanks for review again, we've addressed the comments.

2021-12-03 04:33 UTC, mengaims commented
@mikekistler Thanks for reviewing! We've commit a change other than resolving the comments: added "severity" to required fields of EntireDetectResponse and LastDetectResponse. Sorry for the late change, could you help confirm whether it's valid?

2021-12-13 07:35 UTC, mengaims commented
@mikekistler Thanks for the advices! We have completed your suggested change about "xs-ms-error-code" and adding descriptions, could you please check and help sign off?

2021-12-13 17:13 UTC, mikekistler approved these changes
Looks good. 👍 

I left a few minor comments you should consider.

2021-12-14 04:15 UTC, juaduan commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.1-preview.1/MultivariateAnomalyDetector.json
> +            "x-ms-error-response": true,
Hi @mikekistler, thank you for your comments. We have modified the swagger file per your suggestion.

`x-ms-error-response` has been removed in the default response.

2021-12-14 04:15 UTC, juaduan commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.1-preview.1/MultivariateAnomalyDetector.json
> +            "description": "Submit a multivariate model training task successfully.",
The description message has been changed to "Create and train a multivariate anomaly detection model.".

2021-12-14 04:15 UTC, juaduan commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.1-preview.1/MultivariateAnomalyDetector.json
> +            },
This section is removed and the content-type has been specified in `produces`.

2021-12-14 04:15 UTC, juaduan commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.1-preview.1/MultivariateAnomalyDetector.json
> +              "format": "file"
The type and format has been modified per your suggestion.

2021-12-15 20:21 UTC, jhendrixMSFT approved these changes

2021-12-15 20:22 UTC, jhendrixMSFT commented
@markweitzel have your changes been addressed?  Your review is still "changes requested"

2021-12-15 21:13 UTC, merged