[TrafficManager] Removing RealUserMetrics from 2017-05-01 where it was erroneously added and moving it to preview API. Making Preview API ONLY for HeatMap and RealUserMetrics, leaving other API's in stable version. Adding additional example for HeatMap with null properties in the response.
Azure/azure-rest-api-specs pull request #1668
Opened 2017-09-12 18:32 UTC by hrkulkarMsft

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-09-12 18:32 UTC, msftclas commented
@hrkulkarMsft,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-09-12 19:52 UTC, jhendrixMSFT commented
There are [linter](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/274728152) and [model validation](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/274728154) errors that need to be addressed.

2017-09-12 19:57 UTC, jhendrixMSFT requested changes
Linter and model validation errors need to be fixed.

2017-09-12 22:53 UTC, hrkulkarMsft commented
Hi Joel,

For Operations complaint: 
![image](https://user-images.githubusercontent.com/30481742/30351883-4cda7a2e-97d2-11e7-90a6-842c41e34a83.png)

For lack of "list" operation for heatmaps, this was discussed in PR where this resource was added, here. The heatmap is currently just a singular resource: https://github.com/Azure/azure-rest-api-specs/pull/1580

For the boolean value: would this break existing APIs if changed from enum to boolean?


Thanks,
Hrishi

2017-09-13 17:08 UTC, jhendrixMSFT commented
@hrkulkarMsft you are correct it would introduce a breaking change.  No need to change it in this PR as that's a different API.
The model validation errors [here](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/274818576) are specific to this API and will need to be fixed.  If you'd like to run the validation locally you can find instructions [here](https://github.com/Azure/adx-documentation-pr/blob/master/tools/tools.md).

2017-09-14 08:28 UTC, ravbhatnagar commented
Looks good for ARM

2017-09-14 16:54 UTC, jhendrixMSFT commented
Closing then re-opening to restart travis.

2017-09-14 16:54 UTC, msftclas commented
@hrkulkarMsft,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-09-14 19:03 UTC, hrkulkarMsft commented on specification/trafficmanager/resource-manager/Microsoft.Network/2017-09-01-preview/trafficmanageranalytics.json
> +              "$ref": "#/definitions/DeleteOperationResult"
wouldn't this be repetitive otherwise?

2017-09-14 19:51 UTC, jhendrixMSFT commented on specification/trafficmanager/resource-manager/Microsoft.Network/2017-09-01-preview/trafficmanageranalytics.json
> +              "$ref": "#/definitions/DeleteOperationResult"
Sorry I don't follow what you mean.  Getting back the 200 status code from the delete operation should be sufficient to indicate that the delete happened yes?

2017-09-18 19:01 UTC, jhendrixMSFT commented
@hrkulkarMsft any update here?

2017-09-20 18:37 UTC, hrkulkarMsft commented
Sorry for the delay. Yeah, we can fix these APIs in a future iteration -- however these were already approved as is during earlier PR's in their previous format for the Delete operation.

This PR is more to address the error in api-versions for RealUserMetrics and maintain separate versioning for these two api's versus the other resources.

2017-09-20 21:13 UTC, jhendrixMSFT commented
There is still the open question about the delete operation returning a model.

2017-09-25 22:59 UTC, jhendrixMSFT commented
Closing then re-opening to trigger travis.

2017-09-25 22:59 UTC, msftclas commented
@hrkulkarMsft,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-09-25 23:06 UTC, jhendrixMSFT commented
@hrkulkarMsft I missed your comment about the delete operation returning a model, agreed we can defer that for now.  As for the example failures, sorry I don't have an answer for you.  Have you tried asked on the swagger slack channel?

2017-09-27 17:31 UTC, hrkulkarMsft commented
Sorry @jhendrixMSFT, about the delay in response. That sounds good. I was not able to find an answer through the swagger group, I tried both "x-nullable": true for the property as well as marking latency as not being required. But it still seems to fail the example.

2017-09-27 18:12 UTC, jhendrixMSFT commented
@hrkulkarMsft Usually when a value isn't provided in the response it's simply omitted from the response payload (i.e. not sent across the wire).  Is that not how your service works?

2017-09-27 18:27 UTC, jhendrixMSFT commented
Put another way, if  this property is not marked as required then you should simply be able to omit it from the example response.

2017-10-04 21:09 UTC, jhendrixMSFT commented
@hrkulkarMsft Hello!  Is this PR still required?

2017-10-05 22:23 UTC, hrkulkarMsft commented
Just submitted the fix, apologies for taking so long.

Another question, how quickly could be rebuild the SDK's for 2017-09-01-preview?

2017-10-05 22:37 UTC, jhendrixMSFT requested changes

2017-10-05 22:37 UTC, jhendrixMSFT commented on specification/trafficmanager/resource-manager/Microsoft.Network/2017-09-01-preview/trafficmanageranalytics.json
> +        "operationId": "TrafficManagerUserMetricsKeys_GetDefault",
The example for this operation has some validation errors, see the [log](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/283933876).

2017-10-05 22:39 UTC, jhendrixMSFT commented
@hrkulkarMsft Thanks for following up, just one fix for examples then we can merge this.  As to when the SDKs are built I can't answer that as they all release on a different cadence.  Best bet is to follow up on the slack channel.

2017-10-05 22:39 UTC, hrkulkarMsft commented
How did this example then pass the last submission?

2017-10-05 22:41 UTC, jhendrixMSFT commented
My guess is something changed in the tool to uncover this error.

2017-10-05 23:02 UTC, jhendrixMSFT approved these changes

2017-10-05 23:02 UTC, merged

2017-10-05 23:05 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR1668)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1513

2017-10-05 23:05 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-10-05 23:06 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR1668)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/1022

2017-10-06 00:29 UTC, johnmic commented on specification/trafficmanager/resource-manager/Microsoft.Network/2017-09-01-preview/trafficmanageranalytics.json
> +              "$ref": "#/definitions/DeleteOperationResult"
Yes, seems more RPC style than REST. Should return 204 No Content?