Add Domain Service Swagger Spec
Azure/azure-rest-api-specs pull request #1689
Opened 2017-09-14 21:24 UTC by jihochang

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-09-14 21:24 UTC, msftclas commented
@jihochang,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-09-14 21:59 UTC, jihochang commented
Our service is now public, so moving the swagger from azure-rest-api-specs-pr to azure-rest-api-specs branch.

Here is the link to the previous pull request to azure-rest-api-specs-pr branch:
https://github.com/Azure/azure-rest-api-specs-pr/pull/67

No changes have been made, since last pull request. I was unable to add the previous reviewer veronicagg to this pull request.

2017-09-15 23:30 UTC, salameer commented
Adding Veronica, Since she has the context

2017-09-18 20:34 UTC, veronicagg commented
@jihochang our repo structure changed between your private PR and this one. 
Could you please add a "readme.md" file to match the new one? similar to https://github.com/Azure/azure-rest-api-specs/blob/current/specification/advisor/resource-manager/readme.md You can find more  readme.md examples at https://github.com/Azure/autorest/tree/97b68250afd96111f79047e24e22eeb82a30426f/src/autorest-core/test/variations

2017-09-18 21:28 UTC, veronicagg requested changes
Please see my comment regarding adding a readme.me file.

2017-09-18 21:31 UTC, jihochang commented
I have added the readme file and changed the file structure to match the new file structure.

2017-09-18 21:39 UTC, veronicagg requested changes

2017-09-18 21:39 UTC, veronicagg commented on specification/domainservices/resource-manager/Microsoft.AAD/2017-01-01/DomainServicesSwagger.json
> +            "$ref": "/examples/GetOperations.json"
I believe this references have to be "./examples..." so start with "." - https://travis-ci.org/Azure/azure-rest-api-specs/jobs/277044016

2017-09-19 00:01 UTC, jihochang commented
Updated Example Links

2017-09-19 19:05 UTC, veronicagg approved these changes
LGTM, thanks!

2017-09-19 19:06 UTC, merged

2017-09-19 19:09 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-ruby

2017-09-19 19:09 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-ruby

2017-09-19 19:09 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-09-19 19:09 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-09-19 19:09 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-python

2017-09-19 19:09 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-python