Review request for Microsoft.MachineLearningServices to add version preview/2022-01-01-preview
Azure/azure-rest-api-specs pull request #17079
Opened 2021-12-14 08:04 UTC by superkevin813

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific langauge SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that label "WaitForARMFeedback" will be added automatically to begin ARM API Review. Failure to comply may result in delays to the manifest.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits.

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

2021-12-14 18:25 UTC, superkevin813 commented
LintDiff and ModelValidation error cause by existing API version copied over. Not related to new preview API (Only adding five new properties). Please suggest if need to fix those existing errors.

2021-12-14 21:06 UTC, mentat9 commented
>         "softDeleteEnabled": {

ARM recommends string enums over boolean. Generally enums make better properties than booleans. They are more descriptive, flexible and future-proof while being easier for customers to discover, understand and use.

Wiki page: [https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review](https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html?q=boolean#common-issues-found-in-review)

Best option is to choose a better property (e.g. deleteType: { "Permanent", "Soft" }). Next best option if you really want a True/False value is to use a string enum "softDeleteEnabled": { "True", "False" }. Enums allow adding values later without requiring a new API version.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json:2096 in 960e39a. [](commit_id = 960e39ae3bc4d1d2f8dbee06a042afe4cb6c0629, deletion_comment = False)

2021-12-14 21:06 UTC, mentat9 commented
>         "recoverWorkspace": {

This sounds like an action rather than a property. Actions should be modeled as a POST action.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json:2101 in 960e39a. [](commit_id = 960e39ae3bc4d1d2f8dbee06a042afe4cb6c0629, deletion_comment = False)

2021-12-14 21:07 UTC, mentat9 commented
>         "cosmosDbArmId": {

Recommend ResourceId instead of ArmId for these three property names.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json:4504 in 960e39a. [](commit_id = 960e39ae3bc4d1d2f8dbee06a042afe4cb6c0629, deletion_comment = False)

2021-12-14 21:07 UTC, mentat9 commented
>           "description": "The byok cosmosdb account that customer brings to store customer's data",

Please spell out this acronym (or just remove it).

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json:4505 in 960e39a. [](commit_id = 960e39ae3bc4d1d2f8dbee06a042afe4cb6c0629, deletion_comment = False)

2021-12-15 08:53 UTC, superkevin813 commented
@mentat9  thanks for the review. I have addressed your comments.

2021-12-20 18:43 UTC, superkevin813 commented
@ArcturusZhang can I have a sign off from you? Is there still anything blocking please let me know. he LintDiff and ModelValidation is an existing issue from previous stable version. We will address them in the next stable version

2022-01-05 02:51 UTC, ArcturusZhang requested changes

2022-01-05 02:51 UTC, ArcturusZhang commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json
> +        {
Please do not use anonymous schema here, which usually generates bad SDK code.
Also please do not use multi-inheritance, which usually generates bad SDK code as well

2022-01-05 02:51 UTC, ArcturusZhang commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json
> +    },
Please combine these two schemas instead of using `allOf`.

2022-01-05 02:51 UTC, ArcturusZhang commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json
> +      ],
Same, please do not use anonymous schema and multi-inheritance

2022-01-05 02:51 UTC, ArcturusZhang commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json
> +        {
Same, multi-inheritance and anonymous schema

2022-01-05 02:51 UTC, ArcturusZhang commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json
> +        {
Same, multi-inheritance and anonymous schema

2022-01-05 02:51 UTC, ArcturusZhang commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json
> +        {
Same, multi-inheritance

2022-01-05 02:51 UTC, ArcturusZhang commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json
> +        {
Same, multi-inheritance and anonymous schema

2022-01-05 02:51 UTC, ArcturusZhang commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json
> +        {
Same, multi-inheritance and anonymous schema

2022-01-05 02:51 UTC, ArcturusZhang commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json
> +        {
Same, multi-inheritance and anonymous schema

2022-01-05 02:51 UTC, ArcturusZhang commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json
> +        },
Same, multi-inheritance

2022-01-05 02:51 UTC, ArcturusZhang commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json
> +        {
Same, multi-inheritance

2022-01-05 02:51 UTC, ArcturusZhang commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json
> +        {
Same, multi-inheritance and anonymous schema

2022-01-05 07:20 UTC, jianyexi commented
/azp run

2022-01-05 08:11 UTC, ArcturusZhang approved these changes

2022-01-05 08:11 UTC, ArcturusZhang commented
/azp run

2022-01-06 06:42 UTC, merged