Domain services
Azure/azure-rest-api-specs pull request #1744
Opened 2017-09-26 00:49 UTC by jihochang

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-09-26 00:49 UTC, msftclas commented
@jihochang,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-09-26 00:51 UTC, jihochang commented
Previous Pull Request accepted by veronicagg

https://github.com/Azure/azure-rest-api-specs/pull/1689#issuecomment-330640661

2017-09-26 17:58 UTC, sergey-shandar commented
@ravbhatnagar new API version `DomainServicesSwagger.json`

2017-09-27 16:07 UTC, jihochang commented
The api-version itself is not new. We are just adding the swagger for it now.

2017-09-27 17:31 UTC, olydis commented on specification/domainservices/resource-manager/readme.md
> +- Microsoft.AAD/2017-06-01/domainservices.json
note that this path is *wrong*, the filename is `DomainServicesSwagger.json`. I've just fixed that for the previous API version, please make sure you also adjust this accordingly.

2017-09-28 00:50 UTC, jihochang commented
I renamed the swagger file to match what is in the readme file.

2017-09-28 20:55 UTC, jihochang commented
Could you take another look and approve the pull request? Our ARM swagger deadline for this is tomorrow. This is an already existing API-VERSION and we are just now adding the swagger files corresponding to it.

2017-10-02 17:51 UTC, jihochang commented
Ping any update on this?

2017-10-02 21:00 UTC, ravbhatnagar commented
Looks good.

2017-10-03 17:48 UTC, sergey-shandar requested changes

2017-10-03 17:48 UTC, sergey-shandar commented on specification/domainservices/resource-manager/Microsoft.AAD/2017-01-01/domainservices.json
> +              "$ref": "#/definitions/OperationListResult"
This is definitely an SDK breaking changes. Is there a significant reason to do these breaking changes in the old version of API?

2017-10-03 23:18 UTC, jihochang commented
Creating new pull request, due to bad merge. 

New Pull Request: https://github.com/Azure/azure-rest-api-specs/pull/1790

2017-10-03 23:18 UTC, closed without merging