dedge/api entityid
Azure/azure-rest-api-specs pull request #17854
Opened 2022-02-14 23:51 UTC by dedgems

- Adds base for updating Microsoft.KeyVault from version preview/7.3-preview to version 7.4-preview
- Updates readme
- Updates API version in new specs and examples
- Key Vault 7.4-preview to 7.4-preview.1 (#15900)
- Key Vault keys API: Add OKP key type and EdDSA digital signature (#15989)
- Add EntityId to the API definitions for secrets, keys, and certificates

2022-02-15 00:09 UTC, heaths requested changes
The example responses (see under "examples" directory) should probably be updated as well. Not sure how @jlichwa or others usually do it, but might just be enough to hand-code some sample values rather than record them as long as the model structure is correct.

2022-02-15 00:09 UTC, heaths commented on specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.4-preview.1/certificates.json
> +          "description": "The system-generated ID for this secret."
Seems to be a copy/paste error: you mention "secret" here for certificates. Same for keys. Please be sure to update them all.

2022-02-15 22:55 UTC, heaths approved these changes

2022-02-17 22:44 UTC, heaths commented
/azp run public.rest-api-specs

2022-02-17 23:03 UTC, jhendrixMSFT approved these changes

2022-02-18 00:40 UTC, heaths commented
@lmazuel the [check](https://github.com/Azure/azure-rest-api-specs/pull/17854/checks?check_run_id=5240084358) completed successfully but didn't report back status, even after re-running it. Could you use your magic powers, please?

2022-02-22 18:29 UTC, jhendrixMSFT commented
/azp run

2022-02-23 17:26 UTC, merged