removing resourcetype parameter from global prameters as it is not referenced anywhere.
Azure/azure-rest-api-specs pull request #1795
Opened 2017-10-04 17:09 UTC by amarzavery

The changes in this PR were originally made in #1753.
However, that PR had similar changes for ServiceFabric and RecoveryServicesSiteRecovery. Splitting this so that ResourceHealth changes are standalone.

2017-10-04 17:10 UTC, amarzavery commented
Assigning Veronica as she reviewed this change in #1753.

2017-10-05 17:42 UTC, veronicagg requested changes
@amarzavery could you please tag the appropriate people from ResourceHealth that you're pending sign-off/review from? thanks!

2017-10-06 23:28 UTC, HimanshuMisra1 approved these changes

2017-10-06 23:54 UTC, amarzavery commented
@veronicagg - Himanshu Misra from RH team approved this change.

2017-10-06 23:54 UTC, merged

2017-10-06 23:57 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-10-06 23:57 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-ruby

2017-10-06 23:58 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-python