Adding swagger for ManagementConfiguration and ManagementAssessment o…
Azure/azure-rest-api-specs pull request #1826
Opened 2017-10-09 18:21 UTC by dashimi16

Adding ManagmentConfiguration and ManagementAssocian resources. Actual resource review is on going with Gaurav. Publishing the pull request per his guidance. We should not complete this pull request before the manifest update to make the resource live.
---

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X ] The title of the PR is clear and informative.
- [ X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X ] If applicable, the PR references the bug/issue that it fixes.
- [ X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ]X I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X ] My spec meets the review criteria:
  - [X ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [X ]X [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-10-12 23:27 UTC, ravbhatnagar reviewed
@dashimi16 As we discussed over our skype call, we need to consider a few things w.r.t exposing these APIs specially the ManagementConfiguration ones externally. So I will chat about this on our side and we can close on this hopefully by tomorrow or Monday. So I am not reviewing further and figure out the best way to proceed on this and then we can take a call.  @salameer as FYI @sarangan12 as FYI

2017-10-16 17:08 UTC, dashimi16 commented on specification/operationsmanagement/resource-manager/Microsoft.OperationsManagement/2015-11-01-preview/OperationsManagement.json
> +            "properties": {
It has been implemented. Missed in the swagger. will update the swagger.

2017-10-16 17:08 UTC, dashimi16 commented on specification/operationsmanagement/resource-manager/Microsoft.OperationsManagement/2015-11-01-preview/OperationsManagement.json
> +            "properties": {
It has been implemented. Missed in the swagger. will update the swagger.

2017-10-16 17:09 UTC, dashimi16 commented on specification/operationsmanagement/resource-manager/Microsoft.OperationsManagement/2015-11-01-preview/OperationsManagement.json
> +                "parameters":{
It is not implemented and do that want to add that support.

2017-10-18 18:32 UTC, alvadb requested changes
Please look at example validation errors.

2017-11-01 21:17 UTC, ravbhatnagar commented
Signing off from ARM.

2017-11-09 19:15 UTC, alvadb approved these changes

2017-11-09 19:15 UTC, merged

2017-11-09 19:23 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-python

2017-11-09 19:24 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-11-09 19:24 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-ruby