[CODEOWNERS] Remove invalid code owners
Azure/azure-rest-api-specs pull request #19329
Opened 2022-06-06 04:01 UTC by liurunliang

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

2022-06-06 06:09 UTC, raych1 commented on CODEOWNERS
>  % PRLabel: %Load Test Service
First '%' should be '#'.

2022-06-06 06:14 UTC, raych1 commented
+@weshaggard , will empty owner cause issues for dependencies of CODEOWNER?

2022-06-06 14:10 UTC, mikekistler requested changes
I think we need a solution for directories where there are no known code owners.  We want to keep the directories so the PR labeling still works.

2022-06-06 14:10 UTC, mikekistler commented on CODEOWNERS
> +/specification/adp/
It was my understanding that the automation needs at least one id following the directory name to work correctly, so removing the last id for a directory seems problematic.

2022-06-06 14:10 UTC, mikekistler commented on CODEOWNERS
Shouldn't there be a "PRLabel" line above this directory?

2022-06-07 00:01 UTC, weshaggard commented
We should definitely avoid having empty codeowners I'm not sure how this edit was made. How were the invalid owners determined? Did you only look at the squiggly lines on github? If so that doesn't mean they are not necessarily the right owner it might also mean that they just don't have write permission to the repo. See:
![image](https://user-images.githubusercontent.com/9010698/172268381-22b4aa63-961c-4b8a-bca7-260e89ca57cf.png)

We should avoid blindly removing folks and only remove them if we know they are no longer accurate. @josefree any thoughts on how to identify correct owners?

2022-06-10 09:24 UTC, raych1 approved these changes

2022-06-10 09:27 UTC, raych1 commented
Confirmed by @weshaggard , empty owner won't block it. As synced offline, we removed those alias that are invalid and keep others that are valid but without write permission. For empty lines, we removed that service entry from file and sent you in email for tracking.

2022-06-10 13:37 UTC, mikekistler approved these changes
Looks good! 👍

2022-06-10 18:56 UTC, weshaggard commented
Thanks for the clean-up thus far but lets also try to remove any owners that aren't part of the Azure org on github.

2022-06-14 09:08 UTC, raych1 approved these changes

2022-06-15 01:01 UTC, weshaggard approved these changes

2022-06-15 01:02 UTC, merged