Go automation
Azure/azure-rest-api-specs pull request #19364
Opened 2022-06-08 06:48 UTC by tadelesh

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

2022-06-08 14:23 UTC, tadelesh commented
/azp run

2022-06-10 03:31 UTC, lirenhe requested changes
Could you add some description about what and why of this change so that it would be helpful for reviewers to understand the background.  Thanks

2022-06-10 03:34 UTC, dw511214992 approved these changes

2022-06-13 05:56 UTC, lirenhe commented
@tadelesh, could you help to check why there are so many failures in the SDK generation?

2022-06-13 06:23 UTC, tadelesh commented
> @tadelesh, could you help to check why there are so many failures in the SDK generation?

As we've changed most of the RP's readme config, ci will run SDK automation for all of them. It seems most of the failure may come from batch execution (timeout, rate limit, etc.).

2022-06-13 12:53 UTC, lirenhe approved these changes

2022-06-13 12:53 UTC, lirenhe commented
> > @tadelesh, could you help to check why there are so many failures in the SDK generation?
> 
> As we've changed most of the RP's readme config, ci will run SDK automation for all of them. It seems most of the failure may come from batch execution (timeout, rate limit, etc.).

I see. Then please contact @akning-ms  to get this PR merged.

2022-06-14 05:59 UTC, merged