add v2022-12-01
Azure/azure-rest-api-specs pull request #19520
Opened 2022-06-20 03:25 UTC by gigigoo0

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following appy to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

2022-06-30 09:12 UTC, danielthank commented on specification/maps/data-plane/Spatial/stable/2022-12-01/examples/Spatial_EvaluatePointInPolygon.json
> +    "udid": "[udid]",
How about using a real udid in these examples?

2022-06-30 09:12 UTC, danielthank commented on specification/maps/data-plane/Spatial/stable/2022-12-01/spatial.json
> +    "SharedKey": {
`AzureKey`

2022-06-30 09:12 UTC, danielthank commented on specification/maps/data-plane/Spatial/stable/2022-12-01/spatial.json
> +      "SharedKey": []
`AzureKey`

2022-06-30 09:12 UTC, danielthank commented on specification/maps/data-plane/Spatial/stable/2022-12-01/spatial.json
> +      "default": "2022-12-01",
spectral: A required parameter should not specify a default value.

2022-06-30 09:12 UTC, danielthank commented on specification/maps/data-plane/Spatial/stable/2022-12-01/spatial.json
> +        "operationId": "Spatial_EvaluatePointInPolygon",
Other APIs use `Get` and `Post` in the title. And just this one uses `Evaluate`. How about changing it to `GetPointInPolygon`.
spectral validation: OperationId for get method should contain "Get" or "list"

2022-07-01 08:59 UTC, tianxchen-ms commented
/azp run

2022-07-14 02:03 UTC, tianxchen-ms commented
/azp run

2022-07-14 02:56 UTC, gigigoo0 commented
@tjprescott Do we need to resolve checks from [~[Staging] Swagger LintDiff](https://github.com/Azure/azure-rest-api-specs/pull/19520/checks?check_run_id=7332414281) check?

2022-07-15 16:27 UTC, tjprescott requested changes
This needs to be restructured to facilitate review. 
Commit 1: Copy old Swagger to new folder
Commit 2: Change APIVersion from old value to new one.
Commit 3: Actual API changes from the old version to the new.

2022-07-20 06:38 UTC, tianxchen-ms commented
/azp run

2022-07-21 06:29 UTC, tjprescott approved these changes

2022-07-21 06:29 UTC, merged