Dev cost management microsoft.cost management 2020 08 01 preview
Azure/azure-rest-api-specs pull request #19677
Opened 2022-07-05 20:41 UTC by vibsridh

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. If updating an existing version, please select the specific language SDKs and CLIs that must be refreshed after the swagger is published.
      - [ ] SDK of .NET (need service team to ensure code readiness)
      - [ ] SDK of Python
      - [ ] SDK of Java
      - [ ] SDK of Js
      - [ ] SDK of Go
      - [ ] PowerShell
      - [ ] CLI
      - [ ] Terraform
      - [ ] No refresh required for updates in this PR

### Contribution checklist:
- [ ] I commit to follow the [Breaking Change Policy](http://aka.ms/bcforapi) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist 

> **Applicability**: :warning: 
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs 
> - Adding new properties 
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following appy to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you are using OpenAPIHub to initialize the PR for adding a new version. More details, refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them. 

### Breaking Change Review Checklist 
If any of the following scenarios apply to the PR, request approval from the Breaking Change Review Board as defined in the [Breaking Change Policy](http://aka.ms/bcforapi). 
- [ ] Removing API(s) in a stable version
- [ ] Removing properties in a stable version
- [ ] Removing API version(s) in a stable version
- [ ] Updating API in a stable or public preview version with Breaking Change Validation errors
- [ ] Updating API(s) in public preview over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Addition details on the process and office hours are on the [Breaking change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

2022-07-06 01:49 UTC, tadelesh commented
/azp run

2022-07-06 08:08 UTC, vibsridh commented
/azp run

2022-07-06 17:08 UTC, vibsridh commented
/azp run

2022-07-06 22:06 UTC, vibsridh commented
/azp run

2022-07-06 22:54 UTC, vibsridh commented
/azp run

2022-07-07 18:57 UTC, flanakin requested changes

2022-07-07 18:57 UTC, flanakin commented on specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2020-08-01-preview/costmanagement.insights.json
> +          "url": "https://docs.microsoft.com/en-us/rest/api/costmanagement/"
Not sure if we should be including language here

2022-07-07 18:57 UTC, flanakin commented on specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2020-08-01-preview/costmanagement.insights.json
> +      "description": "Result of listing Insights. It contains a list of available insight values.",
```suggestion
      "description": "Result of listing insights. It contains a list of available cost insights.",
```

2022-07-07 18:57 UTC, flanakin commented on specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2020-08-01-preview/costmanagement.insights.json
> +          "description": "Insight status kept from storage.",
Can we include available values? I believe this should be defined/controlled by the API, right?

```suggestion
          "description": "Status of the insight.",
```

2022-07-07 18:57 UTC, flanakin commented on specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2020-08-01-preview/costmanagement.insights.json
> +          "description": "The date of event resulting in this anomaly.",
```suggestion
          "description": "The day the insight pertains to.",
```

2022-07-07 18:57 UTC, flanakin commented on specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2020-08-01-preview/costmanagement.insights.json
> +          "description": "Cost Management scope for Insights in storage. This includes 'subscriptions/{subscriptionId}' for subscription scope",
```suggestion
          "description": "Resource Manager ID of the subscription, resource group, management group, or other billing scope this insight pertains to.",
```

2022-07-07 18:57 UTC, flanakin commented on specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2020-08-01-preview/costmanagement.insights.json
> +          "description": "Severity of anomaly to be used for surfacing High severity anomalies first.",
```suggestion
          "description": "Severity of the insight. Can be Critical, Major, High, Medium, Low, Minor, Awareness, Informational, or Verbose.",
```

2022-07-07 18:57 UTC, flanakin commented on specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2020-08-01-preview/costmanagement.insights.json
> +          "description": "Details of anomaly.",
```suggestion
          "description": "Lower-level background information about this insight. Note that details schema changes based on kind.",
```

2022-07-07 18:57 UTC, flanakin commented on specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2020-08-01-preview/costmanagement.insights.json
> +          "type": "string"
I thought this was an object?

2022-07-07 18:57 UTC, flanakin commented on specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2020-08-01-preview/costmanagement.insights.json
> +          "description": "Justification as why the impact qualifies as anomaly.",
```suggestion
          "description": "High-level summary information about this insight. Note that justification schema changes based on kind.",
```

2022-07-07 18:57 UTC, flanakin commented on specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2020-08-01-preview/costmanagement.insights.json
> +          "type": "string"
I thought this was an object?

2022-07-07 18:57 UTC, flanakin commented on specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2020-08-01-preview/examples/GetInsights.json
> +                "actual": 53.12
Adding a new property that's coming soon:
```suggestion
                "actual": 53.12,
                "numberOfDays": 60
```

2022-08-03 21:17 UTC, vibsridh commented
/azp run

2022-08-04 00:28 UTC, vibsridh commented on specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2020-08-01-preview/costmanagement.insights.json
> +          "type": "string"
yes good catch! Changed

2022-08-05 04:00 UTC, tadelesh commented
/azp run

2022-08-05 07:37 UTC, tadelesh approved these changes

2022-08-05 07:41 UTC, leni-msft commented
@vibsridh The "SDK azure-resource-manager-schemas" check failed due to Unable to determine scope for resource types scheduledActions . Though not blocking this PR, it affects ARM Template schemas autogeneration for your Swagger. Suggest to submit PR to update the config here: 
https://github.com/Azure/azure-resource-manager-schemas/blob/1836296c227f3651161e6af71852f389c4890bd7/generator/autogenlist.ts#L253-L271

2022-08-05 07:47 UTC, merged