Maulik/mfe preview changes
Azure/azure-rest-api-specs pull request #20372
Opened 2022-08-24 20:02 UTC by Maulik003

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

2022-08-30 22:51 UTC, Maulik003 commented
[https://github.com/Azure/azure-openapi-validator/issues/248](https://github.com/Azure/azure-openapi-validator/issues/248)
[https://github.com/Azure/azure-rest-api-specs/issues/20235](https://github.com/Azure/azure-rest-api-specs/issues/20235)

References of issues for above required failing checks

2022-08-31 21:20 UTC, raosuhas commented
@Maulik003 Is the first checkin the previous version ? I cant make it out since you have updated the version field. If not then please follow the process explained here : 
![image](https://user-images.githubusercontent.com/11067581/187787076-04d0c3aa-b919-4d2c-9a73-05542ded9cae.png)

2022-08-31 22:18 UTC, forteddyt commented
> @Maulik003 Is the first checkin the previous version ? I cant make it out since you have updated the version field. If not then please follow the process explained here : ![image](https://user-images.githubusercontent.com/11067581/187787076-04d0c3aa-b919-4d2c-9a73-05542ded9cae.png)

@raosuhas the first commit is the changes we're making for 2022-10-01-preview. The 2022-10-01-preview API is following the staging branch paradigm (note that we're merging into a staging branch, not main). This PR is adding the changes for the mfe.json file only

I'm confused on what you mean by your comment

2022-09-02 20:05 UTC, raosuhas commented
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/registries/{registryName}/codes/{name}": {

please update to codename rather than just name

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/mfe.json:67 in c4d31c6. [](commit_id = c4d31c6578d3f002bd7664029c130748b4eff063, deletion_comment = False)

2022-09-02 20:07 UTC, raosuhas commented
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/registries/{registryName}/components/{name}": {

componentname

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/mfe.json:652 in c4d31c6. [](commit_id = c4d31c6578d3f002bd7664029c130748b4eff063, deletion_comment = False)

2022-09-02 20:09 UTC, raosuhas commented
>             "name": "listViewType",

can you use ODATA $filter to do this ?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/mfe.json:1214 in c4d31c6. [](commit_id = c4d31c6578d3f002bd7664029c130748b4eff063, deletion_comment = False)

2022-09-02 20:11 UTC, raosuhas commented
>                 {

again can you use ODATA filter ? looks like you are already using it for top and orderby

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/mfe.json:1549 in c4d31c6. [](commit_id = c4d31c6578d3f002bd7664029c130748b4eff063, deletion_comment = False)

2022-09-02 20:15 UTC, raosuhas commented
>             ],

some comment everywhere in this PR for filter

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/mfe.json:1861 in c4d31c6. [](commit_id = c4d31c6578d3f002bd7664029c130748b4eff063, deletion_comment = False)

2022-09-02 22:39 UTC, raosuhas commented
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/registries/{registryName}/environments/{name}": {

enviromentname

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/mfe.json:1264 in c4d31c6. [](commit_id = c4d31c6578d3f002bd7664029c130748b4eff063, deletion_comment = False)

2022-09-02 22:40 UTC, raosuhas commented
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/registries/{registryName}/environments/{name}": {

same comment everywhere in this PR for name

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/mfe.json:1264 in c4d31c6. [](commit_id = c4d31c6578d3f002bd7664029c130748b4eff063, deletion_comment = False)

2022-09-02 22:45 UTC, raosuhas commented
>     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/registries/{registryName}/models/{name}/versions/{version}": {

It seems to be the case , but can you please confirm if all these new resources you are adding are Proxy Resources ?

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/mfe.json:2246 in c4d31c6. [](commit_id = c4d31c6578d3f002bd7664029c130748b4eff063, deletion_comment = False)

2022-09-07 20:00 UTC, mentat9 commented
Still a couple of @raosuhas comments you haven't responded to ($filter recommendation and question about proxy resources).

2022-09-07 21:14 UTC, Maulik003 commented
> Still a couple of @raosuhas comments you haven't responded to ($filter recommendation and question about proxy resources).

All new resources that are added are proxy resources.
Regarding $filter, teams thread is going on to discuss more on that with Suhas, Teddy and Wenbin

2022-09-08 18:55 UTC, mentat9 commented
> Regarding $filter, teams thread is going on to discuss more on that with Suhas, Teddy and Wenbin

Please leave the ARMChangesRequested label until that thread reaches a conclusion.

2022-09-15 04:32 UTC, rkmanda commented
>             "name": "listViewType",

The non-OData style query params like listViewType were originally introduced in GA API version and we need to allow new resource types to follow a similar pattern for the sake of maintaining consistency within the context of the namespace. 

---
In reply to: [1235859712](https://github.com/Azure/azure-rest-api-specs/pull/20372#issuecomment-1235859712) [](http://example.com/codeflow?ancestors=1235859712,1235859712)

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/mfe.json:1214 in c4d31c6. [](commit_id = c4d31c6578d3f002bd7664029c130748b4eff063, deletion_comment = False)

2022-09-16 05:33 UTC, ArcturusZhang requested changes

2022-09-16 05:33 UTC, ArcturusZhang commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/mfe.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/registries/{registryName}/codes": {
This swagger file does not have a globally defined "consumes" and "produces" attributes, nor do we have in these new operations, therefore this is causing our SDK generations to fail.
Could you either
- add produces and consumes in all these operations
- or add a global produces and consumes setting in this swagger file?
Feel free to take either approach you prefer

2022-09-16 05:34 UTC, ArcturusZhang commented
Also the breakign change review required label is added because the breaking change pipeline runs into some issue and produces errors. This does not mean this PR contains breaking changes.
I am not sure if this failure is related with the consumes and produces issue - we could take a look again after that is fixed

2022-09-16 19:31 UTC, forteddyt commented
/azp run

2022-09-22 03:57 UTC, ArcturusZhang approved these changes

2022-09-22 03:58 UTC, merged