Add missing examples for Update operations
Azure/azure-rest-api-specs pull request #2047
Opened 2017-11-26 19:10 UTC by solankisamir

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-11-30 21:33 UTC, marstr requested changes
Couple of typos, also could you include in the PR description/title that there is a new definition as well, not just added examples.

2017-11-30 21:33 UTC, marstr commented on specification/apimanagement/resource-manager/Microsoft.ApiManagement/2017-03-01/apimtenant.json
> +      "description": "Log of the entity being updated/created/updated."
typo, "updated" is duplicated.

2017-11-30 21:54 UTC, solankisamir commented on specification/apimanagement/resource-manager/Microsoft.ApiManagement/2017-03-01/examples/ApiManagementListOperations.json
> +              "description": "Get list of operation results or Get result of a specific operation"
They were generated from real usage. But the number of operations were huge, I just truncated them.

2017-11-30 21:57 UTC, solankisamir commented on specification/apimanagement/resource-manager/Microsoft.ApiManagement/2017-03-01/apimtenant.json
> +          "description": "Action like create/update/delete."
No, this is an evolving list, these are read-only values

2017-11-30 22:27 UTC, solankisamir commented on specification/apimanagement/resource-manager/Microsoft.ApiManagement/2017-03-01/apimtenant.json
> +      "description": "Log of the entity being updated/created/updated."
#fixed

2017-11-30 22:52 UTC, marstr approved these changes

2017-11-30 23:01 UTC, marstr commented
Chatting with @solankisamir offline, he requested that @KedarJoshi review this before I merge.

2017-11-30 23:02 UTC, KedarJoshi commented
#sign-off

2017-12-01 17:31 UTC, merged

2017-12-01 17:35 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-ruby

2017-12-01 17:35 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-node

2017-12-01 17:35 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-python