[CognitiveServices] LUIS Programmatic API Spec
Azure/azure-rest-api-specs pull request #2083
Opened 2017-12-02 02:17 UTC by pcostantini

This PR includes the API Spec for the LUIS Runtime endpoint (Predictions):
https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c2f

The whole the spec has been reviewed and updated. There is still some pending work related to documentation mainly:
- Proper description for all Parameters, Entities and their attributes
- Rename OperationIds to <method-group>_<method-name>. E.g.: Versions_DeleteApplicationVersion -> Versions_Delete
- Model correct error responses (and include unit-tests for the un-happy paths, invalid arguments, etc).

----

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-12-09 07:01 UTC, alvadb requested changes

2017-12-09 07:01 UTC, alvadb commented on specification/cognitiveservices/data-plane/LUIS/Programmatic/v2.0/LUIS-Programmatic.json
> +
Please add description to properties.

2017-12-09 07:01 UTC, alvadb commented on specification/cognitiveservices/data-plane/LUIS/Programmatic/v2.0/LUIS-Programmatic.json
> +
Please add description for properties.

2017-12-09 07:01 UTC, alvadb commented on specification/cognitiveservices/data-plane/LUIS/Programmatic/v2.0/LUIS-Programmatic.json
> +
Please add description to properties.

2017-12-09 07:01 UTC, alvadb commented on specification/cognitiveservices/data-plane/LUIS/Programmatic/v2.0/LUIS-Programmatic.json
> +
Please add description to properties.

2017-12-09 07:02 UTC, alvadb commented
Please review and fix linter and model errors:
linter: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/313223806
model: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/313223807

2017-12-11 20:12 UTC, enzocanoo commented
Hi @alvadb 

We reviewed the lint errors and fixed almost all of them.
The followings autorest-lint errors are related to the current implementation of LUIS API and cannot be addressed without **introducing breaking changes to the current live** API:

- Delete operations with request body (DeleteMustNotHaveRequestBody error)
  Both operations use the request body to specify the entity to delete

- Properties not using camelCase style (DefinitionsPropertiesNamesCamelCase error)
  All these properties are defined as-is from the LUIS API and cannot be changed in the Swagger without updating the API implementation

Regards,
-EnzoC.

2017-12-13 06:45 UTC, alvadb approved these changes

2017-12-13 06:45 UTC, merged

2017-12-13 06:49 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-python

2017-12-13 06:49 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-ruby