Maulik/fix main
Azure/azure-rest-api-specs pull request #20996
Opened 2022-10-04 21:41 UTC by Maulik003

## ARM API Information (Control Plane)

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow.
</i>
Azure 1st Party Service can try out the [Shift Left](https://aka.ms/ShiftLeft) experience to initiate API design review from ADO code repo.  If you are interested, may request engineering support by filling in with the form https://aka.ms/ShiftLeftSupportForm.

### Changelog
Add a changelog entry for this PR by answering the following questions:
  1. What's the purpose of the update?
      - [ ] new service onboarding
      - [ ] new API version
      - [ ] update existing version for new feature
      - [ ] update existing version to fix swagger quality issue in s360
      - [ ] Other, please clarify
  2. When are you targeting to deploy the new service/feature to public regions? Please provide the date or, if the date is not yet available, the month.
  3. When do you expect to publish the swagger? Please provide date or, the the date is not yet available, the month.
  4. By default, Azure SDKs of all languages (.NET/Python/Java/JavaScript for both management-plane SDK and data-plane SDK, Go for management-plane SDK only ) MUST be refreshed with/after swagger of new version is published. If you prefer NOT to refresh any specific SDK language upon swagger updates in the current PR, please leave details with justification here.

### Contribution checklist (MS Employees Only):
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy) of "no breaking changes"
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and errors have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist

> **Applicability**: :warning:
>
> If your changes encompass only the following scenarios, you should SKIP this section, as these scenarios do not require ARM review.
> - Change to data plane APIs
> - Adding new properties
> - All removals

Otherwise your PR may be subject to ARM review requirements. Complete the following:
- [ ] Check this box if any of the following apply to the PR so that the label "ARMReview" and "WaitForARMFeedback" will be added by bot to kick off ARM API Review.  Missing to check this box in the following scenario may result in delays to the ARM manifest review and deployment.
  - Adding a new service
  - Adding new API(s)
  - Adding a new API version
    -[ ] To review changes efficiently, ensure you copy the existing version into the new directory structure for first commit and then push new changes, including version updates, in separate commits. You can use OpenAPIHub to initialize the PR for adding a new version. For more details refer to the [wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).

- [ ] Ensure you've reviewed following [guidelines](https://aka.ms/rpguidelines) including [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md). Estimated time (4 hours). This is required before you can request review from ARM API Review board.

- [ ] If you are blocked on ARM review and want to get the PR merged with urgency, please get the ARM oncall for reviews (*RP Manifest Approvers* team under <ins>Azure Resource Manager service</ins>) from IcM and reach out to them.

### Breaking Change Review Checklist
If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), request approval from the Breaking Change Review Board.

**Action**: to initiate an evaluation of the breaking change, create a new intake using the [template for breaking changes](https://aka.ms/Breakingchangetemplate). Additional details on the process and office hours are on the [Breaking Change Wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes).

NOTE: To update API(s) in public preview for over 1 year (refer to [Retirement of Previews](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37683/Retirement-of-Previews))

Please follow the link to find more details on [PR review process](https://aka.ms/SwaggerPRReview).

2022-10-04 21:55 UTC, erjms approved these changes

2022-10-05 20:19 UTC, TimLovellSmith commented
>           "description": "Specify the boosting type, e.g gbdt for XGBoost.",

Suggest: quoting 'gbdt'

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/mfe.json:17603 in db5edab. [](commit_id = db5edabe932d9ccbc0db36d5f3fa6f53acb6518b, deletion_comment = False)

2022-10-05 20:20 UTC, TimLovellSmith commented on custom-words.txt
> +Paramter
'Paramter' seems like a typo, we shouldn't be adding it right?

2022-10-05 20:21 UTC, TimLovellSmith commented on custom-words.txt
> +Paramter
Actually its already in the file. Can you avoid adding dupes?

2022-10-05 20:23 UTC, TimLovellSmith commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/machineLearningServices.json
> +          "x-nullable": true,
>  "x-nullable": true, [](http://example.com/codeflow?start=8&length=21)

Why is it x-nullable? The service should really return null sometimes?

2022-10-05 20:25 UTC, TimLovellSmith commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/machineLearningServices.json
>            ],
These are not the canonical values for provisioningStatus.
They must be 
'Succeeded'
'Failed'
'Canceled'
plus whatever other NON-TERMINAL states you want.

'Completed' sounds like its an improper terminal state, unfortunately.

[https://github.com/Azure/azure-resource-manager-rpc/blob/c32a616596b9547d391abdd6a45b6a85e6b3936b/v1.0/async-api-reference.md#provisioningstate-property](https://github.com/Azure/azure-resource-manager-rpc/blob/c32a616596b9547d391abdd6a45b6a85e6b3936b/v1.0/async-api-reference.md#provisioningstate-property)

2022-10-05 20:26 UTC, TimLovellSmith commented
>       "additionalProperties": false

Again, improper values for provisioningStatus. But this will be a breaking change to fix.

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/machineLearningServices.json:5385 in 0bc1bc1. [](commit_id = 0bc1bc149ab11b11da40583f0422f24ced7c931b, deletion_comment = False)

2022-10-05 20:28 UTC, TimLovellSmith commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/machineLearningServices.json
>      },
This may be sdk build-breaking to remove enum values

2022-10-05 20:28 UTC, TimLovellSmith commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/machineLearningServices.json
> +      "additionalProperties": false,
>    "additionalProperties": false, [](http://example.com/codeflow?start=2&length=34)

additionalProperties false is the default, so I suggest to omit it.

2022-10-05 20:28 UTC, TimLovellSmith commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/machineLearningServices.json
> +      "additionalProperties": false
> "additionalProperties": false [](http://example.com/codeflow?start=5&length=30)

additionalProperties false is the default, so I suggest to omit it.

2022-10-05 20:30 UTC, TimLovellSmith commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/examples/Registries/get-SystemCreated.json
> +          "discoveryUrl": "string"
>discoveryUrl [](http://example.com/codeflow?start=11&length=12)

can you use a more useful example url?

2022-10-05 20:30 UTC, TimLovellSmith commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/examples/Registries/get-SystemCreated.json
> +          "mlFlowRegistryUri": "string",
>mlFlowRegistryUri [](http://example.com/codeflow?start=11&length=17)

can you use a more useful example url?

2022-10-05 20:31 UTC, TimLovellSmith commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/examples/Registries/update-SystemCreated.json
> +        "type": "string",
better examples than just "string" would be nice

2022-10-05 20:31 UTC, TimLovellSmith commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/examples/Registry/CodeContainer/delete.json
> +    "202": {},
>202 [](http://example.com/codeflow?start=5&length=3)

202 should come with a Location header for the long-running operation shouldn't it?

2022-10-05 20:32 UTC, TimLovellSmith commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/examples/Registry/CodeVersion/delete.json
> +    "202": {},
>"202": {} [](http://example.com/codeflow?start=4&length=9)

202 should come with a Location header for the long-running operation shouldn't it?

2022-10-05 20:32 UTC, TimLovellSmith commented on specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/examples/Registry/ComponentContainer/delete.json
> +    "202": {},
>"202": {} [](http://example.com/codeflow?start=4&length=9)

202 should come with a Location header for the long-running operation shouldn't it?

2022-10-05 20:34 UTC, TimLovellSmith commented
>     },

Should be marked with x-ms-secret

---
Refers to: specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/machineLearningServices.json:3210 in db5edab. [](commit_id = db5edabe932d9ccbc0db36d5f3fa6f53acb6518b, deletion_comment = False)

2022-10-05 20:35 UTC, TimLovellSmith requested changes
:clock1:

2022-10-05 23:54 UTC, closed without merging