Added examples and fixed other errors in swagger spec
Azure/azure-rest-api-specs pull request #2105
Opened 2017-12-06 19:43 UTC by prakharsharma10

In this PR, we have addressed all the validation errors in the swagger spec. The changes include:

1. Added x-ms-examples for all the operations
2. Removed 'location' and 'tags' properties from 'CustomDomain' and 'EdgeNode' as we don't have these in our RP.
3. Added terminal response codes form long running operations.
4. Made 'tag' as an additional property for the 'Profiles_Update' operation.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2017-12-06 23:44 UTC, anuchandy commented
instead of adding `id, type & name` properties to edgeNode & customDomain.. Define following models and do allOf on `ProxyResource`. For the top level resources do allOf on `TrackedResource`. You can refer traffic manager spec for [example](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/trafficmanager/resource-manager/Microsoft.Network/2017-05-01/trafficmanager.json).


```json
    "Resource": {
      "description": "The core properties of ARM resources",
      "properties": {
        "id": {
          "readOnly": true,
          "type": "string",
          "description": "Fully qualified resource Id for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/trafficManagerProfiles/{resourceName}"
        },
        "name": {
          "readOnly": true,
          "type": "string",
          "description": "The name of the resource"
        },
        "type": {
          "readOnly": true,
          "type": "string",
          "description": "The type of the resource. Ex- Microsoft.Network/trafficmanagerProfiles."
        }
      },
      "x-ms-azure-resource": true
    },
    "TrackedResource": {
      "description": "The resource model definition for a ARM tracked top level resource",
      "properties": {
        "tags": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "x-ms-mutability": [
            "read",
            "create",
            "update"
          ],
          "description": "Resource tags."
        },
        "location": {
          "type": "string",
          "x-ms-mutability": [
            "read",
            "create"
          ],
          "description": "The Azure Region where the resource lives"
        }
      },
      "allOf": [
        {
          "$ref": "#/definitions/Resource"
        }
      ]
    },
    "ProxyResource": {
      "description": "The resource model definition for a ARM proxy resource. It will have everything other than required location and tags",
      "allOf": [
        {
          "$ref": "#/definitions/Resource"
        }
      ]
    },
```

2017-12-06 23:45 UTC, anuchandy requested changes

2017-12-06 23:45 UTC, anuchandy commented on specification/cdn/resource-manager/readme.md
> -
Why following entires are removed this is needed in readme file.

2017-12-07 00:49 UTC, prakharsharma10 commented
Thanks @anuchandy!  Addressed both comments.

2017-12-07 01:09 UTC, anuchandy commented
@prakharsharma10 thank you!. Could you pls take a look at the model validation errors reported by [CI](https://travis-ci.org/Azure/azure-rest-api-specs/builds/312718584?utm_source=github_status&utm_medium=notification) here is the [link to validation errors](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/312718592)

2017-12-07 19:31 UTC, prakharsharma10 commented
@anuchandy The errors are mostly about adding examples for all the response codes while in this PR, we have added examples for each operation as we're only targeting the linter errors to meet the swagger violations KPI. We'll add the examples for all response codes in the next set of PRs. Thanks!

2017-12-07 20:00 UTC, anuchandy commented
@prakharsharma10 sounds good! thanks for cleaning up the errors. To track model validation issue just have created a work item [here](https://github.com/Azure/azure-rest-api-specs/issues/2116). Merging this PR.

2017-12-07 20:00 UTC, anuchandy approved these changes

2017-12-07 20:01 UTC, merged

2017-12-07 20:05 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR2105)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/1684

2017-12-07 20:05 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR2105)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/1169