Updated with latest API features
Azure/azure-rest-api-specs pull request #2209
Opened 2018-01-03 16:57 UTC by daveirwin1

Added process groups, Azure metadata and dynamic machine groups.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-01-03 17:47 UTC, anuchandy commented
Addition of properties to an existing api version is breaking changes. Adding ARM to take a look.

2018-01-08 18:16 UTC, anuchandy commented
@ravbhatnagar could you please take a look?

2018-01-08 18:58 UTC, anuchandy requested changes

2018-01-08 18:58 UTC, anuchandy commented on specification/service-map/resource-manager/Microsoft.OperationalInsights/preview/2015-11-01-preview/arm-service-map.json
> +              "readonly": true,
`readOnly` (use camelcase "O")

2018-01-08 18:58 UTC, anuchandy commented on specification/service-map/resource-manager/Microsoft.OperationalInsights/preview/2015-11-01-preview/arm-service-map.json
> +              "readonly": true,
`readOnly` (use camelcase "O")

2018-01-08 18:58 UTC, anuchandy commented on specification/service-map/resource-manager/Microsoft.OperationalInsights/preview/2015-11-01-preview/arm-service-map.json
> +              "readonly": true,
`readOnly` (use camelcase "O")

2018-01-08 18:58 UTC, anuchandy commented on specification/service-map/resource-manager/Microsoft.OperationalInsights/preview/2015-11-01-preview/arm-service-map.json
> +              "description": "Hosting-related configuration. Present if hosting information is discovered for the VM."
From the comment "Present if hosting information is discovered for the VM" it seems this property is readonly, if so add `readOnly` attribute

2018-01-09 19:11 UTC, anuchandy commented
@daveirwin1 please take a look at the comments. 

Are you from the operation insight service team? Was trying to find your contact so that we can include you in the email threads with ARM team, let me know how can we locate you in outlook.

2018-01-09 19:58 UTC, daveirwin1 commented
@anuchandy My alias is dairwin.  I'm a PM on the Service Map team.  I'm not sure what the Operation Insight service team is.

2018-01-09 22:37 UTC, anuchandy commented
@daveirwin1 thanks. Looped you into the email thread with ARM.

2018-01-09 23:27 UTC, anuchandy commented
Answering my [question](https://github.com/Azure/azure-rest-api-specs/pull/2209#issuecomment-356383815) based on the offline follow-up with @daveirwin1 

This is the API for `Service Map`, which is a solution in Operations Management Suite (OMS), formerly known as `Operational Insights`.  OMS is now mostly known as `Log Analytics`. `Service Map` is a part of `OMS/Operational Insights/Log Analytics` but it’s not the whole thing.

2018-01-11 19:15 UTC, anuchandy commented
@daveirwin1, did you get a chance to look into above comments?

2018-01-11 19:47 UTC, daveirwin1 commented
Yes, I talked to our devs and they're getting me an updated json file.
I'll update the PR when I get it.

On Thu, Jan 11, 2018 at 2:15 PM, Anu Thomas Chandy <notifications@github.com
> wrote:

> @daveirwin1 <https://github.com/daveirwin1>, did you get a chance to look
> into above comments?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Azure/azure-rest-api-specs/pull/2209#issuecomment-357031420>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AT31U3uVBFsJBqRW0Sp8JW_Bz48aX9ASks5tJl3egaJpZM4RR_Ij>
> .
>

2018-01-13 00:38 UTC, ravbhatnagar commented
@daveirwin1  @anuchandy  - is this ready for ARM to take a look?

2018-01-17 18:06 UTC, anuchandy commented
@ravbhatnagar not yet, @daveirwin1 is waiting to get updated spec from the dev team

2018-01-19 19:09 UTC, anuchandy commented
@daveirwin1 did you get a chance to update the spec? I'm removing `waitForARMFeedback` since spec needs to be updated in-order to kick of ARM review.

2018-01-19 20:51 UTC, daveirwin1 commented
No, not yet.

On Fri, Jan 19, 2018 at 2:09 PM, Anu Thomas Chandy <notifications@github.com
> wrote:

> @daveirwin1 <https://github.com/daveirwin1> did you get a chance to
> update the spec? I'm removing waitForARMFeedback since spec needs to be
> updated in-order to kick of ARM review.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Azure/azure-rest-api-specs/pull/2209#issuecomment-359060636>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AT31U_tG-SwImAQxUhN5WgxRrRWJLe0uks5tMOhzgaJpZM4RR_Ij>
> .
>

2018-05-07 18:35 UTC, anuchandy commented
@daveirwin1 closing this due to no activity for last 5 months, feel free to open a new PR when you are ready.

2018-05-07 18:35 UTC, closed without merging