Content Moderator new version changes
Azure/azure-rest-api-specs pull request #2317
Opened 2018-01-23 19:31 UTC by v-sodsou

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-01-24 21:30 UTC, lmazuel requested changes
Stable/Preview folder

2018-01-24 21:30 UTC, lmazuel commented on specification/cognitiveservices/data-plane/ContentModerator/readme.md
> +  - v1.1/ContentModerator.json
Stable/Preview has to be used.

2018-01-24 21:48 UTC, fearthecowboy reviewed
@v-sodsou  

Before I get anywhere with the review, a couple salient points:
- Don't remove old revisions, create new ones and add new sections to the configurations. **Never** remove an existing revision. The configuration can be set to only generate a given version, but we need to  preserve everything. If the examples haven't changed, don't move the files, reference them from the old location. If an example is new or changed, create it in the appropriate new folder location. 

- Follow the file-folder layout that is in the repository. We recently introduced a `stable` folder in the path, keep the files in the right places.

2018-01-24 21:48 UTC, fearthecowboy commented on specification/cognitiveservices/data-plane/ContentModerator/readme.md
> +### Release 1.1
Do not remove old releases!

Create a new release section and change the default, but don't remove the old one.

2018-01-24 21:50 UTC, fearthecowboy requested changes
Please make this change additive, not replacing or moving the existing revision, and then I can continue

2018-01-24 22:49 UTC, lmazuel approved these changes

2018-01-24 22:49 UTC, lmazuel commented
Just to be clear, I approved "stable/preview" folder, nothing else. Just to be sure I won't lock the PR when @fearthecowboy is done.

2018-01-25 21:23 UTC, fearthecowboy commented on specification/cognitiveservices/data-plane/ContentModerator/stable/v1.1/ContentModerator.json
> +          "ListManagemen
It appears that this is the only significant change in the API. 

As far as APIs go, having this hardcoded to `Category1/2/3` seems ... inefficient and a bit clumsy. Is it possible to use an array of `Score`s instead?

2018-01-25 21:24 UTC, fearthecowboy requested changes
I'm curious if the API can be refactored to just return an array rather than a class that has fixed fields for category1/2/3

2018-01-25 21:40 UTC, v-sodsou commented on specification/cognitiveservices/data-plane/ContentModerator/stable/v1.1/ContentModerator.json
> +          "ListManagemen
@fearthecowboy For API , naming properties Category1/2/3 was due our CELA lawyers. For more information on this you can reach out to Greg Clark (gregc@microsoft.com) .

2018-01-25 21:42 UTC, v-sodsou commented on specification/cognitiveservices/data-plane/ContentModerator/stable/v1.1/ContentModerator.json
> +          "ListManagemen
Regarding returning an array instead rather than class, we chose to return class instead array so that we can add more fields in future and traverse the fields easily.

2018-01-25 22:04 UTC, fearthecowboy commented on specification/cognitiveservices/data-plane/ContentModerator/stable/v1.1/ContentModerator.json
> +          "ListManagemen
O_o

2018-01-25 22:42 UTC, v-sodsou commented on specification/cognitiveservices/data-plane/ContentModerator/stable/v1.1/ContentModerator.json
> +          "ListManagemen
@fearthecowboy Do you see any concerns?

2018-01-26 17:10 UTC, fearthecowboy commented on specification/cognitiveservices/data-plane/ContentModerator/stable/v1.1/ContentModerator.json
> +          "ListManagemen
It's just a rather rigid way to express something that looks like it could potentially have more than the arbitrary 3 that you've got there. What happens if in the future, you want four?

2018-01-26 17:54 UTC, v-sodsou commented on specification/cognitiveservices/data-plane/ContentModerator/stable/v1.1/ContentModerator.json
> +          "ListManagemen
@swiftarrow11 can provide you more information on why it is implemented as class than an array.

2018-01-26 19:14 UTC, fearthecowboy commented
@v-sodsou   -- the other thing that @lmazuel brought to my attention, is that you've called this 1.1 but the paths all still point to 1.0

The path /contentmoderator/moderate/v1.0/ProcessText/Screen/ in the existing spec returns a different structure. If you change the implementation of the existing endpoint, you will break existing SDK/clients.

You should be either changing the path for that API in the 1.1 version to /contentmoderator/moderate/v1.1/ProcessText/Screen/ (or more likely do the whole set).

What exactly are you plans for rolling out this API version into production? Are you supporting multiple API versions concurrently?

2018-01-26 19:45 UTC, v-sodsou commented
@fearthecowboy we have rolled out this "/contentmoderator/moderate/v1.0/ProcessText/Screen/" API version as v1.0 into production. So I have retained the same in specification file. Earlier this classify feature was in preview mode and only few customers were using it. Now that it is public , customers who are using it , are already notified about this change.  Perhaps, I shouldn't have added this feature in earlier version since it was in preview. Apologies for the confusion caused.

2018-01-26 19:58 UTC, lmazuel commented
@v-sodsou If I understand correctly what you are saying, you should not create a virtual 1.1 that doesn't exists, but update the current v1.0 with the truth. There is no point for anyone to keep trace of a v1.0 folder that does not represent any in the real world.

2018-01-26 20:12 UTC, v-sodsou commented
@lmazuel @fearthecowboy 
We have just updated the response schema of this API and rolled out into prod as  "/contentmoderator/moderate/v1.0/ProcessText/Screen/" .
Ideally could you tell me how to proceed with specification and sdk changes in this situation?

1.Should I not change the version of specification file?
2.Should I not create new folder v1.1 ?
I was asked to create a new version in my previous pull request for this.Hence I created new version of it in specification repository.

Could you tell me the right way to proceed.

2018-01-26 20:16 UTC, fearthecowboy commented
We wanted you to create a new version, because you changed the version number in the configuration, which made us think that you were introducing a new API version.

Given that this is not a new version at all, you're just overwriting an existing API definition in an existing API version, we now suggest that you keep everything at `1.0`

2018-01-26 20:21 UTC, v-sodsou commented
@fearthecowboy Sure. I'll keep everything at 1.0 then. Thanks.

2018-01-29 22:07 UTC, fearthecowboy commented
I think we should be clear for the future; you should at all cost avoid changing an API definition for an existing API -- once a client is shipped, it's really dangerous for us to alter the API. 

If that's absolutely necessary, then I would recommend that you do change the API version and support multiple concurrent API versions so that customers are not broken.

If an API is not considered "stable" (and you will be updating it in production), then we should move the spec to the `preview`  folder until it is considered stable. That way we can tag appropriate SDKs as 'preview' so customers have a better expectation

2018-01-29 22:38 UTC, v-sodsou commented
@fearthecowboy Thank you for the information and assistance. I have conveyed this to my team as well. We shall keep this in mind when we have future changes in API.

2018-01-29 22:45 UTC, v-sodsou commented
@fearthecowboy Build job for Mode=Semantic PR_Only is errored. Can you help me resolve this error.

2018-01-29 23:18 UTC, AutorestCI commented
This commit was treated and no generation was made for Azure/azure-sdk-for-go

2018-01-29 23:30 UTC, AutorestCI commented
Did a commit to Azure/azure-sdk-for-python:
https://github.com/Azure/azure-sdk-for-python/commit/8909170db2a805f2ac9041430a12d42868ac2f6b

2018-01-30 15:11 UTC, fearthecowboy approved these changes

2018-01-30 15:16 UTC, fearthecowboy commented
@v-sodsou I've restarted the CI task. Looks like it went crazy. Looks ok to me now.

If we're OK with this I can merge it.

2018-01-31 00:36 UTC, AutorestCI commented
This commit was treated and no generation was made for Azure/azure-sdk-for-go

2018-01-31 00:37 UTC, AutorestCI commented
Did a commit to Azure/azure-sdk-for-python:
https://github.com/Azure/azure-sdk-for-python/commit/639b61dd7d9c56182af4e84e372a58166b9f49a2

2018-02-01 23:03 UTC, merged

2018-02-01 23:05 UTC, AutorestCI commented
This commit was treated and no generation was made for Azure/azure-sdk-for-go

2018-02-01 23:05 UTC, AutorestCI commented
<details><summary>Swagger to SDK encountered an unknown error: (Azure/azure-sdk-for-go)</summary><p>

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/swaggertosdk/github_tools.py", line 29, in exception_to_github
    yield context
  File "/usr/local/lib/python3.6/dist-packages/swaggertosdk/restapi/github.py", line 180, in rest_handle_action
    return rest_pull_close(body, github_con, restapi_repo, sdk_pr_target_repo, sdkbase)
  File "/usr/local/lib/python3.6/dist-packages/swaggertosdk/restapi/github.py", line 311, in rest_pull_close
    rest_pr.create_issue_comment("Was unable to create SDK %s PR for this closed PR.", sdkid)
TypeError: create_issue_comment() takes 2 positional arguments but 3 were given

```

</p></details>