Adding percentile metric value properties camel case suppression
Azure/azure-rest-api-specs pull request #2334
Opened 2018-01-25 18:52 UTC by dmakwana

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-01-25 19:24 UTC, dsgouda commented on specification/cosmos-db/resource-manager/readme.md
> +    where: $.definitions.MetricValue.properties._count, $.definitions.PercentileMetricValue
Has this suppression been approved by the review committee?

2018-01-25 19:27 UTC, lmazuel commented
@dmakwana Seems the syntax is not correct, see the Python job for more details.
@dsgouda There is an email thread in process, but let's work on this PR to make it green (it's 99% likely that this will be accepted for what I see so far). Python job failing is relevant, and needs to be fixed until it's not green.

2018-01-26 19:20 UTC, AutorestCI commented
Did a commit to Azure/azure-sdk-for-python:
https://github.com/Azure/azure-sdk-for-python/commit/59a011aed2323ca139d457f8a2cdbadbbe412796

2018-01-26 19:21 UTC, AutorestCI commented
Did a commit to Azure/azure-sdk-for-go:
https://github.com/Azure/azure-sdk-for-go/commit/fc6d7cad31182d68ee55ec31c0f6269688a90f86

2018-01-26 19:49 UTC, dmakwana commented
@lmazuel Fixed the syntax errors.

@ravbhatnagar

2018-01-26 21:59 UTC, lmazuel commented
@dmakwana I looked at the generated code, you need to add `"x-ms-parameter-location": "method",` to `sourceRegionParameter`, `targetRegionParameter` and `partitionKeyRangeIdParameter` too.

2018-01-26 21:59 UTC, lmazuel requested changes
@dmakwana I looked at the generated code, you need to add "x-ms-parameter-location": "method", to sourceRegionParameter, targetRegionParameter and partitionKeyRangeIdParameter too.

2018-01-26 22:02 UTC, AutorestCI commented
Did a commit to Azure/azure-sdk-for-python:
https://github.com/Azure/azure-sdk-for-python/commit/9543683128b5822b56f18d9225aeec7cf4ffc9f1

2018-01-26 22:02 UTC, AutorestCI commented
This commit was treated and no generation was made for Azure/azure-sdk-for-go

2018-01-26 22:20 UTC, AutorestCI commented
Did a commit to Azure/azure-sdk-for-python:
https://github.com/Azure/azure-sdk-for-python/commit/0aa180812158160100f73cd7a1f1329900a1769d

2018-01-26 22:21 UTC, AutorestCI commented
Did a commit to Azure/azure-sdk-for-go:
https://github.com/Azure/azure-sdk-for-go/commit/3844ffd349d3d29a9d6e4ff8969d428e86e487c1

2018-01-26 22:33 UTC, AutorestCI commented
Did a commit to Azure/azure-sdk-for-python:
https://github.com/Azure/azure-sdk-for-python/commit/58f02eb32fecc3e65c27d8b1fbe33acc583d340e

2018-01-26 22:33 UTC, AutorestCI commented
This commit was treated and no generation was made for Azure/azure-sdk-for-go

2018-01-26 22:42 UTC, AutorestCI commented
Did a commit to Azure/azure-sdk-for-python:
https://github.com/Azure/azure-sdk-for-python/commit/f6cff478836998e2911ca8cad10aa54e4c8c1377

2018-01-26 22:43 UTC, AutorestCI commented
This commit was treated and no generation was made for Azure/azure-sdk-for-go

2018-01-26 22:47 UTC, lmazuel approved these changes

2018-01-27 01:13 UTC, lmazuel commented
Got the Go from @salameer

2018-01-27 01:13 UTC, merged

2018-01-27 01:16 UTC, AutorestCI commented
This commit was treated and no generation was made for Azure/azure-sdk-for-go

2018-01-27 01:17 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-ruby

2018-01-27 01:17 UTC, AutorestCI commented
No modification for AutorestCI/azure-sdk-for-ruby