[TypeSpec-Clean]: Updating HealthInsights
Azure/azure-rest-api-specs pull request #23966
Opened 2023-05-12 22:12 UTC by markcowl

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

2023-05-12 23:25 UTC, mikeharder requested changes

2023-05-12 23:25 UTC, mikeharder commented on specification/cognitiveservices/HealthInsights/healthinsights.openapi/tspconfig.yaml
> +     output-file: "{azure-resource-provider-folder}/{version-status}/{version}/openapi.json"
```suggestion
     azure-resource-provider-folder: "./data-plane"
     emitter-output-dir: "{project-root}/../.."
     output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
```

Would this be better?  I think this is equivalent and it aligns with `Contoso.WidgetManager` (assuming the sample is most correct).

2023-05-12 23:25 UTC, mikeharder commented on specification/cognitiveservices/HealthInsights/healthinsights.trialmatcher/route.trialmatcher.tsp
> +  #suppress "@azure-tools/typespec-azure-core/use-standard-operations" "There is no long-runnign RPC template in Azure.Core"
```suggestion
  #suppress "@azure-tools/typespec-azure-core/use-standard-operations" "There is no long-running RPC template in Azure.Core"
```

2023-05-12 23:25 UTC, mikeharder commented on specification/cognitiveservices/HealthInsights/healthinsights.oncophenotype/route.oncophenotype.tsp
> +  #suppress "@azure-tools/typespec-azure-core/use-standard-operations" "There is no long-runnign RPC template in Azure.Core"
```suggestion
  #suppress "@azure-tools/typespec-azure-core/use-standard-operations" "There is no long-running RPC template in Azure.Core"
```

2023-05-13 00:06 UTC, mikeharder approved these changes

2023-05-13 00:12 UTC, mikeharder approved these changes

2023-05-13 00:46 UTC, markcowl commented
@mikeharder I made one change - the service name is set from the root namespace, which does not match where this swagger should be emitted.  I used the literal service name rather than the interpolated variable, rather than changing the namespace.

2023-05-13 00:59 UTC, mikeharder commented
> @mikeharder I made one change - the service name is set from the root namespace, which does not match where this swagger should be emitted. I used the literal service name rather than the interpolated variable, rather than changing the namespace.

Should we change the namespace instead?

I'm fine if we want to fix this in a later PR, and for now only make changes required to successfully build the folder.  But longer-term I think we want to align all the existing specs folders in the repo as much as we can.

So if the convention is the swagger should be emitted to a folder named the same as the namespace, I'd like to make this consistent across specs.

2023-05-13 01:34 UTC, merged