[TypeSpec-Clean] Update  OpenAI.Authoring
Azure/azure-rest-api-specs pull request #23969
Opened 2023-05-12 22:22 UTC by markcowl

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

2023-05-13 00:11 UTC, mikeharder requested changes

2023-05-13 00:11 UTC, mikeharder commented on specification/cognitiveservices/OpenAI.Authoring/tspconfig.yaml
> +    output-file: "{azure-resource-provider-folder}/{version}/openapi.json"
Should this output to this folder instead?

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/data-plane/AzureOpenAI/authoring

If so, I think this whole directory should be deleted:

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/OpenAI.Authoring/cadl-output

2023-05-13 00:50 UTC, markcowl commented on specification/cognitiveservices/OpenAI.Authoring/tspconfig.yaml
> +    output-file: "{azure-resource-provider-folder}/{version}/openapi.json"
It is up to you - the swagger here does not (and never did) match the swagger in the associated data-plane directory.  We could emit it to a different folder in data-plane, but I feel like having the swagger in this directory or removing it altogether are the least bad options.

2023-05-13 01:01 UTC, mikeharder commented on specification/cognitiveservices/OpenAI.Authoring/tspconfig.yaml
> +    output-file: "{azure-resource-provider-folder}/{version}/openapi.json"
I'm confused.  If the swagger generated from TypeSpec does not match the swagger in the data-plane directory, why is it being generated at all?  Why does this TypeSpec folder exist in the repo at all?

2023-05-13 01:40 UTC, markcowl commented on specification/cognitiveservices/OpenAI.Authoring/tspconfig.yaml
> +    output-file: "{azure-resource-provider-folder}/{version}/openapi.json"
I am guessing that the swagger was there before and this is a proof of concept.  There are multiple versions in the data-plane folder, and this spec does not even represent the latest one.

2023-05-13 01:46 UTC, mikeharder requested changes

2023-05-13 01:46 UTC, mikeharder commented on specification/cognitiveservices/OpenAI.Authoring/tspconfig.yaml
> +    output-file: "{azure-resource-provider-folder}/{version}/openapi.json"
OK, I'm fine merging this PR as-is with one additional change to remove this file I believe is an extra copy that shouldn't be there:

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/OpenAI.Authoring/cadl-output/openapi.json

2023-05-13 01:47 UTC, mikeharder commented on specification/cognitiveservices/OpenAI.Authoring/tspconfig.yaml
> +    output-file: "{azure-resource-provider-folder}/{version}/openapi.json"
Later we will need to decide what to do with specs that are proof-of-concept or client-only (don't emit swagger).

2023-05-15 21:31 UTC, weshaggard commented on specification/cognitiveservices/OpenAI.Authoring/tspconfig.yaml
> +    output-file: "{azure-resource-provider-folder}/{version}/openapi.json"
If this is a proof of concept I would argue we should have it merged into the main branch. If we plan to ship this we should have it outputting specs where they are supposed to be going and should definitely not have the name "cadl-output" in the path.

2023-05-15 22:13 UTC, mikeharder commented on specification/cognitiveservices/OpenAI.Authoring/tspconfig.yaml
> +    output-file: "{azure-resource-provider-folder}/{version}/openapi.json"
@lmazuel: Do you know the history of the `OpenAI.Authoring` spec, and who is maintaining it going forward?

2023-05-15 22:53 UTC, lmazuel commented on specification/cognitiveservices/OpenAI.Authoring/tspconfig.yaml
> +    output-file: "{azure-resource-provider-folder}/{version}/openapi.json"
Let me ask on our internal chat

2023-05-17 00:18 UTC, mikeharder approved these changes

2023-05-17 00:33 UTC, merged