`sql` @ `2022-11-01-preview` - fixing a data consistency issue
Azure/azure-rest-api-specs pull request #24187
Opened 2023-05-26 08:00 UTC by tombuildsstuff

The Enums for this parameter having conflicting values (`current` in 2 of 3 operations, and `current` and `recommended` in the other) mean that these conflict in downstream operations.

Since it appears that `recommended` is folded into this method to keep this DRY - I've opened this PR intentionally opted to split this out into a `GetRecommended` method which matches the pattern seen in similar APIs.

Fixes https://github.com/hashicorp/pandora/pull/2557/files#diff-c6309cb7c86d8a927d172057baa8ccc0a5381600b6228e4960994d642895a055L17-R22

2023-05-26 08:46 UTC, v-xuto commented
> ### Generated ApiView
> Language	Package Name	ApiView Link
> Swagger	Microsoft.Sql	Create ApiView failed. Please ensure your github account in [Azure](https://github.com/orgs/Azure/people)/[Microsoft](https://github.com/orgs/Microsoft/people) is public and add a comment "/azp run" to re-trigger the CI.
> Go	sdk/resourcemanager/sql/armsql	Create ApiView failed. Please ensure your github account in [Azure](https://github.com/orgs/Azure/people)/[Microsoft](https://github.com/orgs/Microsoft/people) is public and add a comment "/azp run" to re-trigger the CI.
> JavaScript	@azure/arm-sql	Create ApiView failed. Please ensure your github account in [Azure](https://github.com/orgs/Azure/people)/[Microsoft](https://github.com/orgs/Microsoft/people) is public and add a comment "/azp run" to re-trigger the CI.

@tombuildsstuff The `ApiView` link failed to load, please ensure your github account in [Azure/Microsoft](https://github.com/orgs/Azure/people) is public.

2023-05-26 08:50 UTC, tombuildsstuff commented
@v-xuto I'm not a member of the `Azure` or `Microsoft` Github orgs fwiw

2023-05-26 08:54 UTC, v-xuto commented
> @v-xuto I'm not a member of the `Azure` or `Microsoft` Github orgs fwiw

Could you join the https://repos.opensource.microsoft.com/orgs/Azure?

2023-05-26 09:03 UTC, tombuildsstuff commented
@v-xuto I'm an external member of the community, not a Microsoft employee, so I get a 401 hitting that link

2023-05-26 09:30 UTC, v-xuto commented
> @v-xuto I'm an external member of the community, not a Microsoft employee, so I get a 401 hitting that link

Got it. Thanks for your contribution.

2023-05-26 09:33 UTC, v-xuto commented
@jeremyfrosti Can you help to review this PR from the service side? Thanks a lot.

2023-05-26 19:33 UTC, ericshape requested changes
we do not accept swagger direct modify. please contact feature owner of this API path to fix it

2023-05-26 19:36 UTC, ericshape commented on specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/ManagedDatabaseSensitivityLabels.json
> -              "name": "WritableSensitivityLabelSource",
this enum name is not the same type as last one. why do we manually change it? 

all our swagger files are auto generated. please contact feature owner to fix it.

2023-05-26 19:39 UTC, ericshape commented on specification/sql/resource-manager/Microsoft.Sql/preview/2022-11-01-preview/ManagedDatabaseSensitivityLabels.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/managedInstances/{managedInstanceName}/databases/{databaseName}/schemas/{schemaName}/tables/{tableName}
do we have this API in prod? please contact the feature owner to confirm.

2023-05-31 03:23 UTC, v-xuto commented
@tombuildsstuff Please resolve the comments by **Ericshape**.

2023-06-01 13:49 UTC, pmahanandire commented
Hi @tombuildsstuff, I'm venkat from SQL Data Classification team, we own these apis. These swagger files are auto generated by a tool based on our api implementation and can't be changed manually. Could you please give more details about the error you are facing due to the spec so we can figure out a solution from api side?

2023-06-12 08:27 UTC, v-xuto commented
@tombuildsstuff Please resolve the comments by **Ericshape** and **pmahanandire**.

2023-06-12 10:20 UTC, tombuildsstuff commented
@v-xuto there's an email thread associated with this issue where this work is taking place

2023-10-25 09:09 UTC, tombuildsstuff commented
Closing this since this has been superseded by the newer API Version

2023-10-25 09:09 UTC, closed without merging