Add Swagger documention for UpgradeDataWarehouse API
Azure/azure-rest-api-specs pull request #2426
Opened 2018-02-06 00:33 UTC by vsporeddy

UpgradeDataWarehouse allows users to perform maintenance updates on their SQL Data Warehouse instances at their own convenience. This change adds the API specifications for this feature.

2018-02-06 00:34 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-02-06 00:39 UTC, AutorestCI commented
<details><summary>Swagger to SDK encountered a Subprocess error: (Azure/azure-sdk-for-go)</summary><p>

Command: profileBuilder -s preview -name preview
Finished with return code 127
and output:
```shell
/bin/sh: 1: profileBuilder: not found
```

</p></details>

2018-02-06 00:57 UTC, AutorestCI commented
<details><summary>Swagger to SDK encountered a Subprocess error: (Azure/azure-sdk-for-go)</summary><p>

Command: profileBuilder -s preview -name preview
Finished with return code 127
and output:
```shell
/bin/sh: 1: profileBuilder: not found
```

</p></details>

2018-02-09 00:36 UTC, marstr commented
@vsporeddy these changes are to an API Version that is in `preview`. For that reason, you can opt to skip some of the normal review process. However, it would also mean that SDK owners may not generate libraries to target this service.

Is this API Version correctly sorted?

2018-02-09 22:34 UTC, vsporeddy commented
@marstr Yes, this is for a preview API version. However I want it to be available in .NET SDK and Azure PowerShell, is that possible?

2018-02-13 02:40 UTC, marstr commented
I see, sorry for the confusion! So, we should classify this as belonging in the `stable` folder, because it is a Swagger that will be built upon by customers. Please make that update, and we'll start the ARM review, etc.

2018-02-14 02:01 UTC, vsporeddy commented
Oh no, I meant I was going to make it available in .NET SDK/Azure PowerShell myself. It is still only for 2017-03-01-preview.

2018-02-14 23:12 UTC, marstr commented
> @vsporeddy says:
I meant I was going to make it available in .NET SDK/Azure PowerShell myself

Ah just for a private preview, or with the intention of shipping to customers? I think there are two things getting confused here:
1. Whether the API Version is in preview or not (should be denoted by the "-preview" suffix), and speaks to the SLA and long-term availability of that API Version.
1. Whether or not the Swagger is ready for publication to customers (outside of private preview). This is indicated by whether the API Version is in the `preview` or `stable` folder in this repository.

The two aspects are independent of one another. Clearly the API Version is under a more lenient SLA, but should it be considered ready for customers to play with?

2018-02-15 22:22 UTC, ravbhatnagar commented
Looks good.

2018-02-15 23:32 UTC, marstr commented
KK, well all moot at this point! @vsporeddy are you ready for me to merge this in?

2018-02-15 23:32 UTC, marstr approved these changes

2018-02-16 02:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-02-16 05:41 UTC, jaredmoo commented on specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/databases.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/upgradeDataWarehouse": {
missing x-ms-long-running-operation?

2018-02-16 05:43 UTC, jaredmoo requested changes
missing x-ms-long-running-operation

2018-02-16 20:41 UTC, jaredmoo approved these changes

2018-02-23 00:41 UTC, marstr commented
Just to update this thread, we're currently having some offline conversations about the `preview` folder. We should respond more adequately tomorrow with more information.

2018-02-27 23:40 UTC, marstr commented
Sorry for the delay on this. 

After chatting about it internally with @salameer, @johanste, and @lmazuel it seems like some of my statements above had some misinformation. It sounds like we're still committed to publishing bits in the preview folder as public-previews. The only real difference between the `stable` and `preview` folders is that SDKs are required to somehow convey to consumers of SDKs generated from Swaggers in the `preivew` folder that breaking changes may come. Different SDKs will interpret that differently. [Python for instance, will release PyPI packages with a suffix to indicate preview status.](https://pypi.python.org/pypi/azure-keyvault/).

2018-03-09 00:43 UTC, lmazuel commented
@AutorestCI rebuild azure-sdk-for-python

2018-03-09 21:00 UTC, marstr commented
@AutorestCI rebuild azure-sdk-for-go

2018-03-12 23:05 UTC, marstr commented
Howdy @vsporeddy, with the context that I layout above, what is the current status of this PR? Is it ready to be in the `master` branch in the preview folder?

2018-03-14 23:14 UTC, marstr commented
Closing this PR as stale. If these changes are still relevant, feel free to have it re-opened or create a new PR. One caveat, I'll be OOF starting Friday the 16th, so if it is re-opened it will need to be reassigned.

2018-03-14 23:14 UTC, closed without merging

2018-03-14 23:15 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-03-14 23:40 UTC, AutorestCI commented
# Automation for azure-libraries-for-java