Microsoft.Easm Dataplane Version 2023-05-01-Preview
Azure/azure-rest-api-specs pull request #24465
Opened 2023-06-15 16:07 UTC by mspwood

# Data Plane API - Pull Request
- Add a new Microsoft.Easm Dataplane Version 2023-05-01-preview.
- Support exporting assets for a provided filter.
- Support a unified observations endpoint for paginated retrieval of observations related to an asset.

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document: 
    * Observation Unification Design: https://microsoft.sharepoint.com/:w:/t/RiskIQ-Product/ESDNVwTKC5JKuK4gepDedPMByAwHiL46BbwcJu20NzLvbQ?e=ONtyAz
* Previous API Spec Doc:  https://github.com/Azure/azure-rest-api-specs/blob/main/specification/riskiq/data-plane/Microsoft.Easm/preview/2023-03-01-preview/easm.json
* Updated paths:
    * Observations - Added:  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/workspaces/{workspaceName}/assets/{assetId}/observations
    * Asset Export - Added: 
 /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/workspaces/{workspaceName}/assets:export

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

2023-06-16 02:17 UTC, weidongxu-microsoft commented
Did we have a review on it?

2023-07-17 15:06 UTC, mikekistler commented
Reopen for REST API review on 7/18/23

2023-07-18 19:15 UTC, mikekistler commented
/azp run

2023-07-18 19:42 UTC, mikekistler requested changes
I flagged a number of issues reported by the Spectral linter. You could check for these yourself -- just follow the instructions at

https://github.com/Azure/azure-api-style-guide/blob/main/README.md#how-to-use-the-spectral-ruleset

2023-07-18 19:42 UTC, mikekistler commented on specification/riskiq/data-plane/Microsoft.Easm/preview/2023-05-01-preview/easm.json
> +        "operationId": "Assets_Observations",
The operationId for get on a collection should contain "list"

2023-07-18 19:42 UTC, mikekistler commented on specification/riskiq/data-plane/Microsoft.Easm/preview/2023-05-01-preview/easm.json
> +          },
All parameters should have a description.

2023-07-18 19:42 UTC, mikekistler commented on specification/riskiq/data-plane/Microsoft.Easm/preview/2023-05-01-preview/easm.json
> +            "$ref": "./examples/Reports_Snapshot_Export.json"
invalid-ref error ENOENT: no such file or directory

2023-07-18 19:42 UTC, mikekistler commented on specification/riskiq/data-plane/Microsoft.Easm/preview/2023-05-01-preview/easm.json
> +      },
The `value` property in pageable response should be required. This error occurs several more times ... please fix all.

2023-07-18 19:42 UTC, mikekistler commented on specification/riskiq/data-plane/Microsoft.Easm/preview/2023-05-01-preview/easm.json
> +            "$ref": "#/parameters/DiscoGroupNameParameter"
Parameter "groupName" must be used in path.

2023-07-18 23:17 UTC, weshaggard commented
/azp run

2023-07-18 23:22 UTC, weshaggard commented
/azp run

2023-08-21 13:03 UTC, closed without merging