[Hub Generated] Review request for Microsoft.Security to add version preview/2023-08-01-preview
Azure/azure-rest-api-specs pull request #24625
Opened 2023-06-28 15:40 UTC by bamus1166

This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/bamus1166-security-Microsoft.Security-2023-08-01-preview...main/).
# ARM (Control Plane) API Specification Update Pull Request 

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [ ] New API version. (Such PR should have been generated with [OpenAPI Hub](https://aka.ms/openapihub), per [this wiki doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version).)
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [ ] I have reviewed the general guidance on the spec PR review process: https://aka.ms/specprreview.
- [ ] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data-plane related specifications.
- [ ] I commit to follow the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy).
- [ ] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can request review from an ARM API Review board.

### ARM API changes review

- If you want for the ARM team to review this PR, you must add the `ARMReview` label. 
- The automation may automatically add the `ARMReview` label, if appropriate.  
  If this happens, proceed according to guidance given in GitHub comments also added by the automation.

### Breaking change review

If you have any breaking changes as defined in the [Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy/), 
follow the process outlined in the [High-level Breaking Change Process doc](https://aka.ms/breakingchangesprocess#high-level-breaking-change-process).
      
## Getting help

- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For additional help, see https://aka.ms/azsdk/support/spectools.

2023-06-28 16:59 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-06-28 17:11 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-06-28 17:13 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-06-28 17:27 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-06-28 17:50 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-06-29 10:25 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-07-02 13:17 UTC, eliagrady requested changes
First review - needs some changes

2023-07-02 13:17 UTC, eliagrady commented on specification/security/resource-manager/common/v1/types.json
> +    "ScopeResourceId": {
possible redundancy with ARM's common types

2023-07-02 13:17 UTC, eliagrady commented on specification/security/resource-manager/readme.md
> +tag: package-preview-2023-08
this is the default - don't change this.
you need to replace the pricing.json api-version used in the package-composite-v3

2023-07-02 13:17 UTC, eliagrady commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/pricings.json
> +          "description": "The extension name. Supported values are: <br><br>**AgentlessDiscoveryForKubernetes** - API-based discovery of information about Kubernetes cluster architecture, workload ob
description looks like it contains formatting errors and markdown snippets. It is recommended to write succinct descriptions.

2023-07-02 13:49 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-07-02 14:04 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-07-02 14:05 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-07-02 14:45 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-07-02 15:28 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-07-02 15:40 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/GetPricingByNameStorageAccounts_example.json
> +          "subPlan": "PerStorageAccount",
Please update to DefenderForStorageV2, sub plan PerStorageAccount doesn't support extensions.

2023-07-02 15:42 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/GetResourcePricingByNameVirtualMachines_example.json
> +            {
Please add the following extension too:
            {
                "name": "MdeDesignatedSubscription",
                "isEnabled": "False"
            },

2023-07-02 15:43 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/GetResourcePricingByNameVirtualMachines_example.json
> +            {
Update also in specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/ListPricingsWithPlanFilter_example.json file

2023-07-02 15:45 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/ListPricingsWithPlanFilter_example.json
> +              "subPlan": "P2",
What is the meaning of sub-plan & extensions if the plan is disabled on this resource?

2023-07-02 15:47 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/GetPricingByNameStorageAccounts_example.json
> +          "subPlan": "PerStorageAccount",
Update also in specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/ListPricingsWithResourceFilter_example.json file

2023-07-02 15:49 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/GetPricingByNameCloudPosture_example.json
> +              "name": "AgentlessVmScanning",
This extensio has also additional properties, please update the example:
            {
                "name": "AgentlessVmScanning",
                "isEnabled": "True",
                "additionalExtensionProperties": {
                    "ExclusionTags": "[{\"Key\":\"D1\",\"Value\":\"R1\"},{\"Key\":\"Daniel1\",\"Value\":\"Test1\"}]"
                }
            }

2023-07-02 15:49 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/GetPricingByNameCloudPosture_example.json
> +              "name": "AgentlessVmScanning",
Update also in all relevant example files (List DCSPM & Servers)

2023-07-02 15:53 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/ListPricings_example.json
> +            "id": "/subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23/resourceGroups/DEMO/providers/Microsoft.Compute/virtualMachines/VM-2/providers/Microsoft.Security/pricings/VirtualMachines",
What is the purpose of this resource example? It looks the same as the parent..
Consider override one of the values or remove this resource.

2023-07-02 15:54 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/ListResourcePricings_example.json
> +              "subPlan": "P2",
enforce property?

2023-07-02 17:30 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/PutPricingByNamePartialSuccess_example.json
> +                "message": ""
"message": "Successfully enabled extension"

2023-07-02 17:33 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/PutPricingByNamePartialSuccess_example.json
> +                "message": "Extension enablemment failed due to missing permissions."
Minor - let's update all extensions with "failed" status except for this one.
At the moment, Containers VA is the only extension that doesn't require high permissions.
For all the rest - they required the same high permissions, so the 3 of them should fail at the same operation.

2023-07-02 17:34 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/PutPricingByName_example.json
> +                "message": ""
"message": "Successfully enabled extension"

2023-07-02 17:35 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/examples/Pricings/PutResourcePricingByNameVirtualMachines_example.json
> +    "scopeId": "subscriptions/20ff7fc3-e762-44dd-bd96-b71116dcdc23",
Don't we want to describe here a Resource Level put?

2023-07-02 17:40 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/pricings.json
> +        "description": "Lists Microsoft Defender for Cloud pricing configurations (both subscription and resource level) of the subscription.",
Suggest describing here that only resources with different pricing configurations than their parent's (subscription) configuration will be returned.

2023-07-02 17:42 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/pricings.json
> +          "description": "The pricing tier value. Microsoft Defender for Cloud is provided in two pricing tiers: free and standard. The standard tier offers advanced security capabilities, while the
If we are deprecating this field, let's consider requiring the 'isEnabled' field at the Put request, instead of the pricingTier field?

2023-07-02 17:44 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/pricings.json
> +          "type": "boolean",
It's a readOnly property, no?

2023-07-02 17:46 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/pricings.json
> +        "isEnabled": {
Don't we want to use Enum here? In order to use the same convention as the IsEnabled property of the extensions?

2023-07-02 17:48 UTC, danieldahahan commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/pricings.json
> +          "description": "The pricing tier value. Microsoft Defender for Cloud is provided in two pricing tiers: free and standard. The standard tier offers advanced security capabilities, while the
Let's also describe that StandardTier & IsEnabled properties describing the same and will always be in sync.

2023-07-04 10:36 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-07-04 10:49 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-07-04 11:06 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-07-04 15:39 UTC, kerend commented on specification/security/resource-manager/Microsoft.Security/preview/2023-08-01-preview/pricings.json
> +          "description": "Whether to allow descendants of this scope to not inherit the pricing set on this scope or not. Available only for subscription level pricing."
Whether to allow descendants of this scope to inherit

2023-07-06 09:30 UTC, eliagrady approved these changes
LGTM - add the OData refactor as discussed

2023-07-09 10:15 UTC, bamus1166 commented
I reviewed all the remaining errors in the automated checks and all of them are "by design" changes of the API. 
The new API is backward compatible, but now we support another level of resources. The old one supported only subscription level, the new one supports both subscription and resource level. That is why the automated check treats it as a breaking change.

2023-07-09 15:40 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-07-09 16:02 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-07-10 12:36 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-07-10 12:41 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-07-16 19:01 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-07-17 10:50 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-08-03 15:53 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-08-03 16:21 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-08-15 16:09 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-08-16 12:18 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-08-16 13:51 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-08-16 16:09 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-08-23 02:42 UTC, ms-henglu commented
Please fix the lint diff and resolve the conflicts.

2023-08-23 16:16 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-08-23 16:23 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-08-25 02:38 UTC, ms-henglu commented on specification/security/resource-manager/readme.md
> +  suppress: TopLevelResourcesListBySubscription
Syntax error, it should be "- suppress"

2023-08-25 02:42 UTC, ms-henglu commented on specification/security/resource-manager/readme.md
> +  suppress: TopLevelResourcesListBySubscription
After this is fixed, I guess there would be new Lint errors, please also check and fix them.

2023-11-07 19:21 UTC, bamus1166 commented
/azp run unifiedPipeline

2023-11-08 08:21 UTC, msyyc commented
/azp run

2023-12-06 09:50 UTC, kerend approved these changes

2023-12-06 13:59 UTC, kerend approved these changes

2023-12-06 14:03 UTC, visingla-ms commented
/azp run

2023-12-06 18:46 UTC, visingla-ms approved these changes

2023-12-11 14:49 UTC, bamus1166 commented
@visingla-ms can you please merge the PR?

2023-12-12 00:29 UTC, ms-zhenhua commented
please fix errors in https://github.com/Azure/azure-rest-api-specs/pull/24625/checks?check_run_id=19520849172 before it can be merged.

2023-12-13 01:47 UTC, raych1 commented
@lirenhe can you force merge this PR as the Go failure is a known issue in m4?

2023-12-13 03:43 UTC, merged

2023-12-13 03:43 UTC, lirenhe commented
OK, merged.