Adding formatting on save for ts files
Azure/azure-rest-api-specs pull request #24646
Opened 2023-06-29 20:45 UTC by ckairen

closes #24641

2023-06-29 20:50 UTC, mikeharder requested changes

2023-06-29 20:50 UTC, mikeharder commented on .vscode/settings.json
> +  },
Can we enable this at a smaller scope, say only for the `eng` folder but not the rest of the repo?

2023-07-01 00:41 UTC, mikeharder approved these changes
Approved pending changes in my comments

2023-07-01 00:41 UTC, mikeharder commented on .prettierrc.json
> +        "tabWidth": 4
I recommend copying the settings from the typespec repo:

https://github.com/microsoft/typespec/blob/799cb6af21b5274543701096af8ecb9d5c9bb793/.prettierrc.json#L2-L8

2023-07-01 00:41 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts
> -import {exec} from "child_process";
You will need to merge this file from main and re-format.

2023-07-01 00:41 UTC, mikeharder commented on .prettierignore
> +**/*.ts
After further consideration, I would delete this file completely, and apply formatting to all `*.ts` files in the repo.  There's only one other such file (`scripts/prettier-swagger-plugin.ts`), and I don't mind if it gets formatted.

Also, VSCode shows this UI when saving an excluded file (the highlighted `X Prettier`), which I don't think users will like:

<img width="298" alt="image" src="https://github.com/Azure/azure-rest-api-specs/assets/9459391/5681e192-ace3-4e77-a180-30b65e5fa00f">

2023-07-06 22:52 UTC, benbp approved these changes

2023-07-06 23:34 UTC, merged