adding purge protection vault property
Azure/azure-rest-api-specs pull request #2478
Opened 2018-02-12 19:42 UTC by dragav

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](../documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-02-12 19:44 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-02-12 19:53 UTC, schaabs requested changes
The changes you have here look good, but you also need to update the examples createVault.json, getVault.json, and updateVault.json

2018-02-12 19:59 UTC, dragav commented
I would prefer not to include this in the examples. Activating this property is irreversible and creates undeletable objects. The value of including it in the examples is marginal, whereas the effect can be quite confusing. Please consider this argument and let me know if you still think I should make that change. Thanks.

2018-02-13 01:57 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-02-13 02:20 UTC, schaabs approved these changes

2018-02-13 02:23 UTC, schaabs commented
After an offline discussion I agree this should not be added to the create and update examples.  Changes look good to me.

2018-02-13 17:20 UTC, schaabs commented
@sergey-shandar can we go ahead and merge these changes?

2018-02-13 18:42 UTC, sergey-shandar commented
@schaabs LGTM except it may introduce breaking changes for some SDK. We also need ARM approval for this. @ravbhatnagar

2018-02-13 18:49 UTC, schaabs requested changes
@sergey-shandar you're right this is breaking.  @dragav please see comments about property ordering

2018-02-13 18:49 UTC, schaabs commented on specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2016-10-01/keyvault.json
> +        "enablePurgeProtection": {
This needs to be moved after create mode to avoid breaking changes in the sdk

2018-02-13 18:49 UTC, schaabs commented on specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2016-10-01/keyvault.json
> +        "enablePurgeProtection": {
This needs to be moved after create mode to avoid breaking changes in the sdk

2018-02-14 00:58 UTC, schaabs approved these changes
LGTM

2018-02-15 16:15 UTC, schaabs commented
@ravbhatnagar are these changes ready to merge?

2018-02-16 00:24 UTC, ravbhatnagar commented
@schaabs - Apologies but I dont follow. How does moving it after createMode make it non-breaking?

2018-02-16 00:33 UTC, schaabs commented
@ravbhatnagar  The breaking change I was referring to is not in the API itself but the clients generated by autorest. Adding the property before preexisting properties changes the order of parameters in the model constructors.  So even though these are optional parameters, it breaks callers who don't specify the parameters by name, but only by order.  Adding it after all the preexisting properties causes the generated code to have one more optional parameter at the end, so callers who don't specify this parameter will not break.

2018-02-16 08:14 UTC, ravbhatnagar commented
Interesting, I wasnt aware of this. Anyhow, how will it impact the scenario where someone sets this property  using the portal and then GETs this resource using an older SDK which ignores this property since it didnt understand it. Then does a PUT on the same resource, without this property in the payload. How does the value of this property on the server change? Does it get overwritten which could be unintentional from the user perspective in this case?

2018-02-16 16:24 UTC, schaabs commented
@ravbhatnagar This is handled by the server behavior.  This property can only be set on a vault once, and when set cannot be unset.  This is documented in the description of the property "Enabling this functionality is irreversible".  Once this property has been set, subsequent PUT operations which do not have the property specified will have no effect on the properties value.

2018-02-21 02:15 UTC, ravbhatnagar commented
Signing off based on comments from @schaabs . it wont be an unintentional change as the service will handle it.

2018-02-21 02:20 UTC, merged