Fix recursive reference
Azure/azure-rest-api-specs pull request #24832
Opened 2023-07-14 08:17 UTC by evaou

# Data Plane API - Pull Request

The change is to fix recursive reference for "ErrorDetail" definition by introducing "SubErrorDetail" definition to limit the reference to one level down only.

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc:
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

2023-07-14 08:56 UTC, winest approved these changes

2023-07-14 09:01 UTC, weidongxu-microsoft requested changes
I am not sure who is changing this.

This is a shared type for all data-plane.

2023-07-18 03:35 UTC, winest commented
@weidongxu-microsoft it's under common-types but only used by [Email](https://github.com/Azure/azure-rest-api-specs/blob/e1f8a06c495d417ed164f5681a05993169d7bbc2/specification/communication/data-plane/Email/stable/2023-03-31/CommunicationServicesEmail.json#L190) and our Maps services. The file was created by our members previously but have the wrong recursive reference of details field so some 3rd party parsing library like [json-schema-ref-parser](https://github.com/APIDevTools/json-schema-ref-parser) will detect error and having exception. We are trying the way to fix it without adding new fields too keep generated structure the same. Or do you suggest to have a data-plane/v2 version for it?

2023-07-18 03:43 UTC, weidongxu-microsoft commented
@winest The common-types swagger should be in sync with the guideline https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#rest-error-response-body-structure

I think the guideline still uses the recursive reference.

There were lots of existing recursive reference or potential recursive in swagger. I don't think a shortcoming (or bug) in 3rd party lib would reversely impact whether a Swagger is valid or not.

If you really need to change this file, we will need to loop in Mike.

One alternative I can think of, is you use a e.g. common.json in your RP folder, not this shared one. But may still worth a check with Mike before you undergo it.

2023-08-21 13:03 UTC, closed without merging