[Hub Generated] Review request for Route to add version preview/2023-10-01-preview
Azure/azure-rest-api-specs pull request #24987
Opened 2023-07-26 07:33 UTC by koyasu221b

This is a PR generated at [OpenAPI Hub](https://aka.ms/openapihub). You can view your [work branch via this link](https://openapihub.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/koyasu221b-maps-Route-2023-10-01-preview...main/).
# Data Plane API - Pull Request

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope
<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc:
* Updated paths:

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling
 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://aka.ms/style)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications
 * [Azure REST API Guidelines](https://aka.ms/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links
 * [Azure DevTools Wiki](https://aka.ms/azapi)

</details>

2023-09-20 00:39 UTC, FarazGIS commented on specification/maps/data-plane/Route/preview/2023-10-01-preview/route.json
> +                "description": "The route is calculated to minimize the time and avoid road closures. No traffic information except for road closures is used in the calculation. `Note`: Only supporte
@koyasu221b Can you please check if Bing routing gives a response for walking for fastestAvoidClosureWithoutTraffic

2023-09-25 23:36 UTC, FarazGIS commented on specification/maps/data-plane/Route/preview/2023-10-01-preview/route.json
>                  },
@koyasu221b We don't need to mention only supported for driving and truck if it's supported by both travel modes like ferries and toll road and it is implied that avoid highways would not be applicable to walking.

2023-09-27 05:21 UTC, winest requested changes

2023-09-27 05:21 UTC, winest commented on specification/maps/data-plane/Route/preview/2023-10-01-preview/route.json
> +              "limitedAccessHighway",
limitedAccessHighway"s" for consistency with others

2023-09-27 05:47 UTC, koyasu221b commented on specification/maps/data-plane/Route/preview/2023-10-01-preview/route.json
>            "items": {
fixed

2023-10-04 23:52 UTC, winest requested changes
Line 423 also need to include ErrorDetails for DirectionsResponse

2023-10-06 05:19 UTC, koyasu221b commented
> Line 423 also need to include ErrorDetails for DirectionsResponse

After our discussion, we think it's not required

2023-10-06 17:47 UTC, winest approved these changes

2023-11-17 18:06 UTC, JeffreyRichter approved these changes

2023-11-17 18:21 UTC, merged