refactor tsv
Azure/azure-rest-api-specs pull request #25101
Opened 2023-08-01 23:52 UTC by ckairen

closes #24983

2023-08-08 20:18 UTC, mikeharder requested changes

2023-08-08 20:18 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts
> +interface TSVRule {
Please move each interface/class to its own source file

2023-08-11 16:35 UTC, ckairen commented
also ran the typespec - all pipeline https://dev.azure.com/azure-sdk/public/_build/results?buildId=2997645&view=results

2023-08-14 19:19 UTC, mikeharder requested changes

2023-08-14 19:19 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/TSVRules/CompileRule.ts
Let's follow the naming conventions used here:

https://github.com/Azure/typespec-azure/tree/main/packages/typespec-azure-core/src/rules

So this file would be renamed to `rules/compile.ts`.

2023-08-14 19:19 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/TSVRules/RunCmd.ts
Move to a class named `src/utils.ts`.

2023-08-14 19:19 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts
>  debug.enable("simple-git");
Move to ctor of `GitDiffRule`, since it's the only class using `simple-git`.

2023-08-14 19:19 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts
> +  let TSVRules = [new NpmPrefixRule(), new CompileRule(), new FormatRule(), new GitDiffRule()];
```suggestion
  let rules = [new NpmPrefixRule(), new CompileRule(), new FormatRule(), new GitDiffRule()];
```

2023-08-14 19:19 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/TSVRules/TSVRule.ts
> +export interface TSVRule {
```suggestion
export interface Rule {
```

2023-08-14 19:19 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/TSVRules/TSVRule.ts
> +export interface TSVRuleResult {
```suggestion
export interface RuleResult {
```

2023-08-14 19:19 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/TSVRules/CompileRule.ts
> +async function checkFileExists(file: string) {
Move to `src/utils.ts`.

2023-08-14 19:19 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/TSVRules/TSVRule.ts
Move to file `src/rule.ts`.

2023-08-14 19:19 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/TSVRules/TSVRule.ts
> +export interface TSVRuleResult {
Move to `src/rule-result.ts`.

2023-08-14 23:58 UTC, ckairen commented
aside from the comments, also renamed the other files to conform to the "typespec-azure" style

2023-08-15 00:00 UTC, ckairen commented
ran typespec - all as well: https://dev.azure.com/azure-sdk/public/_build/results?buildId=3003591&view=results

2023-08-15 00:42 UTC, mikeharder approved these changes

2023-08-15 00:44 UTC, merged