Update Getting started with OpenAPI specifications.md
Azure/azure-rest-api-specs pull request #25279
Opened 2023-08-11 10:38 UTC by navba-MSFT

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

2023-08-11 14:05 UTC, mikekistler requested changes
Please fix new link.

2023-08-11 14:05 UTC, mikekistler commented on documentation/Getting started with OpenAPI specifications.md
> +* **[`Azure REST API guidelines`](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md)**
Thanks for spotting the broken link, but this is the correct one.
```suggestion
* **[`Azure REST API guidelines`](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md)**
```

2023-08-21 03:53 UTC, navba-MSFT commented
@mikekistler Your suggestions have been incorporated and committed. Could you please review and merge once you get a chance ?

2023-08-21 11:06 UTC, mikekistler approved these changes
Looks good! 👍 

Thank you for this fix.

2023-08-21 13:53 UTC, merged