[TypeSpecValidation] throw error on incorrect tspconfig file extension
Azure/azure-rest-api-specs pull request #25313
Opened 2023-08-15 08:58 UTC by ckairen

closes #25122
I think it's better to throw any non .yaml, having it as a more generalized error

2023-08-16 20:41 UTC, mikeharder requested changes

2023-08-16 20:41 UTC, mikeharder commented on eng/scripts/Get-TypeSpec-Folders.ps1
> +$allChangedFiles = (Get-ChildItem -path ./specification tspconfig.* -Recurse).Directory.FullName | ForEach-Object {[IO.Path]::GetRelativePath($($pwd.path), $_)}
Keep this part of the change, since it's necessary to treat folders containing `tspconfig.yml` as "TypeSpec Folders".

2023-08-16 20:41 UTC, mikeharder commented on eng/scripts/Get-TypeSpec-Folders.ps1
> +$errTspConfig = @()
Please move this part of a check to a rule in `tsv`.  We want this rule to fire if a spec author manually runs `tsv` on a folder with `tspconfig.yml`.

In general, we want to put as much validation as possible into `tsv` itself, and only use the pwsh scripts to find potential spec folders.  I'm even considering moving the functionality from the scripts into `tsv` itself, but waiting for more evidence if this is a good idea.

2023-08-19 00:24 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/rules/file-structure.ts
> +      await runCmd(`(Get-ChildItem -path ${folder} tspconfig.* -Recurse).Name`, process.cwd())
Replace with package `globby`.  Already used in `typespec` repo:

https://github.com/microsoft/typespec/blob/ee3c4fa2f615293747739a739b05353b3d28073f/packages/compiler/package.json#L79

2023-08-19 02:16 UTC, mikeharder requested changes

2023-08-19 02:16 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/rules/file-structure.ts
> +        errorOutput += `Please ensure the file extension of tspconfig is .yaml, found file ${file} instead.\n`;
```suggestion
        errorOutput += `Invalid config file '$file'.  Must be named 'tspconfig.yaml'.\n`;
```

2023-08-19 02:16 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/utils.ts
> +      { encoding: "utf8", maxBuffer: 1024 * 1024 * 64, cwd: cwd, shell: "powershell.exe" },
```suggestion
      { encoding: "utf8", maxBuffer: 1024 * 1024 * 64, cwd: cwd },
```

Revert to remove dependency on `pwsh`

2023-08-21 21:46 UTC, mikeharder requested changes

2023-08-21 21:46 UTC, mikeharder commented on eng/tools/TypeSpecValidation/package.json
> +        "globby": "~13.1.1",
```suggestion
        "globby": "^13.1.1",
```

Dependencies should always use `^` unless there is a reason not to (like `typescript` which allows breaking changes in minor versions).

2023-08-21 21:46 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/rules/file-structure.ts
> +export class FileStructureRule implements Rule {
```suggestion
export class FolderStructureRule implements Rule {
```

I think `FolderStructure` is a slightly better name than `FileStructure`.

2023-08-21 22:30 UTC, mikeharder requested changes

2023-08-21 23:56 UTC, ckairen commented
pipeline failed successfully https://dev.azure.com/azure-sdk/public/_build/results?buildId=3022127&view=logs&j=52599800-cfcd-5615-dd98-137d26e8cb9a&t=c0acbdc7-6ccc-5699-6c3a-c41428f73fe2

2023-08-22 00:27 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/rules/folder-structure.ts
> +  readonly name = "FileStructure";
```suggestion
  readonly name = "FolderStructure";
```

2023-08-22 00:27 UTC, mikeharder commented on eng/tools/TypeSpecValidation/src/rules/folder-structure.ts
> +  readonly description = "Verify spec directory's file structure and naming conventions.";
```suggestion
  readonly description = "Verify spec directory's folder structure and naming conventions.";
```

2023-08-22 00:29 UTC, mikeharder approved these changes

2023-08-22 04:06 UTC, merged