Remove redundant "rotate" from Keys API
Azure/azure-rest-api-specs pull request #25714
Opened 2023-09-07 22:02 UTC by heaths

Original goal was to properly document "Rotate" that Key Vault returned and "rotate" that Managed HSM returned (and was originally in the swagger), but that case-insensitively duplicative value caused issues with some code generators.

Reverts parts of #24475

2023-09-08 17:42 UTC, vickm approved these changes

2023-09-11 21:56 UTC, heaths commented
Note to @rkmanda: this does revert one of the changes we discussed in #24475 and gets rid of "rotate". ARM clients and the related services are already case-insensitive in their requests and responses, so this shouldn't be a problem. It only was a problem for code generation, hence this change.

2023-09-11 22:03 UTC, jlichwa requested changes

2023-09-11 22:03 UTC, jlichwa commented on specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.3-preview/keys.json
> +                "description": "Trigger Event Grid events."
I would like to keep default to 30 days and Key Vault only

2023-09-11 22:16 UTC, jlichwa approved these changes

2023-09-12 21:12 UTC, heaths commented
@rkmanda could you take a look?

2023-09-13 23:37 UTC, rkmanda approved these changes
:shipit:

2023-09-13 23:38 UTC, merged