Test framework for tsv
Azure/azure-rest-api-specs pull request #26166
Opened 2023-10-10 23:15 UTC by ckairen

DO NOT MERGE YET

2023-10-11 00:27 UTC, ckairen commented on eng/tools/TypeSpecValidation/test/test.ts
> +import {expect} from 'chai';
Use assert instead of chai

2023-10-11 01:14 UTC, mikeharder requested changes
I like the overall direction of using a test host with manual mocks.

2023-10-11 01:14 UTC, mikeharder commented on eng/tools/TypeSpecValidation/test/test.ts
Let's use one test file per src file.  So the git-diff tests would live in file `git-diff.test.ts`.

2023-10-11 01:14 UTC, mikeharder commented on eng/tools/TypeSpecValidation/test/tsv-test-host.ts
> +            status: () => {return {modified:[`${folder}\n`], isClean: ()=>{return false}}},
We will need some way to configure the behavior of these mocks for each test.  We could use constructor arguments or APIs after the mock is created.

2023-10-25 21:01 UTC, mikeharder approved these changes

2023-10-26 06:27 UTC, mikeharder commented
/azp run

2023-10-26 06:35 UTC, merged