Al/26223
Azure/azure-rest-api-specs pull request #26321
Opened 2023-10-20 08:19 UTC by ckairen

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

2023-10-20 20:51 UTC, weshaggard approved these changes

2023-10-20 21:34 UTC, mikeharder requested changes
@ckairen: How did you validate this change fixes the issue?

2023-10-20 22:13 UTC, ckairen commented on specification/contosowidgetmanager/Contoso.WidgetManager/tspconfig.yaml
> +asdf
```suggestion

```

2023-10-20 22:14 UTC, ckairen commented on specification/contosowidgetmanager/Contoso.WidgetManager/tspconfig.yaml
> +    namespace: com.azure.contoso.widgetmanager
```suggestion
    namespace: com.azure.contoso.widgetmanager

```

2023-10-23 20:06 UTC, mikeharder approved these changes

2023-10-24 16:51 UTC, merged