[WIP] Add Auto Suggest API specification
Azure/azure-rest-api-specs pull request #2635
Opened 2018-03-10 12:27 UTC by jwood803

Apologies for the WIP pull request, but I'm not exactly sure if I'm on the right track. From my understanding, this is needed to auto-generate the code for the Python Azure SDK.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-03-10 12:27 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=2635) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=2635) before we can accept your contribution.<br/><br/>:x: jwood803 [sign now](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=2635)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-rest-api-specs?pullRequest=2635) it.</sub>

2018-03-10 12:27 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-03-10 12:27 UTC, AutorestCI commented
# Automation for azure-libraries-for-java

2018-03-10 12:27 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-03-14 16:45 UTC, anuchandy commented
@jwood803 thank you. Just trying to get some context here, saw that you are from Wintellect, are you in touch with anyone from Microsoft cognitive service team? if so can you can tag him/her in this PR so that service team also can take a look. In case you don't know anyone in cognitive team please let me know, i can find the contact and help you to progress this PR. Again thanks for the contribution!

2018-03-14 16:48 UTC, jwood803 commented
Thanks for getting back @anuchandy! I don't know anyone at Microsoft myself, but I'm sure some colleagues of mine do. I can ask them if that works.

Apologies for the noise in this PR. I kind of figured things out as they went. I'm sure I still have some updates here, too. 😄

2018-03-14 17:40 UTC, anuchandy commented
@jwood803 no worries, i'm checking with cognitive service team to see whether they can take a look at this PR.

2018-03-14 23:05 UTC, lmazuel commented on specification/cognitiveservices/data-plane/AutoSuggest/readme.md
> +  output-folder: $(python-sdks-folder)/azure-cognitiveservices-search-newssearch/azure/cognitiveservices/search/newssearch
Please change "newssearch" for "autosuggest

2018-03-14 23:08 UTC, lmazuel requested changes
Content LGTM, please fix the Python conf. Thanks!

2018-03-14 23:08 UTC, lmazuel commented on specification/cognitiveservices/data-plane/AutoSuggest/readme.md
> +  output-folder: $(python-sdks-folder)/azure-cognitiveservices-search-newssearch/azure/cognitiveservices/search/newssearch
Please change "newssearch" for "autosuggest

2018-03-14 23:38 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-03-14 23:39 UTC, jwood803 commented
Thanks a ton for reviewing @lmazuel! I plan on doing the [sample](https://github.com/Azure-Samples/cognitive-services-python-sdk-samples), too, so if I notice anything missing I'll make appropriate updates.

2018-03-15 00:15 UTC, lmazuel commented
@AutorestCI rebuild azure-sdk-for-python

2018-03-20 16:32 UTC, lmazuel approved these changes

2018-03-20 16:33 UTC, lmazuel commented
@jwood803 Just to give you update, we need someone from the Autosuggest team to sign-off, but your PR looks good to me

2018-03-20 16:34 UTC, jwood803 commented
Thanks a ton, @lmazuel! I think I broke it when fixing the linting errors, but some extra guidance from that team would be very helpful. Thank you again!

2018-06-14 12:20 UTC, jwood803 commented
Looks like I've been slacking too much and this has already been implemented. Should this PR be closed?

2018-06-14 23:49 UTC, jwood803 commented
No worries, @lmazuel! I should have fixed the issues in this PR a while ago to help it ready for further review. The other PR looks better than mine, too 😄 

I would like to implement the samples in the [samples repository](https://github.com/Azure-Samples/cognitive-services-python-sdk-samples), but I'm not sure about the workflow before it becomes a Python package in PyPI. I'm guessing after [this PR](https://github.com/Azure/azure-sdk-for-python/pull/2710) gets merged the Python package gets auto-generated?

2018-06-15 00:42 UTC, lmazuel commented
@jwood803 Yes, I need to configure the "setup.py" and do some testing, but indeed you got it :)

2018-06-15 00:46 UTC, jwood803 commented
Awesome, @lmazuel, thanks! I'll wait for the package to be generated and I'll hit up some samples! 😃 

I'll close this PR, but thank you for all the help! It's much appreciated!

2018-06-15 00:46 UTC, closed without merging

2018-06-15 00:48 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby