[TypeSpec Validation] exclude trailing slash when calculating folder depth
Azure/azure-rest-api-specs pull request #26626
Opened 2023-11-08 21:18 UTC by ckairen

closes #26549

2023-11-08 22:36 UTC, konrad-jamrozik commented on eng/tools/typespec-validation/src/rules/folder-structure.ts
> +    let folderStruct = folder.split("/").filter(Boolean);
Can you add a comment explaining what this does? I see like no connection between adding `filter(Boolean)` and making trailing slash disappear.

2023-11-08 22:37 UTC, konrad-jamrozik commented on eng/tools/typespec-validation/src/rules/folder-structure.ts
> +    let folderStruct = folder.split("/").filter(Boolean);
Or even you could introduce inline/local function named `excludeTrailingSlash` that does it. "self-documenting code" for the win ;)

2023-11-09 22:13 UTC, ckairen commented on eng/tools/typespec-validation/src/rules/folder-structure.ts
>      // Verify top level folder is lower case
```suggestion
    // Verify top level folder is lower case and remove empty entries when splitting by slash
```

2023-11-17 08:08 UTC, mikeharder approved these changes

2023-11-17 08:09 UTC, mikeharder requested changes
Please add a unit test

2023-11-30 16:25 UTC, ckairen commented
> Please add a unit test

This unit test will be built on top of the unit test in this pr https://github.com/Azure/azure-rest-api-specs/pull/26721

blocked until that pr is merged

2023-12-05 22:13 UTC, mikeharder approved these changes

2023-12-06 02:21 UTC, merged