[TypeSpec Validation] tsv folder path standardization
Azure/azure-rest-api-specs pull request #26721
Opened 2023-11-15 22:15 UTC by ckairen

closes #26546

2023-11-16 04:41 UTC, ckairen commented
tsv . will only work when it's in the correct spec folder. Since the tsv tool is intended to run on spec folders and not finding specs recursivley.

2023-11-17 08:19 UTC, mikeharder requested changes

2023-11-17 08:19 UTC, mikeharder commented on eng/tools/typespec-validation/src/rules/folder-structure.ts
> +    let relativePath = path.relative(gitRoot, folder).split(path.sep).join("/");
Add a unit test exercising these new APIs.

2023-11-17 08:19 UTC, mikeharder commented on eng/tools/typespec-validation/src/index.ts
> +  const absolutePath = path.resolve(folder).split(path.sep).join("/");
Extract a helper function named something like `normalizePath([...paths])` that can be unit tested, and add unit tests.  Unit tests should not rely on current directory.

2023-12-01 00:28 UTC, mikeharder approved these changes
Approved pending fixes to tests.

2023-12-01 00:28 UTC, mikeharder commented on eng/tools/typespec-validation/test/folder-structure.test.ts
> +  it("should fail if no tspconfig has incorrect extension", async function () {
```suggestion
  it("should fail if tspconfig has incorrect extension", async function () {
```

Was this a typo where the intention was reversed?

2023-12-01 00:28 UTC, mikeharder commented on eng/tools/typespec-validation/test/folder-structure.test.ts
> +  it("should fail if no folder under specification/ is capitalized", async function () {
```suggestion
  it("should fail if folder under specification/ is capitalized", async function () {
```

2023-12-01 00:28 UTC, mikeharder commented on eng/tools/typespec-validation/test/folder-structure.test.ts
> +      "/gitroot/specification/Foo/Foo/Foo/Foo",
```suggestion
      "/gitroot/specification/foo/Foo/Foo/Foo",
```

I think the service-family folder should be lower-case, unless we are trying to make it fail?

2023-12-01 00:28 UTC, mikeharder commented on eng/tools/typespec-validation/test/folder-structure.test.ts
> +      "/gitroot/specification/Foo/Foo.foo",
```suggestion
      "/gitroot/specification/foo/Foo.foo",
```

2023-12-01 00:28 UTC, mikeharder commented on eng/tools/typespec-validation/test/folder-structure.test.ts
> +      "/gitroot/specification/Foo/Foo.Management.Foo.Shared",
```suggestion
      "/gitroot/specification/foo/Foo.Management.Foo.Shared",
```

2023-12-01 00:28 UTC, mikeharder commented on eng/tools/typespec-validation/test/folder-structure.test.ts
> +      "/gitroot/specification/Foo/Foo.Management",
```suggestion
      "/gitroot/specification/foo/Foo.Management",
```

2023-12-01 00:28 UTC, mikeharder commented on eng/tools/typespec-validation/test/folder-structure.test.ts
> +      "/gitroot/specification/Foo/Foo.Management",
```suggestion
      "/gitroot/specification/foo/Foo.Management",
```

2023-12-01 00:28 UTC, mikeharder commented on eng/tools/typespec-validation/test/folder-structure.test.ts
> +      "/gitroot/specification/Foo/Foo.Management",
```suggestion
      "/gitroot/specification/foo/Foo.Management",
```

2023-12-05 00:30 UTC, konrad-jamrozik commented on eng/tools/typespec-validation/src/index.ts
> +  console.log("Running TypeSpecValidation on folder:", absolutePath);
@ckairen I think you may want to add a space after `folder:`

2023-12-05 08:34 UTC, ckairen commented on eng/tools/typespec-validation/src/index.ts
> +  console.log("Running TypeSpecValidation on folder:", absolutePath);
```suggestion
  console.log("Running TypeSpecValidation on folder: ", absolutePath);
```

2023-12-05 08:40 UTC, merged