Runbook Linting issues fixed
Azure/azure-rest-api-specs pull request #2687
Opened 2018-03-19 05:21 UTC by vrdmr

Fixed the 200 response issue. Fixed the linting issues related to it. Also fixed the resource group binding.

----
This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-03-19 05:22 UTC, AutorestCI commented
# Automation for azure-libraries-for-java

2018-03-19 05:22 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-03-19 05:23 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-03-19 05:25 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-03-19 18:22 UTC, sergey-shandar commented
@ravbhatnagar new response code (200) has been added.

2018-03-21 17:48 UTC, vrdmr commented
@ravbhatnagar Ping. Could you please review this PR. Thanks.

2018-03-22 14:10 UTC, ravbhatnagar commented
Signing off from ARM. It should not be a breaking change since the 200 response is the final response. Service would be returning a 202 only. Also, there should not be any service side behavior change. Please Correct my understanding.

2018-03-22 15:35 UTC, vrdmr commented
Yes. The service only returns 202 and there is no change done in the service. The 200 is only for fixing the Error statements during the linting.

2018-03-23 17:55 UTC, sergey-shandar commented
@vrdmr please, resolve conflicts.

2018-03-23 20:12 UTC, vrdmr commented
@sergey-shandar Resolved. Thanks.

2018-03-26 18:44 UTC, sergey-shandar requested changes

2018-03-26 20:42 UTC, vrdmr commented on specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/definitions.json
> +      "x-ms-parameter-location": "client"
We are planning to remove the ResourceGroupName and AutomationAccountName and put it only in the automationClient. We can set these values easily. Our SDK is still in preview and this is helping people to simplify the code.

2018-03-27 00:58 UTC, sergey-shandar approved these changes

2018-03-27 00:58 UTC, merged