Gelli/add ga spec
Azure/azure-rest-api-specs pull request #27084
Opened 2023-12-14 17:51 UTC by glorialimicrosoft

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

2023-12-14 18:06 UTC, DominikMe commented on specification/communication/Communication.Messages/routes.tsp
> +  @get
Let's try to use the built-in ResourceRead operation

2023-12-14 18:06 UTC, DominikMe commented on specification/communication/Communication.Messages/routes.tsp
> +  downloadMedia is Azure.Core.Foundations.Operation<
The method name "media" doesn't match the url ("streams"), this will end up with SDK and REST using different terminologies, let's align on one.

2023-12-14 18:06 UTC, DominikMe commented on specification/communication/Communication.Messages/models.tsp
> +model MessageTemplateValue {
Let's remodel this as a polymorphic type with the discriminator decorators. Then you don't have to declare all optional properties in the base model and the SDK will produce reasonable idiomatic types.
https://microsoft.github.io/typespec/standard-library/discriminated-types#string-discriminator

2023-12-14 18:06 UTC, DominikMe commented on specification/communication/Communication.Messages/models.tsp
> +  kind: MessageTemplateValueKind;
This property would move out of the base and into the concrete sub models with a string literal value that specifies their type.

2023-12-14 18:06 UTC, DominikMe commented on specification/communication/Communication.Messages/models.tsp
> +Could be an image, document or
This doc doesn't fit the `image` property. Let's remodel as discriminated types and then check the docs again.

2023-12-14 18:06 UTC, DominikMe commented on specification/communication/Communication.Messages/models.tsp
> +model ListTemplatesResponse {
You can delete this model when you use the built-in ResourceList operation.

2023-12-14 19:01 UTC, DominikMe commented on specification/communication/Communication.Messages/routes.tsp
> +  @doc("List all templates for given ACS channel")
We don't use ACS as an acronym in our public API or documentation, please change to "communication" or "Azure Communication Services" if it needs to reference the service itself.
```suggestion
  @doc("List all templates for given communication channel")
```

2025-04-25 09:15 UTC, v-jiaodi requested changes

2025-04-25 09:15 UTC, v-jiaodi commented on specification/communication/Communication.Messages/tspconfig.yaml
> +    packageDetails:
```suggestion
    package-details:
```

2026-09-16 16:22 UTC, closed without merging

2026-09-16 16:22 UTC, timotheeguerin commented
This PR has been closed because it has had no activity for more than a year. If this change is still needed, please reopen the PR.

<!-- inactive-pr-cleanup:2026-09-16 -->