Abaranwal ms edgeorder microsoft.edge order 2024 02 01
Azure/azure-rest-api-specs pull request #27145
Opened 2023-12-20 10:43 UTC by abaranwal-ms

# ARM (Control Plane) API Specification Update Pull Request 

> Tip: overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

![diagram](https://github.com/Azure/azure-rest-api-specs/assets/20296335/35140fb9-639e-4e44-ac4b-38b1a20dddf9)

<details>
<summary> Click here to see the details of Step 1 </summary>

### Breaking changes review (Diagram Step 1)

If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
- The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
- You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

</details>

<details> 
<summary> Click here to see the details of Step 2 </summary>

### ARM API changes review (Diagram Step 2)

- If this PR is in purview of ARM review then automation will add the `ARMReview` label.
- If you want to force ARM review, add the label yourself.
- Proceed according to the diagram at the top of this comment.

</details>

<details>
<summary> Click here to see the diagram footnotes</summary>

### Diagram footnotes

[1] [ARM review queue] (for **merge** queues, see [2])  
The PRs are processed by time opened, ascending. Your PR may show up on 2nd or later page. 
If you addressed Step 1 from the diagram and your PR is not showing up in the queue, ensure the label `ARMChangesRequested` 
is removed from your PR. This should cause the label `WaitForARMFeedback` to be added.
[2] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])

If you need further help with anything, see `Getting help` section below.

</details>

## Purpose of this PR

What's the purpose of this PR? Check all that apply. This is **mandatory**!

  - [ ] New API version. (If API spec is not defined in TypeSpec, the PR should have been generated using [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix swagger quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [ ] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [ ] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the Diagram Step 2, "ARM API changes Review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/azsdk/pr-suppressions) 
to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://github.com/search?q=org%3AAzure+is%3Apr+is%3Aopen+label%3AWaitForARMFeedback+-label%3AIDCDevDiv++draft%3Afalse+sort%3Acreated-asc+&type=pullrequests
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

2023-12-27 07:25 UTC, abaranwal-ms commented
for ❌ [1036 - ConstraintChanged](https://github.com/Azure/openapi-diff/tree/master/docs/rules/1036.md)

The orderItemName always had this restriction from our Portal Consumer code. Also, the length restriction was added explictly based on comment in our private preview swagger PR

https://github.com/Azure/azure-rest-api-specs-pr/pull/13646

2023-12-28 13:28 UTC, abaranwal-ms commented
/azp run

2023-12-28 13:41 UTC, abaranwal-ms commented
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>


</head>

<body lang=en-IN style='font-family:Calibri;font-size:11.0pt'>
<!--StartFragment-->

<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>&nbsp;</p>

<div style='direction:ltr'>


Breaking Change | Reason
-- | --
1007 -   RemovedClientParameter | We've removed a non-utilised   LocationParameter (since ARM recommends using common types rather than   redefining them). We are not referencing it anywhere also.     ( https://github.com/Azure/azure-openapi-validator/blob/main/docs/parameter-not-using-common-types.md)
1008 -   ModifiedOperationId | This         operationId change was taken when we release new preview api version EdgeOrder 2022-05-01-preview by shreyanshd · Pull         Request #19832 · Azure/azure-rest-api-specs (github.com)     The ARM guidelines         mentions here openapi-diff/docs/rules/1008.md         at master · Azure/openapi-diff (github.com) that modifying         operationId requires a new API version. Since, we are anyways releasing         a new API version, why is this flagged as a breaking change?
1023 -   TypeFormatChanged | This breaking change got introduce         after moving from V2 to V5 for common types.      Earlier all resource Ids were missing the format         attribute, now the format attribute is set to "arm-id".     This change was taken wrt suggestion from arm review         board as per this comment https://github.com/Azure/azure-rest-api-specs-pr/pull/13646#issuecomment-1656557580
1025 -   RequiredStatusChange | Since we are         evolving the address resource to be more generic, In ShippingAddress,         StreetAddress1 is no longer a required property     Since we are evolving the         address resource to be more generic, In AddressProperties,         ContactDetails is no longer a required property     Since we are evolving the         order Item resource to accept external Orders which might not have an         address, In OrderItemProperties, AddressDetails is no longer a required         property.     The ARM guidelines         mentions here openapi-diff/docs/rules/1025.md         at master · Azure/openapi-diff (github.com) that modifying required         status is not a breaking change new API version. Since, we are anyways         releasing a new API version, why is this flagged as a breaking change?
1027 -   DefaultValueChanged | The resource   identity definition was not used in our previous stable version as no   resource supported MSI.     So this does not impact any consumer.
1033 -   RemovedProperty | These breaking   changes are not introduced in this PR, it was introduced in the previous API   version, for which we already got a breaking change approval. (Link to   PR: Azure/azure-rest-api-specs#19832)   When we   created new API version 2022-05-01-preview, it had breaking changes against   version 2021-12-01, for which we received exception and ARM approval.   Now when we   created a new API version 2024-02-01 against 2022-05-01-preview it does not   have any breaking changes, but its again flagging the same set of breaking   changes against 2021-12-01
1036 -   ConstraintChanged | As   per suggestion from arm review board on the comment https://github.com/Azure/azure-rest-api-specs-pr/pull/13646#issuecomment-1656557402 to add format to the parameter,   we took this change.
1044 -   XmsLongRunningOperationChanged | This API was   always synchronous and incorrectly mentioned LRO assuming some use case in   future.       Since the service   never returns 202, we are fixing the swagger to be current and consistent   with the actual implementation.



</div>


<div>

Kindly review the breaking changes for the PR @rkmanda 

</div>

<!--EndFragment-->
</body>

</html>

2023-12-28 18:46 UTC, zizw123 commented
Remove ARMChangesRequested label to continue the ARM review once the breaking change review is done

2023-12-29 14:30 UTC, mikekistler commented
Breaking changes previously reviewed and approved in #19832

2023-12-29 19:35 UTC, zizw123 commented
>         "isCloudBasedProvisioningSupported": {

Consider if this can be enum, for any possible use case for future other than cloudBased

---
Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:1875 in caa298e. [](commit_id = caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c, deletion_comment = False)

2023-12-29 19:36 UTC, zizw123 commented
>         "Completed"

This only has pending and completed, when error happens, what will be this status?

---
Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in caa298e. [](commit_id = caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c, deletion_comment = False)

2023-12-29 19:41 UTC, zizw123 commented
Removed the suppressionReview label, I do not see suppression added in the latest commit.
SDK owners will check the failures for Go and python, if there's no updates, you can follow up with them [here](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750)

2024-01-02 12:44 UTC, abaranwal-ms commented
> > ```
> >     "isCloudBasedProvisioningSupported": {
> > ```
> 
> Consider if this can be enum, for any possible use case for future other than cloudBased
> 
> Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:1875 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)

moved to enum provisioningSupport : Manual or CloudBased

2024-01-02 13:02 UTC, abaranwal-ms commented
> https://github.com/Azure/azure-rest-api-specs/blob/9f2c42702e5bf6c1122375942f2bd014e1f4bf53/specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json#L3779C6-L3779C25

To an end use the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".

2024-01-02 13:02 UTC, abaranwal-ms commented
> > ```
> >     "Completed"
> > ```
> 
> This only has pending and completed, when error happens, what will be this status?
> 
> Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)

To an end use the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".

2024-01-02 23:42 UTC, mentat9 commented
> > > ```
> > >     "Completed"
> > > ```
> > 
> > 
> > This only has pending and completed, when error happens, what will be this status?
> > Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)
> 
> To an end user the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".



> > > ```
> > >     "Completed"
> > > ```
> > 
> > 
> > This only has pending and completed, when error happens, what will be this status?
> > Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)
> 
> To an end user the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".

@abaranwal-ms - Can you add some detail about the states? From the names and descriptions, it sounds like:

Pending - device possession check has started but isn't finished yet.
Completed - device possession check is complete.

How does the client discover:
1. During the check for device possession, there was an error, so the actual result is unknown.
2. If there was an error, what was it?

2024-01-03 11:37 UTC, abaranwal-ms commented
> > > > ```
> > > >     "Completed"
> > > > ```
> > > 
> > > 
> > > This only has pending and completed, when error happens, what will be this status?
> > > Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)
> > 
> > 
> > To an end user the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".
> 
> > > > ```
> > > >     "Completed"
> > > > ```
> > > 
> > > 
> > > This only has pending and completed, when error happens, what will be this status?
> > > Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)
> > 
> > 
> > To an end user the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".
> 
> @abaranwal-ms - Can you add some detail about the states? From the names and descriptions, it sounds like:
> 
> Pending - device possession check has started but isn't finished yet. Completed - device possession check is complete.
> 
> How does the client discover:
> 
> 1. During the check for device possession, there was an error, so the actual result is unknown.
> 2. If there was an error, what was it?

Pending is itself a terminal state and there might be multiple reasons leading to it, the reasons would be conveyed by the Message field.

2024-01-03 19:32 UTC, mikeharder requested changes

2024-01-03 19:32 UTC, mikeharder commented on package.json
Revert

2024-01-03 22:34 UTC, mentat9 commented
>         "responses": {

I understand you got breaking change approval for this PR, but I don't understand why you are purposely eliminating the 200 status code from deletes? Note the RPC requires both 200 and 204 for final status codes. I also noticed this wasn't part of the breaking change approval from the PR that was reviewed in the private repo. @mikekistler should we reconsider whether to allow delete with no 200 response?

---
Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:650 in 4e0e873. [](commit_id = 4e0e873a2e354c9929aabf0aa543242e88fb8715, deletion_comment = False)

2024-01-03 22:35 UTC, mentat9 commented
>         "responses": {

Similar issue here. Why are you removing 200 from delete responses?

---
Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:1023 in 4e0e873. [](commit_id = 4e0e873a2e354c9929aabf0aa543242e88fb8715, deletion_comment = False)

2024-01-03 22:52 UTC, mentat9 commented
> > > > > ```
> > > > >     "Completed"
> > > > > ```
> > > > 
> > > > 
> > > > This only has pending and completed, when error happens, what will be this status?
> > > > Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)
> > > 
> > > 
> > > To an end user the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".
> > 
> > 
> > > > > ```
> > > > >     "Completed"
> > > > > ```
> > > > 
> > > > 
> > > > This only has pending and completed, when error happens, what will be this status?
> > > > Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)
> > > 
> > > 
> > > To an end user the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".
> > 
> > 
> > @abaranwal-ms - Can you add some detail about the states? From the names and descriptions, it sounds like:
> > Pending - device possession check has started but isn't finished yet. Completed - device possession check is complete.
> > How does the client discover:
> > 
> > 1. During the check for device possession, there was an error, so the actual result is unknown.
> > 2. If there was an error, what was it?
> 
> Pending is itself a terminal state and there might be multiple reasons leading to it, the reasons would be conveyed by the Message field.

I find this to be a confusing design. Pending usually implies the service is working on something and the client can expect the state to change in the future (i.e. it's normally a transition state). Couple of concerns with this:
1. If Pending is a terminal state, it implies the system failed to get to Complete. Wouldn't that always be an error? If so, then Failed (or similar) would be a better name.
2. If there are only terminal states, the client has no way to know whether the service has finished working or not. Don't you need a transition state to indicate the system is calculating a new state?
3. What is the state set to when the resource is created?
4. If there was an error, how does the client request that the device possession state calculation should be retried?

2024-01-04 12:40 UTC, abaranwal-ms commented
@mentat9 Thank you for your review and comments. Here are our responses:



> > ```
> >     "responses": {
> > ```
> 
> I understand you got breaking change approval for this PR, but I don't understand why you are purposely eliminating the 200 status code from deletes? Note the RPC requires both 200 and 204 for final status codes. I also noticed this wasn't part of the breaking change approval from the PR that was reviewed in the private repo. @mikekistler should we reconsider whether to allow delete with no 200 response?
> 
> Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:650 in 4e0e873. [](commit_id = [4e0e873](https://github.com/Azure/azure-rest-api-specs/commit/4e0e873a2e354c9929aabf0aa543242e88fb8715), deletion_comment = False)



> > ```
> >     "responses": {
> > ```
> 
> Similar issue here. Why are you removing 200 from delete responses?
> 
> Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:1023 in 4e0e873. [](commit_id = [4e0e873](https://github.com/Azure/azure-rest-api-specs/commit/4e0e873a2e354c9929aabf0aa543242e88fb8715), deletion_comment = False)

**Why we removed 200 from delete response:** We followed the ARM guidelines here. Each 200 in a delete response raised a LintDiff Error for our Asynchronous (LRO) delete operations. Since this is a new version, we avoided the LintDiff Error by removing 200.
**Why we need 202 and 204 response codes for delete operations:** These codes indicate that the delete request was accepted and will be processed asynchronously (202), or that the resource was already deleted (204). Having 200 response code was flagged by the system as an error, which is not the case for our service.
**What we need from you:** We are not sure if the system needs improvement for incorrectly flagging the 200 response code, or if there is a way to override or suppress the LintDiff Error for our service. We would appreciate your guidance on this issue.
**How we handle the breaking change:** We understand that removing 200 response code might be a breaking change for some of our customers who rely on it. However, we believe that following the ARM guidelines and using 202 and 204 codes is more consistent and accurate for our service. If you feel strongly that we should keep 200 response code, we are open to it.

2024-01-04 12:54 UTC, abaranwal-ms commented
> > > > > > ```
> > > > > >     "Completed"
> > > > > > ```
> > > > > 
> > > > > 
> > > > > This only has pending and completed, when error happens, what will be this status?
> > > > > Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)
> > > > 
> > > > 
> > > > To an end user the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".
> > > 
> > > 
> > > > > > ```
> > > > > >     "Completed"
> > > > > > ```
> > > > > 
> > > > > 
> > > > > This only has pending and completed, when error happens, what will be this status?
> > > > > Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)
> > > > 
> > > > 
> > > > To an end user the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".
> > > 
> > > 
> > > @abaranwal-ms - Can you add some detail about the states? From the names and descriptions, it sounds like:
> > > Pending - device possession check has started but isn't finished yet. Completed - device possession check is complete.
> > > How does the client discover:
> > > 
> > > 1. During the check for device possession, there was an error, so the actual result is unknown.
> > > 2. If there was an error, what was it?
> > 
> > 
> > Pending is itself a terminal state and there might be multiple reasons leading to it, the reasons would be conveyed by the Message field.
> 
> I find this to be a confusing design. Pending usually implies the service is working on something and the client can expect the state to change in the future (i.e. it's normally a transition state). Couple of concerns with this:
> 
> 1. If Pending is a terminal state, it implies the system failed to get to Complete. Wouldn't that always be an error? If so, then Failed (or similar) would be a better name.
> 2. If there are only terminal states, the client has no way to know whether the service has finished working or not. Don't you need a transition state to indicate the system is calculating a new state?
> 3. What is the state set to when the resource is created?
> 4. If there was an error, how does the client request that the device possession state calculation should be retried?

- At present, the device verification from device to service can either be pending or completed(like a boolean flag). Until the device has verified itself to the service, the status is PENDING. Once the device has verified, the status becomes COMPLETED.
- We do not have a product flow or customer scenario where the device verification was attempted but failed. However, it could be possible in the future that verification fails due to some reason. When that happens, we will extend the enum to include more values, such as PendingCustomerAction or Failed, along with appropriate error messages.
- Therefore, we are introducing the enum with only two values for now: Pending and Completed. We are keeping it as an enum (instead of a boolean flag) so that new statuses can be added in future API versions without breaking backward compatibility.

2024-01-08 19:34 UTC, abaranwal-ms commented
@mentat9 

To answer the question, why we name this as Pending.

There are 2 Personas involved in this case from customer side.

1. A Cloud Operator -> a person triggering our device ordering APIs via portal flows or a SDK
2. An Edge Operator -> a person located at device delivery place, responsible for setting up the device.

The flow of APIs is such -> a PUT to our ordering API with provisioning resource creates an Order Item with _Pending_ State.
This PUT is triggered by the Cloud Operator. This means the Cloud Operator is waiting for the device to reach the location and is pending setup. As soon as the setup is done, device agent does a POST call, and we mark the State to _Complete_ . 

So for the Cloud Operator persona, actually the proof of possession is in a _Pending_ state until the device got setup.

2024-01-08 19:35 UTC, abaranwal-ms commented
> > > > > > > ```
> > > > > > >     "Completed"
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > This only has pending and completed, when error happens, what will be this status?
> > > > > > Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)
> > > > > 
> > > > > 
> > > > > To an end user the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".
> > > > 
> > > > 
> > > > > > > ```
> > > > > > >     "Completed"
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > This only has pending and completed, when error happens, what will be this status?
> > > > > > Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)
> > > > > 
> > > > > 
> > > > > To an end user the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".
> > > > 
> > > > 
> > > > @abaranwal-ms - Can you add some detail about the states? From the names and descriptions, it sounds like:
> > > > Pending - device possession check has started but isn't finished yet. Completed - device possession check is complete.
> > > > How does the client discover:
> > > > 
> > > > 1. During the check for device possession, there was an error, so the actual result is unknown.
> > > > 2. If there was an error, what was it?
> > > 
> > > 
> > > Pending is itself a terminal state and there might be multiple reasons leading to it, the reasons would be conveyed by the Message field.
> > 
> > 
> > I find this to be a confusing design. Pending usually implies the service is working on something and the client can expect the state to change in the future (i.e. it's normally a transition state). Couple of concerns with this:
> > 
> > 1. If Pending is a terminal state, it implies the system failed to get to Complete. Wouldn't that always be an error? If so, then Failed (or similar) would be a better name.
> > 2. If there are only terminal states, the client has no way to know whether the service has finished working or not. Don't you need a transition state to indicate the system is calculating a new state?
> > 3. What is the state set to when the resource is created?
> > 4. If there was an error, how does the client request that the device possession state calculation should be retried?
> 
> * At present, the device verification from device to service can either be pending or completed(like a boolean flag). Until the device has verified itself to the service, the status is PENDING. Once the device has verified, the status becomes COMPLETED.
> * We do not have a product flow or customer scenario where the device verification was attempted but failed. However, it could be possible in the future that verification fails due to some reason. When that happens, we will extend the enum to include more values, such as PendingCustomerAction or Failed, along with appropriate error messages.
> * Therefore, we are introducing the enum with only two values for now: Pending and Completed. We are keeping it as an enum (instead of a boolean flag) so that new statuses can be added in future API versions without breaking backward compatibility.



@mentat9 

To answer the question, why we name this as Pending.

There are 2 Personas involved in this case from customer side.

1. A Cloud Operator -> a person triggering our device ordering APIs via portal flows or a SDK
2. An Edge Operator -> a person located at device delivery place, responsible for setting up the device.

The flow of APIs is such -> a PUT to our ordering API with provisioning resource creates an Order Item with _Pending_ State.
This PUT is triggered by the Cloud Operator. This means the Cloud Operator is waiting for the device to reach the location and is pending setup. As soon as the setup is done, device agent does a POST call, and we mark the State to _Complete_ . 

So for the Cloud Operator persona, actually the proof of possession is in a _Pending_ state until the device got setup.

2024-01-08 20:48 UTC, mentat9 commented
> > > > > > > > ```
> > > > > > > >     "Completed"
> > > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > This only has pending and completed, when error happens, what will be this status?
> > > > > > > Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)
> > > > > > 
> > > > > > 
> > > > > > To an end user the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".
> > > > > 
> > > > > 
> > > > > > > > ```
> > > > > > > >     "Completed"
> > > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > This only has pending and completed, when error happens, what will be this status?
> > > > > > > Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)
> > > > > > 
> > > > > > 
> > > > > > To an end user the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".
> > > > > 
> > > > > 
> > > > > @abaranwal-ms - Can you add some detail about the states? From the names and descriptions, it sounds like:
> > > > > Pending - device possession check has started but isn't finished yet. Completed - device possession check is complete.
> > > > > How does the client discover:
> > > > > 
> > > > > 1. During the check for device possession, there was an error, so the actual result is unknown.
> > > > > 2. If there was an error, what was it?
> > > > 
> > > > 
> > > > Pending is itself a terminal state and there might be multiple reasons leading to it, the reasons would be conveyed by the Message field.
> > > 
> > > 
> > > I find this to be a confusing design. Pending usually implies the service is working on something and the client can expect the state to change in the future (i.e. it's normally a transition state). Couple of concerns with this:
> > > 
> > > 1. If Pending is a terminal state, it implies the system failed to get to Complete. Wouldn't that always be an error? If so, then Failed (or similar) would be a better name.
> > > 2. If there are only terminal states, the client has no way to know whether the service has finished working or not. Don't you need a transition state to indicate the system is calculating a new state?
> > > 3. What is the state set to when the resource is created?
> > > 4. If there was an error, how does the client request that the device possession state calculation should be retried?
> > 
> > 
> > 
> > * At present, the device verification from device to service can either be pending or completed(like a boolean flag). Until the device has verified itself to the service, the status is PENDING. Once the device has verified, the status becomes COMPLETED.
> > * We do not have a product flow or customer scenario where the device verification was attempted but failed. However, it could be possible in the future that verification fails due to some reason. When that happens, we will extend the enum to include more values, such as PendingCustomerAction or Failed, along with appropriate error messages.
> > * Therefore, we are introducing the enum with only two values for now: Pending and Completed. We are keeping it as an enum (instead of a boolean flag) so that new statuses can be added in future API versions without breaking backward compatibility.
> 
> @mentat9
> 
> To answer the question, why we name this as Pending.
> 
> There are 2 Personas involved in this case from customer side.
> 
> 1. A Cloud Operator -> a person triggering our device ordering APIs via portal flows or a SDK
> 2. An Edge Operator -> a person located at device delivery place, responsible for setting up the device.
> 
> The flow of APIs is such -> a PUT to our ordering API with provisioning resource creates an Order Item with _Pending_ State. This PUT is triggered by the Cloud Operator. This means the Cloud Operator is waiting for the device to reach the location and is pending setup. As soon as the setup is done, device agent does a POST call, and we mark the State to _Complete_ .
> 
> So for the Cloud Operator persona, actually the proof of possession is in a _Pending_ state until the device got setup.

@abaranwal-ms - Thank-you for clarifying this for me. I think the only remaining concern here is the name "Pending", which to me implies a transition state that the system will update after completing some in-flight work. I think something like Waiting, Incomplete,, NotEvaluated, or something similar would better convey the meaning of that state.

2024-01-09 09:43 UTC, abaranwal-ms commented
> > > > > > > > > ```
> > > > > > > > >     "Completed"
> > > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > > This only has pending and completed, when error happens, what will be this status?
> > > > > > > > Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)
> > > > > > > 
> > > > > > > 
> > > > > > > To an end user the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".
> > > > > > 
> > > > > > 
> > > > > > > > > ```
> > > > > > > > >     "Completed"
> > > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > > This only has pending and completed, when error happens, what will be this status?
> > > > > > > > Refers to: specification/edgeorder/resource-manager/Microsoft.EdgeOrder/stable/2024-02-01/edgeorder.json:2422 in [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c). [](commit_id = [caa298e](https://github.com/Azure/azure-rest-api-specs/commit/caa298e548876b3d3ad4bc7dc5ffe2d8a886a48c), deletion_comment = False)
> > > > > > > 
> > > > > > > 
> > > > > > > To an end user the status is either Pending or Completed. To provide more insights into why it is pending adding new message field in a new object "DevicePresenceVerificationDetails".
> > > > > > 
> > > > > > 
> > > > > > @abaranwal-ms - Can you add some detail about the states? From the names and descriptions, it sounds like:
> > > > > > Pending - device possession check has started but isn't finished yet. Completed - device possession check is complete.
> > > > > > How does the client discover:
> > > > > > 
> > > > > > 1. During the check for device possession, there was an error, so the actual result is unknown.
> > > > > > 2. If there was an error, what was it?
> > > > > 
> > > > > 
> > > > > Pending is itself a terminal state and there might be multiple reasons leading to it, the reasons would be conveyed by the Message field.
> > > > 
> > > > 
> > > > I find this to be a confusing design. Pending usually implies the service is working on something and the client can expect the state to change in the future (i.e. it's normally a transition state). Couple of concerns with this:
> > > > 
> > > > 1. If Pending is a terminal state, it implies the system failed to get to Complete. Wouldn't that always be an error? If so, then Failed (or similar) would be a better name.
> > > > 2. If there are only terminal states, the client has no way to know whether the service has finished working or not. Don't you need a transition state to indicate the system is calculating a new state?
> > > > 3. What is the state set to when the resource is created?
> > > > 4. If there was an error, how does the client request that the device possession state calculation should be retried?
> > > 
> > > 
> > > 
> > > * At present, the device verification from device to service can either be pending or completed(like a boolean flag). Until the device has verified itself to the service, the status is PENDING. Once the device has verified, the status becomes COMPLETED.
> > > * We do not have a product flow or customer scenario where the device verification was attempted but failed. However, it could be possible in the future that verification fails due to some reason. When that happens, we will extend the enum to include more values, such as PendingCustomerAction or Failed, along with appropriate error messages.
> > > * Therefore, we are introducing the enum with only two values for now: Pending and Completed. We are keeping it as an enum (instead of a boolean flag) so that new statuses can be added in future API versions without breaking backward compatibility.
> > 
> > 
> > @mentat9
> > To answer the question, why we name this as Pending.
> > There are 2 Personas involved in this case from customer side.
> > 
> > 1. A Cloud Operator -> a person triggering our device ordering APIs via portal flows or a SDK
> > 2. An Edge Operator -> a person located at device delivery place, responsible for setting up the device.
> > 
> > The flow of APIs is such -> a PUT to our ordering API with provisioning resource creates an Order Item with _Pending_ State. This PUT is triggered by the Cloud Operator. This means the Cloud Operator is waiting for the device to reach the location and is pending setup. As soon as the setup is done, device agent does a POST call, and we mark the State to _Complete_ .
> > So for the Cloud Operator persona, actually the proof of possession is in a _Pending_ state until the device got setup.
> 
> @abaranwal-ms - Thank-you for clarifying this for me. I think the only remaining concern here is the name "Pending", which to me implies a transition state that the system will update after completing some in-flight work. I think something like Waiting, Incomplete,, NotEvaluated, or something similar would better convey the meaning of that state.

@mentat9 - As per feedback, we have renamed the state _Pending_ to _NotInitiated_

2024-01-09 23:44 UTC, mentat9 commented
/azp run

2024-01-10 18:49 UTC, abaranwal-ms commented
> Removed the suppressionReview label, I do not see suppression added in the latest commit. SDK owners will check the failures for Go and python, if there's no updates, you can follow up with them [here](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750)

@mentat9, @zizw123 

There is no supression requested in this PR. Please help to remove the suppression by adding the Approved-Suppression label
https://github.com/Azure/azure-rest-api-specs/pull/27145/checks?check_run_id=20323335391

2024-01-12 01:43 UTC, live1206 commented
.NET track 2 automation is failing due to breaking changes, we can handle it during SDK generation, not a blocker for this PR.

2024-01-12 07:22 UTC, abaranwal-ms commented
/azp run

2024-01-12 17:09 UTC, abaranwal-ms commented
/pr RequestMerge

2024-01-12 19:10 UTC, mentat9 commented
@mikeharder - I think you need to approve your requested changes here https://github.com/Azure/azure-rest-api-specs/pull/27145#discussion_r1440854565 before we can merge.

2024-01-12 20:52 UTC, mikeharder approved these changes

2024-01-12 20:54 UTC, merged