Microsoft.Solutions add 2018-02-01
Azure/azure-rest-api-specs pull request #2715
Opened 2018-03-21 01:05 UTC by ilahat

Adding new version because our "patch" had required fields in the body
before. Server-side we do not allow any properties except resource-level
properties with tags being the only ones that actually get updated.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-03-21 01:07 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-03-21 01:16 UTC, AutorestCI commented
# Automation for azure-libraries-for-java

2018-03-21 01:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-03-21 01:36 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-03-21 16:58 UTC, dsgouda commented
Working on network related PRs

2018-03-22 18:46 UTC, jianghaolu requested changes

2018-03-22 18:46 UTC, jianghaolu commented on specification/resources/resource-manager/Microsoft.Solutions/stable/2018-02-01/managedapplications.json
> +    "/{applicationDefinitionId}": {
This is a duplicate of line 580.

2018-03-22 18:46 UTC, jianghaolu commented on specification/resources/resource-manager/Microsoft.Solutions/stable/2018-02-01/examples/getApplication.json
> +  "parameters": {
Parameter `applicationName` is missing.

2018-03-22 18:46 UTC, jianghaolu commented on specification/resources/resource-manager/Microsoft.Solutions/stable/2018-02-01/examples/getApplication.json
> +        "resourceGroup": "rg",
`resourceGroup` is not defined in `Application`.

2018-03-22 18:46 UTC, jianghaolu commented on specification/resources/resource-manager/Microsoft.Solutions/stable/2018-02-01/examples/getApplication.json
> +          "managedApplicationDefinitionId": "/subscriptions/subid/resourceGroups/rg/providers/Microsoft.Solutions/managedApplicationDefinitions/myAppDef",
`managedApplicationDefinitionId` is not defined in `Application`.

2018-03-22 18:46 UTC, jianghaolu commented on specification/resources/resource-manager/Microsoft.Solutions/stable/2018-02-01/examples/createOrUpdateApplication.json
> +  "responses": {
Please also provide 200 response example.

2018-03-22 18:46 UTC, jianghaolu commented on specification/resources/resource-manager/Microsoft.Solutions/stable/2018-02-01/examples/createOrUpdateApplication.json
> +  "parameters": {
Parameter `applicationName` missing.

2018-03-22 18:46 UTC, jianghaolu commented on specification/resources/resource-manager/Microsoft.Solutions/stable/2018-02-01/examples/createOrUpdateApplication.json
> +      "body": {
Similar to getApplication.json - the response here does not match the definition of `Application`.

2018-03-22 18:46 UTC, jianghaolu commented on specification/resources/resource-manager/Microsoft.Solutions/stable/2018-02-01/examples/getApplicationDefinition.json
> +  "parameters": {
Parameter `applicationDefinitionName` missing.

2018-03-22 18:46 UTC, jianghaolu commented on specification/resources/resource-manager/Microsoft.Solutions/stable/2018-02-01/examples/getApplicationDefinition.json
> +      "body": {
The response here does not match the definition of `ApplicationDefinition`.

2018-03-22 18:46 UTC, jianghaolu commented on specification/resources/resource-manager/Microsoft.Solutions/stable/2018-02-01/examples/getApplicationDefinition.json
> +      "body": {
Same elsewhere.

2018-03-22 18:46 UTC, jianghaolu commented on specification/resources/resource-manager/Microsoft.Solutions/stable/2018-02-01/managedapplications.json
> +          "404": {
All the negative response status code descriptions MUST be defined in the description of the "default" status code (if the intention is for documentation purpose only). Example: "description": "'404' - 'Not found'.\n'400' - 'Bad request'.\n'500': 'Internal Server Error'."' 

Same elsewhere.

2018-06-27 19:06 UTC, veronicagg commented
@ilahat should this PR be closed? it's been opened for a long time with no activity. thanks.

2018-07-19 19:01 UTC, jianghaolu commented
Closing as we haven't heard back. Please feel free to reopen, thanks!

2018-07-19 19:01 UTC, closed without merging

2018-07-19 19:02 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-07-19 19:07 UTC, AutorestCI commented
# Automation for azure-sdk-for-java