OS History API - Swagger
Azure/azure-rest-api-specs pull request #2743
Opened 2018-03-23 03:12 UTC by sds6

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-03-23 03:13 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=2743) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=2743) before we can accept your contribution.<br/><br/>:x: sds6 [sign now](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=2743)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-rest-api-specs?pullRequest=2743) it.</sub>

2018-03-23 03:16 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-03-23 03:16 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-03-23 03:16 UTC, AutorestCI commented
# Automation for azure-libraries-for-java

2018-03-23 18:52 UTC, lmazuel commented
@AutorestCI rebuild azure-libraries-for-java

2018-03-23 20:27 UTC, sarangan12 commented
@sds6 The contributor license agreement has not been signed yet. Could you join the appropriate org to resolve the issue?

2018-03-23 21:49 UTC, sds6 commented
@sarangan12 signed.

2018-03-23 22:14 UTC, sarangan12 commented
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/357213506
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/357213505

Please take a look at these errors and try to fix them.

2018-03-28 17:49 UTC, sarangan12 commented
@sds6 Any updates????

2018-03-28 21:16 UTC, sds6 commented
Will have an update early next week.

On Wed, Mar 28, 2018 at 10:49 AM, Sarangan Rajamanickam <
notifications@github.com> wrote:

> @sds6 <https://github.com/sds6> Any updates????
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Azure/azure-rest-api-specs/pull/2743#issuecomment-376975958>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIg6-Fr__w_H9yw557CviiFGsEx21UmBks5ti81FgaJpZM4S4HHD>
> .
>

2018-04-03 21:59 UTC, sds6 commented
@sarangan12 All the errors I see are for x-ms-examples.  Compute is adding them gradually for all APIs over the next few months. Similar PR #2589 was also approved ignoring x-ms-examples. Adding in @hyonholee to chime in.

2018-04-05 17:44 UTC, sarangan12 approved these changes

2018-04-05 17:45 UTC, sarangan12 commented
@sds6 Take a look at this: https://travis-ci.org/Azure/azure-rest-api-specs/jobs/357213505 These errors are not related to x-ms-examples. These errors must be fixed before approval

2018-04-05 17:46 UTC, sarangan12 requested changes
Please see the link https://travis-ci.org/Azure/azure-rest-api-specs/jobs/357213505 These are not x-ms-examples errors. They must be fixed before approval

2018-04-09 22:02 UTC, sarangan12 commented
@sds6 The recent changes have introduced more new errors. Please check the travis CI.

2018-04-10 19:58 UTC, sds6 commented
@sarangan12 Those changes are not related to the push I made.

2018-04-10 21:00 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2017-12-01/compute.json
> +          "description": "Start time of the upgrade."
"End time of the upgrade"

2018-04-10 21:01 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2017-12-01/compute.json
> +          "description": "Error Details for this upgrade if there are any.",
Update the description

2018-04-10 21:01 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2017-12-01/compute.json
> +          "type": "string",
"readOnly": true,

2018-04-10 21:01 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2017-12-01/compute.json
> +        "description": "Virtual Machine Scale Set OS Upgrade History operation response."
NIT: fix indent

2018-04-10 22:12 UTC, jhendrixMSFT commented
@AutorestCI regenerate azure-sdk-for-go

2018-04-11 19:52 UTC, sarangan12 approved these changes

2018-04-11 19:52 UTC, merged