Bug fix: Remove maxLeng on ScopeParameter
Azure/azure-rest-api-specs pull request #27616
Opened 2024-02-01 19:16 UTC by allenjzhang

# ARM (Control Plane) API Specification Update Pull Request 

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

> [!NOTE]
> As of January 2024 there is no PR assignee. This is expected. See https://aka.ms/azsdk/pr-arm-review.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

![diagram](https://github.com/Azure/azure-rest-api-specs/assets/20296335/35140fb9-639e-4e44-ac4b-38b1a20dddf9)

<details>
<summary> Click here to see the details of Step 1 </summary>

### Breaking changes review (Diagram Step 1)

If the automation determines you have breaking changes, i.e. Step 1 from the diagram applies to you,
  you must follow the [breaking changes process].  
  **IMPORTANT** This applies even if:
- The tool fails while it shouldn't, e.g. due to runtime exception, or incorrect detection of breaking changes.
- You believe there is no need for you to request breaking change approval, for any reason. 
    Such claims must be reviewed, and the process is the same.

</details>

<details> 
<summary> Click here to see the details of Step 2 </summary>

### ARM API changes review (Diagram Step 2)

- For help with Step 2 / "ARM review", see https://aka.ms/azsdk/pr-arm-review.

</details>

<details>
<summary> Click here to see the diagram footnotes</summary>

### Diagram footnotes

[1] See [ARM review queue] (for **PR merge** queues, see [2]).  
[2] [public repo merge queue], [private repo merge queue] (for **ARM review** queue, [1])  
The ARM reviewer on-call engineer visits the merge queue twice a day, so the approximate ETA for merges is 12 - 24 hours.

</details>

## Purpose of this PR

What's the purpose of this PR? Check the specific option that applies. This is **mandatory**!

  - [ ] New resource provider.
  - [ ] New API version for an existing resource provider. (If API spec is not defined in TypeSpec, the PR should have been generated using [OpenAPI Hub](https://aka.ms/openapihub)).
  - [ ] Update existing version for a new feature. (This is applicable only when you are revising a private preview API version.)
  - [ ] Update existing version to fix OpenAPI spec quality issues in S360.
  - [ ] Other, please clarify:
    - _edit this with your clarification_

## Due diligence checklist

To merge this PR, you **must** go through the following checklist and confirm you understood 
and followed the instructions by checking all the boxes:

- [ ] I confirm this PR is modifying Azure Resource Manager (ARM) related specifications, and not data plane related specifications.
- [ ] I have reviewed following [Resource Provider guidelines](https://aka.ms/rpguidelines), including
  [ARM resource provider contract](https://github.com/Azure/azure-resource-manager-rpc) and
  [REST guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) (estimated time: 4 hours).  
  I understand this is required before I can proceed to the diagram Step 2, "ARM API changes review", for this PR.

## Additional information

<details>
<summary> Viewing API changes</summary>

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

</details>
<details>
<summary>Suppressing failures</summary>

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[suppressions guide](https://aka.ms/azsdk/pr-suppressions) to get approval.

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom. Please fill out the `Purpose of this PR` and `Due diligence checklist`.
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- For help with PR workflow diagram Step 2 (ARM review), see https://aka.ms/azsdk/pr-arm-review.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

[ARM review queue]: https://aka.ms/azsdk/pr-arm-review#about-the-arm-review-queue
[public repo merge queue]: https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+draft%3Afalse+sort%3Acreated-asc
[private repo merge queue]: https://github.com/Azure/azure-rest-api-specs-pr/pulls?q=is%3Aopen+is%3Apr+label%3AMergeRequested+-label%3AApproved-OkToMerge+draft%3Afalse+sort%3Acreated-asc
[breaking changes process]: https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingproductbreakingchanges#breaking-change-process-1

2024-02-01 19:21 UTC, allenjzhang commented
In v4 and v5 common-type definitions, `ScopeParameter` has maxLength: 90 constraints on it. I think this is an obvious bug given it's composed parts like RG name has max of 90. Spec examples with reasonable data (simple one resource scope was 140) triggers validation errors. This really limited re-usability of this parameter. It also impacted TypeSpec as we often generate ref to common-types.
 
I propose we remove the maxLength limit for v4 and v5. It is NOT a breaking change as it widen the data range. Client SDK doesn't use that info either. So it should be safe to do.

2024-02-02 12:55 UTC, visingla-ms commented
Allowing values with longer length now, should be fine, and should not cause any breaking changes per my understanding also.
@mikekistler @JeffreyRichter Can you please confirm?

2024-02-02 14:06 UTC, mikekistler requested changes
I would strongly prefer changing the `maxLength` to the correct value than removing `maxLength` altogether.

2024-02-02 17:02 UTC, JeffreyRichter commented
Widening a data range IS a breaking change because an old client (expecting a smaller range) could now receive the widened range causing a buffer overflow (for example).

2024-02-02 20:47 UTC, allenjzhang commented
> Widening a data range IS a breaking change because an old client (expecting a smaller range) could now receive the widened range causing a buffer overflow (for example).

As far as I know, we don't do client-side validation in our SDKs. Besides, it pretty much renders this un-usable **AT ALL**. For a normal URL with super short RG name, 90 stops at `Microsoft.`
/subscriptions/24d273df-8743-42fe-b46b-a84c558e3045/resourceGroups/rg1/providers/Microsoft**90**.Storage/storageAccounts/sacc

```diff
@@/subscriptions/24d273df-8743-42fe-b46b-a84c558e3045/resourceGroups/rg1/providers/Microsoft.@@Storage/storageAccounts/sacc
```

2024-02-02 20:52 UTC, allenjzhang commented
> I would strongly prefer changing the `maxLength` to the correct value than removing `maxLength` altogether.

Not possible. https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md. Given hierarchy of resources (no upper bound), each segment can grow 260+. No limit is the right thing to do here.

2024-02-02 20:52 UTC, allenjzhang commented
> I would strongly prefer changing the `maxLength` to the correct value than removing `maxLength` altogether.

Not possible. https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md. Given hierachy of resources (no upper bound), each segment can grow 260+.

2024-02-03 05:20 UTC, JeffreyRichter commented
I don't know what the full goal is here. It is true that our SDKs do not do client-side validation but I rarely care about what SDKs do because API specs are contracts and these contracts apply to ALL Azure customers whether they use an SDK or not. So, a contract that says one thing and then changes can easily break all these customers. 

Languages that must pre-allocate buffers (like, C, C++ and Rust) based on the maxLength are very likely to have serious problems if we change a contract size constraint.

2024-02-06 18:11 UTC, allenjzhang commented
> I don't know what the full goal is here. It is true that our SDKs do not do client-side validation but I rarely care about what SDKs do because API specs are contracts and these contracts apply to ALL Azure customers whether they use an SDK or not. So, a contract that says one thing and then changes can easily break all these customers.
> 
> Languages that must pre-allocate buffers (like, C, C++ and Rust) based on the maxLength are very likely to have serious problems if we change a contract size constraint.

This will almost always result LintDiff errors in PR when people supplies the reasonable data in examples.

2024-02-06 22:17 UTC, JeffreyRichter commented
Allen & I spoke about this offline. Removing the constraint is considered a bug fix so I'm OK with it.

2024-02-06 22:45 UTC, mikekistler approved these changes
Dropping my objection.

2024-02-07 05:59 UTC, allenjzhang commented
/pr RequestMerge

2024-02-07 19:01 UTC, merged