AzureStack Gallery Admin
Azure/azure-rest-api-specs pull request #2780
Opened 2018-03-29 22:16 UTC by deathly809

Initial commit for the AzureStack Gallery admin specs.

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-03-29 22:16 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-03-29 22:16 UTC, AutorestCI commented
# Automation for azure-libraries-for-java

2018-03-29 22:16 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-03-29 22:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-03-29 22:26 UTC, bganapa approved these changes

2018-03-29 22:56 UTC, deathly809 commented
@lmazuel Hmm, looks like it does not like objects with no properties.  Not really sure what to do with this.

2018-04-10 23:09 UTC, deathly809 commented
@lmazuel Ping.

2018-04-12 22:27 UTC, jhendrixMSFT requested changes

2018-04-12 22:27 UTC, jhendrixMSFT commented on specification/azsadmin/resource-manager/gallery/Microsoft.Gallery.Admin/preivew/2015-04-01/Gallery.json
> +                "operationId": "ListOperations",
This really should be Operations_List.

2018-04-12 22:27 UTC, jhendrixMSFT commented on specification/azsadmin/resource-manager/gallery/Microsoft.Gallery.Admin/preivew/2015-04-01/Gallery.json
> +                    "nextLinkName": null
Curious why this is null?  There's a nextLink field defined in OperationList.

2018-04-12 22:27 UTC, jhendrixMSFT commented on specification/azsadmin/resource-manager/gallery/Microsoft.Gallery.Admin/preivew/2015-04-01/GalleryItem.json
> +                    "nextLinkName": null
Another null nextLinkName.

2018-04-13 20:04 UTC, jhendrixMSFT approved these changes

2018-04-13 20:04 UTC, merged