Users/harshanb/loadtesting 2024 03 01 preview
Azure/azure-rest-api-specs pull request #28315
Opened 2024-03-19 08:44 UTC by Harshan01

# Data Plane API - Pull Request

### Locust Configuration
Customers have a need to run load tests with different load testing frameworks and tools apart from the one currently supported. We add new enum values for `TestKind` and `FileType` enums with values `Locust` and `TEST_SCRIPT` respectively. `Locust` is the name of the load testing framework, and `TEST_SCRIPT` will now be preferred instead of `JMX_FILE` as JMX file is specific to the framework currently supported, but `TEST_SCRIPT` will be generic for all test frameworks which will be supported currently and in future.

We also expose `LocustConfiguration` model inside the `LoadTestConfiguration` model which will input a few parameters required by the test framework to run the load test

### Other features go here...

## API Info: The Basics
Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [x] a public preview
- [ ] GA release

### Change Scope

<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document: https://dev.azure.com/devdiv/OnlineServices/_git/CloudNativeTest-Docs?path=/documentation/Design/Multi-Engine/Multi-Engine-API.md , https://dev.azure.com/devdiv/OnlineServices/_git/CloudNativeTest-Docs?path=/documentation/Design/Test-Rig/MultiRegion.md
* Previous API Spec Doc:
* Updated paths:

### Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

### Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/pr-suppressions) 
to get approval.

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling

 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)
 * [Open API Hub](https://aka.ms/openapiportal)

### Guidelines & Specifications

 * [Azure REST API Guidelines](https://aka.ms/azapi/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/azapi/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links

 * [Schedule a data plane REST API spec review](https://aka.ms/azsdk/onboarding/restapischedule)

</details>

<details>
  <summary>Checks stuck in `queued` state?</summary>
If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.  
</details>

2024-04-07 02:51 UTC, weidongxu-microsoft commented
The change on "readOnly" to true would require a sign off from breaking changes review board.

2024-04-07 03:03 UTC, weidongxu-microsoft commented on specification/loadtestservice/LoadTestService/models.tsp
> +  durationInSeconds?: int32;
not API. SDK may want you to use duration with `@encode(int32)` https://typespec.io/docs/standard-library/built-in-decorators#@encode

2024-04-07 03:03 UTC, weidongxu-microsoft commented on specification/loadtestservice/LoadTestService/models.tsp
> +  region: string;
Could you address meeting comment?
https://github.com/Azure/azure-rest-api-specs/issues/28376#issuecomment-2037496122

2024-04-08 09:15 UTC, Harshan01 commented
> The change on "readOnly" to true would require a sign off from breaking changes review board.
> 
> However I didn't see any change in tsp that could result in this. Maybe you can try refresh main, and rerun the tsp step, as latest now be 0.55 https://github.com/Azure/azure-rest-api-specs/blob/main/package.json#L10

@weidongxu-microsoft Installed typespec compiler after pulling main and the readonly changes have been reverted

2024-04-16 01:17 UTC, weidongxu-microsoft approved these changes

2024-05-07 16:06 UTC, Harshan01 commented
@mikekistler @weidongxu-microsoft Requesting re-review. We've removed the newly added `LocustConfiguration` object and use alternate ways to get same information from users using existing `environmentVariables`. There are no other modifications/additions

2024-05-08 01:37 UTC, mikekistler requested changes
This issue was raised in the API review but appears to be not addressed.

2024-05-08 01:37 UTC, mikekistler commented on specification/loadtestservice/data-plane/Microsoft.LoadTestService/preview/2024-03-01-preview/loadtestservice.json
> +          "description": "Test run statistics.",
Please document the key for testRunStatistics

2024-05-08 02:20 UTC, weidongxu-microsoft commented
> @mikekistler @weidongxu-microsoft Requesting re-review. We've removed the newly added `LocustConfiguration` object and use alternate ways to get same information from users using existing `environmentVariables`. There are no other modifications/additions

Can you elaborate a bit more on this "alternate ways"? E.g. any example file that include such info in `environmentVariables`?

2024-05-08 05:37 UTC, Harshan01 commented
> > @mikekistler @weidongxu-microsoft Requesting re-review. We've removed the newly added `LocustConfiguration` object and use alternate ways to get same information from users using existing `environmentVariables`. There are no other modifications/additions
> 
> Is this "alternate ways" demonstrated anywhere? E.g. any example file that include such info in `environmentVariables`?

@weidongxu-microsoft These are standard environment variables which the Locust framework supports
https://docs.locust.io/en/stable/configuration.html#all-available-configuration-options

We will be adding these information in our product docs and tutorials. Should these be added in REST API examples as well?

2024-05-08 05:49 UTC, weidongxu-microsoft commented
> We will be adding these information in our product docs and tutorials (not yet public since these are preview). Should these be added in REST API examples as well?

You don't have to. But it still recommend to provide similar info to your REST API users. Maybe just an aka link to the doc site.

2024-05-08 05:59 UTC, Harshan01 commented
> > We will be adding these information in our product docs and tutorials (not yet public since these are preview). Should these be added in REST API examples as well?
> 
> You don't have to. But it still recommended to provide similar info to your REST API users. Maybe just an aka link to the doc site.

Would it be possible to add this link once the docs are published?

2024-05-08 06:09 UTC, weidongxu-microsoft commented
> Would it be possible to add this link once the docs are published?

Yes, that is fine.

2024-05-16 14:12 UTC, mikekistler approved these changes
Looks good! 👍

2024-05-22 06:03 UTC, merged