Change connection-string to be object and support making severname, d…
Azure/azure-rest-api-specs pull request #2834
Opened 2018-04-08 07:30 UTC by zhanyu2014

…atabasename visible to customers

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-04-08 07:30 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=2834) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=2834) before we can accept your contribution.<br/><br/>:x: zhanyu2014 [sign now](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=2834)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-rest-api-specs?pullRequest=2834) it.</sub>

2018-04-08 07:32 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-04-08 07:33 UTC, AutorestCI commented
# Automation for azure-libraries-for-java

2018-04-08 07:34 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-04-08 07:34 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-04-09 18:24 UTC, marstr requested changes
The descriptions should really be updated to mention that there is a non-trivial string type.

2018-04-09 22:34 UTC, marstr commented
@AutorestCI help

2018-04-09 22:34 UTC, AutorestCI commented
This is what I can do:
- `rebuild`
- `regenerate`
- `help` : this help message

2018-04-09 22:34 UTC, AutorestCI commented
This is what I can do:
- `rebuild`
- `regenerate`
- `help` : this help message

2018-04-09 22:34 UTC, AutorestCI commented
This is what I can do:
- `rebuild`
- `regenerate`
- `help` : this help message

2018-04-09 22:34 UTC, AutorestCI commented
This is what I can do:
- `rebuild`
- `regenerate`
- `help` : this help message

2018-04-09 22:35 UTC, marstr commented
@AutorestCI rebuild go

2018-04-09 22:42 UTC, marstr commented
Ah, another thing that I should point out @zhanyu2014 is that it says your CLA hasn't been signed. I assume you're a Microsoft employee, so you should go to http://opensource and join the appropriate organizations.

2018-04-10 03:43 UTC, zhanyu2014 commented on specification/datafactory/resource-manager/Microsoft.DataFactory/preview/2017-09-01-preview/entityTypes/LinkedService.json
> +          "description": "The encrypted credential used for authentication. Credentials are encrypted using the integration runtime credential manager. Type: string (or Expression with resultType str
Description is updated.

2018-04-10 20:59 UTC, marstr commented
Adding the ARM review label before I forget.

2018-04-10 23:10 UTC, jhendrixMSFT commented
@AutorestCI regenerate azure-sdk-for-go

2018-04-13 16:49 UTC, marstr commented
I'd like to remind you @zhanyu2014 that our License CLA bot still says that you are not appropriately documented as a Microsoft Employee. I cannot merge this PR until your CLA is recognized.

2018-04-16 23:45 UTC, marstr commented
Please acknowledge, @zhanyu2014. If I see no response, I'll have to close this PR as inactive.

2018-04-17 02:05 UTC, zhanyu2014 commented
The related SLA has been validated and passed, related comments in change has been resolved, please help continue to finish this review and merge it. @marstr, @jianghaolu.

2018-04-17 17:08 UTC, marstr commented
The only thing remaining now is @ravbhatnagar or another ARM representative to sign off. Thanks for signing the CLA, @zhanyu2014.

2018-04-19 19:50 UTC, marstr approved these changes

2018-04-19 19:51 UTC, marstr commented
Ready for me to merge, @zhanyu2014?

2018-04-20 05:45 UTC, zhanyu2014 commented
@marstr, please help us finish the code merge.

2018-04-20 17:10 UTC, merged