[Data Factory]Add schema mapping for hierarchical data
Azure/azure-rest-api-specs pull request #2906
Opened 2018-04-19 09:12 UTC by iamapi

2018-04-19 09:15 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-04-19 09:16 UTC, AutorestCI commented
# Automation for azure-libraries-for-java

2018-04-19 09:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-04-19 09:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-04-19 16:36 UTC, lmazuel commented on specification/datafactory/resource-manager/Microsoft.DataFactory/preview/2017-09-01-preview/entityTypes/Pipeline.json
> +        },
Could you update or add an example for that?

2018-04-24 15:46 UTC, lmazuel commented on specification/datafactory/resource-manager/Microsoft.DataFactory/preview/2017-09-01-preview/entityTypes/Pipeline.json
> +        },
I meant, x-ms-example, like this:
https://github.com/iamapi/azure-rest-api-specs/tree/a3c2bff7ee233f1de44032b1fccc27450874c77f/specification/datafactory/resource-manager/Microsoft.DataFactory/preview/2017-09-01-preview/examples

2018-04-24 15:47 UTC, lmazuel requested changes

2018-04-24 15:47 UTC, lmazuel commented on specification/datafactory/resource-manager/Microsoft.DataFactory/preview/2017-09-01-preview/entityTypes/Pipeline.json
> +          "description": "Column mappings. Example: \"UserId: MyUserId, Group: MyGroup, Name: MyName\" Type: string (or Expression with resultType string)."
I meant, x-ms-example, like this:
https://github.com/iamapi/azure-rest-api-specs/tree/a3c2bff7ee233f1de44032b1fccc27450874c77f/specification/datafactory/resource-manager/Microsoft.DataFactory/preview/2017-09-01-preview/examples

2018-05-21 19:56 UTC, lmazuel commented
I'm about to close this PR for inactivity. Friendly reminder. Thank you.

2018-05-21 23:04 UTC, hvermis commented
@lmazuel Please wait for couple days. I think our China team is OOF

2018-06-06 07:14 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-06-08 18:22 UTC, lmazuel approved these changes

2018-06-08 18:22 UTC, merged