[DO NOT MERGE] Update jobs.json to latest generated swagger file as well as it's updated examples
Azure/azure-rest-api-specs pull request #2909
Opened 2018-04-19 20:29 UTC by johnpaulkee

# Summary

Updated sql readme.md to include jobs.json where necessary (will need confirmation if this is correctly placed)

Regenerated swagger to include job step and target executions, sku name and capacity support in agent createOrUpdate and get, as well as filter for top executions.

Job examples were updated to reflect correct json request and response paramters for agent and target group.

# Review checklist

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
- [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

( I ran this: oav validate-spec jobs.json --azure-validator and it gave no errors were found )

2018-04-19 20:32 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-04-19 20:36 UTC, AutorestCI commented
# Automation for azure-libraries-for-java

2018-04-19 20:36 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-04-19 20:42 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-04-19 23:31 UTC, hovsepm commented
```
  "id": "1026",
  "code": "TypeChanged",
  "message": "The new version has a different type 'integer' than the previous one 'string'.",
  "jsonref": "#/paths/~1subscriptions~1{subscriptionId}~1resourceGroups~1{resourceGroupName}~1providers~1Microsoft.Sql~1servers~1{serverName}~1jobAgents~1{jobAgentName}~1executions/get/$skip",
  "json-path": "#/paths/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/jobAgents/{jobAgentName}/executions/get/$skip",
  "type": "Error"
```

You are introducing breaking changes to all the generated client SDKs. Should this be combined with API version bump PR?

2018-04-19 23:43 UTC, johnpaulkee commented
@hovsepm I think it's fine to keep this breaking change, but I think before we merge this PR I'll wait for @jaredmoo to sign off on this too since he's almost back from vacation.

2018-04-20 18:04 UTC, jaredmoo commented
This API is not yet published in the SDK, so there is technically no breaking change here.

2018-04-20 18:07 UTC, jaredmoo requested changes
Looks great, just undo readme.md plz

2018-04-20 18:07 UTC, jaredmoo commented on specification/sql/resource-manager/readme.md
> +- Microsoft.Sql/preview/2017-03-01-preview/jobs.json
Please don't add to readme.md until we are ready to publish SDK.

2018-04-20 19:41 UTC, johnpaulkee commented
Undid readme.md, updating title to remove do not merge.

2018-04-20 19:43 UTC, jaredmoo approved these changes
Thanks!

2018-04-24 00:31 UTC, jaredmoo commented
It has been reviewed internally by email and already lit up, but I don't think @ravbhatnagar has explicitly approved on github.

2018-04-24 17:59 UTC, hovsepm commented
@ravbhatnagar could you take a look to the entire swagger? We never got a sign-off from ARM.

2018-04-25 22:46 UTC, ravbhatnagar commented on specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/jobs.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/jobAgents/{jobAgentName}/jobs/{jobName}/executions/{jobExecutionId}/steps/{stepNam
GET on /targets or /steps returns the same entity - JobExecution?

2018-04-26 22:13 UTC, ravbhatnagar commented
Signing off!

2018-04-26 23:14 UTC, hovsepm commented
@johnpaulkee @jaredmoo Please add the readme.md changes back and keep this PR open until your service will be deployed and SDK's could be generated.

2018-04-26 23:16 UTC, hovsepm commented
Also please fix linter error - https://travis-ci.org/Azure/azure-rest-api-specs/jobs/369280805

2018-04-26 23:25 UTC, hovsepm commented
Please fix sample issues reported in sample validation - https://travis-ci.org/Azure/azure-rest-api-specs/jobs/369280815

2018-04-27 00:34 UTC, jaredmoo commented
The linter error is expected. Operation API is defined in a different file (operations.json)

The `Missing required property: password` model errors are all bugs in validator. "Password" is a required write-only property and it is intentionally null in responses.

The tablename errors (e.g. https://travis-ci.org/Azure/azure-rest-api-specs/jobs/369280815#L900 ) might be legit. @johnpaulkee I'll let you check it out.

2018-04-27 00:40 UTC, jaredmoo commented
Filed https://github.com/Azure/oav/issues/239 for the OAV false positive.

2018-05-17 19:05 UTC, johnpaulkee commented
I've also removed [Do not merge] from the title as we're intending on checking this in since we're getting close to public preview and we've received ARM sign off.

2018-05-17 19:08 UTC, jaredmoo approved these changes
Minor comments. Thanks!

2018-05-17 19:10 UTC, jaredmoo commented on specification/sql/resource-manager/readme.md
> + - New SQL database agent APIs
In other words: please delete the new line 54 & 55 :)

2018-05-17 20:10 UTC, johnpaulkee commented on specification/sql/resource-manager/readme.md
> + - New SQL database agent APIs
You got it :)

2018-05-17 20:10 UTC, johnpaulkee commented on specification/sql/resource-manager/readme.md
> +- Microsoft.Sql/preview/2017-03-01-preview/jobs.json
Will update to be in alphabetical order.

2018-05-17 20:16 UTC, johnpaulkee commented
Updated based on feedback from @jaredmoo.
@hovsepm when you get a chance can you review once more?
We're ready to publish this :)

2018-05-17 20:42 UTC, hovsepm approved these changes

2018-05-17 20:42 UTC, merged