Network 2018 04 01
Azure/azure-rest-api-specs pull request #2934
Opened 2018-04-24 00:33 UTC by MikhailTryakhov

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-04-24 00:36 UTC, MikhailTryakhov commented
+@dsgouda

2018-04-24 00:52 UTC, AutorestCI commented
# Automation for azure-libraries-for-java

2018-04-24 01:08 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-04-24 01:30 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-04-24 01:46 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-04-24 15:29 UTC, dsgouda commented on specification/network/resource-manager/Microsoft.Network/stable/2018-02-01/ddosProtectionPlan.json
> +      "description": "A DDoS protection plan in a resource group.",
@MikhailTryakhov please undo any changes to the 2018-02-01 directory files.

2018-04-24 15:50 UTC, lmazuel requested changes

2018-04-24 15:50 UTC, lmazuel commented on specification/network/resource-manager/Microsoft.Network/stable/2018-04-01/applicationSecurityGroup.json
> +    "version": "2018-02-01"
Invalid ApiVersion for this folder. Same pattern applies to all files that are currently 2018-02-01 if necessary (don't touch VMSS files)

2018-04-24 19:03 UTC, MikhailTryakhov commented
@dsgouda  @lmazuel fixed requested changes. please review

2018-04-24 21:25 UTC, dsgouda commented
@lmazuel nice catch!
Any other comments I might have missed?

2018-04-24 21:30 UTC, dsgouda approved these changes
LGTM

2018-04-24 21:31 UTC, dsgouda commented
@MikhailTryakhov once @lmazuel approves we're good to merge

2018-04-24 22:15 UTC, MikhailTryakhov commented
Thanks @dsgouda. Can we create May branch right after that?
@lmazuel to make review easier. I've changed a version from 2018-02-01 to 2018-04-01 in all files of network branch except VMSS (2 files). Please let me know if there something else to change

2018-04-25 19:32 UTC, lmazuel commented on specification/network/resource-manager/Microsoft.Network/stable/2018-04-01/examples/ApplicationGatewayAvailableSslOptionsGet.json
> +    "api-version": "2018-02-01",
Please update ApiVersion of examples as well

2018-04-25 19:34 UTC, lmazuel approved these changes
I approve to unlock, since last thing is a detail, but api-version of example needs to be in sync of the Swagger content.

2018-04-25 20:54 UTC, merged