[VideoTranslation] Initial add TypedSpec and swagger
Azure/azure-rest-api-specs pull request #29572
Opened 2024-06-25 08:10 UTC by DapengLi2016

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

2024-06-25 17:24 UTC, mikeharder commented on specification/cognitiveservices/VideoTranslation/.gitignore
You shouldn't need this

2024-06-25 17:29 UTC, mikeharder commented
All the errors in check `TypeSpec Validation` are actually caused by the changes under folder `VideoTranslation`.  Start by fixing this error:

```
tspconfig.yaml must define the following property:

linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
```

https://dev.azure.com/azure-sdk/public/_build/results?buildId=3904744&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=0f4aa080-c997-58ca-481c-4930865ae0f8&l=1219

After this, I also think you have some formatting errors in your tsp files.

2024-06-25 17:29 UTC, mikeharder requested changes, later dismissed
Remove .gitignore

2024-06-27 20:30 UTC, allenjzhang commented on specification/cognitiveservices/VideoTranslation/main.tsp
> +// alias ops = Azure.Core.StandardResourceOperations;
nit: remove

2024-06-28 14:44 UTC, mikekistler commented
This API version was reviewed and approved in private repo PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/18399

2024-09-11 02:44 UTC, mikekistler approved these changes
Looks good. 👍

2024-09-11 04:40 UTC, weidongxu-microsoft commented on specification/cognitiveservices/Speech.VideoTranslation/main.tsp
> +  speakerCount?: int32;
nit, what exactly this is? "number of speakers in the video"?

2024-09-11 04:40 UTC, weidongxu-microsoft commented on specification/cognitiveservices/Speech.VideoTranslation/main.tsp
> +  subtitleMaxCharCountPerSegment?: int32;
What is the Char? unicode16? unicode8? or other encoding?

2024-09-11 06:27 UTC, weidongxu-microsoft approved these changes

2024-09-11 06:48 UTC, merged