SnapToRoads and RouteRange 2024-07-01-preview
Azure/azure-rest-api-specs pull request #29919
Opened 2024-07-19 05:33 UTC by koyasu221b

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

2024-07-19 15:20 UTC, mikekistler requested changes
I found a couple small problems. Pls fix and then tag me to re-review.

2024-07-19 15:20 UTC, mikekistler commented on specification/maps/data-plane/Route/preview/2024-07-01-preview/route.json
> +          "format": "date-time",
One more. This is the last one I'll flag. Pls check for and fix any others.
```suggestion
          "type": "string",
          "format": "date-time",
```

2024-07-19 15:20 UTC, mikekistler commented on specification/maps/data-plane/Route/preview/2024-07-01-preview/route.json
> +          "format": "date-time",
Here too. Why were these removed?
```suggestion
          "type": "string",
          "format": "date-time",
```

2024-07-19 15:20 UTC, mikekistler commented on specification/maps/data-plane/Route/readme.md
> +  - preview/2024-06-01-preview/route.json
I think this will fix your Avocado errors.
```suggestion
  - preview/2024-07-01-preview/route.json
```

2024-07-22 18:31 UTC, mikekistler approved these changes
Looks good! 👍

2024-07-22 20:26 UTC, FarazGIS approved these changes

2024-08-10 01:02 UTC, FarazGIS commented on specification/maps/data-plane/Route/preview/2024-07-01-preview/route.json
> +        "axleCount": {
@koyasu221b axleCount is not support by Route Matrix v2. Can you check and remove?

2024-10-30 13:07 UTC, merged