Added missing APIs to complete RP-ARM SLA
Azure/azure-rest-api-specs pull request #3031
Opened 2018-05-07 21:14 UTC by akumardu

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-05-07 21:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-05-07 21:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-05-07 21:17 UTC, AutorestCI commented
# Automation for azure-libraries-for-java

2018-05-07 21:58 UTC, jianghaolu commented on specification/iothub/resource-manager/Microsoft.Devices/stable/2018-04-01/examples/iothub_testallroutes.json
> +                "isEnabled": "true"
This should be a boolean.

2018-05-07 21:59 UTC, jianghaolu commented on specification/iothub/resource-manager/Microsoft.Devices/stable/2018-04-01/iothub.json
> +
Remove empty lines.

2018-05-07 22:04 UTC, jianghaolu requested changes
Couple minor issues - please take a look.

2018-05-08 23:04 UTC, akumardu commented on specification/iothub/resource-manager/Microsoft.Devices/stable/2018-04-01/examples/iothub_testallroutes.json
> +                "isEnabled": "true"
Ack.

2018-05-09 18:47 UTC, jianghaolu requested changes

2018-05-09 18:47 UTC, jianghaolu commented on specification/iothub/resource-manager/Microsoft.Devices/stable/2018-04-01/examples/iothub_testallroutes.json
> +                "endpointNames": ["id1", "id2"],
Sorry for the late response. Here is another issue I found - this array is defined to have max length of 1: https://github.com/Azure/azure-rest-api-specs/pull/3031/files#diff-54dafbe4198f749bac837b913372bcddR2417

2018-05-09 22:15 UTC, jianghaolu commented on specification/iothub/resource-manager/Microsoft.Devices/stable/2018-04-01/examples/iothub_testnewroute.json
> +          "id2"
Thanks for addressing my comment - please also fix it here.

2018-05-09 23:35 UTC, jianghaolu commented on specification/iothub/resource-manager/Microsoft.Devices/stable/2018-04-01/examples/iothub_testallroutes.json
> +                "name": "Route id",
Name doesn't match requirement ^[A-Za-z0-9-._]{1,64}$: https://github.com/Azure/azure-rest-api-specs/pull/3031/files#diff-54dafbe4198f749bac837b913372bcddR2393

2018-05-09 23:35 UTC, jianghaolu commented on specification/iothub/resource-manager/Microsoft.Devices/stable/2018-04-01/examples/iothub_testnewroute.json
> +        "name": "Route id",
Same here

2018-05-10 21:12 UTC, jianghaolu approved these changes

2018-05-10 21:12 UTC, merged