Add Management Groups 2018-03-01-preview version
Azure/azure-rest-api-specs pull request #3064
Opened 2018-05-14 03:56 UTC by rajshah11

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-05-15 13:56 UTC, annatisch commented
Thanks @rajshah11 - could you take a look at the model validation errors:
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/378549766

2018-05-15 16:25 UTC, annatisch commented
@ravbhatnagar - looks like we have a new preview API for you to review :)
FYI @rajshah11

2018-05-17 22:10 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-05-17 22:11 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-05-17 22:11 UTC, AutorestCI commented
# Automation for azure-libraries-for-java

2018-05-17 22:13 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-05-18 07:17 UTC, ravbhatnagar commented
Looks good.

2018-05-18 18:08 UTC, annatisch requested changes
Some small fixes are needed:
- please remove all the newline characters from the end of descriptions.
- please make query parameters located on the method rather than client.
- please fix the last model validation error in the CI

2018-05-18 18:08 UTC, annatisch commented on specification/managementgroups/resource-manager/Microsoft.Management/preview/2018-03-01-preview/management.json
> +      "x-ms-parameter-location": "client"
The parameter location needs to be "method"

2018-05-18 18:08 UTC, annatisch commented on specification/managementgroups/resource-manager/Microsoft.Management/preview/2018-03-01-preview/management.json
> +      "x-ms-parameter-location": "client"
The parameter location needs to be "method"

2018-05-18 18:08 UTC, annatisch commented on specification/managementgroups/resource-manager/Microsoft.Management/preview/2018-03-01-preview/management.json
> +      "x-ms-parameter-location": "client"
The parameter location needs to be "method"

2018-05-18 18:08 UTC, annatisch commented on specification/managementgroups/resource-manager/Microsoft.Management/preview/2018-03-01-preview/management.json
> +      "x-ms-parameter-location": "client"
The parameter location needs to be "method"

2018-05-18 18:08 UTC, annatisch commented on specification/managementgroups/resource-manager/Microsoft.Management/preview/2018-03-01-preview/management.json
> +      "x-ms-parameter-location": "client"
The parameter location needs to be "method"

2018-05-18 18:08 UTC, annatisch commented on specification/managementgroups/resource-manager/Microsoft.Management/preview/2018-03-01-preview/management.json
> +      "x-ms-parameter-location": "client"
The parameter location needs to be "method"

2018-05-18 18:08 UTC, annatisch commented on specification/managementgroups/resource-manager/Microsoft.Management/preview/2018-03-01-preview/management.json
> +      "x-ms-parameter-location": "client"
The parameter location needs to be "method"

2018-05-18 20:12 UTC, annatisch commented on specification/managementgroups/resource-manager/Microsoft.Management/preview/2018-03-01-preview/management.json
> +        "x-ms-long-running-operation": true
@rajshah11 - can you confirm that this list operation is indeed also a long running operation?

2018-05-18 22:28 UTC, annatisch approved these changes

2018-05-18 22:30 UTC, merged