[Language] Restructure Language swagger files
Azure/azure-rest-api-specs pull request #31161
Opened 2024-10-22 22:09 UTC by bidisha-c

# Data Plane API Specification Update Pull Request

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

![spec_pr_review_workflow_diagram](https://github.com/Azure/azure-rest-api-specs/assets/4429827/5bb5e7ce-8aff-4dbb-a3f8-0d9b68fef5b1)

## API Info: The Basics

Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope

<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc:
* Updated paths:

### Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

### Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/pr-suppressions) 
to get approval.

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling

 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)

### Guidelines & Specifications

 * [Azure REST API Guidelines](https://aka.ms/azapi/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/azapi/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links

 * [Schedule a data plane REST API spec review](https://aka.ms/azsdk/onboarding/restapischedule)

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories) 
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

2024-10-22 23:50 UTC, heaths requested changes, later dismissed
What's the purpose of these changes? Just to better align with the TypeSpec migration? Relocating these files in `main` will break a lot of use cases including Azure SDKs - at least when we update references (but that can be fixed) - and likely Microsoft Learn docs.

If these are strictly to better compare with TypeSpec, I'd also recommend changing "-Authoring" directories to ".Authoring" to match with package names, which we more typically use "." in general naming.

2024-10-23 17:40 UTC, bidisha-c commented
@heaths  to give some context, since we already have separate api release schedules for Language, our generated API docs are not reflecting the correct API versions for each capability.  

So during the API review for the new API version we were asked to get this fixed. In an attempt to fix, that I submitted this PR to re-organize the swagger files according to the api grouping we will release. 
I will also update the related documentation/SDKs in a separate PR.

The organization we are proposing (after discussion with our internal team):
```
Language/AnalyzeConversations - Typespec project Language.Conversations
Language/AnalyzeText - Typespce project Language.AnalyzeText
Language/AnalyzeDocuments - Typespec project Language.AnalyzeDocuments
Language/AnalyzeConversations.Authoring (as suggested) Typespec project Language.AnalyzeConversations-authoring
Language/AnalyzeText.Authoring (as suggested) - Typespec project Language.AnalyzeText-authoring
Language/QuestionAnswering - not in typespec yet.
Language/QuestionAnswering.Authoring - not in type spec yet.
```
 
Adding @JeffreyRichter, @mikekistler @allenjzhang for their review/comments

2024-10-24 16:23 UTC, bidisha-c commented
@JeffreyRichter , yes, I am updating the typespecs as well to point to the correct swagger directory in this next iteration. 

The preview folder under Language shows up as there were 2 random files which were part of the preview folders, which I am assuming should not have been merged. They show up as removed as they are not moved anywhere. Rather they are deleted. 

 
1. oav
2. readme

2024-10-24 16:27 UTC, JeffreyRichter approved these changes
Great job! Thanks for doing this.

2024-11-23 02:01 UTC, bidisha-c commented
@heaths @mikekistler @allenjzhang,

As discussed in the last language API review here is the PR to separate the individual language APIs to enable independent release cadence. As expected there are a lot of test and automation failures, Can you please help review and approve this? 
Once this PR is merged we will start to release the new beta SDKs. Also in case we need to update anywhere else, please share the pointers.

2025-07-28 21:36 UTC, heaths commented on specification/cognitiveservices/Language.Conversations/tspconfig.yaml
> +    output-file: "{azure-resource-provider-folder}/Language/AnalyzeConversations/{version-status}/{version}/analyzeconversations.json"
Why doesn't this one match the project name e.g., "Conversations" for "Language.Conversations"? The inconsistency might be confusing.

2025-08-07 18:31 UTC, bidisha-c commented on specification/cognitiveservices/Language.Conversations/tspconfig.yaml
> +    output-file: "{azure-resource-provider-folder}/Language/AnalyzeConversations/{version-status}/{version}/analyzeconversations.json"
Updating.

2025-08-08 18:36 UTC, heaths commented
This has been open for almost 2 years and suddenly there's more activity. @bidisha-c please let me know if/when you're expecting another review. Until then, I highly recommend making it a draft so we know it's not ready to review. There are clearly a lot of validation errors that need to be worked out yet.

2025-08-08 19:04 UTC, bidisha-c commented
> This has been open for almost 2 years and suddenly there's more activity. @bidisha-c please let me know if/when you're expecting another review. Until then, I highly recommend making it a draft so we know it's not ready to review. There are clearly a lot of validation errors that need to be worked out yet.

@Heath we were blocked on this PR as we had many preview APIs which were not removed. As a result this restructure caused multiple validation failures. However, now we have deprecated all old previews and retiring them . I have merged the pr to remove all old preview APIs last week https://github.com/Azure/azure-rest-api-specs/pull/31781

So I have resumed this PR and it is ready for review 



We want to prioti

2025-08-08 19:13 UTC, bidisha-c commented
@heaths, @mikekistler, @JeffreyRichter 

I am looking for advise on how to fix the errors and merge this PR? 

For AnalyzeText and Conversations typespec project the change is basically to update the Typespec location to create the swaggers and update individual READMEs. 
 
But for the rest of the skills, we have a few missing old GA API versions in Typespec:

1. `QuestionAnswering` and `QuestionANswering.Authoring` - we are missing `2021-10-01` GA API in Typespec.  It was manually moved to the new structure
2. `Conversations` and `Conversations.Authoring` - `2022-05-01`  API is missing in Typespec. Also manually moved to the new folder structure

Now this is causing bunch of failures in validation. How do we handle this?

2025-08-08 22:09 UTC, heaths commented
If the old versions' swaggers are available and just aren't in the TypeSpecs, I'm in favor of bypassing those validation errors; however, @mikekistler and @JeffreyRichter are the ones on the breaking change board. This is just my $0.02, not that that's worth what it used to be.

2025-08-09 13:46 UTC, mikekistler approved these changes
This is just a reorg of the directory structure for Language.

Looks good. 👍

2025-08-11 22:29 UTC, bidisha-c commented
@mikekistler I am still not able to merge. It complains about missing Typespec for the older GA APIs missing for QuestionAnswering and Conversations.Authoring and Analyze-Text.Authoring. 
How do we handle these?

2025-08-11 22:43 UTC, heaths commented
I've overridden that Avocado error, but I'm concerned about the LintDiff error since the endpoint should be `{endpoint}` and not `{endpoint}/language`. Is generated code handling that correctly on the TypeSpecs, or is generated code still using the swaggers and you don't know? The emitters might make certain assumptions, right or wrong. If clients emitting based on the TypeSpec are working, it may be fine; though, I worry about other customers who might still use the swaggers.

2025-08-11 23:53 UTC, bidisha-c commented
@heath I did not follow your comment here but the endpoint is unchanged in the swagger.

<img width="544" height="155" alt="image" src="https://github.com/user-attachments/assets/6b69bc1c-5353-41c6-b3cb-18117dfe66ca" />


 

But for the lint diffs errors are only for the 2 old API versions which are missing either in Authoring or QuestionAnswering.

<img width="926" height="605" alt="image" src="https://github.com/user-attachments/assets/d6bdfb10-e4fb-4bc7-bc11-a5d2275ec2cb" />

2025-08-13 00:06 UTC, heaths commented
@mikekistler @johanste I don't remember who is supposed to approve suppressions. Is anyone on the REST API board?

Not sure about the other blocking issue mentioned in "sign off requirements".

2025-08-13 22:13 UTC, lmazuel commented
Adding @mikeharder and @weshaggard , it seems some of those issues are specific to v1 to v2 migration.

2025-08-14 04:17 UTC, mikeharder commented
@bidisha-c: Please update your branch with the latest changes from main and resolve conflicts, so we can see the latest check results.

2025-08-14 17:32 UTC, bidisha-c commented
@mikeharder I am still not able to merge

2025-08-14 20:13 UTC, mikeharder commented
@JeffreyRichter, @qiaozha: If this spec is being reorganized, should it convert directly to folder structure v2?  It's currently using v1.

2025-08-14 20:36 UTC, mikeharder commented
For TypeSpecRequirement: https://github.com/Azure/azure-rest-api-specs/wiki/TypeSpec-Requirement#renaming-specs

2025-08-14 20:37 UTC, mikeharder commented
LintDiff: https://github.com/Azure/azure-rest-api-specs/wiki/Swagger-LintDiff#adding-scoped-suppressions

2025-08-15 12:52 UTC, qiaozha commented
> @JeffreyRichter, @qiaozha: If this spec is being reorganized, should it convert directly to folder structure v2? It's currently using v1.

There're two problems here that is violating the folder structure v2. 
1. It's not unifying the TypeSpec and swagger into the same service folder, like ./specification/cognitiveservices/data-plane/{serviceName}
2. In folder structure v2, I don't think we support service group concept, which means the Language folder in ./specification/cognitiveservices/data-plane/Language/{serviceName} should not be supported.  If you have to have a service group to indicate that they are somewhat related, I'd suggest to use Language as the serviceName prefix instead. 

@JeffreyRichter could you double confirm here? I see you have approved this in last October, which should probably happened before this folder structure v2 guideline being finalized.

2025-08-15 17:28 UTC, bidisha-c commented
> > @JeffreyRichter, @qiaozha: If this spec is being reorganized, should it convert directly to folder structure v2? It's currently using v1.
> 
> There're two problems here that is violating the folder structure v2.
> 
> 1. It's not unifying the TypeSpec and swagger into the same service folder, like ./specification/cognitiveservices/data-plane/{serviceName}
> 2. In folder structure v2, I don't think we support service group concept, which means the Language folder in ./specification/cognitiveservices/data-plane/Language/{serviceName} should not be supported.  If you have to have a service group to indicate that they are somewhat related, I'd suggest to use Language as the serviceName prefix instead.
> 
> @JeffreyRichter could you double confirm here? I see you have approved this in last October, which should probably happened before this folder structure v2 guideline being finalized.

This is our current folder structure proposed in this PR is 

Typespec:
`/specifications/cognitiveservices/Language.Conversations/`
`/specifications/cognitiveservices/Language.AnalyzeText/`
...

data-plane
`/specifications/cognitiveservices/data-plane/Language/Language.Conversations`
`/specifications/cognitiveservices/data-plane/Language/Language.AnalyzeText`
...

When you mentioned to move under  `./specification/cognitiveservices/data-plane/{serviceName}`, does that mean we move the typespec and swagger under same structure?

Typespec:
`/specifications/cognitiveservices/Language/Language.Conversations/*.tsp` files (all typespec files)
`/specifications/cognitiveservices/Language/Language.Conversations/stable/**/*.json` files (swaggers)

2025-08-15 18:20 UTC, JeffreyRichter commented
The folder structure is supposed to be /specifications/cognitiveservices/data-plane/**_<public-facing Azure service name>_**
So, how do these services appear to customers in the doc TOC?
I'm sure we don't call it "Azure Language Language Conversations".
Is it Azure Language Conversations? if so, then we want:
   /specifications/cognitiveservices/data-plane/**_LanguageConversations_**
   /specifications/cognitiveservices/data-plane/**_LanguageAnalyzeText_**

How do customers discover these services and learn their name when then then use for docs and SDK discovery?
This is how we also do repo folder discovery.

2025-08-15 18:48 UTC, bidisha-c commented
> Azure Language Conversations

The unified service is named as "Azure AI Language" https://learn.microsoft.com/en-us/azure/ai-services/language-service/overview
- Under this we have Conversations, Analyze-Text, QuestionAnswering etc.

2025-08-15 19:16 UTC, mikeharder commented
> When you mentioned to move under ./specification/cognitiveservices/data-plane/{serviceName}, does that mean we move the typespec and swagger under same structure?

@bidisha-c: Yes.  You can use our sample as an example:

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/widget/data-plane/WidgetAnalytics

Note you may need to update paths in your `tspconfig.yaml` after moving the file.

2025-10-07 17:47 UTC, sarkar-rajarshi commented
@JeffreyRichter @mikeharder @qiaozha  the restructuring has now been done following the v2 folder structure. Now the Language services have structured as

/specification/cognitiveservices/data-plane/**LanguageAnalyzeConversations**
/specification/cognitiveservices/data-plane/**LanguageAnalyzeConversationsAuthoring**
/specification/cognitiveservices/data-plane/**LanguageAnalyzeDocuments**
/specification/cognitiveservices/data-plane/**LanguageAnalyzeText**
/specification/cognitiveservices/data-plane/**LanguageAnalyzeTextAuthoring**
/specification/cognitiveservices/data-plane/**LanguageQuestionAnswering**
/specification/cognitiveservices/data-plane/**LanguageQuestionAnsweringAuthoring**

2025-10-07 17:51 UTC, sarkar-rajarshi commented
All breaking changes are from swaggers located under new locations

2025-10-08 20:17 UTC, kristapratico approved these changes
Approving for codeowners based on REST API board approvals.

2025-10-08 20:32 UTC, heaths approved these changes

2025-10-08 21:47 UTC, mikeharder approved these changes

2025-10-08 22:02 UTC, MattGal approved these changes

2025-10-08 22:36 UTC, merged