[Contoso.Management] Use ArmResourcePatchSync instead of ArmCustomPatchSync
Azure/azure-rest-api-specs pull request #31279
Opened 2024-10-28 22:28 UTC by mikeharder

2024-10-28 22:32 UTC, MUHAMMADIHSANALIKAP approved these changes
Please update my Trading Account's details as I'm suffering a lot and don't have any access to my Broker's account number and details?????
MUHAMMAD IHSAN ALI.

2024-10-29 00:27 UTC, markcowl requested changes, later dismissed
We shoudl remove this setting, to avoid PatchBodyParametersSchema issues: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/contosowidgetmanager/Contoso.Management/tspconfig.yaml#L12

2024-10-29 19:06 UTC, markcowl approved these changes

2024-10-29 19:12 UTC, mikeharder commented
@allenjzhang: Do you agree this code is better for the sample?

2024-10-30 21:54 UTC, allenjzhang approved these changes

2024-10-30 23:32 UTC, merged