Adding new value to VA baseline name
Azure/azure-rest-api-specs pull request #3143
Opened 2018-05-27 06:39 UTC by yaakoviyun

Adding new value to VA baseline name

2018-05-27 06:41 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-05-27 06:46 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-05-27 06:47 UTC, AutorestCI commented
# Automation for azure-libraries-for-java

2018-05-27 06:47 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-05-27 06:52 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-05-28 09:41 UTC, yaakoviyun commented
@marstr  - can you merge?

2018-05-30 06:44 UTC, yaakoviyun commented on specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/databaseVulnerabilityAssessmentBaselines.json
> +            "description": "The name of the vulnerability assessment rule baseline (default implies a baseline on a database level rule and master for server level rule).",
currently we don't support a "server level" configuration. In the meantime, the user can set a server rule baseline in the context of a single database

2018-05-30 17:17 UTC, marstr approved these changes

2018-05-30 17:18 UTC, marstr commented
These changes seem small enough that they don't warrant ARM review. @jaredmoo, @yaakoviyun, anything else that needs to happen before this is merged?

2018-05-30 17:36 UTC, jaredmoo commented
Before your merge, let me chat with Yaakov and check that I agree with this design :)

2018-05-30 18:02 UTC, jaredmoo commented on specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/databaseVulnerabilityAssessmentBaselines.json
> +            "description": "The name of the vulnerability assessment rule baseline (default implies a baseline on a database level rule and master for server level rule).",
Ok, so if I set the master baseline for one database, that doesn't affect the master baseline for another database, is that right? When I look at my VA scan results, how do I know whether I need to update the current or master baseline?

2018-05-30 18:17 UTC, yaakoviyun commented
Jared, you are correct.

With regard to choosing the baseline target, it can be found in the scan results file.
Each check (rule) result has a property that indicates whether it is a database level or server level .
Sent from Outlook
________________________________
מאת: Jared Moore <notifications@github.com>
‏‏נשלח: יום רביעי 30 מאי 2018 21:02:40
‏‏אל: Azure/azure-rest-api-specs
עותק: Yaakov Iyun; Mention
‏‏נושא: Re: [Azure/azure-rest-api-specs] Adding new value to VA baseline name (#3143)


@jaredmoo commented on this pull request.

________________________________

In specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/databaseVulnerabilityAssessmentBaselines.json<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F3143%23discussion_r191866154&data=02%7C01%7Cyaiyun%40microsoft.com%7Ca0abf34101404117dcc208d5c65789c9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636633001633703508&sdata=14a%2B9NR1c9uZT1TWpT%2F03OLYSwziFf3gawlZ%2BYU87Uw%3D&reserved=0>:

> @@ -140,11 +141,12 @@
           {
             "name": "baselineName",
             "in": "path",
-            "description": "The name of the vulnerability assessment rule baseline.",
+            "description": "The name of the vulnerability assessment rule baseline (default implies a baseline on a database level rule and master for server level rule).",


Ok, so if I set the master baseline for one database, that doesn't affect the master baseline for another database, is that right? When I look at my VA scan results, how do I know whether I need to update the current or master baseline?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F3143%23discussion_r191866154&data=02%7C01%7Cyaiyun%40microsoft.com%7Ca0abf34101404117dcc208d5c65789c9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636633001633703508&sdata=14a%2B9NR1c9uZT1TWpT%2F03OLYSwziFf3gawlZ%2BYU87Uw%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALNguT5_whwxDmouhjQvIoNdxI1n4jomks5t3t7AgaJpZM4UPKus&data=02%7C01%7Cyaiyun%40microsoft.com%7Ca0abf34101404117dcc208d5c65789c9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636633001633703508&sdata=UpIWsbxUciKZhjpuMUnBKTUQY6olR04W7YMc4sdq5MM%3D&reserved=0>.

2018-05-30 18:21 UTC, jaredmoo approved these changes
Sounds good

2018-05-30 18:23 UTC, jaredmoo commented on specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/databaseVulnerabilityAssessmentBaselines.json
> +              "Default"
I think this should be 'master' , 'default'. The C# code generator should capitalize the first letter for the enum name when it generated code.

2018-05-30 18:23 UTC, jaredmoo commented on specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/databaseVulnerabilityAssessmentBaselines.json
> +    "Resource": {
Please remove Resource & ProxyResource definitions

2018-05-30 18:23 UTC, jaredmoo commented on specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/databaseVulnerabilityAssessmentBaselines.json
> +          "$ref": "#/definitions/ProxyResource"
Please undo this, the common/v1 definition should be used

2018-05-30 18:24 UTC, jaredmoo requested changes
Overall looks good, minor changes needed

2018-05-31 06:32 UTC, jaredmoo approved these changes

2018-05-31 06:41 UTC, yaakoviyun commented
@marstr , can you merge?

2018-05-31 16:20 UTC, merged