[Azure Maps] Traffic Incident 2025-04-01
Azure/azure-rest-api-specs pull request #31578
Opened 2024-11-16 01:03 UTC by miaxzhitong

# Data Plane API Specification Update Pull Request

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

![spec_pr_review_workflow_diagram](https://github.com/Azure/azure-rest-api-specs/assets/4429827/5bb5e7ce-8aff-4dbb-a3f8-0d9b68fef5b1)

## API Info: The Basics

Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope

<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc:
* Updated paths:

### Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

### Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/pr-suppressions) 
to get approval.

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling

 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)

### Guidelines & Specifications

 * [Azure REST API Guidelines](https://aka.ms/azapi/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/azapi/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links

 * [Schedule a data plane REST API spec review](https://aka.ms/azsdk/onboarding/restapischedule)

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories) 
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

2025-01-07 03:48 UTC, dubiety commented on specification/maps/data-plane/Traffic/stable/2025-01-01/traffic.json
> +      "description": "These are the [Microsoft Entra OAuth 2.0](https://docs.microsoft.com/azure/active-directory/develop/v1-overview) Flows. When paired with [Azure role-based access](https://docs.m
`Microsoft Entra OAuth 2.0` link is now directed to <https://learn.microsoft.com/en-us/entra/identity-platform/v2-overview>. I suggest updating the link directly to the new link

2025-01-07 03:55 UTC, dubiety commented on specification/maps/data-plane/Traffic/stable/2025-01-01/traffic.json
> +            "$ref": "../../../Common/preview/1.0/common.json#/responses/default"
Why do we use `preview/1.0` here but not `stable/2023-06-01`? Is there any blocker?

2025-01-10 21:10 UTC, mikekistler requested changes
I left comments on a few minor problems -- should be very easy to fix.

2025-01-10 21:10 UTC, mikekistler commented on specification/maps/data-plane/Traffic/stable/2025-01-01/traffic.json
> +          "description": "Specifies the type of incident. \n\n• Accident \n\n• Congestion \n\n• DisabledVehicle \n\n• MassTransit \n\n• Miscellaneous \n\n• OtherNews \n\n• PlannedEvent \n\n• RoadHaza
Should this field be an enum? It can stay as "type: string" but the values can be defined formally.

2025-01-10 21:10 UTC, mikekistler commented on specification/maps/data-plane/Traffic/stable/2025-01-01/traffic.json
> +      "default": "2025-01-01",
A required parameter or property should not specify a default.

2025-01-23 19:11 UTC, FarazGIS commented
@mikekistler Is there any other outstanding item we need to take care of before this can be ready to merge? As you know there was a separate conversation on the breaking change review, so I want to make sure we have all the feedback in this PR. Thank you!

2025-02-05 00:22 UTC, miaxzhitong commented on specification/maps/data-plane/Traffic/stable/2025-01-01/traffic.json
> +      "description": "These are the [Microsoft Entra OAuth 2.0](https://docs.microsoft.com/azure/active-directory/develop/v1-overview) Flows. When paired with [Azure role-based access](https://docs.m
thank for catching it! updated!

2025-02-05 00:22 UTC, miaxzhitong commented on specification/maps/data-plane/Traffic/stable/2025-01-01/traffic.json
> +            "$ref": "../../../Common/preview/1.0/common.json#/responses/default"
thanks for catching that! updated

2025-02-05 00:24 UTC, miaxzhitong commented on specification/maps/data-plane/Traffic/stable/2025-01-01/traffic.json
> +          "type": "number",
thanks for catching it! updated int64 as type

2025-02-05 00:24 UTC, miaxzhitong commented on specification/maps/data-plane/Traffic/stable/2025-01-01/traffic.json
> +          "type": "number",
thanks for catching that, use int32 as type

2025-02-05 00:32 UTC, miaxzhitong commented on specification/maps/data-plane/Traffic/stable/2025-01-01/traffic.json
> +          "description": "Specifies the type of incident. \n\n• Accident \n\n• Congestion \n\n• DisabledVehicle \n\n• MassTransit \n\n• Miscellaneous \n\n• OtherNews \n\n• PlannedEvent \n\n• RoadHaza
use IncidentTypeEnum

2025-02-27 17:26 UTC, miaxzhitong commented
/azp run

2025-03-17 17:32 UTC, FarazGIS approved these changes

2025-03-18 22:34 UTC, miaxzhitong commented
@mikekistler could you please help to review the changes? I have resolved those changes requested by you. Thanks so much!

2025-03-19 17:20 UTC, ismael-ms approved these changes

2025-03-19 17:31 UTC, FarazGIS commented
@mikekistler Your approval is required to unblock the PR since you requested changes which we have completed. Thank you!

![image](https://github.com/user-attachments/assets/125b8334-6144-4695-b6b3-37e2be9e2362)

2025-03-19 19:53 UTC, mikekistler approved these changes
Looks good. 👍

2025-03-19 20:10 UTC, merged