Add pagination to quantum
Azure/azure-rest-api-specs pull request #31747
Opened 2024-12-04 03:10 UTC by 04diiguyi

# Data Plane API Specification Update Pull Request

> [!TIP]
> Overwhelmed by all this guidance? See the `Getting help` section at the bottom of this PR description.

## PR review workflow diagram

Please understand this diagram before proceeding. It explains how to get your PR approved & merged.

![spec_pr_review_workflow_diagram](https://github.com/Azure/azure-rest-api-specs/assets/4429827/5bb5e7ce-8aff-4dbb-a3f8-0d9b68fef5b1)

## API Info: The Basics

Most of the information about your service should be captured in the issue that serves as your [*API Spec engagement record*](https://aka.ms/azsdk/onboarding/restapischedule).

* Link to API Spec engagement record issue:

Is this review for (select one):

- [ ] a private preview
- [ ] a public preview
- [ ] GA release

### Change Scope

<sup>This section will help us focus on the specific parts of your API that are new or have been modified. <br/>Please share a link to the design document for the new APIs, a link to the previous API Spec document (if applicable), and the root paths that have been updated. </sup>
* Design Document:
* Previous API Spec Doc:
* Updated paths:

### Viewing API changes

For convenient view of the API changes made by this PR, refer to the URLs provided in the table 
in the `Generated ApiView` comment added to this PR. You can use ApiView to show API versions diff. 

### Suppressing failures

If one or multiple validation error/warning suppression(s) is detected in your PR, please follow the 
[Swagger-Suppression-Process](https://aka.ms/pr-suppressions) 
to get approval.

## ❔Got questions? Need additional info?? We are here to help!

<details>
  <summary> Contact us!</summary>

The [Azure API Review Board](https://aka.ms/azsdk/onboarding/restapischedule) is dedicated to helping you create amazing APIs. You can read about our mission and learn more about our process on our [wiki](https://aka.ms/azsdk/onboarding/restapischedule).
* 💬 [Teams Channel](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
* 💌 [email](mailto://azureapirbcore@microsoft.com)

</details>

<details>
  <summary>Click here for links to tools, specs, guidelines & other good stuff</summary>

### Tooling

 * [Open API validation tools](https://aka.ms/swaggertools) were run on this PR. Go here to see [how to fix errors](https://aka.ms/ci-fix)
 * [Spectral Linting](https://github.com/Azure/azure-api-style-guide/blob/main/README.md)

### Guidelines & Specifications

 * [Azure REST API Guidelines](https://aka.ms/azapi/guidelines)
 * [OpenAPI Style Guidelines](https://aka.ms/azapi/style)
 * [Azure Breaking Change Policy](https://aka.ms/AzBreakingChangesPolicy)

### Helpful Links

 * [Schedule a data plane REST API spec review](https://aka.ms/azsdk/onboarding/restapischedule)

</details>

## Getting help

- First, please carefully read through this PR description, from top to bottom.
- If you don't have permissions to remove or add labels to the PR, request `write access` per [aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories](https://aka.ms/azsdk/access#request-access-to-rest-api-or-sdk-repositories) 
- To understand what you must do next to merge this PR, see the `Next Steps to Merge` comment. It will appear within few minutes of submitting this PR and will continue to be up-to-date with current PR state.
- For guidance on fixing this PR CI check failures, see the hyperlinks provided in given failure 
  and https://aka.ms/ci-fix.
- If the PR CI checks appear to be stuck in `queued` state, please add a comment with contents `/azp run`.
  This should result in a new comment denoting a `PR validation pipeline` has started and the checks should be updated after few minutes.
- If the help provided by the previous points is not enough, post to https://aka.ms/azsdk/support/specreview-channel and link to this PR.

2024-12-04 03:12 UTC, 04diiguyi commented
This PR is copied from PR:
https://github.com/Azure/azure-rest-api-specs-pr/pull/19707

2024-12-04 03:13 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[Microsoft.Quantum](https://apiview.dev/Assemblies/Review/bb87199124f84cb2b1c9424ba3cafb34?revisionId=8033f919ee104d22b12f8e7a99a43b19)

2025-02-11 21:30 UTC, mikekistler commented on specification/quantum/Quantum.Workspace/operations/sessions.tsp
> +    #suppress "@azure-tools/typespec-azure-core/use-standard-operations" """
@allenjzhang or @mario-guerra to review this new TypeSpec suppression.

2025-02-11 21:32 UTC, mikekistler approved these changes
Looks good for preview. 👍 

But pls wait for review by @allenjzhang or @mario-guerra on the TypeSpec suppression changes.

2025-02-12 01:17 UTC, weidongxu-microsoft commented on specification/quantum/Quantum.Workspace/operations/sessions.tsp
>      @operationId("SessionsJobs_List")
@allenjzhang If I remember correctly, use of `@operationId` is discouraged?

2025-02-12 22:48 UTC, 04diiguyi commented
> Looks good for preview. 👍
> 
> But pls wait for review by @allenjzhang or @mario-guerra on the TypeSpec suppression changes.

@mikekistler Could you please add APIStewardshipBoard-SignedOff label or you need to wait for feedbacks about TypeSpec supression changes? In addition, where can I get PublishToCustomers label? Thanks.

2025-02-14 22:10 UTC, allenjzhang reviewed
I have one comment on tspconfig.yaml you should fix.

2025-02-14 22:10 UTC, allenjzhang commented on specification/quantum/Quantum.Workspace/tspconfig.yaml
> +    default: "2024-10-01-preview"
I dont think hardcoding the versions here is the correct approach. The autorest emitter will emit multiple versions of swagger based on version and version-status automatically. By allowing emitter to do full emission, it will help reducing regressions as you evolve API in tsp. If other versions of swagger shows up in the changeset, then you probably have not applied the versioning decorators correctly. 

Can you remove line 6-9?

2025-02-14 22:10 UTC, allenjzhang commented on specification/quantum/Quantum.Workspace/operations/sessions.tsp
>      @operationId("SessionsJobs_List")
Correct. It is discouraged. However in Quantum cases they have multiple parents situation that we have not solved. It does provide an escape valve. So I can sign off.

2025-02-18 21:44 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/tspconfig.yaml
> +    default: "2024-10-01-preview"
Could you point me to the versioning of tsp since this PR creates a new version, but somehow, the older versions have issues related to tsp versioning. I do not think this is related to this version, do you think it is possible for me to add the default version using this new version and add back support of tsp for older version in another PR?

2025-03-05 03:47 UTC, weidongxu-microsoft commented on specification/quantum/Quantum.Workspace/main.tsp
> +  interface TopLevelItems {}
Why these empty `interface`?

2025-03-05 17:36 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/main.tsp
> +  interface TopLevelItems {}
The previous changes passed the typespec validation for versioning, however, there's a prerequisite for versioning in APIView that failed this PR. Mark Cowlishaw suggested APIView team to update their approach to get versioning, however, for now, he recommends me to fix on my side. So I am working with Mark to revise the spec to fix the issues.

2025-03-05 20:11 UTC, markcowl requested changes

2025-03-05 20:11 UTC, markcowl commented on specification/quantum/Quantum.Workspace/common/base-operations.tsp
> +@post
Operation templates can continue to be in the same namespace as before.  No need to change this

2025-03-05 20:11 UTC, markcowl commented on specification/quantum/Quantum.Workspace/common/versions.tsp
> +  @useDependency(Azure.Core.Versions.v1_0_Preview_1)
You should use Preview_2 version, as you were before.  Also, why remove the older versions?

2025-03-05 20:11 UTC, markcowl commented on specification/quantum/Quantum.Workspace/main.tsp
> +  interface Jobs extends Quantum.Workspace.Services.JobOperations {}
No, this entire usage of extends is the problem.  These operations don't need to move into a different namespace.

2025-03-05 20:11 UTC, markcowl commented on specification/quantum/Quantum.Workspace/operations/cost-estimates.tsp
> +namespace Quantum.Workspace.Services;
This does not need to change.

2025-03-05 20:11 UTC, markcowl commented on specification/quantum/Quantum.Workspace/operations/items.tsp
> +@parentResource(Quantum.Workspace.QuantumWorkspace)
You should be able to use just `QuantumWorkspace`, since it is defined in the parent namespace

2025-03-05 20:11 UTC, markcowl commented on specification/quantum/Quantum.Workspace/operations/items.tsp
> +namespace Quantum.Workspace.Services;
Note that these types can be defined in any namespace (say Quantum.Workspace).  Only the namespace of the operations needs to be Quantum.Workspace.Services

2025-03-05 20:11 UTC, markcowl commented on specification/quantum/Quantum.Workspace/operations/items.tsp
> +interface ItemsOperations {
This should be renamed to match the interface name from main.tsp.  The same should be done for all of these individual  interface definitions.  These interface definitions *do* need to be in the Quantum.Workspace.Services namespace

2025-03-05 20:11 UTC, markcowl commented on specification/quantum/Quantum.Workspace/main.tsp
> +  interface Sessions extends Quantum.Workspace.Services.SessionOperations {}
Remove every single one of these interface extends statements.

2025-03-05 22:31 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/main.tsp
> +  interface TopLevelItems {}
All the interfaces are removed in this file due to the namespace updates. The operations are defined in the other files now

2025-03-05 22:33 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/common/versions.tsp
> +  @useDependency(Azure.Core.Versions.v1_0_Preview_1)
Updated. The reason to remove the old versions is that, the typespec migration was done since 2024 version, and my change is the only one change after that version. We were recommended to only keep the version from migration and start adding versioning afterwards

2025-03-05 22:33 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/main.tsp
> +  interface Jobs extends Quantum.Workspace.Services.JobOperations {}
Fixed

2025-03-05 22:33 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/operations/items.tsp
> +@parentResource(Quantum.Workspace.QuantumWorkspace)
Updated

2025-03-05 22:34 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/operations/items.tsp
> +namespace Quantum.Workspace.Services;
Sure, I moved all the types to the common folder and only keep operators here so that the structure is clean

2025-03-05 22:34 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/operations/items.tsp
> +interface ItemsOperations {
Yes, updated

2025-03-05 22:34 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/main.tsp
> +  interface Sessions extends Quantum.Workspace.Services.SessionOperations {}
Removed

2025-03-05 22:45 UTC, markcowl submitted a review, later dismissed

2025-03-05 22:45 UTC, markcowl commented on specification/quantum/Quantum.Workspace/common/versions.tsp
>    @useDependency(DefaultAzureCoreVersion)
Note that, if you are getting rid of these old preview versions, you should delete the accompanying generated swagger and examples in the output directory

2025-03-05 22:45 UTC, markcowl commented on specification/quantum/Quantum.Workspace/common/models-storage.tsp
> +model BlobDetails {
Feels like this should be under some namespace

2025-03-05 23:05 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/common/models-storage.tsp
> +model BlobDetails {
Added

2025-03-05 23:05 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/common/versions.tsp
>    @useDependency(DefaultAzureCoreVersion)
Deleted

2025-03-06 01:59 UTC, weidongxu-microsoft commented on specification/quantum/Quantum.Workspace/common/models-items.tsp
> +model KeyValue<Value = string> {
Is it used somewhere? You may need a `@friendlyName` on this templated model to have it work properly in SDK codegen.

2025-03-06 02:01 UTC, weidongxu-microsoft commented on specification/quantum/Quantum.Workspace/common/models-items.tsp
> +  itemType: ItemType;
so, currently only the "name" property can be updated?

2025-03-06 02:06 UTC, weidongxu-microsoft commented on specification/quantum/Quantum.Workspace/common/modes-jobs.tsp
> +  metadata?: {};
`{}` would be a model without any property.

Do you want `Record<unknown>`?

2025-03-06 02:18 UTC, weidongxu-microsoft commented
Could you reply here or in issue, about your solution upon review meeting feedback?
https://github.com/Azure/azure-rest-api-specs-pr/issues/19740#issuecomment-2400812638

From the PR, I see `orderby` is still here.

2025-03-06 02:45 UTC, 04diiguyi commented
> Could you reply here or in issue, about your solution upon review meeting feedback? [Azure/azure-rest-api-specs-pr#19740 (comment)](https://github.com/Azure/azure-rest-api-specs-pr/issues/19740#issuecomment-2400812638)
> 
> From the PR, I see `orderby` is still here.

Thanks, I replied to the issue and copy the answer to here as well.

Probably want top rather than maxpagesize: We use top
Be very careful with orderby -- it can be very expensive. Sure, we still use orderby, Cosmos DB has support for orderby
Make sure parameter case is as defined in the API guidelines, and that parameters are treated case-sensitively. Confirmed
Filter syntax - maybe reuse the PowerFX filter library. We follow Odata guidelines and use odata libraries

2025-03-06 02:49 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/common/models-items.tsp
> +  itemType: ItemType;
I moved this piece of code from the original file to fulfill the namespace requirements.
Back to this question, yes

2025-03-06 02:51 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/common/models-items.tsp
> +model KeyValue<Value = string> {
No, I do not think so. Remove it

2025-03-06 02:54 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/common/modes-jobs.tsp
> +  metadata?: {};
The metadata is provided by users, it is a json object, we do not have any predefined properties.

2025-03-06 03:05 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/common/modes-jobs.tsp
> +  metadata?: {};
Sounds good. Update metadata and inputParams

2025-03-06 03:25 UTC, weidongxu-microsoft commented on specification/quantum/Quantum.Workspace/operations/items.tsp
> +    listv2 is CustomListOperation<
nit, wondering whether a `@clientName("list")` could make the operationId be `TopLevelItems_List` in Swagger.

Currently it is `TopLevelItems_Listv2` in Swagger, and this name feels unnatural.

Please try it in your local first.

From SDK viewpoint, it does not matter and we can have a `@clientName` in client.tsp to fix the naming.
The name in Swagger could affect the documentation though (like learn site, if REST API doc generated automatically).

2025-03-06 03:27 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/common/modes-jobs.tsp
> +  metadata?: {};
Hi Weidong, I checked the generated python SDK, this metadata is settable. 

def __init__(
        self,
        *,
        name: str,
        provider_id: str,
        target: str,
        container_uri: str,
        job_type: Optional[Union[str, "_models.JobType"]] = None,
        session_id: Optional[str] = None,
        input_data_uri: Optional[str] = None,
        input_data_format: Optional[str] = None,
        metadata: Optional[Any] = None,
        tags: Optional[List[str]] = None,
        input_params: Optional[Any] = None,
        output_data_uri: Optional[str] = None,
        output_data_format: Optional[str] = None,
    ) -> None: ...

2025-03-06 03:36 UTC, weidongxu-microsoft commented on specification/quantum/Quantum.Workspace/common/modes-jobs.tsp
> +  metadata?: {};
Is this generated from `{}`?

If so, I would need to check with Python dev...

2025-03-06 04:19 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/operations/items.tsp
> +    listv2 is CustomListOperation<
It creates an error saying list is duplicate which conflicts with the list in the old version.
Client name: "list" is duplicated in language scope: "AllScopes"TypeSpec(@azure-tools/typespec-client-generator-core/duplicate-client-name)

2025-03-06 04:58 UTC, weidongxu-microsoft commented on specification/quantum/Quantum.Workspace/common/modes-jobs.tsp
> +  metadata?: {};
I've confirmed with Yuchao, that Python emitter currently does something special on the unnamed `{}`.

For normal processing of SDK,
```
model Empty {}
```
would be same as
```
alias Empty = {};
```
And same when used in property
```
prop1: Empty;
prop2: {};
```

@markcowl Let me know if this look OK for you.

2025-03-06 05:22 UTC, weidongxu-microsoft commented on specification/quantum/Quantum.Workspace/common/modes-jobs.tsp
> +  metadata?: {};
Why revert it? User cannot set anything into the `{}` if not python.

2025-03-06 05:29 UTC, 04diiguyi commented on specification/quantum/Quantum.Workspace/common/modes-jobs.tsp
> +  metadata?: {};
Azure quantum service only supports python. We do not support other languages.
We manage our own repo which is not the mono repo. Our SDK repo is:
https://github.com/microsoft/azure-quantum-python

2025-03-06 05:32 UTC, weidongxu-microsoft commented on specification/quantum/Quantum.Workspace/common/modes-jobs.tsp
> +  metadata?: {};
OK. I will leave this as my opinion is `{}` is the wrong TypeSpec definition here.

2025-03-06 16:30 UTC, merged