Incorporating api review board name suggestion
Azure/azure-rest-api-specs pull request #31772
Opened 2024-12-05 01:54 UTC by vasanthrajams

As part of the api review board meeting, it was suggested to rename the `certificates` attribute to indicate the set of certificates but not in a plural form as the output returned to the customer is a single base64 url encoded string. Incorporating the review board suggestion and renaming the certificates attribute to certificateBundle.

2024-12-05 15:27 UTC, chen-karen approved these changes

2024-12-07 00:18 UTC, heaths requested changes

2024-12-07 00:18 UTC, heaths commented on specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.6-preview.2/keys.json
>            "description": "A base64url-encoded string containing certificates in PEM format, used for attestation validation."
I don't think this captures the feedback. "certificateBundle" is no more descriptive than "certificates". The concern here was that, unlike other APIs you already have, you're base64-encoding a PEM file that is already ASCII and contains base64-encoded certificates. The feedback was also in regard to the order, which I explained in chat afterward was not specified as guaranteed but many customers take a reliance on anyway.

The only thing different here I see is that you only purport to support PEM files as opposed to the other "certificates" fields/parameters you have, which are either base64url-encoded PKCS12 (PFX) files, or as-is PEM files.

So I don't think the name should change here or, if it does, I remember the feedback was more to call out these are PEM files e.g., `"certificatePemFile"` or something to that effect.

2024-12-10 00:12 UTC, heaths approved these changes

2024-12-10 00:41 UTC, heaths commented
Breaking Changes appear to be in err.

2024-12-10 00:56 UTC, heaths commented
LintDiff issues are pre-existing.

2024-12-10 00:56 UTC, merged