Adding new property isBootstrapCertificate to CSES
Azure/azure-rest-api-specs pull request #31851
Opened 2024-12-12 06:07 UTC by avilgoelms

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

<a href="?expand=1&template=sdk_configuration_template.md">Click here</a> to open a PR for only SDK configuration.

2024-12-12 19:42 UTC, haagha requested changes
Please run the prettier check and target this to main branch.

2024-12-12 19:47 UTC, haagha requested changes
Change bool to boolean, also please run the prettier check on example file and target this to main branch.

2024-12-12 19:47 UTC, haagha commented on specification/compute/resource-manager/Microsoft.Compute/CloudserviceRP/stable/2024-11-04/cloudService.json
> +          "type": "bool"
```suggestion
          "type": "boolean"
```

2024-12-13 03:15 UTC, grizzlytheodore commented
Please address haider comment. That should resolve most of the failing CI failures.
But we want to have lintdiff, modelvalidation, prettiercheck, and semanticvalidation all passing

2024-12-17 13:31 UTC, grizzlytheodore approved these changes

2024-12-17 13:31 UTC, merged