added python emitter to authoring
Azure/azure-rest-api-specs pull request #31925
Opened 2024-12-18 22:27 UTC by amber-ccc

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

<a href="?expand=1&template=sdk_configuration_template.md">Click here</a> to open a PR for only SDK configuration.

2024-12-18 22:31 UTC, azure-sdk commented
**API change check**

APIView has identified API level changes in this PR and created following API reviews.

[AnomalyDetector](https://apiview.dev/Assemblies/Review/87c532f5eac34924a5e70d2ee035fbb3?revisionId=511bcb29c2b743cb90e93f5152661a3a)

2025-04-25 07:39 UTC, v-jiaodi requested changes

2025-04-25 07:39 UTC, v-jiaodi commented on specification/cognitiveservices/Language.AnalyzeText-authoring/tspconfig.yaml
> +      name: "@azure-rest/azure-ai-language-text-authoring-rest"
```suggestion
    package-dir: "azure-ai-language-text-authoring-rest"
    package-details:
      name: "@azure-rest/azure-ai-language-text-authoring"
```

2026-09-16 16:22 UTC, closed without merging

2026-09-16 16:22 UTC, timotheeguerin commented
This PR has been closed because it has had no activity for more than a year. If this change is still needed, please reopen the PR.

<!-- inactive-pr-cleanup:2026-09-16 -->