Add new version for proactive detection config
Azure/azure-rest-api-specs pull request #3224
Opened 2018-06-13 07:13 UTC by aviled

2018-06-13 07:14 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-06-13 07:14 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-06-13 07:14 UTC, AutorestCI commented
# Automation for azure-libraries-for-java

2018-06-13 07:15 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-06-13 07:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-06-13 23:34 UTC, anuchandy requested changes
@aviled there is CI failure - with error message `DuplicateModelCollsion` -. This detects invalid SDK situation that we weren’t detecting before: if two files that are in the same “tag” in the Readme defines the same model name Foo, both object have to be exactly (at the comma exactly level) the same. Here we have Resource model defined in webTests_API.json, components_API.json and workbooks_API.json, it seems these 3 definitions are not same. could you fix it?

2018-06-19 18:49 UTC, anuchandy commented
@aviled can you fix the error reported by CI (see previous comments) ?

2018-06-21 08:33 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-06-21 17:07 UTC, anuchandy approved these changes

2018-06-22 01:05 UTC, anuchandy requested changes
Please model patch payload correctly as described in the email

2018-06-25 18:16 UTC, anuchandy commented
Looking in Eric Chong @ericc1103 owner of workbooks_api-json spec to address ARM violation.

ARM-Violation: "Properties of a PATCH request body must not be required. PATCH operation: 'Workbook_Update' Model Definition: 'WorkbookResource' Property: 'location'"

'WorkbookResource' model inherits from ‘Resource’ (for which we marked location as required), this model is used for both [PATCH](https://github.com/aviled/azure-rest-api-specs/blob/f013ccb70bb6f2428ebfccb11e9b46f54beb9e17/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/workbooks_API.json#L211) and [PUT](https://github.com/aviled/azure-rest-api-specs/blob/f013ccb70bb6f2428ebfccb11e9b46f54beb9e17/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/workbooks_API.json#L159). It is required that all the properties of model representing PATCH operation has to be optional. This also indirectly means service should not enforce any requiredness in the PATCH payload.

In-order to fix this, we need to define a new model representing Workbook PATCH payload (with all properties optional). The PATCH payload model looks something like WorkbookUpdateParameters as shown below. But please note that only you know what are the PATCH-able properties of workbook so you will need to update (by adding or removing properties) the below model accordingly.

```json
    "WorkbookUpdateParameters": {
        "properties": {
            "kind": {
                "type": "string",
                "description": "The kind of workbook. Choices are user and shared.",
                "enum": [
                    "user",
                    "shared"
                ],
                "x-ms-enum": {
                    "name": "SharedTypeKind",
                    "modelAsString": true
                }
            },
            "tags": {
                "type": "object",
                "additionalProperties": {
                    "type": "string"
                },
                "description": "Resource tags"
            },
            "properties": {
                "x-ms-client-flatten": true,
                "description": "Metadata describing a web test for an Azure resource.",
                "$ref": "#/definitions/WorkbookPropertiesUpdateParameters"
            }
        },
        "description": "The parameters that can be provided when updating workbook properties properties."
    },
    "WorkbookPropertiesUpdateParameters": {
        "description": "Properties that contain a workbook.",
        "properties": {
          "name": {
            "type": "string",
            "description": "The user-defined name of the workbook."
          },
          "serializedData": {
            "type": "string",
            "description": "Configuration of this particular workbook. Configuration data is a string containing valid JSON"
          },
          "version": {
            "type": "string",
            "description": "This instance's version of the data model. This can change as new features are added that can be marked workbook."
          },
          "workbookId": {
            "type": "string",
            "description": "Internally assigned unique id of the workbook definition."
          },
          "kind": {
           "description": "Enum indicating if this workbook definition is owned by a specific user or is shared between all users with access to the Application Insights component.",
            "x-ms-client-name": "SharedTypeKind",
            "default": "shared",
            "type": "string",
            "enum": [
              "shared",
              "user"
            ],
            "x-ms-enum": {
              "name": "SharedTypeKind",
              "modelAsString": true
            }
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "A list of 0 or more tags that are associated with this workbook definition"
          },
          "userId": {
            "type": "string",
            "description": "Unique user id of the specific user that owns this workbook."
          },
          "sourceResourceId": {
            "type": "string",
            "description": "Optional resourceId for a source resource."
          }
        }
      }

```

2018-06-25 21:39 UTC, ericc1103 commented
I have updated mine to make PATCH operation of properties as not required. The PR is @ https://github.com/Azure/azure-rest-api-specs/pull/2950

2018-06-25 23:11 UTC, anuchandy commented
@ericc1103 thanks, your PR is for new preview api-version. The issue here is with 2015-05-01 version of workbooks. I replied to your email and clarified, please take a look.

2018-07-09 09:48 UTC, ravbhatnagar commented on specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2018-05-01/componentProactiveDetection_API.json
> +        "responses": {
add a default response to capture the error responses. The schema should match the ARm error contract schema. Example can be found in Batch RP swagger.

2018-07-09 09:48 UTC, ravbhatnagar commented on specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2018-05-01/componentProactiveDetection_API.json
> +        "name": {
this should also be readonly as it comes from the URL

2018-07-09 09:48 UTC, ravbhatnagar commented on specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2018-05-01/componentProactiveDetection_API.json
> +      "properties": {
"tags" ARM top level property missing? Is this a tracked or proxy resource? Seems tracked since it has a location property

2018-07-09 09:48 UTC, ravbhatnagar commented on specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2018-05-01/componentProactiveDetection_API.json
> +        "Name": {
how is this name different from the one outside of properties? If different, please call this something else like ruleName

2018-07-09 09:48 UTC, ravbhatnagar commented on specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2018-05-01/componentProactiveDetection_API.json
> +        "Enabled": {
bools are typically not recommended. String enums generally work better.

2018-07-09 09:48 UTC, ravbhatnagar commented on specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2018-05-01/componentProactiveDetection_API.json
> +        "SendEmailsToSubscriptionOwners": {
same as above.

2018-07-09 09:48 UTC, ravbhatnagar commented on specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2018-05-01/componentProactiveDetection_API.json
> +        "LastUpdatedTime": {
readonly should be true

2018-07-09 09:48 UTC, ravbhatnagar commented on specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2018-05-01/componentProactiveDetection_API.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insights/components/{resourceName}/ProactiveDetectionConfigs":
Delete API missing. If this is a tracked resource type, patch also MUST be supported atleast for the update of tags but preferably to allow update of any patachable properties.

2018-07-31 17:54 UTC, veronicagg commented
Closing due to inactivity, please reopen/comment when you're back to this. Thanks.

2018-07-31 17:54 UTC, closed without merging