Updating 2018-03-01-preview to include a few extra fields and parameters
Azure/azure-rest-api-specs pull request #3267
Opened 2018-06-19 21:46 UTC by sendhil

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [X] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [X] If applicable, the PR references the bug/issue that it fixes.
- [X] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [X] My spec meets the review criteria:
  - [X] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [X] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-06-19 21:54 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-06-19 22:00 UTC, hovsepm commented on specification/managementgroups/resource-manager/Microsoft.Management/preview/2018-03-01-preview/management.json
>        }
does this POST operation also have 202 response?

2018-06-19 22:04 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-06-19 22:09 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-06-19 22:12 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-06-19 22:32 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-06-21 22:01 UTC, hovsepm commented on specification/managementgroups/resource-manager/Microsoft.Management/preview/2018-03-01-preview/management.json
> +      "x-ms-parameter-location": "client"
>client [](start = 34, length = 6)

why is this parameter changed from method location to client? By doing this change you require developers to set global parameter on the client instance and not on the method parameters.

2018-06-21 22:02 UTC, hovsepm commented on specification/managementgroups/resource-manager/Microsoft.Management/preview/2018-03-01-preview/management.json
> -      "x-ms-parameter-location": "method"
Same question here - why is the location changed from method signature to client object?

2018-06-21 22:02 UTC, hovsepm commented on specification/managementgroups/resource-manager/Microsoft.Management/preview/2018-03-01-preview/management.json
> +      "x-ms-parameter-location": "client"
>client [](start = 34, length = 6)

please revert all these changes for method location.

2018-06-21 22:04 UTC, hovsepm commented
@sendhil could you provide some information on why do you add so many line breaks? are you trying to fix any particular documentation rendering issue? Swagger should be UI agnostic service endpoint description. Please remove all `\n` special characters from the PR.

2018-06-21 22:06 UTC, hovsepm requested changes
Please address review comments.

2018-07-06 17:13 UTC, rajshah11 commented
@hovsepm I will close this PR and make a new one from my forked repo. Will make the changes in the comments too. Thanks!

2018-07-06 17:49 UTC, hovsepm commented
Closed per owner team request. /cc @rajshah11

2018-07-06 17:49 UTC, closed without merging