Add two missing "by subscription" operations for completeness and compliance
Azure/azure-rest-api-specs pull request #3285
Opened 2018-06-21 06:28 UTC by gucalder

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-06-21 06:29 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-06-21 07:54 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-06-21 08:31 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-06-21 10:22 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-06-21 10:43 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-06-21 18:27 UTC, dsgouda requested changes

2018-06-21 23:12 UTC, gucalder commented on specification/monitor/resource-manager/microsoft.insights/stable/2015-04-01/autoscale_API.json
> +            "examples": {
"Examples" nodes removed. The actual examples are already in the x-ms-examples referenced files.

2018-06-22 17:03 UTC, gucalder commented
Last commit addresses issue #3293

2018-06-22 17:17 UTC, dsgouda commented
@gucalder Some of the added examples seem to fail validation. Please take look at the logs [here](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/395287731) and fix the issues

2018-06-22 23:50 UTC, gucalder commented
@dsgouda To be honest, I do not understand the errors in metricAlert (I do not own this one)
The only thing that comes to my mind is:
Should I remove the second member of the odatatype enumeration for MetricAlertCriteria?
,
            "Microsoft.Azure.Monitor.DefaultCriteria" 

Because it is not defined and/or used anywhere else.

2018-06-25 16:54 UTC, dsgouda commented
@gucalder I think the API owners should be fixing it. Will open an issue regarding this.

2018-06-25 16:54 UTC, dsgouda approved these changes
LGTM

2018-06-25 16:57 UTC, merged

2018-06-25 16:57 UTC, dsgouda commented
@gucalder as a best practice please make changes in a branch other than `master` for opening the PRs. Keeps the commit history clean and would be easier for you too