[Cognitive Services] Create a package for common tasks.
Azure/azure-rest-api-specs pull request #3349
Opened 2018-07-03 18:32 UTC by yangyuan

Create a new package CognitiveServices.Common, which doesn't contain any API spec.

### Background
Cognitive Services need to provide a package for common tasks. These common tasks involves some common data structure, which I think it should be auto generated so that we don't need to maintain them in all platforms.
AutoRest will generate a client class, but it won't be included when configuration the package.

Feel free to give comments.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-07-03 18:32 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-07-03 18:33 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-07-03 18:34 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-07-03 18:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-07-03 18:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-07-03 19:06 UTC, marstr requested changes
Correct me if I'm wrong, but I believe that these are going to be referenced from many API Versions, but do not actually represent something that should be packaged independently.

Please follow the example of how the SQL team did this. You can see it here: https://github.com/Azure/azure-rest-api-specs/tree/29fa32175f4cc517f7a3290dffa81a01cad3f931/specification/sql/resource-manager

Notice, the common assets are not associated with an RP folder, or API Version folder.

2018-07-03 19:54 UTC, yangyuan commented
@marstr It looks like not the same scenario with SQL team.
This package will be referenced from many CognitiveServices SDKs. The package will contains some helper classes/functions for cognitive services.

For example: 
There will be a CognitiveServicesEndPoint class. `CognitiveServicesEndPoint(AzureRegion.WestUS, EndpointBasePath.TextAnalyticsV2)`

There will be a CognitiveServicesCredential class which will magically choose between different authentication methods.

So for TextAnalytics SDK, developers can do this after installed this common package.
`TextAnalyticsClient(new CognitiveServicesEndPoint(AzureRegion.WestUS, EndpointBasePath.TextAnalyticsV2), new CognitiveServicesCredential(), handlers: handler);`

For both, we will have some enums and string constants. 

### Why not directly create projects for .net/python....
We do not have to use azure-rest-api-specs to keep track of enums and string constants. However, maintain those enums and constants for all platforms might be painful.

### Why not refer those enums in API SDKs.
Because we dont want to update all API SDK for when we update the enums or common codes.

I do understand that keeping them in azure-rest-api-specs doesn't seems to be a perfect design. Please let me know if you have other suggestions.

2018-07-05 21:10 UTC, yangyuan commented
Closed due to these common files might bring many potential issues.

2018-07-05 21:10 UTC, closed without merging