[Cognitive Services] Update endpoint URL template for Content Moderator.
Azure/azure-rest-api-specs pull request #3505
Opened 2018-07-25 21:49 UTC by yangyuan

Detail background and explainations in here: https://github.com/Azure/azure-rest-api-specs/issues/3489 Cognitive Services URL template (endpoint)

Please hold for swiftarrow11's review.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-07-25 21:49 UTC, yangyuan commented on specification/cognitiveservices/data-plane/ContentModerator/readme.nodejs.md
> -  override-client-name: ContentModeratorAPIClient
Remove this to keep consistency

2018-07-25 21:50 UTC, yangyuan commented on specification/cognitiveservices/data-plane/ContentModerator/stable/v1.0/ContentModerator.json
> -    "description": "You use the API to scan your content as it is generated. Content Moderator then processes your content and sends the results along with relevant information either back to your sy
Remove the outdated region list.

2018-07-25 21:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-07-25 21:53 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-07-25 21:53 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-07-25 21:54 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-07-25 22:04 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-08-01 22:58 UTC, jhendrixMSFT commented
@yangyuan are we still waiting for other reviewers?

2018-08-01 22:58 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-08-02 00:12 UTC, yangyuan commented
Hi @jhendrixMSFT. I've updated some SDKs, but heard some negative feedback (also found an small issue in auto-generated documents).
So I decide to hold this PR for a few days and collect feedbacks in case of back/forth changes.

2018-08-07 06:44 UTC, sanjeev3 commented
@yangyuan @jhendrixMSFT, I am good with these. @swiftarrow11, how about you?

2018-08-07 16:19 UTC, jhendrixMSFT requested changes
There are some model validation failures that need to be addressed, please see the travis [log](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/408262332).

2018-08-08 23:42 UTC, yangyuan commented
hi @jhendrixMSFT, I've fixed the model validation error.

It shows that Linter Diff complaints some operations missing x-ms-examples.
How about we create an issue and deal with it later? two reasons I recommend that.
1. Its some legacy issues not related to this change.
2. The examples should be provided by Content Moderator team.

2018-08-08 23:53 UTC, jhendrixMSFT commented
@bsiegel I understand you're working on this new linter diff in CI?  I don't think it should be failing for this PR as it doesn't add any new operations.

2018-08-09 21:44 UTC, jhendrixMSFT commented
@veronicagg do you know about this new linter behavior?

2018-08-09 21:56 UTC, veronicagg commented
@jhendrixMSFT I asked @bsiegel about this in the morning. @bsiegel I think this is another case for the issue you fixed earlier today, in which case this branch would need to be rebased to pick up Brandon's fix. @bsiegel could you check other PRs that may be opened and got affected by it?

2018-08-10 00:31 UTC, yangyuan commented
@jhendrixMSFT I have rebase the branch and now all passes. :)

2018-08-10 01:10 UTC, jhendrixMSFT approved these changes
There are some model validation failures that need to be addressed, please see the travis [log](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/408262332).

2018-08-10 01:10 UTC, merged