Introduce Publicipprefix to swagger
Azure/azure-rest-api-specs pull request #3520
Opened 2018-07-26 23:35 UTC by anilingle-ms

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-07-26 23:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-07-26 23:41 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-07-26 23:43 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-07-26 23:45 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-07-26 23:52 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-07-27 23:17 UTC, anavinahar commented on specification/network/resource-manager/Microsoft.Network/stable/2018-07-01/examples/PublicIpPrefixGet.json
> +            "ipTags" : [
We're exposing tags as part of the prefix? 

Also, should it align with this: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-06-01/examples/PublicIpAddressList.json

2018-07-28 00:29 UTC, anavinahar approved these changes

2018-07-30 17:01 UTC, lmazuel requested changes
Change ApiVersion, otherwise LGTM. Need ARM feedback.

2018-07-30 17:01 UTC, lmazuel commented on specification/network/resource-manager/Microsoft.Network/stable/2018-07-01/publicIpPrefix.json
> +      "version": "2018-06-01"
Incorrect API version

2018-07-30 17:45 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-07-30 18:08 UTC, anilingle-ms commented
Fixed. Please Re-Review if needed.

- Anil

From: Laurent Mazuel <notifications@github.com>
Sent: Monday, July 30, 2018 10:02 AM
To: Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com>
Cc: Anil Ingle <Anil.Ingle@microsoft.com>; Author <author@noreply.github.com>
Subject: Re: [Azure/azure-rest-api-specs] Introduce Publicipprefix to swagger (#3520)


@lmazuel requested changes on this pull request.

Change ApiVersion, otherwise LGTM. Need ARM feedback.

________________________________

In specification/network/resource-manager/Microsoft.Network/stable/2018-07-01/publicIpPrefix.json<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F3520%23discussion_r206247697&data=02%7C01%7CAnil.Ingle%40microsoft.com%7C8a2a868e46e04101df8208d5f63e24b1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636685669124666805&sdata=SV6TuuXiblS1xz0BlSQ2dJ%2B03w7Secq2iePGZPS7afM%3D&reserved=0>:

> @@ -0,0 +1,426 @@

+{

+    "swagger": "2.0",

+    "info": {

+      "title": "NetworkManagementClient",

+      "description": "The Microsoft Azure Network management API provides a RESTful set of web services that interact with Microsoft Azure Networks service to manage your network resources. The API has entities that capture the relationship between an end user and the Microsoft Azure Networks service.",

+      "version": "2018-06-01"

Incorrect API version

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F3520%23pullrequestreview-141625880&data=02%7C01%7CAnil.Ingle%40microsoft.com%7C8a2a868e46e04101df8208d5f63e24b1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636685669124666805&sdata=Qzfh8bDrTV8eMgZlhEBQzLpi%2B623AgnuZaDSkR5L7o4%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAgdxIiqVODulL3FWlkheFHi6iJB8KztLks5uLzv9gaJpZM4VisrD&data=02%7C01%7CAnil.Ingle%40microsoft.com%7C8a2a868e46e04101df8208d5f63e24b1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636685669124676813&sdata=pb5dfEx37pRAMxHna8tRPaG411JkVBOvXPS8nYKrNFY%3D&reserved=0>.

2018-07-30 20:58 UTC, lmazuel approved these changes

2018-07-30 21:45 UTC, lmazuel commented
@anilingle-ms Actually, your example does not pass validation:
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/410049638

Example, some examples contains `publicIPAllocationMethod` that are not defined in the Swagger. Either add these to the Swagger if they are expected/returned by the server, or remove them from examples.

2018-07-30 21:45 UTC, lmazuel requested changes
Examples validation error.

2018-07-31 16:15 UTC, lmazuel approved these changes

2018-07-31 16:18 UTC, lmazuel commented
@ravbhatnagar could you check everything is fine fro; an ARM point of view? All PR is passing CI now. Thanks!

2018-07-31 17:11 UTC, ravbhatnagar commented
This has been reviewed.

2018-07-31 17:12 UTC, merged