add checknameavailability
Azure/azure-rest-api-specs pull request #3608
Opened 2018-08-08 09:25 UTC by tarostok

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-08-08 09:26 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-08-08 09:26 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-08-08 09:26 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-08-08 09:27 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-08-08 09:27 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-08-08 09:30 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-08-08 13:44 UTC, annatisch commented
Thanks @tarostok,
The spec is currently invalid - could you take a look?
```
ERROR: Schema violation: Additional properties not allowed: /subscriptions/{subscriptionId}/providers/Microsoft.PowerBIDedicated/locations/{location}/checkNameAvailability
    - file:///tmp/tmp2octhxb6/rest/specification/powerbidedicated/resource-manager/Microsoft.PowerBIdedicated/stable/2017-10-01/powerbidedicated.json:1:0 ($)
ERROR: Schema violation: Data does not match any schemas from 'oneOf'
    - file:///tmp/tmp2octhxb6/rest/specification/powerbidedicated/resource-manager/Microsoft.PowerBIdedicated/stable/2017-10-01/powerbidedicated.json:820:4 ($.parameters.CheckCapacityNameAvailabilityResult)
ERROR: Schema violation: Data does not match any schemas from 'oneOf'
    - file:///tmp/tmp2octhxb6/rest/specification/powerbidedicated/resource-manager/Microsoft.PowerBIdedicated/stable/2017-10-01/powerbidedicated.json:802:4 ($.parameters.CheckCapacityNameAvailabilityParameters)
```

2018-08-08 17:51 UTC, sergey-shandar commented
@annatisch you can assign the PR to me.

2018-08-08 19:47 UTC, tarostok commented
Fixed spec.

2018-08-10 17:22 UTC, sergey-shandar requested changes

2018-08-10 19:02 UTC, tarostok commented on specification/powerbidedicated/resource-manager/Microsoft.PowerBIdedicated/stable/2017-10-01/examples/checkNameAvailability.json
> +  },
right, thanks, fixed the typo

2018-08-17 18:43 UTC, sergey-shandar approved these changes
@tarostok could you add codeowners for PowerBI dedicated to this file https://github.com/Azure/azure-rest-api-specs/blob/master/CODEOWNERS ? We need codeowners to request review if someone else create a PR against your RP.

2018-08-19 07:51 UTC, tarostok commented
@sergey-shandar updated code owners

2018-08-20 18:21 UTC, merged