Azure Attestation create, get and delete api
Azure/azure-rest-api-specs pull request #3691
Opened 2018-08-21 21:00 UTC by DevOnGekko

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-08-21 21:00 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-08-21 21:01 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-08-21 21:01 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-08-21 21:01 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-08-21 21:02 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-08-21 21:05 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-08-22 17:56 UTC, dsgouda commented
@DevOnGekko 
please confirm that these APIs have been through ARM and API reviews

2018-08-22 17:59 UTC, dsgouda commented
@DevOnGekko Also fix all the CI failures reported

2018-08-22 18:21 UTC, dsgouda requested changes
This is a partial review, will review the rest when semantic errors are fixed and ARM/API review is finished

2018-08-22 18:59 UTC, DevOnGekko commented on specification/azureattestation/resource-manager/Microsoft.AzureAttestation/preview/2017-11-01/AzureAttestation.json
> +          "404": {
Fixed

2018-08-22 18:59 UTC, DevOnGekko commented on specification/azureattestation/resource-manager/Microsoft.AzureAttestation/preview/2017-11-01/AzureAttestation.json
> +          "description": "Attestation signing keys."
fixed

2018-08-22 18:59 UTC, DevOnGekko commented on specification/azureattestation/resource-manager/Microsoft.AzureAttestation/preview/2017-11-01/AzureAttestation.json
> +            }
Its not long running taken few ms

2018-08-22 19:00 UTC, DevOnGekko commented on specification/azureattestation/resource-manager/Microsoft.AzureAttestation/preview/2017-11-01/AzureAttestation.json
> +            }
Not long running task takes few ms

2018-08-22 19:53 UTC, DevOnGekko commented on specification/azureattestation/resource-manager/Microsoft.AzureAttestation/preview/2017-11-01/AzureAttestation.json
> +      "type": "object",
Thanks!, its a Get operation hence changed the signature

2018-08-22 20:34 UTC, dsgouda requested changes
Left a few more comments

2018-08-22 20:34 UTC, dsgouda commented on specification/azureattestation/resource-manager/Microsoft.AzureAttestation/preview/2017-11-01/AzureAttestation.json
> +              "$ref": "#/definitions/AttestationSigningKeys"
Please add the `x-ms-pageable` extension here

2018-08-22 20:34 UTC, dsgouda commented on specification/azureattestation/resource-manager/Microsoft.AzureAttestation/preview/2017-11-01/AzureAttestation.json
> +        "operationId": "Operations_List",
Make this operation as pageable

2018-08-22 20:34 UTC, dsgouda commented
@azuresdkci Retest this please

2018-08-23 16:57 UTC, dsgouda requested changes

2018-08-23 16:57 UTC, dsgouda commented on specification/azureattestation/resource-manager/Microsoft.AzureAttestation/preview/2017-11-01/AzureAttestation.json
> +        "operationId": "Get_AttestationService",
OperationIds must be of the form `Resource_OperationName`, please take a look at rules R1003-R1007 [here](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md) and rename operation Ids accordingly

2018-08-29 22:42 UTC, dsgouda commented
Closing this in lieu of PR opened [here](https://github.com/Azure/azure-rest-api-specs-pr/pull/551)

2018-08-29 22:42 UTC, closed without merging