added restore deleted apps and get list of deleted apps
Azure/azure-rest-api-specs pull request #3696
Opened 2018-08-21 22:52 UTC by connorlee77

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-08-21 22:53 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-08-21 22:53 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-08-21 22:54 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-08-21 22:55 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-08-22 17:22 UTC, marstr requested changes

2018-08-22 19:36 UTC, connorlee77 commented
Could @amarzavery @lmazuel @yugangw-msft test it out/fix any errors?

2018-08-24 20:51 UTC, marstr commented
I'm going to be OOF all next week, so this PR should be reassigned.

2018-08-28 18:41 UTC, lmazuel commented on specification/graphrbac/data-plane/stable/1.6/graphrbac.json
> +          },
Probably missing the api version to get apiversion=1.6
```
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
```

2018-08-28 18:46 UTC, lmazuel requested changes

2018-08-28 18:46 UTC, lmazuel commented on specification/graphrbac/data-plane/stable/1.6/graphrbac.json
> +          {
Missing the api version to get apiversion=1.6
```
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
```

2018-08-28 18:50 UTC, lmazuel commented on specification/graphrbac/data-plane/stable/1.6/graphrbac.json
> +        "operationId": "Applications_HardDelete",
If I understand correctly the purpose of this operation, the idea is to "purge" deletedApplications and remove for real the application without waiting 30 days. This means the app has to have been deleted before.
If that so, then operationId should be `DeletedApplications_Delete`

2018-10-05 19:56 UTC, lmazuel commented
Left the company.

2018-10-05 19:56 UTC, closed without merging

2018-10-05 19:58 UTC, AutorestCI commented
# Automation for azure-sdk-for-js