Add mariadb swagger spec
Azure/azure-rest-api-specs pull request #3797
Opened 2018-09-03 07:29 UTC by elemount

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-09-03 07:29 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-09-03 07:30 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-09-03 07:31 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-09-03 07:31 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-09-03 07:31 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-09-03 07:31 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-09-06 16:24 UTC, dsgouda requested changes
Left a few comments. Please refactor your models and apply readonly-ness as pointed out,
Do get a feeling this needs an API review.

2018-09-07 02:08 UTC, elemount commented on specification/mariadb/resource-manager/Microsoft.DBforMariaDB/preview/2018-06-01-preview/mariadb.json
> +    "ServerPropertiesForCreate": {
I set it to `ServerPropertiesForCreate` to concise with MySQL and PostgreSQL. For example, for java SDK, MySQL and PostgreSQL both use it as the API interface. We want to match with them.

2018-09-07 02:13 UTC, elemount commented on specification/mariadb/resource-manager/Microsoft.DBforMariaDB/preview/2018-06-01-preview/mariadb.json
> +    "NameAvailability": {
Agree with you. That is for matching with MySQL and PostgreSQL.

2018-09-07 02:15 UTC, elemount commented on specification/mariadb/resource-manager/Microsoft.DBforMariaDB/preview/2018-06-01-preview/mariadb.json
> +          "$ref": "#/definitions/SecurityAlertPolicyProperties",
at line 1785 of same file.

2018-09-07 02:33 UTC, elemount commented on specification/mariadb/resource-manager/Microsoft.DBforMariaDB/preview/2018-06-01-preview/mariadb.json
> +        "modelAsString": false
That is expected. The value is a boolean originally. On reviewing MySQL and PostgreSQL, we were pointed out that we should use a enum for the enforce or not. This enum only have two option and will not add any options.

2018-09-07 02:43 UTC, elemount commented on specification/mariadb/resource-manager/Microsoft.DBforMariaDB/preview/2018-06-01-preview/mariadb.json
> +    "ServerUpdateParameters": {
They are totally different. The option customer create database are not the same thing for their update the server resource. Move common properties can lead misunderstanding.

2018-09-07 02:45 UTC, elemount commented on specification/mariadb/resource-manager/Microsoft.DBforMariaDB/preview/2018-06-01-preview/mariadb.json
> +    "ServerForCreate": {
We have several server creating model, so create `ServerPropertiesForDefaultCreate`, `ServerPropertiesForRestore`, `ServerPropertiesForGeoRestore`. They are inherit from `ServerPropertiesForCreate`. To match such creating model (Which do not a things which the server response we get). We use `ServerForCreate` and `Server`

2018-09-07 02:50 UTC, elemount commented on specification/mariadb/resource-manager/Microsoft.DBforMariaDB/preview/2018-06-01-preview/mariadb.json
> +    "ServerUpdateParameters": {
Also, we need match with MySQL and PostgreSQL for same api.

2018-09-07 03:02 UTC, elemount commented on specification/mariadb/resource-manager/Microsoft.DBforMariaDB/preview/2018-06-01-preview/mariadb.json
> +        "url": {
Sure, I've set it to readonly.

2018-09-07 03:02 UTC, elemount commented on specification/mariadb/resource-manager/Microsoft.DBforMariaDB/preview/2018-06-01-preview/mariadb.json
> +        "location": {
Sure.

2018-09-07 03:02 UTC, elemount commented on specification/mariadb/resource-manager/readme.md
> +openapi-type: arm
Thanks, I've updated it.

2018-09-07 03:03 UTC, elemount commented on specification/mariadb/resource-manager/Microsoft.DBforMariaDB/preview/2018-06-01-preview/mariadb.json
> +          "$ref": "#/definitions/OperationDisplay",
Sure.

2018-09-12 22:20 UTC, dsgouda approved these changes
LGTM

2018-09-12 22:21 UTC, merged