Add Network Profile swagger and examples
Azure/azure-rest-api-specs pull request #3806
Opened 2018-09-05 11:23 UTC by jcgknudson

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-09-05 11:30 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-09-05 11:30 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-09-05 11:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-09-05 11:49 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-09-05 11:50 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-09-05 11:55 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-09-05 15:03 UTC, jcgknudson commented
@jianghaolu , would you mind reviewing as well? Unable to request review since I don't have write access on the repo :)

2018-09-05 16:51 UTC, lmazuel commented
@ravbhatnagar from ARM as well for review

2018-09-05 16:58 UTC, lmazuel commented on specification/network/resource-manager/Microsoft.Network/stable/2018-08-01/networkProfile.json
> +          "$ref": "#/definitions/ContainerPropertiesFormat",
You probably want to use x-ms-client-flatten to make better SDK.
Example:
https://github.com/Azure/azure-rest-api-specs/blob/32b0d873aa851d456dfde7d6ba1d89ff33f897f0/specification/network/resource-manager/Microsoft.Network/stable/2016-12-01/applicationGateway.json#L511

2018-09-05 16:58 UTC, lmazuel commented on specification/network/resource-manager/Microsoft.Network/stable/2018-08-01/networkProfile.json
> +          "$ref": "#/definitions/IPConfigurationProfilePropertiesFormat",
You probably want to use x-ms-client-flatten to make better SDK.
Example:
https://github.com/Azure/azure-rest-api-specs/blob/32b0d873aa851d456dfde7d6ba1d89ff33f897f0/specification/network/resource-manager/Microsoft.Network/stable/2016-12-01/applicationGateway.json#L511

2018-09-05 16:58 UTC, lmazuel commented on specification/network/resource-manager/Microsoft.Network/stable/2018-08-01/networkProfile.json
> +          "$ref": "#/definitions/ContainerNetworkInterfaceConfigurationPropertiesFormat",
You probably want to use x-ms-client-flatten to make better SDK.
Example:
https://github.com/Azure/azure-rest-api-specs/blob/32b0d873aa851d456dfde7d6ba1d89ff33f897f0/specification/network/resource-manager/Microsoft.Network/stable/2016-12-01/applicationGateway.json#L511

2018-09-05 16:58 UTC, lmazuel commented on specification/network/resource-manager/Microsoft.Network/stable/2018-08-01/networkProfile.json
> +          "$ref": "#/definitions/ContainerNetworkInterfacePropertiesFormat",
You probably want to use x-ms-client-flatten to make better SDK.
Example:
https://github.com/Azure/azure-rest-api-specs/blob/32b0d873aa851d456dfde7d6ba1d89ff33f897f0/specification/network/resource-manager/Microsoft.Network/stable/2016-12-01/applicationGateway.json#L511

2018-09-05 16:58 UTC, lmazuel commented on specification/network/resource-manager/Microsoft.Network/stable/2018-08-01/networkProfile.json
> +          "$ref": "#/definitions/NetworkProfilePropertiesFormat",
You probably want to use x-ms-client-flatten to make better SDK.
Example:
https://github.com/Azure/azure-rest-api-specs/blob/32b0d873aa851d456dfde7d6ba1d89ff33f897f0/specification/network/resource-manager/Microsoft.Network/stable/2016-12-01/applicationGateway.json#L511

2018-09-05 17:01 UTC, lmazuel approved these changes
Sounds good. A few remark about flatenning, this would avoid `myvariable.properties.myname` to be simply `myvariable.myname`

2018-09-05 17:45 UTC, tjprescott requested changes
Please implement @lmazuel's flattening suggestions. Without them, then Python SDK is a mess.

2018-09-05 20:18 UTC, tjprescott approved these changes

2018-09-06 00:55 UTC, ravbhatnagar commented
This was reviewed in person. Signing off!

2018-09-06 17:01 UTC, lmazuel commented
Hi @jcgknudson 
Please also fix the model validation errors:
https://travis-ci.org/Azure/azure-rest-api-specs/jobs/424973532

This could mean that the examples are wrong, or the Swagger is wrong. Be sure that the example reflects the exact truth of the service. Once it's done, if there is still issues, this means your Swagger is wrong (because if example tells the truth, then it should match).
Let me know if something is unclear.
Thank you!

2018-09-06 23:00 UTC, jcgknudson commented
Hey @lmazuel, fixed the issues with the model validation, sorry about that.
There were a few fields omitted in the model, nothing too big.

2018-09-07 00:14 UTC, merged