[Datafactory] Add Variables and related activities to Pipeline.
Azure/azure-rest-api-specs pull request #3828
Opened 2018-09-07 01:56 UTC by haricr

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-09-07 01:57 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-09-07 01:58 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-09-07 02:03 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-09-07 02:05 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-09-07 02:31 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-09-07 20:06 UTC, lmazuel commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json
> +    "SetVaraibleActivity": {
Typo

2018-09-07 20:06 UTC, lmazuel commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json
> +      "x-ms-discriminator-value": "SetVaraible",
Typo

2018-09-07 20:07 UTC, lmazuel commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json
> +    "AppendVaraibleActivity": {
Typo

2018-09-07 20:07 UTC, lmazuel commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json
> +      "x-ms-discriminator-value": "AppendVaraible",
Typo

2018-09-07 20:07 UTC, lmazuel requested changes
A few typos

2018-09-07 23:46 UTC, lmazuel commented
Hi @haricr 
Being the complexity of the object, it would be valuable to have a x-ms-example. Thank you.

2018-09-17 20:57 UTC, hvermis commented
Splitting the changes into variables only an the rest. Please review https://github.com/Azure/azure-rest-api-specs/pull/3917

2018-09-17 20:57 UTC, closed without merging