[DO NOT MERGE] Added list support to VA policies
Azure/azure-rest-api-specs pull request #3878
Opened 2018-09-12 08:07 UTC by t-robalt

Added support to get list of VA policies for servers and managed instance, including databases.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-09-12 08:09 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-09-12 08:10 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-09-12 08:11 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-09-12 08:14 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-09-12 08:35 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-09-12 08:42 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-09-12 11:30 UTC, t-robalt commented
@yaakoviyun @yoavfr

2018-09-12 16:31 UTC, jianghaolu requested changes

2018-09-12 16:31 UTC, jianghaolu commented on specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/examples/DatabaseVulnerabilityAssessmentListByDatabase.json
> +    },
Missing required parameter "databaseName".

2018-09-13 07:32 UTC, t-robalt commented on specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/examples/DatabaseVulnerabilityAssessmentListByDatabase.json
> +    },
Fixed.

2018-09-13 16:35 UTC, jianghaolu approved these changes

2018-09-13 16:35 UTC, merged