Swagger changes for adding diffdisksettings property for the Ephemeral OS Disks
Azure/azure-rest-api-specs pull request #3944
Opened 2018-09-18 21:35 UTC by hari-bodicherla

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-09-18 21:36 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=3944) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=3944) before we can accept your contribution.<br/><br/>:x: hari-bodicherla [sign now](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=3944)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-rest-api-specs?pullRequest=3944) it.</sub>

2018-09-18 21:38 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-09-18 21:40 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-09-18 22:16 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-09-18 23:30 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-09-18 23:31 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-09-19 22:20 UTC, jhendrixMSFT requested changes
Can you please update at least one of the examples with this new field?

2018-09-21 05:55 UTC, hari-bodicherla commented
Added a example "CreateAScaleSetWithDiffOsDisk.json" using the new field as requested

2018-09-21 15:49 UTC, jhendrixMSFT commented
@AutorestCI regenerate azure-sdk-for-go

2018-09-21 15:59 UTC, jhendrixMSFT commented
@hari-bodicherla thanks for adding the example, the only thing remaining is to update the appropriate operation ID in compute.json to reference it.  Once that's done and model validation passed I can merge.

2018-09-21 22:00 UTC, hyonholee commented
Please also update stable\2018-10-01\compute.json  (and examples under 2018-10-01 folder)

2018-09-22 00:42 UTC, hari-bodicherla commented
updated the operation ID in compute.json to reference the new example file added

2018-09-22 00:43 UTC, hari-bodicherla commented
Updated compute.json and examples under 2018-10-01 folder

2018-09-24 16:16 UTC, jhendrixMSFT commented on specification/compute/resource-manager/Microsoft.Compute/stable/2018-06-01/compute.json
> +        "name": "DiffDiskOptions",
This will introduce a breaking change.  Looks like it can't be avoided though due to the name collision?

2018-09-24 16:20 UTC, jhendrixMSFT commented on specification/compute/resource-manager/Microsoft.Compute/stable/2018-06-01/compute.json
> +        "name": "DiffDiskOptions",
Oh nevermind this is part of the original commit.

2018-09-24 16:22 UTC, jhendrixMSFT approved these changes

2018-09-24 16:23 UTC, merged

2018-09-24 17:02 UTC, jhendrixMSFT commented
@AutorestCI regenerate azure-sdk-for-go

2018-09-24 19:15 UTC, hari-bodicherla commented
hi jhendrixMSFT , I am planning to add another example file for single Vm creation similar to scaleset creation using differencing os disk. Can we reopen this PR for these additional changes?

2018-09-24 19:17 UTC, jhendrixMSFT commented
Sorry you'll have to add it it a new PR.  Feel free to tag me in it and I'll help expedite the review.

2018-09-24 19:17 UTC, hari-bodicherla commented
thanks jhendrixMSFT