New resource: Add InGuest resource type software to Compute
Azure/azure-rest-api-specs pull request #4012
Opened 2018-09-26 19:22 UTC by abhinav-ghai

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-09-26 19:30 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-09-26 19:44 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-09-26 19:47 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-09-26 19:48 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-09-27 19:26 UTC, anuchandy requested changes

2018-09-28 18:53 UTC, abhinav-ghai commented on specification/compute/resource-manager/Microsoft.Compute/stable/2018-10-01/compute.json
> +        }
Yes, it's an ARM resource. Example:
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/guestResourceTypes/software/items/{itemId}

2018-09-28 18:54 UTC, abhinav-ghai commented on specification/compute/resource-manager/Microsoft.Compute/stable/2018-10-01/compute.json
> +            "name": "itemId",
Yes, Example:
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/guestResourceTypes/software/items/{**itemId**}

2018-09-28 19:41 UTC, anuchandy commented
@abhinav-gha - Larent @lmazuel noted that we are adding these apis to 2016-04-30-preview and 2018-10-01, but what about other api-versions in the middle 2017-12-01, 2018-06-01? It's weird to see that an operation exist in old API disappears in next couple of api-versions then come back in later one.

2018-09-28 21:04 UTC, abhinav-ghai commented on specification/compute/resource-manager/Microsoft.Compute/stable/2018-10-01/compute.json
> +      "description": "The List of Software items operation response."
Done

2018-09-28 21:05 UTC, abhinav-ghai commented on specification/compute/resource-manager/Microsoft.Compute/stable/2018-10-01/compute.json
> +      "description": "Describes the properties of an InGuest software item."
Done

2018-09-28 21:05 UTC, abhinav-ghai commented on specification/compute/resource-manager/readme.md
> +    - TrackedResourcePatchOperation
Okay

2018-10-02 21:05 UTC, ravbhatnagar reviewed
Few notes, Please take a look.

2018-10-02 21:05 UTC, ravbhatnagar commented on specification/compute/resource-manager/Microsoft.Compute/preview/2016-04-30-preview/compute.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/guestResourceTypes/software/items":{
lets make the values of guestResourceTypes as an enum and add the allowed values there.

2018-10-02 21:05 UTC, ravbhatnagar commented on specification/compute/resource-manager/Microsoft.Compute/preview/2016-04-30-preview/compute.json
> +        "name": {
top level property names should not be repeated inside the properties bag. Lets rename this to softwareName

2018-10-02 21:05 UTC, ravbhatnagar commented on specification/compute/resource-manager/Microsoft.Compute/preview/2016-04-30-preview/compute.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/guestResourceTypes/software/items/{itemId}":{
What would GET on /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/guestResourceTypes/software return? Do you want to support this API?

2018-10-08 18:42 UTC, anuchandy commented
@abhinav-ghai can you address ARM comments and my question on not having this feature in some api-versions?

2018-10-15 18:12 UTC, anuchandy commented
Closing the PR to due to inactivity.

2018-10-15 18:12 UTC, closed without merging