Add Multi Resource Alert changes for Metric Alert API
Azure/azure-rest-api-specs pull request #4016
Opened 2018-09-27 06:58 UTC by sanjaypavan

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-09-27 06:59 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-09-27 06:59 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-09-27 07:00 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-09-27 07:00 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-09-27 07:00 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-09-27 07:02 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-09-27 07:03 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-09-28 19:26 UTC, jhendrixMSFT requested changes

2018-10-03 09:29 UTC, sanjaypavan commented on specification/monitor/resource-manager/microsoft.insights/stable/2018-03-01/metricAlert_API.json
> +      "x-ms-discriminator-value": "Microsoft.Azure.Monitor.MultipleResourceMultipleMetricCriteria",
Hello @jhendrixMSFT We use similar name for **MetricAlertSingleResourceMultipleMetricCriteria**  We need to keep that consistent for the new changes as well. Any issues for not having a short name?

2018-10-03 15:03 UTC, jhendrixMSFT commented on specification/monitor/resource-manager/microsoft.insights/stable/2018-03-01/metricAlert_API.json
> +      "x-ms-discriminator-value": "Microsoft.Azure.Monitor.MultipleResourceMultipleMetricCriteria",
I was referring to the discriminator value, it generates a really long type name e.g. `MicrosoftAzureMonitorMultipleResourceMultipleMetricCriteria`.  Removing the `Microsoft.Azure.Monitor.` prefix shortens it nicely and is easier to read.

2018-10-04 13:29 UTC, sanjaypavan commented on specification/monitor/resource-manager/microsoft.insights/stable/2018-03-01/metricAlert_API.json
> +      "x-ms-discriminator-value": "Microsoft.Azure.Monitor.MultipleResourceMultipleMetricCriteria",
You are correct @jhendrixMSFT, but I need to follow the existing pattern which the customer already knew. We already have a discriminator value which is Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria. Hence, I declared this one in the same way.

2018-10-04 16:53 UTC, jhendrixMSFT commented on specification/monitor/resource-manager/microsoft.insights/stable/2018-03-01/metricAlert_API.json
> +      "x-ms-discriminator-value": "Microsoft.Azure.Monitor.MultipleResourceMultipleMetricCriteria",
So `Microsoft.Azure.Monitor.MultipleResourceMultipleMetricCriteria` is the value sent over the wire, including the `.` characters?

2018-10-04 17:25 UTC, jhendrixMSFT reviewed
Switching my review to comments.

2018-10-04 17:25 UTC, jhendrixMSFT approved these changes

2018-10-04 18:02 UTC, merged

2018-10-08 16:15 UTC, jhendrixMSFT commented
@AutorestCI regenerate azure-sdk-for-go

2018-10-11 17:06 UTC, jhendrixMSFT commented
@AutorestCI regenerate azure-sdk-for-go

2018-10-11 23:05 UTC, AutorestCI commented
<details><summary>Encountered a Subprocess error</summary><p>

Command: go generate ./profiles/...
Finished with return code 1
and output:
```shell
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: flushing $WORK/b001/exe/main: write $WORK/b001/exe/main: no space left on device
profiles/2017-03-09/generate.go:17: running "go": exit status 2
[STATUS] Output-Location set to:
[ERROR] path 'github.com/Azure/azure-sdk-for-go/services/appinsights/v1/insights' does not resemble a known package path
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/advisor/mgmt/advisor/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/analysisservices/mgmt/analysisservices/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/appinsights/mgmt/insights/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/apimanagement/mgmt/apimanagement/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/authorization/mgmt/authorization/models.go
[STATUS] Success formatting profile.
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/automation/mgmt/automation/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/azsadmin/mgmt/fabric/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/batch/batch/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/azsadmin/mgmt/infrastructureinsights/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/batchai/mgmt/batchai/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/batch/mgmt/batch/models.go
[STATUS] Success formatting profile.
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cognitiveservices/computervision/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cognitiveservices/contentmoderator/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cognitiveservices/customsearch/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cognitiveservices/entitysearch/models.go
[STATUS] Success formatting profile.
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cognitiveservices/face/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cognitiveservices/imagesearch/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cognitiveservices/luis/programmatic/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cognitiveservices/luis/runtime/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cognitiveservices/newssearch/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cognitiveservices/spellcheck/models.go
[STATUS] Success formatting profile.
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cognitiveservices/textanalytics/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cognitiveservices/videosearch/models.go
[STATUS] Success formatting profile.
[STATUS] Success formatting profile.
[STATUS] Success formatting profile.
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/containerservice/mgmt/containerservice/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/consumption/mgmt/consumption/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cognitiveservices/websearch/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cognitiveservices/mgmt/cognitiveservices/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/compute/mgmt/compute/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/containerregistry/mgmt/containerregistry/models.go
[STATUS] Success formatting profile.
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/cosmos-db/mgmt/documentdb/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/containerservice/mgmt/containerservice/models.go
[STATUS] Success formatting profile.
[STATUS] Success formatting profile.
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/customerinsights/mgmt/customerinsights/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/datalake/analytics/catalog/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/datacatalog/mgmt/datacatalog/models.go
[STATUS] Success formatting profile.
[STATUS] Success formatting profile.
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/datalake/analytics/job/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/datalake/analytics/mgmt/account/models.go
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/datalake/store/filesystem/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/datalake/store/mgmt/account/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/provisioningservices/mgmt/iothub/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/devtestlabs/mgmt/dtl/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/dns/mgmt/dns/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/domainservices/mgmt/aad/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/eventgrid/eventgrid/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/eventgrid/mgmt/eventgrid/models.go
[STATUS] Success formatting profile.
[STATUS] Writing File: /tmp/tmpx910ikfw/src/github.com/Azure/azure-sdk-for-go/profiles/latest/eventhub/mgmt/eventhub/models.go
[STATU [...]

2018-10-15 17:17 UTC, jhendrixMSFT commented
@AutorestCI regenerate azure-sdk-for-go