Add applicationinsights/data-plane/readme.typescript.md
Azure/azure-rest-api-specs pull request #4145
Opened 2018-10-10 21:08 UTC by kpajdzik

Autogenerated

2018-10-10 21:09 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-10-10 21:10 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-10-10 21:20 UTC, marstr commented
Waiting on @daschult's review before I take further action.

2018-10-10 21:45 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-10-10 22:03 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-10-10 22:13 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-10-10 22:36 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-10-11 18:42 UTC, ghost requested changes

2018-10-11 18:42 UTC, daschult commented on specification/applicationinsights/data-plane/readme.typescript.md
> +    remove-operation: Events_GetOdataMetadata
Please describe why this is here and not in the main readme.md file.

2018-10-11 18:48 UTC, ghost approved these changes

2018-10-11 18:49 UTC, merged

2018-10-12 01:20 UTC, AutorestCI commented
# Automation for azure-sdk-for-go