Add batch/data-plane/readme.typescript.md
Azure/azure-rest-api-specs pull request #4150
Opened 2018-10-10 21:18 UTC by kpajdzik

Autogenerated

2018-10-10 21:19 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-10-10 21:19 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-10-10 22:38 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-10-10 22:46 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-10-10 22:48 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-10-10 22:49 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-10-11 18:39 UTC, ghost requested changes

2018-10-11 18:39 UTC, daschult commented on specification/batch/data-plane/readme.typescript.md
> +  output-folder: "$(typescript-sdks-folder)/packages/@azure/arm-batch"
Data planes should not have the "arm-" prefix.

2018-10-12 17:22 UTC, ghost approved these changes

2018-10-12 17:22 UTC, merged

2018-10-12 18:43 UTC, AutorestCI commented
# Automation for azure-sdk-for-go