Add datalake-store/data-plane/readme.typescript.md
Azure/azure-rest-api-specs pull request #4212
Opened 2018-10-11 18:22 UTC by kpajdzik

Autogenerated

2018-10-11 18:36 UTC, ghost requested changes

2018-10-11 18:36 UTC, daschult commented on specification/datalake-store/data-plane/readme.typescript.md
> +  source-code-folder-path: lib/filesystem
We talked about not adding this file, but I'm okay with adding this file. Please manually compare this file to the readme.nodejs.md version to make sure that the properties are correct.

2018-10-11 23:50 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-10-12 00:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-10-12 16:32 UTC, closed without merging

2018-10-12 16:32 UTC, AutorestCI commented
# Automation for azure-sdk-for-js
A PR has been created for you:
https://github.com/Azure/azure-sdk-for-js/pull/139