Microsoft.StorageSync : Update ApiVersion 2018-10-01
Azure/azure-rest-api-specs pull request #4249
Opened 2018-10-16 22:29 UTC by ankushbindlish2

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-10-16 22:30 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-10-16 22:30 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-10-16 22:30 UTC, ankushbindlish2 commented
Will move it to stable once it reaches production.

2018-10-16 22:30 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-10-16 22:32 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-10-16 22:34 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-10-17 16:33 UTC, ghost requested changes

2018-10-17 16:33 UTC, daschult commented on specification/storagesync/resource-manager/readme.typescript.md
> -  package-name: "@azure/arm-storagesync"
Please revert these changes. These relate to the TypeScript SDKs.

2018-10-21 21:52 UTC, anuchandy requested changes

2018-10-21 21:52 UTC, anuchandy commented on specification/storagesync/resource-manager/Microsoft.StorageSync/preview/2018-10-01/examples/CloudEndpoints_Create.json
> +                    "backupEnabled" : "false",
use boolean false here instead of string

2018-10-27 00:17 UTC, anuchandy commented
@ankushbindlish2 could you address the comment?

2018-11-10 18:38 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-11-10 18:40 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-11-12 20:30 UTC, daschult commented on specification/storagesync/resource-manager/readme.typescript.md
> -  package-name: "@azure/arm-storagesync"
No. These should remain as they are. Let me look around this folder and make sure you have everything configured correctly.

2018-11-12 20:31 UTC, daschult commented on specification/storagesync/resource-manager/readme.typescript.md
> -  package-name: "@azure/arm-storagesync"
Everything looks fine. Just revert changes to this file. We're going to be publishing these TypeScript-based SDKs this week.

2018-11-12 20:32 UTC, daschult commented on specification/storagesync/resource-manager/readme.typescript.md
> -  package-name: "@azure/arm-storagesync"
You can see the generated SDK here: https://github.com/Azure/azure-sdk-for-js/tree/master/packages/%40azure/arm-storagesync.

2018-11-12 20:38 UTC, ghost approved these changes

2018-11-13 00:26 UTC, anuchandy commented on specification/storagesync/resource-manager/Microsoft.StorageSync/preview/2018-10-01/examples/CloudEndpoints_Create.json
> +                    "backupEnabled" : "false",
but this is indeed a boolean in swagger https://github.com/Azure/azure-rest-api-specs/blob/2cf4198df15d2fb24f6643065f79677b05706915/specification/storagesync/resource-manager/Microsoft.StorageSync/preview/2018-10-01/storagesync.json#L3274

2018-11-13 00:28 UTC, anuchandy commented
@ankushbindlish2 please take a look at the comment https://github.com/Azure/azure-rest-api-specs/pull/4249#discussion_r232857771

2018-11-13 00:37 UTC, anuchandy commented
Also fix other error reported by model validator https://travis-ci.org/Azure/azure-rest-api-specs/jobs/454160923

2018-11-13 00:44 UTC, anuchandy commented on specification/storagesync/resource-manager/Microsoft.StorageSync/preview/2018-10-01/examples/ServerEndpoints_Create.json
> +                "offlineDataTransferShareName": "myfileshare"
Looking at the model, these two properties are nested properties of a property with name `parameters` https://github.com/Azure/azure-rest-api-specs/blob/73b14d60d8d686e0626fb6cdb67c41e0a90b9023/specification/storagesync/resource-manager/Microsoft.StorageSync/preview/2018-10-01/storagesync.json#L1466

2018-11-13 20:36 UTC, anuchandy commented
@ravbhatnagar @KrisBash please review from ARM side.

2018-11-13 20:42 UTC, anuchandy approved these changes

2018-11-17 01:37 UTC, ravbhatnagar commented
Under preview, although API version does not indicate that. So adding new properties is ok since its preview. Signing off from ARM side.

2018-11-19 05:35 UTC, merged