[Maps] Introduce Event Grid Publisher event schema
Azure/azure-rest-api-specs pull request #4326
Opened 2018-10-25 00:53 UTC by jp94

Did not update the `readme.md`, because Event Grid support for Azure Maps is not available for public yet; however, this knowledge is not embargoed (hence public PR).

---

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [x] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x] If applicable, the PR references the bug/issue that it fixes.
- [x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [x] My spec meets the review criteria:
  - [x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-10-25 00:54 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-10-25 00:54 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-10-25 00:55 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-10-25 00:55 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-10-25 00:55 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-10-25 00:55 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-10-25 18:25 UTC, sarangan12 requested changes

2018-10-25 22:15 UTC, jp94 commented on specification/eventgrid/data-plane/Microsoft.Maps/stable/2018-01-01/Maps.json
> +    "paths": {},
I was following examples that are already checked into the `eventgrid/data-plane`, eg https://github.com/Azure/azure-rest-api-specs/blob/master/specification/eventgrid/data-plane/Microsoft.ContainerRegistry/stable/2018-01-01/ContainerRegistry.json.

This schema represents the **data model** for events published through Event Grid publisher, and does not represent a REST method.

2018-10-25 22:33 UTC, jp94 commented on specification/eventgrid/data-plane/Microsoft.Maps/stable/2018-01-01/Maps.json
> +            "properties": {}
We are ready to submit this to the public `azure-rest-api-specs`, and the schema's finalized.

2018-10-30 18:04 UTC, sarangan12 approved these changes

2018-10-30 18:04 UTC, merged

2018-10-30 18:12 UTC, AutorestCI commented
# Automation for azure-sdk-for-java