Add new api-version for Azure SignalR service
Azure/azure-rest-api-specs pull request #4329
Opened 2018-10-25 09:34 UTC by juniwang

Azure SignalR Service is adding a new api-version `2018-10-01` since we already went GA.  However there is no new API comparing to the spec for `2018-03-01-preview`. We only changed the version in readme files, spec and examples.

Quality control:
All validations documented at https://github.com/Azure/adx-documentation-pr/wiki/Azure-Swagger-Tools passed.

2018-10-25 09:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-10-25 09:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-10-25 09:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-10-25 09:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-10-25 09:35 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-10-25 09:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-10-25 20:39 UTC, hovsepm requested changes
@juniwang please reorganize your PR in a way that it will have 2 commits. First one would be simply copy of the existing base version. Second would be all the changes. In that way we will be able to see diff and review.

2018-10-26 02:50 UTC, closed without merging

2018-10-26 02:50 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-10-26 03:01 UTC, juniwang commented
@hovsepm Thanks for the review. A new organized PR sent: https://github.com/Azure/azure-rest-api-specs/pull/4335