Swagger closure for Azure Migration Hub Opeartions
Azure/azure-rest-api-specs pull request #4330
Opened 2018-10-25 15:15 UTC by peetlotla

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-10-25 15:15 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=4330) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=4330) before we can accept your contribution.<br/><br/>:x: peetlotla [sign now](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=4330)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-rest-api-specs?pullRequest=4330) it.</sub>

2018-10-25 15:16 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-10-25 15:16 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-10-25 15:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-10-25 15:20 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-10-25 15:47 UTC, AutorestCI commented
# Automation for azure-sdk-for-js
A PR has been created for you:
https://github.com/Azure/azure-sdk-for-js/pull/321

2018-10-25 15:52 UTC, danschultequb commented on specification/migrateprojects/resource-manager/readme.nodejs.md
> +  output-folder: $(node-sdks-folder)/lib/services/migrateprojects
Please change this to `migrateprojectsManagement`.
```suggestion
  output-folder: $(node-sdks-folder)/lib/services/migrateprojectsManagement
```

2018-10-25 15:53 UTC, danschultequb commented on specification/migrateprojects/resource-manager/readme.nodejs.md
> +  package-name: azure-arm-migrate
Please reflect your service's complete name (`azure-arm-migrateprojects`).
```suggestion
  package-name: azure-arm-migrateprojects
```

2018-10-25 17:55 UTC, lmazuel commented
@AutorestCI rebuild azure-sdk-for-java

2018-10-25 17:55 UTC, AutorestCI commented
<details><summary>Encountered an unknown error</summary><p>

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/azure_devtools/ci_tools/github_tools.py", line 33, in exception_to_github
    yield context
  File "/usr/local/lib/python3.6/dist-packages/azure_devtools/ci_tools/bot_framework.py", line 105, in manage_comment
    response = getattr(self.handler, orderstr)(webhook_data.issue, *split_text)
  File "/usr/local/lib/python3.6/dist-packages/swaggertosdk/restapi/restbot.py", line 36, in rebuild
    self.sdk_default_base
  File "/usr/local/lib/python3.6/dist-packages/swaggertosdk/restapi/github_handler.py", line 151, in rest_pr_management
    sdk_tag=sdk_tag
  File "/usr/local/lib/python3.6/dist-packages/swaggertosdk/SwaggerToSdkNewCLI.py", line 249, in generate_sdk_from_git_object
    with tempfile.TemporaryDirectory() as temp_dir:
  File "/usr/lib/python3.6/tempfile.py", line 931, in __init__
    self.name = mkdtemp(suffix, prefix, dir)
  File "/usr/lib/python3.6/tempfile.py", line 499, in mkdtemp
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
  File "/usr/lib/python3.6/tempfile.py", line 269, in _sanitize_params
    dir = gettempdir()
  File "/usr/lib/python3.6/tempfile.py", line 437, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/lib/python3.6/tempfile.py", line 372, in _get_default_tempdir
    dirlist)
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/git-restapi']

```

</p></details>

2018-10-25 17:56 UTC, lmazuel commented
@AutorestCI rebuild azure-sdk-for-java

2018-10-25 17:56 UTC, AutorestCI commented
<details><summary>Encountered an unknown error</summary><p>

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/azure_devtools/ci_tools/github_tools.py", line 33, in exception_to_github
    yield context
  File "/usr/local/lib/python3.6/dist-packages/azure_devtools/ci_tools/bot_framework.py", line 105, in manage_comment
    response = getattr(self.handler, orderstr)(webhook_data.issue, *split_text)
  File "/usr/local/lib/python3.6/dist-packages/swaggertosdk/restapi/restbot.py", line 36, in rebuild
    self.sdk_default_base
  File "/usr/local/lib/python3.6/dist-packages/swaggertosdk/restapi/github_handler.py", line 151, in rest_pr_management
    sdk_tag=sdk_tag
  File "/usr/local/lib/python3.6/dist-packages/swaggertosdk/SwaggerToSdkNewCLI.py", line 249, in generate_sdk_from_git_object
    with tempfile.TemporaryDirectory() as temp_dir:
  File "/usr/lib/python3.6/tempfile.py", line 931, in __init__
    self.name = mkdtemp(suffix, prefix, dir)
  File "/usr/lib/python3.6/tempfile.py", line 499, in mkdtemp
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
  File "/usr/lib/python3.6/tempfile.py", line 269, in _sanitize_params
    dir = gettempdir()
  File "/usr/lib/python3.6/tempfile.py", line 437, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/lib/python3.6/tempfile.py", line 372, in _get_default_tempdir
    dirlist)
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/git-restapi']

```

</p></details>

2018-10-25 18:01 UTC, ghost requested changes

2018-10-25 18:01 UTC, daschult commented on specification/migrateprojects/resource-manager/readme.nodejs.md
> +  package-name: azure-arm-migrate
Please reflect your service's complete name (`azure-arm-migrateprojects`).
```suggestion
  package-name: azure-arm-migrateprojects
```

2018-10-25 18:01 UTC, daschult commented on specification/migrateprojects/resource-manager/readme.nodejs.md
> +  output-folder: $(node-sdks-folder)/lib/services/migrateprojects
Please change this to `migrateprojectsManagement`.
```suggestion
  output-folder: $(node-sdks-folder)/lib/services/migrateprojectsManagement
```

2018-10-26 10:12 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-11-05 19:40 UTC, praries880 approved these changes

2018-11-05 19:40 UTC, praries880 commented
@daschult are you satisfied with the changes?

2018-11-05 19:54 UTC, ghost approved these changes

2018-11-08 22:53 UTC, praries880 commented
@azuresdkci add to whitelist

2018-11-08 22:54 UTC, merged

2018-11-09 04:42 UTC, peetlotla commented
Hi,

The PR was raised for ARM review. We were not looking forward to merge into master or generate the SDKs for this change as we may have modifications to the swagger based on the review. Can you please revert the merge?

Thanks,
-Peet
From: Pareekshit Singh <notifications@github.com>
Sent: Friday, November 9, 2018 4:24 AM
To: Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com>
Cc: Peetambaram Lotla <pelotla@microsoft.com>; Author <author@noreply.github.com>
Subject: Re: [Azure/azure-rest-api-specs] Swagger closure for Azure Migration Hub Operations (#4330)


Merged #4330<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F4330&data=02%7C01%7Cpelotla%40microsoft.com%7C5ed14a2fb63d4cd21e5d08d645cd2047%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636773144665096512&sdata=Yjj3cJFG2w8ALQIscDL2D5b%2Fab7okn9tKGR7Q%2FBRX0o%3D&reserved=0> into master.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F4330%23event-1955626776&data=02%7C01%7Cpelotla%40microsoft.com%7C5ed14a2fb63d4cd21e5d08d645cd2047%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636773144665096512&sdata=WVGOZbJW0X34lnkA3JnE2jS5znsmcYJxRbL44vkk1is%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAd9AQZEtO7V_tWH8GKyYSW55lFiMyi10ks5utLYegaJpZM4X6g2k&data=02%7C01%7Cpelotla%40microsoft.com%7C5ed14a2fb63d4cd21e5d08d645cd2047%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636773144665106516&sdata=%2FFXTPb3%2Fv3sjML14c9P8K2nUtbdeBfwh%2FqxuAGdVp4Q%3D&reserved=0>.

2018-11-14 10:57 UTC, peetlotla commented
Pareekshit,

Can you please let us know if this is reverted?

From: Peetambaram Lotla
Sent: Friday, November 9, 2018 10:13 AM
To: Azure/azure-rest-api-specs <reply@reply.github.com>; Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com>; Pareekshit Singh <Pareekshit.Singh@microsoft.com>
Cc: Author <author@noreply.github.com>; Gaurav Bhatnagar <Gaurav.Bhatnagar@microsoft.com>
Subject: RE: [Azure/azure-rest-api-specs] Swagger closure for Azure Migration Hub Operations (#4330)

Hi,

The PR was raised for ARM review. We were not looking forward to merge into master or generate the SDKs for this change as we may have modifications to the swagger based on the review. Can you please revert the merge?

Thanks,
-Peet
From: Pareekshit Singh <notifications@github.com<mailto:notifications@github.com>>
Sent: Friday, November 9, 2018 4:24 AM
To: Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com<mailto:azure-rest-api-specs@noreply.github.com>>
Cc: Peetambaram Lotla <pelotla@microsoft.com<mailto:pelotla@microsoft.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: Re: [Azure/azure-rest-api-specs] Swagger closure for Azure Migration Hub Operations (#4330)


Merged #4330<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F4330&data=02%7C01%7Cpelotla%40microsoft.com%7C5ed14a2fb63d4cd21e5d08d645cd2047%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636773144665096512&sdata=Yjj3cJFG2w8ALQIscDL2D5b%2Fab7okn9tKGR7Q%2FBRX0o%3D&reserved=0> into master.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F4330%23event-1955626776&data=02%7C01%7Cpelotla%40microsoft.com%7C5ed14a2fb63d4cd21e5d08d645cd2047%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636773144665096512&sdata=WVGOZbJW0X34lnkA3JnE2jS5znsmcYJxRbL44vkk1is%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAd9AQZEtO7V_tWH8GKyYSW55lFiMyi10ks5utLYegaJpZM4X6g2k&data=02%7C01%7Cpelotla%40microsoft.com%7C5ed14a2fb63d4cd21e5d08d645cd2047%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636773144665106516&sdata=%2FFXTPb3%2Fv3sjML14c9P8K2nUtbdeBfwh%2FqxuAGdVp4Q%3D&reserved=0>.