Adds Rewrite rule set for Header CRUD
Azure/azure-rest-api-specs pull request #4331
Opened 2018-10-25 19:52 UTC by sai-manoj-kumar

Adds the structure of rewriteRuleSets in the applicationGatewayProperties.
Adds recursively the sub structures in the rewriteRuleSet.
Adds the reference to rewriteRuleSet in the requestRoutingRule for both Basic rule and Path based rule.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] The spec follows the guidelines described in the [Swagger checklist](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md) document.
  - [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-10-25 19:52 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-10-25 19:55 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-10-25 19:57 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-10-25 19:58 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-10-25 20:02 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-10-25 20:05 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-10-25 20:05 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-10-29 17:44 UTC, MikhailTryakhov commented
do we need to create any examples?

2018-11-09 05:54 UTC, sai-manoj-kumar commented
> 
> 
> do we need to create any examples?
@MikhailTryakhov , I have added the examples.

2018-11-14 18:59 UTC, dsgouda requested changes

2018-11-14 19:14 UTC, sai-manoj-kumar commented on specification/network/resource-manager/Microsoft.Network/stable/2018-10-01/applicationGateway.json
> +        "name": {
etag is also readOnly. Marked it also as readOnly. No other readOnly properties present.

2018-11-14 19:21 UTC, dsgouda approved these changes
LGTM, will merge when CIs pass. By passing ARM review since this is high pri

2018-11-14 19:58 UTC, sai-manoj-kumar commented
Checks have passed but it is not merged automatically. Should we merge it manually?

2018-11-14 20:48 UTC, merged