Remove security contact phone field mandatory fields
Azure/azure-rest-api-specs pull request #4417
Opened 2018-11-07 15:27 UTC by eliagrady

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.

2018-11-07 15:28 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-11-07 15:28 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-11-07 15:29 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-11-07 15:29 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-11-07 15:30 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-11-07 15:39 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-11-08 22:26 UTC, praries880 requested changes

2018-11-11 09:42 UTC, eliagrady commented on specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/security.json
>                  "alertNotifications",
@praries880 I've updated the security contacts examples

2018-11-11 15:44 UTC, chlahav approved these changes

2018-11-11 15:44 UTC, chlahav commented on specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/examples/SecurityContacts/CreateSecurityContact_full_example.json
> +                    "email": "default1@contoso.com",
change back to john

2018-11-11 15:44 UTC, chlahav commented on specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/examples/SecurityContacts/CreateSecurityContact_min_example.json
> +                    "email": "default2@contoso.com",
change to a real name

2018-11-11 15:44 UTC, chlahav commented on specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/examples/SecurityContacts/GetSecurityContact_full_example.json
> +                    "email": "default1@contoso.com",
change back to john

2018-11-11 15:44 UTC, chlahav commented on specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/examples/SecurityContacts/GetSecurityContact_min_example.json
> +                    "email": "default2@contoso.com",
use a real name

2018-11-11 15:44 UTC, chlahav commented on specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/examples/SecurityContacts/GetSecurityContactsSubscription_full_example.json
> +                        "email": "default1@contoso.com",
john

2018-11-11 15:44 UTC, chlahav commented on specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/examples/SecurityContacts/GetSecurityContactsSubscription_min_example.json
> +                        "email": "default2@contoso.com",
use a real name

2018-11-11 15:44 UTC, chlahav commented on specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/examples/SecurityContacts/UpdateSecurityContact_full_example.json
> +                    "email": "default1@contoso.com",
change back to john

2018-11-11 15:44 UTC, chlahav commented on specification/security/resource-manager/Microsoft.Security/preview/2017-08-01-preview/examples/SecurityContacts/UpdateSecurityContact_min_example.json
> +                    "email": "default2@contoso.com",
use a real name

2018-11-12 18:34 UTC, praries880 approved these changes

2018-11-12 18:34 UTC, merged

2018-11-14 23:57 UTC, jhendrixMSFT commented
@AutorestCI regenerate azure-sdk-for-go