Application Gateway - Adds Rewrite rule set for Header CRUD
Azure/azure-rest-api-specs pull request #4426
Opened 2018-11-08 12:24 UTC by sai-manoj-kumar

Adds the structure of rewriteRuleSets in the applicationGatewayProperties.
Adds recursively the sub structures in the rewriteRuleSet.
Adds the reference to rewriteRuleSet in the requestRoutingRule for both Basic rule and Path based rule.

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.

2018-11-08 12:29 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-11-08 12:30 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-11-08 12:36 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-11-08 12:56 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-11-08 13:03 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-11-08 18:55 UTC, MikhailTryakhov requested changes
please follow one of design in our one note docs.
no need to merge directly to master

2018-11-08 19:04 UTC, dsgouda commented
Closing per Mikhail's review

2018-11-08 19:04 UTC, closed without merging

2018-11-09 05:37 UTC, sai-manoj-kumar commented
Sorry, I have raised to master by mistake.