Add sensitivityLabels.json to readme.md
Azure/azure-rest-api-specs pull request #4479
Opened 2018-11-15 09:48 UTC by bashahee

Removing duplication of sensitivityLabels.json files, and updating readme.md
I noticed that same files are sitting under 2018-06-01-preview and 2017-03-01-preview versions, hence removing duplication. In addition, adding sensitivityLabels.json file to readme.md file.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.

2018-11-15 09:50 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-11-15 09:50 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-11-15 09:50 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-11-15 09:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-11-15 09:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-11-15 09:53 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-11-15 10:06 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-11-19 11:20 UTC, bashahee commented
@jaredmoo can you please review?

2018-11-19 18:49 UTC, jaredmoo requested changes
We are discussing this API offline, please do not merge for now.

2018-11-19 22:12 UTC, bashahee commented
@jaredmoo PR was updated

2018-11-24 18:53 UTC, sarangan12 approved these changes

2018-11-24 18:53 UTC, merged