typo: Fix customer-insights/resource-manager/Microsoft.CustomerInsights/customer-insights
Azure/azure-rest-api-specs pull request #4517
Opened 2018-11-20 04:16 UTC by nschonni

- interation -> interaction
- retreive -> retrieve
- exisiting -> existing
- refered -> referred
- assiciated -> associated
- monified -> modified
- mangement -> management
- ingored -> ignored
- c onnector -> connector
- singnas -> singnals

2018-11-20 04:16 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-11-20 04:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-11-20 04:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-11-20 04:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-11-20 04:18 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-11-20 04:18 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-11-20 04:21 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-11-20 21:14 UTC, amarzavery commented on specification/customer-insights/resource-manager/Microsoft.CustomerInsights/stable/2017-04-26/customer-insights.json
> +          "description": "The singnals used."
si**n**gnals -> signals

2018-11-20 21:15 UTC, amarzavery requested changes
one pending typo fix

2018-11-21 03:00 UTC, nschonni commented on specification/customer-insights/resource-manager/Microsoft.CustomerInsights/stable/2017-04-26/customer-insights.json
> +          "description": "The singnals used."
Fixed

2018-11-21 20:45 UTC, amarzavery approved these changes

2018-11-21 20:45 UTC, merged