Swagger Update: Software Update deployment  addition (Private Preview)
Azure/azure-rest-api-specs pull request #4649
Opened 2018-12-01 03:42 UTC by Atchub

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2018-12-01 03:43 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-12-01 03:43 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-12-01 03:43 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-12-01 03:54 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-12-01 06:32 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-12-01 06:49 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-12-03 16:56 UTC, jhendrixMSFT requested changes
Can you please fix the formatting for all documents as there is inconsistencies with indentation.

2018-12-03 16:56 UTC, jhendrixMSFT commented
@Atchub has this API been reviewed by ARM and/or the API review board?

2018-12-03 16:59 UTC, jhendrixMSFT commented on specification/compute/resource-manager/Microsoft.Compute/preview/2018-11-30-preview/softwareUpdateDeployment.json
> +		"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/SoftwareUpdateDeployments/{softwareUpdateDeploymentName}": {
Is the leading 'S' in `SoftwareUpdateDeployments` supposed to be capitalized?  I believe this is the reason for [this](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/462070669) failure.

2018-12-03 17:02 UTC, jhendrixMSFT commented on specification/compute/resource-manager/Microsoft.Compute/preview/2018-11-30-preview/softwareUpdateDeployment.json
> +		"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/SoftwareUpdateDeployments/{softwareUpdateDeploymentName}/instanceView": {
Missing definition for `softwareUpdateDeploymentName` path parameter.

2018-12-03 17:03 UTC, jhendrixMSFT commented on specification/compute/resource-manager/Microsoft.Compute/preview/2018-11-30-preview/softwareUpdateDeployment.json
> +		"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/SoftwareUpdateDeployments/{softwareUpdateDeploymentName}": {
Is the leading 'S' in `SoftwareUpdateDeploymentName` supposed to be capitalized?  I believe ARM states this should be camel case (please see other instances of this issue).

2018-12-03 18:37 UTC, safeermohammed commented on specification/compute/resource-manager/Microsoft.Compute/preview/2018-11-30-preview/examples/GetSoftwareUpdateDeployment.json
> +		"api-version": "2017-05-15-preview",
Is the API version correct?

2018-12-11 18:08 UTC, jhendrixMSFT commented
@Atchub any update?

2019-01-07 17:08 UTC, jhendrixMSFT commented
Closing due to inactivity.  Please re-open when ready to engage.

2019-01-07 17:08 UTC, closed without merging