[Portal Generated] Review request for Microsoft.Batch to add version 2018-12-01
Azure/azure-rest-api-specs pull request #4720
Opened 2018-12-02 22:32 UTC by kiwidev

If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/app/branch/kiwidev/azure-rest-api-specs/dev-batch-Microsoft.Batch-2018-12-01).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2018-12-02 22:33 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-12-02 22:33 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-12-02 22:33 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-12-02 22:33 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-12-02 22:33 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-12-02 22:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-12-02 22:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-12-03 16:20 UTC, nschonni reviewed
Few things I cleaned up in the other versions already

2018-12-03 16:20 UTC, nschonni commented on specification/batch/resource-manager/Microsoft.Batch/stable/2018-12-01/BatchManagement.json
> +                "description": "The ETag HTTP response header. This is an opaque string. You can use i
visibile -> visible

2018-12-03 16:20 UTC, nschonni commented on specification/batch/resource-manager/Microsoft.Batch/stable/2018-12-01/BatchManagement.json
> +                "description": "The ETag HTTP response header. This is an opaque string. You can use i
visibile -> visible

2018-12-03 16:20 UTC, nschonni commented on specification/batch/resource-manager/Microsoft.Batch/stable/2018-12-01/BatchManagement.json
> +                "description": "The ETag HTTP response header. This is an opaque string. You can use i
VNETs -> VNets

2018-12-03 21:40 UTC, kiwidev commented
Thanks @nschonni, have resolved.

2018-12-03 22:13 UTC, kiwidev commented
FYI @matthchr, @xingwu1

2018-12-03 22:16 UTC, xingwu1 approved these changes

2018-12-03 22:17 UTC, xingwu1 commented
Do not merge until we finish the deployment.

2018-12-03 23:09 UTC, jhendrixMSFT commented
@kiwidev has this been reviewed by ARM?

2018-12-03 23:11 UTC, jhendrixMSFT requested changes
There are a few examples that need fixing, please see the [log](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/463028366) for more info.

2018-12-11 18:09 UTC, jhendrixMSFT commented
@kiwidev any update?

2018-12-11 19:14 UTC, xingwu1 commented
@jhendrixMSFT Service is rolling out. You can merge it now.

2018-12-11 19:36 UTC, xingwu1 commented
@jhendrixMSFT There is a field named "password" which is required for POST. We added this field to the "required" section. However, it will not send back by service when you call GET. Since there is no "writeOnly" supporting for autorest now, I don't know what can we do for the examples.

2018-12-11 20:01 UTC, jhendrixMSFT commented
@xingwu1 has ARM reviewed this API version?

2018-12-11 21:03 UTC, kiwidev commented
@jhendrixMSFT waiting on ARM review. Also waiting for service API version to be enabled, so keeping the "Do Not Merge" label

2018-12-12 08:32 UTC, ravbhatnagar commented
Signing off from ARM side.

2018-12-12 15:31 UTC, jhendrixMSFT commented
@kiwidev please don't forget to look at the model validation failures.

2018-12-12 22:43 UTC, kiwidev commented
@jhendrixMSFT I'm not seeing any model validation failures that aren't covered by suppressions. The OpenAPI Hub portal doesn't show any model validation issues. Can you highlight any that are an issue? Thanks

2018-12-12 23:49 UTC, jhendrixMSFT commented
Thanks for clarifying, I see these were suppressed now although it's odd the task shows as failed but there are no errors, see the [log](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/466686515).  Will sign off.

2018-12-12 23:50 UTC, jhendrixMSFT approved these changes

2018-12-12 23:50 UTC, merged