Adding refresh and get IntegrationRuntimeObjectMetadata API
Azure/azure-rest-api-specs pull request #4724
Opened 2018-12-03 07:18 UTC by meiyan-Li

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2018-12-03 07:19 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-12-03 07:20 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-12-03 07:36 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-12-03 07:39 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-12-03 07:49 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-12-06 21:18 UTC, KrisBash approved these changes
LGTM for ARM

2018-12-07 02:16 UTC, hvermis commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json
> +              "description": "Metadata path"
Needs dot at the end

2018-12-07 02:17 UTC, hvermis commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json
> +        "description": "Refresh a ssis integration runtime object metadata.",
Change to "SSIS"

2018-12-07 02:17 UTC, hvermis commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json
> +        "description": "Get a ssis integration runtime object metadata by specified path. The return is pageable metadata list.",
Same here, and any other if there are more

2018-12-07 02:19 UTC, hvermis commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/examples/IntegrationRuntimeObjectMetadata_Refresh.json
> +        "Location": "https://management.azure.com/subscriptions/12345678-1234-1234-1234-12345678abc/resourceGroups/exampleResourceGroup/providers/Microsoft.DataFactory/factories/exampleFactoryName/in
This URI does not conform to ARM standard, will email you separately

2018-12-07 02:19 UTC, hvermis commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/examples/IntegrationRuntimeObjectMetadata_Refresh.json
> +        "Location": "https://management.azure.com/subscriptions/12345678-1234-1234-1234-12345678abc/resourceGroups/exampleResourceGroup/providers/Microsoft.DataFactory/factories/exampleFactoryName/in
It doesn't block your swagger changes

2018-12-07 02:19 UTC, hvermis approved these changes

2018-12-07 03:48 UTC, meiyan-Li commented
@sergey-shandar Could you help merge the code?

2018-12-07 22:57 UTC, sergey-shandar commented
@meiyan-Li could you fix model validation errors?

2018-12-08 03:46 UTC, amarzavery commented
@meiyan-Li There are model validation failures. Please fix them. You can take a look at the logs over [here](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/464773467#L574).

2018-12-08 03:48 UTC, amarzavery requested changes
fix model validation failures.

2018-12-08 04:16 UTC, meiyan-Li commented
@amarzavery I have fixed my model validation issue. For the existing operation model validation issue, hermins have a backlog to fix it. Please see this PR for more info: https://github.com/Azure/azure-rest-api-specs/pull/3957

2018-12-11 02:55 UTC, meiyan-Li commented
@amarzavery Please help merge this PR

2018-12-11 03:53 UTC, amarzavery approved these changes

2018-12-11 03:53 UTC, merged