Newprofile
Azure/azure-rest-api-specs pull request #4870
Opened 2018-12-10 23:03 UTC by sijuman

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2018-12-10 23:03 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-12-10 23:03 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-12-10 23:03 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-12-10 23:03 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-12-10 23:03 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-12-10 23:03 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-12-10 23:06 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-12-11 23:09 UTC, anuchandy requested changes
@sijuman Many of the resources specified in the profile does not exists. I've pointed around 20+ of them but seems there are more.  Could you please go through entire profile and make sure entries are pointing to existing api-version and resources exists in the spec repo? This is very important to fix before we generate and publish any SDKs.

2018-12-11 23:09 UTC, anuchandy commented on profile/2018-12-01-profile.json
> +                           "internalNotify",
`dnsOperationResults`, `dnsOperationStatuses`, `internalNotify` endpoints does not exists in microsoft.network `2018-05-01`, see [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/dns/resource-manager/Microsoft.Network/stable/2018-05-01/dns.json).

2018-12-11 23:09 UTC, anuchandy commented on profile/2018-12-01-profile.json
> +                             "operationResults",
`operationResults` endpoint is not defined in microsoft.notificationHubs `2016-03-01` see [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/stable/2016-03-01/notificationhubs.json).

2018-12-11 23:09 UTC, anuchandy commented on profile/2018-12-01-profile.json
> +                            "locations/operationstatuses"
`locations/operationresults` and `locations/operationstatuses` endpoint does not exists in microsoft.powerBIDedicated `2017-10-01` see [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/powerbidedicated/resource-manager/Microsoft.PowerBIdedicated/stable/2017-10-01/powerbidedicated.json).

2018-12-13 17:20 UTC, lmazuel commented on profile/2018-12-01-profile.json
> +                        "2017-09-01":[
Nor here https://github.com/Azure/azure-rest-api-specs/tree/master/specification/resources/resource-manager/Microsoft.Authorization/stable

2018-12-14 01:04 UTC, sijuman commented on profile/2018-12-01-profile.json
> +                        "2018-03-01":[
These exist....check https://github.com/Azure/azure-rest-api-specs/tree/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2018-03-01

2018-12-18 00:20 UTC, sijuman commented on profile/2018-12-01-profile.json
> +        "microsoft.features": {
Check underneath Microsoft.Resources folder

2019-04-03 22:53 UTC, salameer commented
Hi @anuchandy what's the status on this, it's been open for a while now

2019-04-17 18:12 UTC, anuchandy commented
@salameer we had email conversation with profile team on this long back, the issue is - many of the model and api declared in this swagger as supported by an api-version is not exists in the spec for that api Version. I haven't heard anything from profile team on this. 

@sijuman closing this PR due to no action. \\cc @joshgav

2019-04-17 18:12 UTC, closed without merging