[AKS]: Remove 200/OK response from reset SP/AAD api
Azure/azure-rest-api-specs pull request #4948
Opened 2018-12-19 19:56 UTC by zqingqing1

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2018-12-19 19:57 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2018-12-19 19:57 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2018-12-19 19:57 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2018-12-19 19:58 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2018-12-19 19:58 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2018-12-19 19:59 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2018-12-19 20:02 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-12-19 20:26 UTC, jhendrixMSFT requested changes
Need confirmation from @ravbhatnagar that returning 202 from a synchronous operation is ok.

2018-12-19 21:30 UTC, zqingqing1 commented on specification/containerservices/resource-manager/Microsoft.ContainerService/preview/2018-08-01-preview/managedClusters.json
> -        "x-ms-long-running-operation": true,
It is a long-running operation, but we only return back the 202 response to customer.

2018-12-19 21:31 UTC, jhendrixMSFT commented on specification/containerservices/resource-manager/Microsoft.ContainerService/preview/2018-08-01-preview/managedClusters.json
> -        "x-ms-long-running-operation": true,
There is no `Location` or `Azure-AsyncOperation` header being returned?

2018-12-19 22:38 UTC, azuresdkci commented
Hello!!

The Rest API Specs team wishes everyone a happy holiday and would like to kindly inform you that responses and review to Pull request will be delayed during the holiday period (now -> 2nds of January) to allow for Awesome reviewers to have an awesome time with their families during the holidays!

Thanks and Have a WONDERFUL HOLIDAY

2018-12-20 18:15 UTC, jhendrixMSFT commented
@zqingqing1 can you please explain why this is being removed?  It's introducing new SDK validation failures, see [here](https://github.com/Azure/azure-rest-api-specs/pull/4948/checks?check_run_id=43074728).  Current requirement is to model the terminal LRO state in the swagger.

2018-12-20 18:37 UTC, zqingqing1 commented
The reason why it is been removed, because 200 is not in the response status of these 2 APIs. So right now, I am thinking maybe we can return operation status as 200 after polling header, if we wanna resolve this error.

2018-12-20 18:44 UTC, jhendrixMSFT commented
@lmazuel I was told you asked to have this validation rule put in place.  Can you please explain the details behind it?

2019-01-03 22:01 UTC, zqingqing1 commented
@jhendrixMSFT, I added 200 response to resolve the error. Please review :)

2019-01-07 17:36 UTC, jhendrixMSFT commented
@zqingqing1 there is a merge conflict, can you please resolve it?

2019-01-08 18:45 UTC, jhendrixMSFT commented
With these changes the generated code no longer returns a `ManagedCluster` object when the LRO completes.  Take a look at the [Go codegen](https://github.com/Azure/azure-sdk-for-go/pull/3829/files#diff-3cc4ae0a07e198ede58c0be8ee523998) for an example.  Is this expected?

2019-01-08 18:47 UTC, zqingqing1 commented
Yes, it is expected.

2019-01-08 18:49 UTC, jhendrixMSFT commented
So when the polling completes the user needs to make a separate API call then to retrieve the result?

2019-01-08 20:51 UTC, zqingqing1 commented
Yes, that is right.

2019-01-08 21:36 UTC, jhendrixMSFT approved these changes

2019-01-08 21:36 UTC, merged