Swagger and examples for Microsoft.DataBoxEdge RP
Azure/azure-rest-api-specs pull request #4952
Opened 2018-12-20 05:21 UTC by anponnet

Swagger and examples for Microsoft.DataBoxEdge RP

2018-12-20 05:32 UTC, azuresdkci commented
Can one of the admins verify this patch?

2018-12-22 03:18 UTC, nschonni commented on specification/edgegateway/resource-manager/Microsoft.DataBoxEdge/stable/2018-07-01/edgedateway.json
> +      "description": "Errordetails for the alert.",
Errordetails -> Error details

2018-12-22 03:18 UTC, nschonni commented on specification/edgegateway/resource-manager/Microsoft.DataBoxEdge/stable/2018-07-01/edgedateway.json
> +          "description": "ErrorDetails of the alert."
Errordetails -> Error details

2018-12-22 03:18 UTC, nschonni commented on specification/edgegateway/resource-manager/Microsoft.DataBoxEdge/stable/2018-07-01/edgedateway.json
> +        "occurences": {
occurences -> occurrences

2018-12-22 03:18 UTC, nschonni commented on specification/edgegateway/resource-manager/Microsoft.DataBoxEdge/stable/2018-07-01/edgedateway.json
> +          "description": "Number of occurences.",
occurences -> occurrences

2018-12-22 03:18 UTC, nschonni commented on specification/edgegateway/resource-manager/Microsoft.DataBoxEdge/stable/2018-07-01/edgedateway.json
> +          "description": "The start time of the schdule in UTC.",
schdule -> schedule

2018-12-22 03:18 UTC, nschonni commented on specification/edgegateway/resource-manager/Microsoft.DataBoxEdge/stable/2018-07-01/edgedateway.json
> +
aggreagtion -> aggregation

2018-12-22 03:18 UTC, nschonni commented on specification/edgegateway/resource-manager/Microsoft.DataBoxEdge/stable/2018-07-01/edgedateway.json
> +
Accessprotocol -> Access protocol

2018-12-22 03:18 UTC, nschonni commented on specification/edgegateway/resource-manager/Microsoft.DataBoxEdge/stable/2018-07-01/edgedateway.json
> +
atleast -> at least

2018-12-22 03:18 UTC, nschonni commented on specification/edgegateway/resource-manager/Microsoft.DataBoxEdge/stable/2018-07-01/edgedateway.json
> +
installl -> install

2019-01-04 19:29 UTC, sarangan12 requested changes

2019-01-07 08:58 UTC, anponnet reviewed
Changes requested are made and pushed

2019-01-07 22:12 UTC, sarangan12 approved these changes

2019-01-07 22:12 UTC, merged