Generating latest spec
Azure/azure-rest-api-specs pull request #4976
Opened 2019-01-03 09:10 UTC by mehm23

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-01-03 09:10 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=4976) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=4976) before we can accept your contribution.<br/><br/>:x: mehm23 [sign now](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=4976)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-rest-api-specs?pullRequest=4976) it.</sub>

2019-01-03 09:11 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-01-03 09:11 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-01-03 09:12 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-01-03 09:14 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2019-01-03 09:33 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-01-03 09:39 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-01-09 22:13 UTC, hovsepm commented
@mehm23 please walk over Breaking Changes and Model Validator errors and fix them. Since you are making changes in the stable swagger there should be no breaking changes.

2019-01-11 20:53 UTC, praries880 commented
@mehm23 have these changes been trough an A/AzureAPI review?

2019-01-14 18:10 UTC, KrisBash commented on specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2016-12-01/bms.json
> +      "description": "BEK is bitlocker encrpytion key.",
Spelling

2019-01-14 18:30 UTC, KrisBash commented on specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2016-12-01/bms.json
> +          "description": "This property will be used as the discriminator for deciding the specific types in the polymorhpic chain of types.",
Spelling

2019-01-14 18:30 UTC, KrisBash commented on specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2016-12-01/bms.json
> +      "description": "SQL specific recoverypoint, specifcally encaspulates full/diff recoverypoint alongwith extended info",
Spelling and spacing errors

2019-01-14 18:30 UTC, KrisBash commented on specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2016-12-01/bms.json
> +      "description": "Workload specific recoverypoint, specifcally encaspulates full/diff recoverypoint",
spelling "specifically"

2019-01-14 18:30 UTC, KrisBash commented on specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2016-12-01/bms.json
> +          "description": "This property will be used as the discriminator for deciding the specific types in the polymorhpic chain of types.",
Spelling - "polymorphic" for all cases

2019-01-14 18:30 UTC, KrisBash commented on specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2016-08-10/operations.json
> +          "description": "List of available operationss.",
Please check spelling throughout. "operations"

2019-01-14 18:34 UTC, KrisBash requested changes
Changes to add the "put" api and SAP definitions appear to be ok for ARM. Numerous spelling errors were introduced in these commits and should be corrected for the benefit of documentation quality.

2019-01-16 21:10 UTC, praries880 commented
@KrisBash Do the latest changes take care of your review comments?

2019-01-17 21:09 UTC, KrisBash approved these changes
LGTM

2019-01-17 21:14 UTC, merged