Fix duplicate path in old Network API versions (Network January branch)
Azure/azure-rest-api-specs pull request #5003
Opened 2019-01-08 08:05 UTC by number213

Pick https://github.com/Azure/azure-rest-api-specs/pull/4940 and https://github.com/Azure/azure-rest-api-specs/pull/5002 from `master` into January branch

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-01-08 08:07 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-01-08 08:13 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-01-08 08:15 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-01-08 08:32 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-01-08 08:44 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-01-08 09:39 UTC, number213 commented
Travis fails with OOM exception
```
v8::Utils::ReportOOMFailure(char const*, bool) [node]\n 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool)
```
I tried linter on my local machine and had the same error. Managed to bypass it by using `--max_old_space_size=8192`.

@dsgouda @jianghaolu could you please take a look?

2019-01-08 09:56 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-01-08 17:37 UTC, dsgouda requested changes
Looks fine apart from the comment.

2019-01-08 17:37 UTC, dsgouda commented on specification/network/resource-manager/Microsoft.Network/stable/2015-06-15/virtualNetworkGateway.json
> -    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/connections/{connectionSharedKeyName}/sharedkey": {
@number213  can you explain how you are fixing duplicate nw paths here

2019-01-09 11:44 UTC, number213 commented
CI failures are related to this issue https://github.com/Azure/azure-rest-api-specs/pull/5008

2019-01-09 19:00 UTC, dsgouda approved these changes
LGTM

2019-01-09 19:01 UTC, merged