Budgets gtm preview
Azure/azure-rest-api-specs pull request #5050
Opened 2019-01-16 22:58 UTC by shalinved

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-01-16 22:59 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-01-16 22:59 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-01-16 23:00 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-01-16 23:01 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2019-01-16 23:04 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-01-16 23:14 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-01-16 23:23 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-01-17 01:11 UTC, nschonni commented on specification/consumption/resource-manager/Microsoft.Consumption/preview/2018-12-01-preview/consumption.json
> +          "description": "Has start and end date of the budget. The start date must be first of the month and should be less than the end date. Budget start date must be on or after June 1, 2017. Fut
timegrain -> time grain

2019-01-22 21:49 UTC, sergey-shandar requested changes
Because it's a new API version, to review it we need two commits. The first one should e a copy of previous API version. The second commit should contain changes.

2019-01-31 19:12 UTC, sergey-shandar requested changes
@shalinved are you still working on this PR?

2019-02-01 19:02 UTC, closed without merging