A script to generate multiapi readme files. OAV update.
Azure/azure-rest-api-specs pull request #5097
Opened 2019-01-26 00:18 UTC by sergey-shandar

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-01-26 00:18 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-01-26 00:18 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-01-26 00:18 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-01-26 00:18 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2019-01-26 00:18 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-01-26 00:18 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-01-26 00:19 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-01-26 01:12 UTC, nschonni commented on package.json
> +    "ts-node": "^8.0.1"
Think this needs to move up, or the next install will re-order it automatically

2019-01-31 18:11 UTC, sergey-shandar commented
See also generated readme files https://github.com/Azure/azure-rest-api-specs/pull/5080/files

2019-02-01 19:43 UTC, veronicagg requested changes
Few questions before approving, regarding the output, the readmes just contain the files to pick up for generation and no other settings, so they won't be suitable to replace any of the existing. If they are used for code generation, how are we consuming the other setting from existing readme files?
Also I see that we're picking up all the file paths and putting them together for generation, is that what the muti-api feature will take as input? 
Code itself looks good to me.

2019-02-01 21:43 UTC, sergey-shandar commented
@veronicagg, @fearthecowboy knows the answers but, I suspect, it's on early stages of development so we cane address these issues after.

2019-02-01 21:49 UTC, veronicagg approved these changes

2019-02-06 00:39 UTC, merged