Swagger changes for ADF newly released features:
Azure/azure-rest-api-specs pull request #5218
Opened 2019-02-17 08:36 UTC by wuchunchunt19

1. I can load data from o365 by leveraging the REST endpoint of o365
2. Support copying incremental files based on lastModifiedTime for S3/File/Blob
3. Enable ADLS Gen2 connector as both source & sink
4. Support data migration from MongoDB to CosmosDB (MongoDB API)
5. Make Kusto source/sink better and support Azure Data exploer source/sink
6. Support copy from ADLS Gen1 to ADLS Gen2 with ACL
7. serviceUrl @ S3 linked service
8. I can copy from Dynamics AX
9. AAD OAuth for OData Linked Service
10. I can copy from Oracle Service Cloud and Google Adwords

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-02-17 08:36 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby
Nothing to generate for azure-sdk-for-ruby

2019-02-17 08:36 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-02-17 08:37 UTC, AutorestCI commented
# Automation for azure-sdk-for-python
<details><summary>Encountered a Subprocess error: (azure-sdk-for-python)</summary><p>

Command: ['/usr/local/bin/autorest', '/tmp/tmpuc1hoxj2/rest/specification/datafactory/resource-manager/readme.md', '--multiapi', '--python', '--python-mode=update', '--python-sdks-folder=/tmp/tmpuc1hoxj2/sdk', '--use=@microsoft.azure/autorest.python@~3.0.56', '--version=preview']
Finished with return code 1
and output:
```shell
AutoRest code generation utility [version: 2.0.4283; node: v8.11.3]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/root/.autorest/@microsoft.azure_autorest-core@2.0.4302/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4302)
   Loading AutoRest extension '@microsoft.azure/autorest.python' (~3.0.56->3.0.58)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.44->2.3.44)
ERROR: Schema violation: Additional properties not allowed: limit,skip,sort,project
    - file:///tmp/tmpuc1hoxj2/rest/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json:705:8 ($.definitions.MongoDbV2Source.properties.cursorMethods)
ERROR: Schema violation: Additional properties not allowed: limit,skip,sort,project
    - file:///tmp/tmpuc1hoxj2/rest/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json:742:8 ($.definitions.CosmosDbMongoDbApiSource.properties.cursorMethods)
ERROR: Schema violation: Expected type string but found type object
    - file:///tmp/tmpuc1hoxj2/rest/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/LinkedService.json:1854:10 ($.definitions.AmazonS3LinkedServiceTypeProperties.properties.serviceUrl.description)
FATAL: swagger-document/individual/schema-validator - FAILED
FATAL: Error: [OperationAbortedException] Error occurred. Exiting.
Process() cancelled due to exception : [OperationAbortedException] Error occurred. Exiting.
```

</p></details>

2019-02-17 08:37 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2019-02-17 08:37 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-02-17 08:38 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-02-17 08:39 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-02-18 01:21 UTC, nschonni commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/LinkedService.json
> +      "description": "Google Awords service linked service.",
Awords 0-> AdWords

2019-02-18 01:21 UTC, nschonni commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/LinkedService.json
> +      "description": "Dynamics AXlinked service properties.",
AXlinked -> AX linked

2019-02-18 05:17 UTC, wuchunchunt19 commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/LinkedService.json
> +      "description": "Google Awords service linked service.",
Thanks for the reminder. Fixed.

2019-02-18 05:17 UTC, wuchunchunt19 commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/LinkedService.json
> +      "description": "Dynamics AXlinked service properties.",
Thanks for the reminder. Fixed.

2019-02-20 00:42 UTC, veronicagg requested changes
Thanks for submitting the PR. Have these changes been reviewed by ARM team? 
Based on the title looks like these updates have been released already, is that correct? 
Please note that these changes are on a stable spec and may cause breaking changes in SDKs (or data loss for existing clients).

2019-02-20 03:26 UTC, wuchunchunt19 commented
Yes, you are correct. These updates are already released in our product, most of them have been released for several months.
Besides, these changes are all newly add-on entity models which won't bring any breaking changes, and it also doesn't impact any existing API. Do we need ARM team review on this?

2019-02-20 18:26 UTC, veronicagg commented
@wuchunchunt19 thanks for your response. Regarding the new entity models, just be aware that old/current SDK generated clients will not have them, so if the service responds with the new model the currently released clients won't know about them. New versions of SDKs released from this version of the spec, will contain the update. Thanks!

2019-02-20 18:27 UTC, veronicagg approved these changes

2019-02-20 18:28 UTC, merged