Elastic Server Restart
Azure/azure-rest-api-specs pull request #5244
Opened 2019-02-21 20:50 UTC by ravindrakreddy

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-02-21 20:50 UTC, ravindrakreddy commented
Adding Qingqing Yuan to review the code

2019-02-21 20:50 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-02-21 20:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-02-21 20:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-02-21 20:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-02-21 20:52 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2019-02-21 20:53 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-02-21 21:12 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-02-22 18:06 UTC, praries880 requested changes

2019-02-22 18:53 UTC, ravindrakreddy commented on specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2017-12-01/mysql.json
> +        "operationId": "Server_Restart",
fixed

2019-02-22 18:53 UTC, ravindrakreddy commented on specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2017-12-01/postgresql.json
> +        "operationId": "Server_Restart",
fixed

2019-02-22 19:20 UTC, praries880 approved these changes

2019-02-22 23:20 UTC, ravbhatnagar reviewed
just one minor note. Please add the default response.

2019-02-22 23:20 UTC, ravbhatnagar commented on specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2017-12-01/postgresql.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DBforPostgreSQL/servers/{serverName}/restart": {
"Default" response missing from all APIs. Please add. sample here - https://github.com/Azure/azure-rest-api-specs/blob/master/specification/batch/resource-manager/Microsoft.Batch/stable/2018-12-01/BatchManagement.json#L101

2019-02-23 01:32 UTC, ravindrakreddy commented on specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2017-12-01/postgresql.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DBforPostgreSQL/servers/{serverName}/restart": {
fixed.

2019-02-23 01:33 UTC, ravbhatnagar commented
Signing off from ARM side.

2019-02-25 21:00 UTC, praries880 commented
@ravindrakreddy  [Build is breaking](https://travis-ci.org/Azure/azure-rest-api-specs/jobs/497332465#L569) because the definition of [`#/definitions/CloudError`](https://github.com/Azure/azure-rest-api-specs/pull/5244/commits/517ef876682c88a58342f72eb583818173e2a335#diff-7cd2ea152db3e6d1d7b53d7ce09d8faaR320) can not be found. Can you validate that you are referencing the correct type and its in the path specified?

2019-02-26 01:10 UTC, praries880 approved these changes

2019-02-26 01:10 UTC, merged