Add missing MarketplaceOrdering operations to swagger
Azure/azure-rest-api-specs pull request #5279
Opened 2019-02-27 03:21 UTC by zachraMSFT

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-02-27 03:23 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-02-27 03:23 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-02-27 03:29 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-02-27 03:30 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-02-27 03:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2019-02-27 03:42 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-02-27 04:14 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-03-01 18:45 UTC, sergey-shandar commented
@zachraMSFT could you update your branch (merge the latest changes from master)?

2019-03-02 03:05 UTC, zachraMSFT commented
> @zachraMSFT could you update your branch (merge the latest changes from master)?

Did that and added the examples to resolve the failing auto checks

2019-03-04 19:01 UTC, ghost requested changes

2019-03-04 19:01 UTC, daschult commented on specification/marketplaceordering/resource-manager/Microsoft.MarketplaceOrdering/stable/2015-06-01/Agreements.json
> +        "description": "Get marketplace agreements.",
```suggestion
        "description": "Get marketplace agreement.",
```

2019-03-04 19:01 UTC, daschult commented on specification/marketplaceordering/resource-manager/Microsoft.MarketplaceOrdering/stable/2015-06-01/Agreements.json
> +        "description": "List marketplace agreements.",
```suggestion
        "description": "List marketplace agreements in the subscription.",
```

2019-03-05 01:34 UTC, zachraMSFT commented
@daschult It looks like the checks failed due to some internal failure (IP not accessible). Is there something I should do to resolve that?

2019-03-05 17:48 UTC, daschult commented
Closing and reopening to restart CI.

2019-03-05 18:12 UTC, ghost approved these changes

2019-03-05 18:12 UTC, merged