Adding Private Endpoints (formerly Interface Endpoints)
Azure/azure-rest-api-specs pull request #5293
Opened 2019-02-28 03:37 UTC by rupalivohra

### Reviewers Please Note
I'm creating this PR for ARM reviewers to have extra clarity on the changes to the resources.
Please do not review this PR - it can't be checked in until the network-march-release branch is ready.
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-02-28 03:38 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-02-28 03:43 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-02-28 03:45 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-02-28 03:54 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-02-28 04:04 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-02-28 04:38 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2019-02-28 04:53 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-03-02 07:28 UTC, KrisBash requested changes
Please see the few comments. Thanks

2019-03-02 07:28 UTC, KrisBash commented on specification/network/resource-manager/Microsoft.Network/stable/2019-02-01/privateEndpoint.json
> +            "description": "The name of the private endpoint."
Please add the "default" response to model errors, i.e. :
``
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "./network.json#/definitions/Error"
            }
          }
``

2019-03-02 07:28 UTC, KrisBash commented on specification/network/resource-manager/Microsoft.Network/stable/2019-02-01/privateEndpoint.json
> +              "$ref": "#/definitions/PrivateEndpoint"
Please add the "default" response to model errors, i.e. :
``
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "./network.json#/definitions/Error"
            }
          }
``

2019-03-02 07:28 UTC, KrisBash commented on specification/network/resource-manager/Microsoft.Network/stable/2019-02-01/privateEndpoint.json
> +            "description": "Update successful. The operation returns the resulting PrivateEndpoint resource.",
See above regarding "default" response

2019-03-02 07:28 UTC, KrisBash commented on specification/network/resource-manager/Microsoft.Network/stable/2019-02-01/privateEndpoint.json
> +        "manualPrivateLinkServiceConnection": {
Is this used? Is it intended to be identical to `privateLinkServiceConnection`

2019-03-19 01:12 UTC, MikhailTryakhov commented
closed due to milestone was missed. please retarget to newer branch when it's ready

2019-03-19 01:12 UTC, closed without merging