[Datafactory] Add upgrade api
Azure/azure-rest-api-specs pull request #5297
Opened 2019-02-28 18:18 UTC by leonliang33

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ x ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ x ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ x ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-02-28 18:18 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-02-28 18:20 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-02-28 18:23 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-02-28 18:29 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2019-02-28 18:46 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-02-28 20:38 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-02-28 23:08 UTC, hvermis approved these changes

2019-03-03 23:30 UTC, anuchandy commented
Requesting ARM review since this introduces a new api to stable API Version? 
cc @KrisBash @ravbhatnagar

2019-03-06 18:33 UTC, anuchandy commented
@KrisBash @ravbhatnagar could you take a look please?

2019-03-11 21:58 UTC, sanjaiganesh commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json
> +            }
I don't think you would like to return the resource representation here.. just 200 (OK) should be good.

2019-03-11 21:58 UTC, sanjaiganesh commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json
> +            }
+ @ravbhatnagar

2019-03-12 00:41 UTC, sanjaiganesh commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json
> +            }
Can you add more details on the upgrade behavior ? whether it is a one time thing, in the life cycle of a resource ? 
POST can't be expressed in ARM template and is discouraged for things that customer would like to express them in declarative manner (in template). 

---
In reply to: [264448182](https://github.com/Azure/azure-rest-api-specs/pull/5297#discussion_r264448182) [](ancestors = 264448182)

2019-03-12 02:27 UTC, hvermis requested changes
Please do not merge these changes. It seems we do not need this API.

2019-03-12 02:36 UTC, adxsdknet commented
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5403 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5403/commits/f83f3730df3ca5c613e49c9f8366428b90405827

2019-04-17 18:04 UTC, anuchandy commented
Requesting for reviewer reassign since I'm OOF

2019-04-23 18:03 UTC, salameer commented
@hvermis if this is not deleted please close this PR

2019-04-23 18:04 UTC, closed without merging

2019-04-23 18:04 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby