[Hub Generated] Review request for Microsoft.CognitiveServices to add version 2017-04-18
Azure/azure-rest-api-specs pull request #5355
Opened 2019-03-11 07:20 UTC by DavidLiCIG

If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/app/branch/DavidLiCIG/azure-rest-api-specs/dev-cognitiveservices-Microsoft.CognitiveServices-2017-04-18).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2019-03-11 07:20 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-03-11 07:20 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-03-11 07:21 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-03-11 07:21 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-03-11 07:21 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-03-11 07:21 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2019-03-11 07:22 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-03-13 15:19 UTC, anuchandy commented on specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2017-04-18/cognitiveservices.json
> +        "description": "Check available SKUs.",
Is the description correct? I thought this API is to check availability of domain name.

2019-03-13 15:19 UTC, anuchandy commented on specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2017-04-18/cognitiveservices.json
> +        "operationId": "Locations_CheckDomainAvailabilityPost",
it would be good if we can rename operation id to `Locations_CheckDomainAvailability`, no need to include underneath HTTP verb in the method name

2019-03-13 15:19 UTC, anuchandy commented on specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2017-04-18/cognitiveservices.json
> +            "description": "Check Domain Availability POST body."
you could say "Check Domain Availability parameter."

2019-03-18 18:33 UTC, dsgouda commented
@anuchandy Please disregard the `default` failures here

2019-03-18 18:44 UTC, adxsdknet commented
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5493 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5493/commits/d0ff9dae223b90ba0cdaac44a5e0a67d26b96a28

2019-03-21 15:37 UTC, anuchandy requested changes
@dsgouda thanks for the heads up. @DavidLiCIG can you make necessary updates based on our team discussion?

2019-04-04 20:17 UTC, anuchandy commented
@DavidLiCIG could you please update the PR as we discussed?

2019-04-09 00:49 UTC, anuchandy commented
Closing due to inactivity. @DavidLiCIG please open a new PR when you're ready. thanks!

2019-04-09 00:49 UTC, closed without merging