[Hub Generated] Review request for Microsoft.Devices to add version 2019-03-12
Azure/azure-rest-api-specs pull request #5404
Opened 2019-03-15 21:16 UTC by jlian

If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/app/branch/jlian/azure-rest-api-specs/dev-iothub-Microsoft.Devices-ops-mon-stable).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2019-03-15 21:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-03-15 21:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-03-15 21:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-03-15 21:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2019-03-15 21:19 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-03-15 21:19 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-03-15 21:20 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-03-15 21:23 UTC, adxsdknet commented
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5478 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5478/commits/0c60a919da00031c0b3a2ef8a4bbb775c07c85a7

2019-03-18 16:42 UTC, dsgouda requested changes

2019-03-18 16:42 UTC, dsgouda commented on specification/iothub/resource-manager/Microsoft.Devices/stable/2019-03-12/examples/iothub_delete.json
> +                "id": "/subscriptions/91d12660-3dec-467a-be2a-213b5544ddc0/resourceGroups/myResourceGroup/providers/Microsoft.Devices/IotHubs/testHub",
nit: its good practice to avoid using production style subscription ids

2019-03-18 16:43 UTC, dsgouda commented
Looks good for the most part, just need a quick approval from ARM for the deleted models

2019-03-18 17:59 UTC, jlian commented
Thanks. This means we have to meet with ARM team right?

2019-03-18 18:09 UTC, dsgouda commented
@jlian ARM will post their comments on this PR, don't think you need to meet them since it is a relatively small change

2019-03-18 18:15 UTC, jlian commented
Ok thanks. We're not ready for this to be merged into master yet (I'm preempting a little with this PR). Just want to make sure that we can get a heads up before the merge? Or is there a "hold-off" label like docs we can use?

2019-03-18 18:17 UTC, dsgouda commented
I have added the `DoNotMerge` label

2019-03-25 23:34 UTC, dsgouda commented
startbuild

2019-03-26 17:35 UTC, dsgouda commented
startbuild

2019-04-02 16:20 UTC, KrisBash approved these changes
LGTM

2019-04-02 16:49 UTC, dsgouda approved these changes
LGTM

2019-04-02 16:50 UTC, dsgouda commented
@jlian We are ready to merge this one. Please let us know when we can.

2019-04-02 17:56 UTC, jlian commented
We're still getting ready on our side. Sorry for the delay

2019-04-10 18:54 UTC, dsgouda commented
@jlian gentle reminder, we will close the PR by EOW if there is no activity

2019-04-12 20:30 UTC, dsgouda commented
startbuild

2019-04-13 00:54 UTC, jlian commented
Gonna close this until we can figure it out form our end

2019-04-13 00:54 UTC, closed without merging