Creating stable version for settings type
Azure/azure-rest-api-specs pull request #5435
Opened 2019-03-20 14:12 UTC by chlahav

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-03-20 14:12 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-03-20 14:12 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-03-20 14:12 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-03-20 14:12 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-03-20 14:13 UTC, AutorestCI commented
# Automation for azure-sdk-for-node

2019-03-20 14:13 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-03-20 14:17 UTC, adxsdknet commented
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/-1 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/-1/commits/

2019-03-20 14:23 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-03-20 23:06 UTC, eliagrady commented on specification/security/resource-manager/readme.md
> +These settings apply only when `--tag=package-composite-v3` is specified on the command line.
v3 in v2 section

2019-03-20 23:07 UTC, eliagrady commented on specification/security/resource-manager/readme.md
> +- Microsoft.Security/stable/2018-06-01/pricings.json
I think we should sort by api-version date like [sql did here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/readme.md)

2019-03-20 23:08 UTC, eliagrady requested changes
Minor changes

2019-03-28 21:03 UTC, sergey-shandar requested changes

2019-03-28 21:03 UTC, sergey-shandar commented on specification/security/resource-manager/readme.md
> +### Tag: package-composite-v2
```suggestion
### Tag: package-composite-v3
```

2019-04-02 20:35 UTC, KrisBash approved these changes
LGTM

2019-04-03 04:28 UTC, eliagrady approved these changes

2019-04-06 14:58 UTC, sergey-shandar approved these changes

2019-04-06 14:58 UTC, merged