Updating description for enableAutomaticUpdates and enableAutomaticOS…
Azure/azure-rest-api-specs pull request #5503
Opened 2019-03-28 22:58 UTC by Deepali-Gupta

…Upgrade

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-03-28 22:58 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-03-28 23:00 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-03-28 23:00 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-03-28 23:00 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-03-28 23:02 UTC, Deepali-Gupta commented
Hi,

I was just made aware that we have to make swagger changes on the Github repo. Can you please review this change? https://github.com/Azure/azure-rest-api-specs/pull/5503
I had earlier made a PR to the Core repo (https://msazure.visualstudio.com/DefaultCollection/One/_git/Compute-CPlat-Core/pullrequest/1521548).
Please let me know if anything else is required.

Thanks,
Deepali

From: Azure Builder <notifications@github.com>
Sent: Thursday, March 28, 2019 3:59 PM
To: Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com>
Cc: Deepali Gupta <Deepali.Gupta@microsoft.com>; Author <author@noreply.github.com>
Subject: Re: [Azure/azure-rest-api-specs] Updating description for enableAutomaticUpdates and enableAutomaticOS… (#5503)
Importance: High


Can one of the admins verify this patch?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F5503%23issuecomment-477801273&data=02%7C01%7CDeepali.Gupta%40microsoft.com%7C1adeb16ebc0845753f5308d6b3d0ee9f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636894107272041402&sdata=xhBpeXcHSoD5MoDeDrNSJ8b%2FTBSL30QNFhOtNcORsi4%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL9KG6SRgwwk3aZr-z1OhxpPm-Q8CpuYks5vbUklgaJpZM4cRS9q&data=02%7C01%7CDeepali.Gupta%40microsoft.com%7C1adeb16ebc0845753f5308d6b3d0ee9f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636894107272051406&sdata=xnTnElZjtCeFh6f1k0CBjcq8XorPWFQEq%2FASep5ysao%3D&reserved=0>.

2019-03-28 23:03 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-03-28 23:05 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-03-28 23:25 UTC, jhendrixMSFT commented
@Deepali-Gupta this contains breaking changes in a stable API version, is that intended?

2019-03-28 23:37 UTC, Deepali-Gupta commented
Hi, Do all tests pass after your update?

It looks like this is a breaking change, because you are changing some objects.

Do you really need this change with the same API version?

Thanks,

Hyonho

From: Deepali Gupta <Deepali.Gupta@microsoft.com>
Sent: Thursday, March 28, 2019 4:02 PM
To: Azure/azure-rest-api-specs <reply@reply.github.com>; Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com>
Cc: Ravikiran Reddy <raredd@microsoft.com>; Hyonho Lee <Hyonho.Lee@microsoft.com>
Subject: RE: [Azure/azure-rest-api-specs] Updating description for enableAutomaticUpdates and enableAutomaticOS… (#5503)

Hi,

I was just made aware that we have to make swagger changes on the Github repo. Can you please review this change? https://github.com/Azure/azure-rest-api-specs/pull/5503<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F5503&data=02%7C01%7CHyonho.Lee%40microsoft.com%7C673380b6e2444a2dac9408d6b3d170c3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636894109477033601&sdata=GandvDeX%2FsXXrjH8tKbPeoywp8cAQ57HjQHk%2BfeEIq4%3D&reserved=0>
I had earlier made a PR to the Core repo (https://msazure.visualstudio.com/DefaultCollection/One/_git/Compute-CPlat-Core/pullrequest/1521548<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmsazure.visualstudio.com%2FDefaultCollection%2FOne%2F_git%2FCompute-CPlat-Core%2Fpullrequest%2F1521548&data=02%7C01%7CHyonho.Lee%40microsoft.com%7C673380b6e2444a2dac9408d6b3d170c3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636894109477043605&sdata=bKNV5QWyQBuPuse0RuVK%2F9Ii4Qnk0RjzG%2B67VCCmbPc%3D&reserved=0>).
Please let me know if anything else is required.

Thanks,
Deepali

From: Azure Builder <notifications@github.com<mailto:notifications@github.com>>
Sent: Thursday, March 28, 2019 3:59 PM
To: Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com<mailto:azure-rest-api-specs@noreply.github.com>>
Cc: Deepali Gupta <Deepali.Gupta@microsoft.com<mailto:Deepali.Gupta@microsoft.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: Re: [Azure/azure-rest-api-specs] Updating description for enableAutomaticUpdates and enableAutomaticOS… (#5503)
Importance: High


Can one of the admins verify this patch?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F5503%23issuecomment-477801273&data=02%7C01%7CHyonho.Lee%40microsoft.com%7C673380b6e2444a2dac9408d6b3d170c3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636894109477053618&sdata=SFG%2B9vSEmlXzR3WwsRyvdUbUroz%2FB9lmub0tN3J2vR0%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL9KG6SRgwwk3aZr-z1OhxpPm-Q8CpuYks5vbUklgaJpZM4cRS9q&data=02%7C01%7CHyonho.Lee%40microsoft.com%7C673380b6e2444a2dac9408d6b3d170c3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636894109477053618&sdata=jw%2F4GVMY30fgJfqzjT1n%2BPzNmPbGdJOfSDB3PNKXZmk%3D&reserved=0>.

2019-03-29 16:50 UTC, jhendrixMSFT commented
@AutorestCI regenerate azure-sdk-for-go

2019-04-03 22:29 UTC, KrisBash requested changes
Please see comment

2019-04-03 22:29 UTC, KrisBash commented on specification/compute/resource-manager/Microsoft.Compute/stable/2018-10-01/compute.json
> +          "description": "Indicates whether virtual machine is enabled for automatic windows updates. <br> <br> Default behavior is true."
Swagger definitions look fine for this. However, there are risks in adding new properties to an existing API version. When updated and non-updated clients have different models for the resource, updates can be ambiguous as to whether a missing property was an intentional removal or simply the result of a downlevel client. Do these need to be added to an existing API version or can they go out in a new version?

2019-04-04 21:45 UTC, KrisBash approved these changes
Property additions are spurious and due to separation of definitions for two resource types to expose discrete definitions. LGTM

2019-04-11 17:05 UTC, jhendrixMSFT commented
@AutorestCI regenerate azure-sdk-for-go

2019-04-11 17:16 UTC, AutorestCI commented
<details><summary>Encountered an unknown error</summary><p>

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/azure_devtools/ci_tools/github_tools.py", line 33, in exception_to_github
    yield context
  File "/usr/local/lib/python3.6/dist-packages/azure_devtools/ci_tools/bot_framework.py", line 105, in manage_comment
    response = getattr(self.handler, orderstr)(webhook_data.issue, *split_text)
  File "/usr/local/lib/python3.6/dist-packages/swaggertosdk/restapi/restbot.py", line 54, in regenerate
    return self.rebuild(issue, repotag)
  File "/usr/local/lib/python3.6/dist-packages/swaggertosdk/restapi/restbot.py", line 36, in rebuild
    self.sdk_default_base
  File "/usr/local/lib/python3.6/dist-packages/swaggertosdk/restapi/github_handler.py", line 151, in rest_pr_management
    sdk_tag=sdk_tag
  File "/usr/local/lib/python3.6/dist-packages/swaggertosdk/SwaggerToSdkNewCLI.py", line 309, in generate_sdk_from_git_object
    sdk_repo.git.push('origin', base_branch, set_upstream=True)
  File "/usr/local/lib/python3.6/dist-packages/git/cmd.py", line 548, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push --set-upstream origin restapi_auto_compute/resource-manager
  stderr: 'To https://github.com/Azure/azure-sdk-for-go.git
 ! [rejected]            restapi_auto_compute/resource-manager -> restapi_auto_compute/resource-manager (fetch first)
error: failed to push some refs to 'https://AutorestCI:58ab395c311d1bd75b3e1db1cc8adaf9acc42afe@github.com/Azure/azure-sdk-for-go.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'

```

</p></details>

2019-04-18 16:12 UTC, jhendrixMSFT requested changes
The 2019-03-01 compute.json swagger already exists in master.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-03-01/compute.json
This is causing a merge conflict.  Please rebase on top of latest master.

2019-04-18 19:22 UTC, jhendrixMSFT commented
Superseded by https://github.com/Azure/azure-rest-api-specs/pull/5697

2019-04-18 19:22 UTC, closed without merging