Swagger spec change for Namespace Sku and patch op
Azure/azure-rest-api-specs pull request #553
Opened 2016-09-19 19:57 UTC by amolr

Includes the newly incorporated Sku change in the namespace and patch operation for namespaces

2016-09-19 19:57 UTC, azurecla commented
Hi __@amolr__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (amolr). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-09-20 01:03 UTC, amarzavery commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +	  "patch": {
indentation 2 spaces.

2016-09-20 01:03 UTC, amarzavery commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +		"responses": {
replace tabs with spaces and indentation 2 spaces

2016-09-20 01:04 UTC, amarzavery commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +				"description": "Namespace is Create/Update",
"Namespace is updated"

2016-09-20 01:05 UTC, amarzavery commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +		"description":""
general comment: empty descriptions are not allowed.

2016-09-20 01:06 UTC, amarzavery commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +	 "properties": {
What are the required properties of "Sku"?

Can name, tier, family, capacity, size be enums? Do they have a finite set of values? How will the user know what values to provide?

2016-09-20 01:06 UTC, amarzavery requested changes

2016-09-21 17:32 UTC, anudeepsharma commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +		"operationId": "Namespaces_Patch",
Namespace_Update, Patch seems too technical

2016-09-21 17:32 UTC, anudeepsharma commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +		"description": "Patches the existing namespace",
Updates

2016-09-21 17:32 UTC, anudeepsharma commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +            "description": "The name of the resource group."
@amarzavery Yesterday you were showing me to put something here, is this applicable to this PR as well.

2016-09-21 17:33 UTC, anudeepsharma commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +              "$ref": "#/definitions/NamespacePatchParameters"
NamespaceUpdateParameters

2016-09-21 17:34 UTC, anudeepsharma commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +            "description": "Parameters supplied to create a Namespace Resource."
Properties to be updated in Namespace resource

2016-09-21 17:35 UTC, anudeepsharma commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +      "description": "Parameters supplied to the Patch Namespace operation."
Parameters supplied to the update Namespace resource.

2016-09-21 17:36 UTC, anudeepsharma commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> -          "readOnly": true,
Not sure why would you remove it, name from the body does not suppose to be used by RP, so this suppose to be read only.

2016-09-21 17:36 UTC, anudeepsharma commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +		"sku": {
Fix indentation

2016-09-21 17:37 UTC, anudeepsharma approved these changes
Approved with comments.

2016-09-21 17:40 UTC, amarzavery commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +		"operationId": "Namespaces_Patch",
That is the recommended pattern. That makes things clear to the customer that it is a PATCH operation.

2016-09-21 17:57 UTC, amarzavery commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +            "description": "The name of the resource group."
@anudeepsharma This [extension](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-extensions.md#x-ms-parameter-location) should provide you more info.

2016-09-21 21:21 UTC, amolr commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> -          "readOnly": true,
This was caused by remote merge

2016-09-21 21:29 UTC, amarzavery commented on arm-notificationhubs/2016-03-01/swagger/notificationhubs.json
> +          ]
```
"x-ms-enum": {
   "name": "SkuName",
   "modelAsString": true
}
```

2016-09-22 01:02 UTC, amarzavery approved these changes

2016-09-22 01:03 UTC, merged

2016-09-22 01:56 UTC, AutorestCI commented
No modification for Python

2016-09-22 02:00 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-node.svg?branch=RestAPI-PR553)](https://travis-ci.org/AutorestCI/azure-sdk-for-node) https://github.com/Azure/azure-sdk-for-node/pull/1897

2016-09-22 02:01 UTC, AutorestCI commented
No modification for Ruby