Network mar
Azure/azure-rest-api-specs pull request #5578
Opened 2019-04-08 17:05 UTC by khannarheams

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-04-08 17:08 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-04-08 17:14 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-04-08 17:20 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-04-08 17:20 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-04-08 17:36 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-04-08 17:50 UTC, dsgouda commented
@khannarheams 
- Please target the appropriate branch
@MikhailTryakhov Please take a look

2019-04-08 17:57 UTC, nschonni commented on specification/network/resource-manager/Microsoft.Network/stable/2019-02-01/applicationGateway.json
> +
SSDL -> SSL?

2019-04-08 17:57 UTC, nschonni commented on specification/network/resource-manager/Microsoft.Network/stable/2019-02-01/webapplicationfirewall.json
> +        "negationConditon": {
```suggestion
        "negationCondition": {
```

2019-04-08 18:26 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-04-09 23:49 UTC, MikhailTryakhov requested changes
1) please follow our process [https://microsoft.sharepoint.com/teams/WAG/AzureNetworking/_layouts/OneNote.aspx?id=%2Fteams%2FWAG%2FAzureNetworking%2FOneNotes%2FNRP%20migrated&wd=target%28Hydra%20%2B%20SDK.one%7C96F7B95B-A378-4CA5-903B-C88F894873EF%2FSwagger%20-%3E%20SDK%20-%3E%20PowerShell%20Process%20Overview%7C71B816ED-DAE5-4907-94D8-DE7EE13278A0%2F%29](One Note)

2) please target to ```network-march-release```
3) please DON'T MAKE functional changes in older API? We're not sure all of them may be supported on the server side
4) azure firewall just removed "Alert" from swagger, why are you returning this?

2019-04-09 23:56 UTC, closed without merging