SSIS File System Support
Azure/azure-rest-api-specs pull request #5588
Opened 2019-04-09 09:31 UTC by HaoQian-MS

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-04-09 09:31 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-04-09 09:32 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-04-09 09:33 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-04-09 09:37 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-04-09 09:42 UTC, adxsdknet commented
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5739 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5739/commits/d5e28c6bf69a6eb471530e44648e39f3d63be349

2019-04-09 10:00 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-04-09 23:28 UTC, veronicagg requested changes
Have the changes to these properties been deployed in the API already?

2019-04-10 00:10 UTC, nschonni commented on specification/datafactory/resource-manager/Microsoft.DataFactory/preview/2017-09-01-preview/entityTypes/Pipeline.json
> +          "description": "SSIS package exection log location.",
```suggestion
          "description": "SSIS package execution log location.",
```

2019-04-10 00:10 UTC, nschonni commented on specification/datafactory/resource-manager/Microsoft.DataFactory/preview/2017-09-01-preview/entityTypes/Pipeline.json
> +      "description": "SSIS package exection log location",
```suggestion
      "description": "SSIS package execution log location",
```

2019-04-10 00:10 UTC, nschonni commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json
> +          "description": "SSIS package exection log location.",
```suggestion
          "description": "SSIS package execution log location.",
```

2019-04-10 00:10 UTC, nschonni commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json
> +      "description": "SSIS package exection log location",
```suggestion
      "description": "SSIS package execution log location",
```

2019-04-10 00:40 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-04-12 22:53 UTC, veronicagg commented
@HaoQian-MS please let me know if the properties have been deployed, if so I can approve and merge this PR. 
Please resolve conflicts.

2019-04-15 03:44 UTC, HaoQian-MS commented
@veronicagg , we decided to hold this change currently as some adjustment is needed for our feature.

2019-04-15 18:27 UTC, veronicagg commented
@HaoQian-MS ok, thanks for letting me know. Should we close the PR until you're ready to come back to it?

2019-04-16 02:30 UTC, HaoQian-MS commented
@veronicagg  , if it's closed, can I reopen it later? If not, can we keep it open?

2019-04-16 18:23 UTC, veronicagg commented
@HaoQian-MS yes, we can reopen it at anytime, just let me know if you're not able to reopen it. Thanks!

2019-04-16 18:23 UTC, closed without merging