support for 2016-07-01-preview updates
Azure/azure-rest-api-specs pull request #561
Opened 2016-09-21 19:24 UTC by r22016

created a new version of swagger spec that includes changes to support the latest preview api updates

testing:

- used autorest to generate C# sdk on local machine
- built new version of sdk and verified existing tests pass
- updated tests to include calls to service updates, verified that these work

2016-09-21 19:24 UTC, azurecla commented
Hi __@r22016__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (rameshr). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2016-09-21 19:27 UTC, amarzavery commented on arm-servermanagement/2016-07-01-preview/servermanagement.json
> +{
indentation 2 spaces.
If using VS  Ctrl + A and then Ctrl + K + D.
Make sure that tab are set to 2 spaces and are also replaced by spaces in Tools -> Options settings for json documents.

2016-09-21 19:28 UTC, amarzavery commented
@fearthecowboy - you should definitely review this.

2016-09-21 19:57 UTC, fearthecowboy commented
thanks @amarzavery  .. on it!

2016-09-21 21:03 UTC, fearthecowboy commented on arm-servermanagement/2016-07-01-preview/servermanagement.json
> +                            "$ref": "#/definitions/
probably should have ` "format": "date-time", ` on the `publishedTypeUtc

2016-09-21 21:05 UTC, fearthecowboy commented on arm-servermanagement/2016-07-01-preview/servermanagement.json
> +                            "$ref": "#/definitions/
Given the berevity in the names, there should really be descriptions on these.

2016-09-21 21:07 UTC, fearthecowboy commented on arm-servermanagement/2016-07-01-preview/servermanagement.json
> +                            "$ref": "#/definitions/
Did you get the Visual Studio Code linter working ? The missing descriptions should have been caught by the editor.

2016-09-21 21:13 UTC, fearthecowboy requested changes
You should install the VsCode and the OpenAPI (swagger) linter. 

Just download 

https://github.com/Azure/openapi-lint-extension/releases/download/v0.5-pre/swagger-linter-0.5.0.vsix 

and open that file in VS Code (and restart when it tells you). No other config should be needed.

You'll see the missing description notifications (there are only 15 missing descriptions in the whole doc)

2016-09-22 18:52 UTC, fearthecowboy approved these changes

2016-09-22 18:52 UTC, fearthecowboy commented
Looks good to me; once the CI is done I'll merge it.

2016-09-22 21:13 UTC, merged

2016-09-22 21:41 UTC, AutorestCI commented
No modification for Python

2016-09-22 21:42 UTC, AutorestCI commented
No modification for NodeJS

2016-09-22 21:44 UTC, AutorestCI commented
No modification for Ruby