[Hub Generated] Review request for Microsoft.ManagementPartner to add version preview/2018-02-01
Azure/azure-rest-api-specs pull request #5726
Opened 2019-04-22 19:57 UTC by jetts

If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/app/branch/jetts/azure-rest-api-specs/dev-managementpartner-Microsoft.ManagementPartner-2018-02-01...master).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2019-04-22 19:58 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-04-22 19:58 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-04-22 19:58 UTC, jetts commented
The changes have been signed off by Anu and Ryan in the private repo: https://github.com/Azure/azure-rest-api-specs-pr/pull/729

2019-04-22 19:58 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-04-22 19:59 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-04-22 20:00 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-04-22 20:00 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-04-22 20:03 UTC, adxsdknet commented
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/azure-sdk-for-net/pull/5894 
.NET SDK Commits: 
https://github.com/adxsdknet/azure-sdk-for-net/pull/5894/commits/735b4f0aa1f56f22356f0636741d138258add8e3

2019-04-24 00:25 UTC, shahabhijeet requested changes
Everything else looks good. Once you update the example with tags, this PR is ready to be merged.

2019-04-24 00:25 UTC, shahabhijeet commented on specification/managementpartner/resource-manager/Microsoft.ManagementPartner/preview/2018-02-01/examples/GetPartnerDetailsNoPartnerId.json
> +    "api-version": "2018-02-01"
@jetts you updated existing spec with new tags.
Do you mind adding an example that shows the request that has the newly added tags.

2019-04-24 19:48 UTC, shahabhijeet approved these changes

2019-04-24 19:48 UTC, merged