Adding Suspend and Resume APIs
Azure/azure-rest-api-specs pull request #583
Opened 2016-10-04 12:26 UTC by athipp

2016-10-06 17:02 UTC, fearthecowboy requested changes
Looks pretty good, just questions about long-running operations.

2016-10-06 17:02 UTC, fearthecowboy commented on arm-asazure/2016-05-16/swagger/asazure.json
> +          "202": {
You use `202 Accepted` -- is this supposed to be a long-running operation ( ie, use `"x-ms-long-running-operation": true` ?)

2016-10-06 17:02 UTC, fearthecowboy commented on arm-asazure/2016-05-16/swagger/asazure.json
> +          "202": {
You use `202 Accepted` -- is this supposed to be a long-running operation ( ie, use `"x-ms-long-running-operation": true` ?)

2016-10-13 02:17 UTC, athipp commented on arm-asazure/2016-05-16/swagger/asazure.json
> +          "202": {
good catch, added the property

2016-10-13 02:17 UTC, athipp commented on arm-asazure/2016-05-16/swagger/asazure.json
> +          "202": {
good catch, added the property

2016-10-14 19:08 UTC, fearthecowboy approved these changes

2016-10-14 19:08 UTC, merged

2016-10-14 19:10 UTC, AutorestCI commented
No modification for Ruby

2016-10-14 19:11 UTC, AutorestCI commented
No modification for NodeJS

2016-10-14 19:11 UTC, AutorestCI commented
No modification for Python