Add new Event Grid event type for SignalR Service
Azure/azure-rest-api-specs pull request #5913
Opened 2019-05-10 06:15 UTC by zackliu

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-05-10 06:15 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-05-10 06:15 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-05-10 06:15 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-05-10 06:15 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-05-10 06:29 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-05-10 08:47 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-05-13 22:53 UTC, veronicagg requested changes
@zackliu how are you consuming these definitions from the other specs?

2019-05-13 22:56 UTC, veronicagg requested changes
Please check inline comment to resolve semantic validation failure.

2019-05-13 22:56 UTC, veronicagg commented on specification/eventgrid/data-plane/Microsoft.SignalRService/stable/2018-01-01/SignalRService.json
> +                    "type": "date-time"
please take a look at type and format for "date-time" https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types

2019-05-17 08:37 UTC, zackliu commented
@veronicagg We use C# sdk to publish events from our SignalR service runtime

2019-05-20 23:23 UTC, veronicagg approved these changes

2019-05-20 23:24 UTC, merged