Updated descriptions in webapplicationfirewall.json
Azure/azure-rest-api-specs pull request #5965
Opened 2019-05-15 07:45 UTC by EvgenyAgafonchikov

NetworkValidation CI task currently checks descriptions code style (first letter casing).
This fixes potential failures in the next PRs.
Also, added trailing dots to update all at once.
[Related job](https://dev.azure.com/azure-sdk/public/_build/results?buildId=31164)

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-05-15 07:46 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-05-15 07:47 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-05-15 07:47 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-05-15 07:48 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-05-15 07:54 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-05-15 08:55 UTC, anton-evseev requested changes

2019-05-15 08:55 UTC, number213 commented on specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/webapplicationfirewall.json
> +          "description": "Describes  policySettings for policy.",
Extra space after "Describes"

2019-05-15 09:15 UTC, anton-evseev requested changes

2019-05-15 09:15 UTC, number213 commented on specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/webapplicationfirewall.json
> +          "description": "Describes policyDetailSettings for policy.",
Please make "policyDetailSettings" more human-readable, e.g. "policy detail settings"

2019-05-15 09:15 UTC, number213 commented on specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/webapplicationfirewall.json
> +          "description": "Describes policySettings for policy.",
Please make "policySettings" more human-readable, e.g. "policy settings"

2019-05-15 09:15 UTC, number213 commented on specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/webapplicationfirewall.json
> +      "description": "Defines ManagedRuleSets - array of managedRuleSet.",
description -> "Array of managed rule sets"

2019-05-15 09:24 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-05-15 09:56 UTC, EvgenyAgafonchikov commented
@venkatsvpr, I've discovered [this item](https://github.com/Azure/azure-rest-api-specs/pull/5965/files#diff-a369a92061eba6d5f1ece36a6c9309a8R591) only during updating descriptions. It seems to have predefined values, so shouldn't we add enum there?
Please also review other changes and confirm if they look good.

2019-05-15 16:24 UTC, dsgouda approved these changes
LGTM, will merge once all reviewers approve

2019-05-16 07:42 UTC, EvgenyAgafonchikov commented
Closing as the change is in progress of reverting now.
@venkatsvpr, feel free to reuse any part of these changes in the new PR

2019-05-16 07:42 UTC, closed without merging