Racastur/associations
Azure/azure-rest-api-specs pull request #6040
Opened 2019-05-21 00:58 UTC by ramacasturi

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-05-21 00:59 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-05-21 00:59 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-05-21 00:59 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-05-21 01:01 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-05-21 01:25 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-05-21 06:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-05-21 18:09 UTC, amarzavery requested changes

2019-05-21 18:09 UTC, amarzavery commented on specification/customproviders/resource-manager/Microsoft.CustomProviders/preview/2018-09-01-preview/customproviders.json
> +    "/{scope}/providers/Microsoft.CustomProviders/associations/{associationName}": {
indentation 2 spaces, please.

2019-05-21 18:09 UTC, amarzavery commented on specification/customproviders/resource-manager/Microsoft.CustomProviders/preview/2018-09-01-preview/examples/createOrUpdateAssociation.json
> +{
indentation 2 spaces

2019-05-21 18:09 UTC, amarzavery commented on specification/customproviders/resource-manager/Microsoft.CustomProviders/preview/2018-09-01-preview/examples/createOrUpdateAssociation.json
> +                    "provisioningState": "Accepted"
provisioningState for 200 should be "Succeeded"

2019-05-22 00:44 UTC, amarzavery approved these changes

2019-05-22 18:25 UTC, merged

2019-05-29 18:48 UTC, ravbhatnagar commented
@sanjaiganesh - This has been merged already but service team wants an ARM review. Can you please take a look?