Adding AWS CloudTrail to swagger
Azure/azure-rest-api-specs pull request #6122
Opened 2019-05-27 09:32 UTC by mahmoudraedhasanmsft

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-05-27 09:33 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-05-27 09:33 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-05-27 09:34 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-05-27 09:34 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-05-27 09:34 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-05-27 09:35 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-06-12 10:55 UTC, mahmoudraedhasanmsft commented
@shahabhijeet please review my PR. thanks

2019-06-28 22:56 UTC, loarabia commented
@shahabhijeet this looks like it is getting stale is there a blocker?

2019-07-03 07:37 UTC, mahmoudraedhasanmsft commented
Hi @loarabia , @shahabhijeet ,
Who can review this PR?
Thanks

2019-07-07 22:19 UTC, shahabhijeet requested changes

2019-07-07 22:19 UTC, shahabhijeet commented on specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2019-01-01-preview/SecurityInsights.json
> +              "x-ms-client-flatten": true,
@mahmoudraedhasanmsft please verify if flattening produces the model that you expect.

2019-07-08 12:50 UTC, mahmoudraedhasanmsft commented
@shahabhijeet I think it should be the same like the other connectors.
@nirgfani , what do you think?

2019-07-09 14:46 UTC, mahmoudraedhasanmsft commented
@shahabhijeet , I checked it with my team and it's ok. Please approve if you see that everything is OK.

2019-07-15 07:50 UTC, mahmoudraedhasanmsft commented
@loarabia can you please approve the PR?

2019-07-15 17:56 UTC, shahabhijeet approved these changes

2019-07-15 17:56 UTC, merged