Add inconsistency api
Azure/azure-rest-api-specs pull request #6129
Opened 2019-05-28 13:26 UTC by mouthwatering

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-05-28 13:26 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-05-28 13:26 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=6129) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=6129) before we can accept your contribution.<br/><br/>:x: mouthwatering [sign now](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=6129)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-rest-api-specs?pullRequest=6129) it.</sub>

2019-05-28 13:27 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-05-28 13:27 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-05-28 13:27 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-05-28 13:27 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-05-28 13:27 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-05-29 16:11 UTC, kpajdzik commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +        "operationId": "DetectInconsistency",
We recommend `{noun}_{verb}` pattern for operation IDs. It looks better in generated SDKs.

2019-05-29 16:12 UTC, kpajdzik commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +        "operationId": "QueryTimeSeriesGroup",
Same here

2019-05-29 16:13 UTC, kpajdzik commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +          "200": {
No 201 here?

2019-05-29 16:14 UTC, kpajdzik commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +        "summary": "",
Are all those summaries and descriptions intended to be empty?

2019-05-29 16:14 UTC, kpajdzik commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +        "modelAsString": false
I know this was just moved but is there any reason why you don't want `modelAsString` set to true?

2019-05-29 16:15 UTC, kpajdzik requested changes
Waiting for the feedback response.

2019-06-03 22:14 UTC, KrisBash commented
Does not appear to be a control plane API

2019-06-03 22:15 UTC, kpajdzik commented
> Does not appear to be a control plane API

My bad!

2019-06-20 20:02 UTC, kpajdzik commented
Closing as stale

2019-06-20 20:02 UTC, closed without merging