chore: jsonfmt machinelearning
Azure/azure-rest-api-specs pull request #6138
Opened 2019-05-29 03:56 UTC by nschonni

Ran `jsonfmt -w "specification/machinelearning/**/*.json"`

2019-05-29 03:56 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-05-29 03:57 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-05-29 03:58 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-05-29 03:58 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-05-29 03:58 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-05-29 03:59 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-05-29 04:19 UTC, nschonni commented
Fixed the casing issues with model validation is separate commits. They can be removed if prefered. There is an outstanding error still, but the 200 status description says "Internal use only." so maybe that is by-design.
Not sure about the BreakingChange error

2019-06-06 18:25 UTC, sergey-shandar requested changes

2019-06-06 18:25 UTC, sergey-shandar commented on specification/machinelearning/resource-manager/Microsoft.MachineLearning/stable/2017-01-01/examples/getWebService.json
> +            "nodes": {
This PR contains changes that shouldn't be included as json formatting.

2019-06-06 18:26 UTC, sergey-shandar commented
@nschonni could you create two separate PRs?

2019-06-06 18:26 UTC, closed without merging

2019-06-06 18:32 UTC, nschonni commented
@sergey-shandar if you want to re-open this one, i'll rebase out the non-formatting changes and move them to a second PR

2019-06-07 07:04 UTC, nschonni commented
@sergey-shandar I opened up the format-only PR in #6272. I'll submit something with the other commits after that lands