Adding missing docs for existing routes for QnA Maker APIM
Azure/azure-rest-api-specs pull request #6140
Opened 2019-05-29 13:01 UTC by rokulka

Adding missing docs for existing routes for QnA Maker APIM
  - Add /endpointsetttings path for service
Adding new docs for existing routes for QnA Maker Runtime
  - New swagger file as the "x-ms-parameterized-host" is different for them
  - Add /generateAnswer path for Runtime
  - Add /train path for Runtime

2019-05-29 13:01 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-05-29 13:02 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-05-29 13:02 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-05-29 13:02 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-05-29 13:02 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-05-29 13:03 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-05-29 17:24 UTC, tjprescott commented
Numerous linter checks failing

2019-05-31 07:04 UTC, bingisbestest commented on specification/cognitiveservices/data-plane/QnAMaker/stable/v4.0/QnAMakerRuntime.json
> +    "description": "An API for QnAMaker Service"
runtime

2019-05-31 07:52 UTC, ghost requested changes

2019-05-31 07:52 UTC, bingisbestest commented on specification/cognitiveservices/data-plane/QnAMaker/stable/v4.0/QnAMakerRuntime.json
> +            "$ref": "#/definitions/QueryDTO"
Needs to be a parameter def, see qnamaker.json

2019-06-03 14:33 UTC, tjprescott approved these changes
LGTM. However, please address @bingisbestest's comments.

2019-06-03 14:46 UTC, ghost approved these changes

2019-06-03 14:47 UTC, merged