[Cog Service AnomalyDetector] add more apis [DO NOT MERGE]
Azure/azure-rest-api-specs pull request #6142
Opened 2019-05-29 13:49 UTC by moreOver0

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-05-29 13:50 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-05-29 13:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-05-29 13:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-05-29 13:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-05-29 13:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-05-29 13:52 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-06-03 22:17 UTC, yangyuan commented
I don't see any issue from Cognitive Services scope.
As long as we get sign off from Azure API Review Board and ADX, we can proceed.

2019-06-12 21:18 UTC, NelsonDaniel commented
Reassigning this b/c I will be OOF.

2019-06-21 06:05 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +          "default": {
error code

2019-06-21 06:05 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +            "description": "Error response.",
error code

2019-06-21 06:05 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +          "default": {
error code

2019-06-21 06:06 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +    "/timeseries/{timeSeriesId}/query": {
consider paging in query API

2019-06-21 06:06 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +            "description": "Error response.",
error code

2019-06-21 06:09 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +        "operationId": "TimeSeries_Create",
When user create a time series with same body should return 204,  if it's a successful call, it should return 201

2019-06-21 06:10 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "delete": {
if the time series does not exist, should return 204

2019-06-21 06:10 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +        "summary": "Delete the specified timeseries.",
Enable E-tag in GET/CREATE/DELETE

2019-06-21 06:11 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "put": {
Consider providing batch write API to write multiple time series points together

2019-06-21 06:12 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +    "/timeseries/{timeSeriesId}/timeseriesgroups": {
Combine getting group interface with the time series creating one, for example /anomalydetector/v1.0/timeseries/{timeSeriesId}? timeseriesgroups=true

2019-06-21 06:14 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +    "/timeseriesgroups/{timeSeriesGroupId}/inconsistency/query": {
Consider make it as a get API

2019-06-21 06:14 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +    "/timeseriesgroups/{timeSeriesGroupId}/timeseries/{timeSeriesId}": {
Not the right way to represent relation between time series group and time series

2019-06-21 06:16 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +        "name": {
name is not a valid one since name and id are same thing

2019-06-21 06:17 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +        "groupId": {
should be timeseriesGroupId

2019-06-21 06:24 UTC, conhua requested changes

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +            "schema": {
Failure code is not the right one

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +          "default": {
Add Failure code

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "post": {
Create should be PUT

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +            "$ref": "#/parameters/timeSeriesId"
When user create a time series with same body should return 204, if it's a successful call, it should return 201

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +            "description": "Successful operation."
Add failure code

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "delete": {
add failure code

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "delete": {
if the time series does not exist, should return 204 to let the customer know it has been deleted

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +        "description": "Delete the specified timeseries.",
Enable E-tag in GET/CREATE/DELETE

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +            "$ref": "#/parameters/next"
next should be a link

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +              "$ref": "#/definitions/APIError"
Failure code is not right

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "put": {
write should be post

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "put": {
Consider providing batch write API to write multiple time series points together

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +              "$ref": "#/definitions/APIError"
error code

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +              "$ref": "#/definitions/APIError"
error code

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +            "description": "Error response.",
error code

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "post": {
consider paging in query API

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +            "schema": {
error code

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "get": {
Combine getting group interface with the time series creating one, for example /anomalydetector/v1.0/timeseries/{timeSeriesId}? timeseriesgroups=true

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "post": {
Consider make it as a get API

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "post": {
Not the right way to represent relation between time series group and time series

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +        "name": {
name is not a valid one since name and id are same thing

2019-06-21 06:24 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +        "groupId": {
should be timeseriesGroupId

2019-06-21 13:41 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +            "$ref": "#/parameters/next"
Can not be resolved

2019-06-21 13:42 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +          "default": {
resolved

2019-06-21 13:42 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +            "$ref": "#/parameters/timeSeriesId"
Resolved

2019-06-21 13:43 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "delete": {
Resolved

2019-06-21 13:43 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "delete": {
Resolved

2019-06-21 13:43 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +        "description": "Delete the specified timeseries.",
Resolved

2019-06-21 13:44 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +              "$ref": "#/definitions/APIError"
Resolved

2019-06-21 13:44 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +              "$ref": "#/definitions/APIError"
Resolved

2019-06-21 13:44 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +            "description": "Error response.",
Resolved

2019-06-21 13:45 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "post": {
Resolved, no need paging since the API will limit the response within 8640 points. Begin will always be close, end will be open

2019-06-21 13:48 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "post": {
Resolved

2019-06-21 13:49 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "put": {
Resolved

2019-06-21 13:50 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "put": {
Resolved. We won't provide batch write as we are using Azure Table. But Azure table don't support batch write so we try to avoid batch write scenario

2019-06-21 13:50 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +            "schema": {
Resolved

2019-06-21 13:51 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "get": {
Resolved, all time series group interface has been removed in this version

2019-06-21 13:51 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "post": {
Resolved, this interface has been removed

2019-06-21 13:51 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +      "post": {
Resolved, Removed group related operations

2019-06-21 13:52 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +        "name": {
Resolved, name & description has been removed from Meta

2019-06-21 13:52 UTC, conhua commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +        "groupId": {
Resolved, all group concept has been removed

2019-06-25 12:57 UTC, nschonni commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +    "/timeseries/changepoint/detect": {
```suggestion
    "/timeseries/changePoint/detect": {
```

2019-06-25 12:57 UTC, nschonni commented on specification/cognitiveservices/data-plane/AnomalyDetector/preview/v1.0/AnomalyDetector.json
> +    "/timeseries/{timeSeriesId}/changepoint/detect": {
```suggestion
    "/timeseries/{timeSeriesId}/changePoint/detect": {
```

2019-06-27 15:54 UTC, KrzysztofCwalina approved these changes

2019-07-01 18:25 UTC, praries880 commented
@moreOver0  the changes look good to me.. id this PR ready to be merged?

2019-07-02 03:05 UTC, moreOver0 commented
> @moreOver0 the changes look good to me.. id this PR ready to be merged?

@praries880 No, it's not ready. We still need to commit some new changes. I will inform you when everything is done.

2019-07-02 20:50 UTC, yangyuan approved these changes

2019-08-06 04:52 UTC, erich-wang commented
@moreOver0, is this change ready for merge?

2019-08-06 17:33 UTC, moreOver0 commented
> @moreOver0, is this change ready for merge?

NO.

2019-08-15 01:50 UTC, yungezz commented
@moreOver0 is it ok close the PR for now since you're not ready for merge, and the PR is over several months. Pls create new PR when you're ready for review and merge.

2019-08-28 05:29 UTC, yungezz commented
Hi @moreOver0  the PR is still over 3 months, what's your plan to proceed? how about close it for now then maybe reopen or create a new pr?

2019-08-28 08:00 UTC, moreOver0 commented
> Hi @moreOver0 the PR is still over 3 months, what's your plan to proceed? how about close it for now then maybe reopen or create a new pr?

Does it need to go through ARM review after reopening if we close the pr for now?

2019-08-29 04:53 UTC, yungezz commented
> > Hi @moreOver0 the PR is still over 3 months, what's your plan to proceed? how about close it for now then maybe reopen or create a new pr?
> 
> Does it need to go through ARM review after reopening if we close the pr for now?

if no new change after reopening, it doesn't need another round of PR review. Otherwise, it need another round of reiviewing no matter  it's always open or re-open.

2019-11-06 08:48 UTC, moreOver0 commented
@yungezz This PR is ready to merge now. :)

2019-11-06 08:51 UTC, yungezz commented
/azp run

2019-11-06 12:05 UTC, yungezz commented
HI @weidongxu-microsoft , could you pls help to look at the SDK java generation failure? Thanks.

2019-11-07 03:13 UTC, NullMDR commented
/azp run

2019-11-07 08:57 UTC, weidongxu-microsoft commented
Phoenix is still looking into it.

2019-11-08 04:58 UTC, erich-wang commented
@moreOver0, please clean up commit history

2019-11-12 07:39 UTC, moreOver0 commented
Can anyone help look into the failed required check? It's weird because the java sdk generation with autorest works well on my pc.
@erich-wang I think we have already went through the ARM review and did changes according to feedback we got.

2019-11-12 08:13 UTC, weidongxu-microsoft commented
@moreOver0 Phoenix investigated and find that pom.xml is not generated by the automation.

However this is data-plane SDK, which uses a different version of autorest.java extension than management-plane SDK.

If your autorest.java works good, would you share it (the command line, output with autorest.core and autorest.java version, and other info if available) so Swagger team can configure that for data-plane automation job?

2019-11-12 08:33 UTC, moreOver0 commented
@weidongxu-microsoft Emm...It looks like I misunderstood something. Sorry, I didn't know it's a different version of autorest.java. 
So please go ahead with your investigation, and it will be very nice if you have an ETA to fix the java SDK generation.

2019-11-12 08:43 UTC, weidongxu-microsoft commented
@mssfang 
Hello Shawn, this is the PR related to my email yesterday. I saw you actively update cognitiveservices in https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cognitiveservices

Would you provide autorest.java configure for cognitiveservices data-plane SDK?

2019-12-11 05:35 UTC, weidongxu-microsoft commented
There is no public autorest generator for data-plane.

Short term solution for this failed SDK java build could be adding this config into readme java section:

  `regenerate-manager: true`

This asks autorest.java (V2, at least) to generate pom.xml.

2019-12-12 05:34 UTC, AutorestCI commented
/azp run automation - sdk

2019-12-13 06:18 UTC, moreOver0 commented
@KrzysztofCwalina Could you help add label “AzureAPIBoardSignedOff” to mark that you have already signed off this PR? This label is required according to @erich-wang.

2019-12-17 09:29 UTC, erich-wang commented
Already sent email to @KrzysztofCwalina

2019-12-21 05:38 UTC, erich-wang commented
Since @KrzysztofCwalina already signed off, merge this PR.

2019-12-21 05:38 UTC, merged