Update cipher suites
Azure/azure-rest-api-specs pull request #6213
Opened 2019-06-04 08:44 UTC by EvgenyAgafonchikov

Sync May branch with https://github.com/Azure/azure-rest-api-specs/pull/6212

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-06-04 08:46 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-06-04 08:46 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-06-04 08:47 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-06-04 08:47 UTC, AutorestCI commented
# Automation for azure-sdk-for-js

2019-06-04 08:52 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-06-04 09:02 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-06-05 02:12 UTC, MikhailTryakhov commented
@EvgenyAgafonchikov can you please confirm what api version issue is caused by a breaking change only so could be ignored

2019-06-05 06:37 UTC, EvgenyAgafonchikov commented
@MikhailTryakhov, yes, NetworkValidation fails on Azure PS build step because of replacing of InterfaceEndpoints with PrivateEndpoints and we don't have the related update merged in Azure PS yet.

2019-06-05 15:27 UTC, tjprescott approved these changes

2019-06-07 08:23 UTC, anton-evseev requested changes

2019-06-07 08:23 UTC, number213 commented on specification/network/resource-manager/Microsoft.Network/stable/2019-06-01/applicationGateway.json
> +        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
I agree with @sergey-shandar, let's add new enum values at the end.

2019-06-07 11:29 UTC, number213 commented
Addressed Sergey's comments from related PR https://github.com/Azure/azure-rest-api-specs/pull/6212
NetworkValidation's failure is a known issue with PowerShell, please ignore

2019-06-07 16:15 UTC, tjprescott commented
@number213 are you requested changes implemented then? Your review is blocking the merge.

2019-06-08 15:57 UTC, anton-evseev approved these changes

2019-06-10 16:13 UTC, merged