Adding Rules API to ServiceBus swagger
Azure/azure-rest-api-specs pull request #629
Opened 2016-10-24 21:22 UTC by sazeesha

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ ] If applicable, the PR references the bug/issue that it fixes.
- [ ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ ] My spec meets the review criteria:
  - [ ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [ ] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [ ] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

2016-10-25 01:23 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +		"CompatibilityLevel": {
incorrect indentation. make sure that indentation is 2 spaces

2016-10-25 02:11 UTC, amarzavery requested changes

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +            "description": "The subscriptionName name."
Better description. It gets confusing with subscriptionId and subscriptionName

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +            "description": "Parameters supplied to create a rules."
"Parameters supplied to create a rule~~s~~.

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +        "externalDocs": {
why have this defined if it is empty?

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +      "description": "Description of Subscription Resource."
description seems incorrect

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +          "type": "string",
readOnly: true ?

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +          "description": "Gets creation time of the rule."
Remove the phrase Gets

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +      "properties": {
which properties are required in this object ?

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +         "RequiresPreprocessing": {
what are the required set of properties?

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +          "description": "Gets the SQL expression."
Can you provide an example in the description?

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +         "RequiresPreprocessing": {
is this a required property or an optional property? If optional then what is the default value? If there is a default then it should be defined.

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +      "properties": {
what are the required and readOnly properties of this object ?

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +          "description": "Gets the address to send to."
should this be an email address or twitter handle? Can you provide an example in the description?

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +		"ContentType": {
enum candidate?

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +      "properties": {
are there any required or any readOnly properties in this object?

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +          "description": "Preprocesses the filter expression and returns a preprocessed FilterExpression."
description seems to be out of context

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +          "description": "The SQL expression."
example?

2016-10-25 02:11 UTC, amarzavery commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +      "properties": {
are there any required or any readOnly properties in this object?

2016-11-07 22:41 UTC, v-Ajnava commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +            "description": "The subscriptionName name."
Resolved.

2016-11-08 00:29 UTC, v-Ajnava commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +            "description": "Parameters supplied to create a rules."
Resolved

2016-11-08 00:52 UTC, sazeesha commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +		"ContentType": {
Not really, it is used to just match the whatever is in the brokered message.

2016-11-08 00:53 UTC, sazeesha commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +          "description": "Gets the address to send to."
I will update it with a better description. It is used to match the To property of a brokered message

2016-11-09 00:21 UTC, v-Ajnava commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +          "description": "Gets a value indicating whether the SQL filter expression requires preprocessing."
Resolved

2016-11-09 00:23 UTC, v-Ajnava commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +          "description": "Gets the SQL expression."
Resolved, example added.

2017-01-05 18:38 UTC, v-Ajnava commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +		"CompatibilityLevel": {
Corrected indentation.

2017-01-05 18:38 UTC, v-Ajnava commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +      "description": "Description of Subscription Resource."
Resolved.

2017-01-05 18:39 UTC, v-Ajnava commented on arm-servicebus/2015-08-01/swagger/servicebus.json
> +          "description": "Gets creation time of the rule."
Resolved.

2017-01-24 02:40 UTC, closed without merging