Update public swagger
Azure/azure-rest-api-specs pull request #6381
Opened 2019-06-19 09:43 UTC by Yiliu-microsoft

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-06-19 09:43 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-06-19 09:44 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-06-19 09:45 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-06-19 09:47 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-06-19 10:02 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-07-01 17:08 UTC, amarzavery commented
@Yiliu-microsoft - Please resolve merge conflicts.

2019-07-01 17:10 UTC, amarzavery requested changes

2019-07-01 17:10 UTC, amarzavery commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json
> +          "description": "Specifies whether to disable collecting data source metrics. Type: boolean (or Expression with resultType boolean)."
Can you update x-ms-examples for the operation that uses this model in the request body or response body and populate the example with this new property that has been added in this PR.

2019-07-01 18:46 UTC, ravbhatnagar reviewed
a couple of comments. please ping me in case of any questions.

2019-07-01 18:46 UTC, ravbhatnagar commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json
> +          "minLength": 1
this is a breaking change. Looks like this restriction is added in the existing api-version.

2019-07-01 18:46 UTC, ravbhatnagar commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json
> +        "disableMetricsCollection": {
writable properties are typically added in new api-version as they can result in unintentional update of goal state when done in same api-version.

2019-08-12 07:06 UTC, yungezz commented
@Yiliu-microsoft  could you pls resolve comments and fixing CI? otherwise is it ok to close the PR for now, and pls create new PR when you're ready.

2019-08-28 07:33 UTC, yungezz commented
close the PR since no update for a while. I cannot find corresponding email address from internal site either.

2019-08-28 07:33 UTC, closed without merging