[Blueprints] Add published blueprint object to the payload to support change notes
Azure/azure-rest-api-specs pull request #6399
Opened 2019-06-20 21:50 UTC by filizt

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-06-20 21:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-06-20 21:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-06-20 21:51 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-06-20 21:52 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-06-20 22:03 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-06-21 06:16 UTC, erich-wang requested changes
@filizt , please make sure all checks are passed, thanks.

2019-06-21 13:29 UTC, filizt commented
> @filizt , please make sure all checks are passed, thanks.

The model validation failures in the checks are caused by a tooling issue here: https://github.com/Azure/oav/issues/431. We had an another PR earlier this week that had the same failures but the they were suppressed and PR was merged since the failures were also due to the tooling issue. See here: https://github.com/Azure/azure-rest-api-specs/pull/6297

Could you help suppress the failures and merge the PR?

2019-06-21 18:26 UTC, majastrz commented on specification/blueprint/resource-manager/Microsoft.Blueprint/preview/2018-11-01-preview/blueprintDefinition.json
>            }
Note for other reviewers:
The blueprint backend has always supported this and it was always optional. So SDKs generated from swaggers with and without this change will work just fine.

2019-06-21 18:26 UTC, majastrz approved these changes
Looks good from ARM side.

2019-06-24 13:46 UTC, filizt commented
@erich-wang could you review the PR please?

2019-06-25 01:48 UTC, erich-wang approved these changes
approve the change since the check failure is caused by tool bug.

2019-06-25 01:51 UTC, erich-wang commented
@sergey-shandar, the check failure is caused by a bug in ova, please merge this PR, thanks.

2019-06-25 04:58 UTC, merged