Network: added package tags in java readme
Azure/azure-rest-api-specs pull request #6460
Opened 2019-06-26 16:19 UTC by iscai-msft

2019-06-26 16:20 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-06-26 16:20 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-06-26 16:22 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-06-26 16:24 UTC, kpajdzik commented on specification/network/resource-manager/readme.java.md
> +regenerate-manager: true
I think the formatting is incorrect.

2019-06-26 16:24 UTC, kpajdzik requested changes
Please fix YAML formatting

2019-06-26 16:25 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-06-26 16:33 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-06-27 17:50 UTC, iscai-msft commented on specification/network/resource-manager/readme.java.md
> +regenerate-manager: true
thanks for catching this

2019-06-28 18:32 UTC, kpajdzik approved these changes

2019-06-28 18:33 UTC, kpajdzik commented
@iscai-msft, Do you want me to merge it?

2019-07-09 15:47 UTC, merged