Dev/ccelik/dedicated host swagger
Azure/azure-rest-api-specs pull request #6475
Opened 2019-06-27 01:19 UTC by celikcigdem

Added new APIs for DedicatedHostGroups and DedicatedHosts

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [X] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [X] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [X] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [X] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [X] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-06-27 01:20 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-06-27 01:20 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-06-27 01:22 UTC, AutorestCI commented
# Automation for azure-sdk-for-ruby

2019-06-27 01:26 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-06-27 01:31 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-06-27 21:34 UTC, anuchandy commented
@sarangan12 @sergey-shandar linter emitted below error:

```
R2020 - RequiredPropertiesMissingInResourceModel
Model definition 'DedicatedHostGroupUpdate' must have the properties 'name', 'id' and 'type' in its hierarchy and these properties must be marked as readonly. 
at specification/compute/resource-manager/Microsoft.Compute/stable/2019-03-01/compute.json:5491
```

This is the PATCH request payload and is not used as response model.

However this type derive `UpdateResource` type which is marked as  "x-ms-azure-resource", I don't see a need to mark it so though. Do you think linter emit this error due to this annotation? or anything else causing this error to trigger?

2019-06-27 22:02 UTC, sarangan12 requested changes
The new file is not referenced in the readme file. Please update it

2019-07-03 19:24 UTC, celikcigdem commented
> The new file is not referenced in the readme file. Please update it

@sarangan12, @anuchandy, I resolved your comments, the new iteration is available. Could you please review it?

2019-07-03 19:27 UTC, celikcigdem commented
@hyonholee , @huangpf could you please review this PR?

2019-07-03 19:46 UTC, sarangan12 approved these changes

2019-07-03 19:47 UTC, merged

2019-07-09 22:28 UTC, adewaleo commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-03-01/compute.json
> +        "sku": {
Should this be sku or something else?

Also this property / its definition was not defined

2019-07-09 22:31 UTC, adewaleo commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-03-01/compute.json
> +          "$ref": "#/definitions/Sku",
@celikcigdem @sarangan12, should this be #/definitions/sku or something else?

This definition does not exist

2019-07-10 16:24 UTC, adewaleo commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-03-01/compute.json
> +          "$ref": "#/definitions/Sku",
Correction: this Sku exists. Its comment says it describes a virtual machine scale set sku. I will use it for now, but I would have imagined that a new type DedicatedHostSkuTypes would be defined for this property.