Add Microsoft.Security applicationWhitelistings API
Azure/azure-rest-api-specs pull request #6553
Opened 2019-07-04 13:30 UTC by erelh

initial commit

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-07-04 13:30 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=6553) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=6553) before we can accept your contribution.<br/><br/>:x: erelh [sign now](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=6553)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-rest-api-specs?pullRequest=6553) it.</sub>

2019-07-04 13:31 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-07-04 13:31 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-07-04 13:34 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-07-04 13:34 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-07-04 15:25 UTC, erelh commented
API already exists in ARM , but is not documented

2019-07-04 16:11 UTC, nschonni commented on specification/security/resource-manager/Microsoft.Security/preview/2015-06-01-preview/applicationWhitelistings.json
> +paths:
The file extension is JSON, but the file is written as YAML

2019-07-05 01:19 UTC, raych1 commented on specification/security/resource-manager/Microsoft.Security/preview/2015-06-01-preview/applicationWhitelistings.json
> +        '400':
Usually don't define negative responses and define 'default' response for all negative responses instead. Please refer to [here](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#default-response).

2019-07-05 01:29 UTC, raych1 commented
It needs to update [readme](https://github.com/Azure/azure-rest-api-specs/tree/93d38ae64d0462e0b109418bd5ce1a5dfe7f2016/specification/security/resource-manager#tag-package-composite-v3) to add this newly added spec.

2019-07-05 01:51 UTC, raych1 requested changes
Please resolve my comments and the CI failures.

2019-07-05 08:15 UTC, sergey-shandar requested changes

2019-07-05 08:15 UTC, sergey-shandar commented on specification/security/resource-manager/Microsoft.Security/preview/2015-06-01-preview/applicationWhitelistings.json
> +paths:
Please, use JSON instead of YAML.

2019-07-07 13:20 UTC, erelh commented
hi
i fixed some errors, but i dont understand the current error messages in the **semantic** validation, can someone please review and assist what is invalid ?
thanks!

2019-07-09 09:44 UTC, raych1 commented
@amarzavery , can you help explain the semantics errors?

2019-07-09 10:20 UTC, erelh commented
@raych1 

> @amarzavery , can you help explain the semantics errors?


Hi,

The CI is only failing on SpellCheck because the API is "applicationWhitelistings" and "whitelistings" is not a word

The API is already in Production so can you please give us a hallpass on this one

Thanks

2019-07-09 22:22 UTC, nschonni commented
You can add the word to https://github.com/Azure/azure-rest-api-specs/blob/master/custom-words.txt
Although I think it should probably be "Whitelisting" without the "s"

2019-07-10 01:17 UTC, raych1 approved these changes

2019-07-10 13:28 UTC, erelh commented
@sergey-shandar can you please re-review ?
thanks

2019-07-10 23:56 UTC, sergey-shandar approved these changes

2019-07-10 23:56 UTC, sergey-shandar commented
We still need ARM approval

2019-07-11 04:37 UTC, erelh commented
@ryansbenson @antmarti-microsoft @ravbhatnagar @KrisBash @majastrz @sanjaiganesh 

Hi, this PR is documenting and existing API that is already Production GA.
Can you please review and approve ?

Thanks

2019-07-12 12:03 UTC, erelh commented
friendly ping

2019-07-16 04:46 UTC, KrisBash commented
@erelh - If this is truly retrofitting API spec to a production API, there's not much we can do in review. I will sign off. Please note that APIs are expected to undergo review before shipping, and ideally before implementation.

2019-07-16 04:47 UTC, KrisBash approved these changes
API is already in production...

2019-07-16 05:07 UTC, merged

2019-07-17 06:28 UTC, erelh commented
@raych1  how much time does it take for the changes to be reflected ?
in [https://docs.microsoft.com/en-gb/rest/api/securitycenter/](url)

2019-07-17 08:36 UTC, raych1 commented
@erelh , normally the content would be refreshed in 12 hours.

2019-07-17 09:01 UTC, erelh commented
@raych1 24 hours have passed, does this mean something went wrong ?