[DataFactory] Enable Avro Dataset in Public Swagger
Azure/azure-rest-api-specs pull request #6560
Opened 2019-07-05 11:24 UTC by yuzhangyi

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-07-05 11:26 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-07-05 11:30 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-07-05 11:30 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-07-05 11:31 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-07-08 06:03 UTC, michaeljqzq commented
Please provide example including the newly added property

2019-07-08 06:04 UTC, michaeljqzq requested changes
Please add example

2019-07-19 02:02 UTC, yuzhangyi commented
> Please add example
Hi, after having sync with our engineer team, we don't need external example to validate it, because we already has example at "datafactory\resource-manager\Microsoft.DataFactory\stable\2018-06-01\examples"

2019-07-19 02:03 UTC, yuzhangyi commented
> Please add example

Hi, after having sync with our engineer team, we don't need external example to validate it, because we already has example at "datafactory\resource-manager\Microsoft.DataFactory\stable\2018-06-01\examples"

2019-07-19 02:03 UTC, yuzhangyi commented
> Please provide example including the newly added property

Hi, after having sync with our engineer team, we don't need external example to validate it, because we already has example at "datafactory\resource-manager\Microsoft.DataFactory\stable\2018-06-01\examples"

2019-07-19 21:03 UTC, hvermis commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json
> +      "description": "Delimited text write settings.",
Fix the comment, should say Avro

2019-07-19 21:04 UTC, hvermis approved these changes
Make sure to fix the description

2019-07-19 21:05 UTC, hvermis commented
@KrisBash Could you review this one too? This is another dataset type with settings, again similar to what you already reviewed.

2019-07-22 11:43 UTC, yuzhangyi commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json
> +      "description": "Delimited text write settings.",
Thanks, will fix it later.

2019-07-22 11:44 UTC, yuzhangyi commented
> @KrisBash Could you review this one too? This is another dataset type with settings, again similar to what you already reviewed.

Hi, @KrisBash, can you help finish reviewing this change and merge it into master? thanks!

2019-07-30 05:26 UTC, michaeljqzq commented
@yuzhangyi , is this PR still valid? If yes, please fix the comments. Otherwise I will close it

2019-07-31 01:10 UTC, yuzhangyi commented
> @yuzhangyi , is this PR still valid? If yes, please fix the comments. Otherwise I will close it

Hi, @michaeljqzq, this public swagger change is valid, can you help signoff and merge it into master? For the comment raised by hvermis, I will fix it in next change.

2019-07-31 04:42 UTC, michaeljqzq commented
@yuzhangyi , we can not merge a PR in a mid-state. Please either update this one or create another PR

2019-07-31 05:53 UTC, yuzhangyi commented
Close it and use new one.

2019-07-31 05:53 UTC, closed without merging