[Hub Generated] Review request for Microsoft.Consumption to add version stable/2019-05-01
Azure/azure-rest-api-specs pull request #6620
Opened 2019-07-15 08:22 UTC by santoshsinha100

If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/santoshsinha100/azure-rest-api-specs/dev-consumption-Microsoft.Consumption-2019-05-01...master/).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2019-07-15 08:23 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-07-15 08:25 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-07-15 08:34 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-07-15 09:00 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-07-15 18:19 UTC, santoshsinha100 commented
Review request for Microsoft.Consumption to add version stable/2019-05-01.
New API added are...
=>Recommendation Single/shared on billing account scope
=>RIUsage Details  on billing account scope
=>RIUsage Summary on billing account scope

Please review and approve this PR to procced with ARM manifest related changes.

2019-07-15 21:57 UTC, nschonni commented on specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-05-01/consumption.json
> +    "/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.Consumption/reservationdetails": {
```suggestion
    "/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.Consumption/reservationDetails": {
```

2019-07-15 21:57 UTC, nschonni commented on specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-05-01/consumption.json
> +	"/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.Consumption/reservationsummaries": {
```suggestion
    "/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.Consumption/reservationSummaries": {
```

2019-07-15 21:57 UTC, nschonni commented on specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-05-01/examples/ReservationSummariesDaily.json
> +            "type": "Microsoft.Consumption/reservationsummaries",
```suggestion
            "type": "Microsoft.Consumption/reservationSummaries",
```

2019-07-15 21:57 UTC, nschonni commented on specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-05-01/examples/ReservationSummariesDailyWithReservationId.json
> +            "type": "Microsoft.Consumption/reservationsummaries",
```suggestion
            "type": "Microsoft.Consumption/reservationSummaries",
```

2019-07-15 21:57 UTC, nschonni commented on specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-05-01/examples/ReservationSummariesMonthly.json
> +            "type": "Microsoft.Consumption/reservationsummaries",
```suggestion
            "type": "Microsoft.Consumption/reservationSummaries",
```

2019-07-15 21:57 UTC, nschonni commented on specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-05-01/examples/ReservationSummariesMonthlyWithReservationId.json
> +            "type": "Microsoft.Consumption/reservationsummaries",
```suggestion
            "type": "Microsoft.Consumption/reservationSummaries",
```

2019-07-16 02:23 UTC, santoshsinha100 commented on specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-05-01/consumption.json
> +	"/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.Consumption/reservationsummaries": {
commited

2019-07-16 02:39 UTC, nschonni commented on specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-05-01/consumption.json
> +    "/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.Consumption/reservationsummaries": {
```suggestion
    "/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.Consumption/reservationSummaries": {
```

2019-07-16 03:21 UTC, santoshsinha100 commented on specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-05-01/consumption.json
> +    "/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.Consumption/reservationsummaries": {
already fixed

2019-07-17 18:31 UTC, santoshsinha100 commented
Hi Nick,

Can you mark this item complete. I already addressed all your suggestions. We need this to roll out ASAP.

Thanks & Regards
Santosh

2019-07-17 19:19 UTC, nschonni commented
Sorry, I'm not an MS employee, but I think there is instructions over here if you need to escalate https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html

2019-07-19 21:22 UTC, santoshsinha100 commented
Can some one please approve this PR. This is active since last 4 to 5 days.

2019-07-22 17:30 UTC, ms-premp commented
We have preview version for usage details already merged in 
https://github.com/Azure/azure-rest-api-specs/pull/6575 
We are moving this to GA and adding one more API in this GA version. Please review.

2019-07-30 22:52 UTC, majastrz commented
>     "/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/providers/microsoft.consumption/ReservationRecommendations": {

nit - should be camelCase

---
Refers to: specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-05-01/consumption.json:968 in d04e302. [](commit_id = d04e302c85bdffe4cb2c5f966faef6fa1df32921, deletion_comment = False)

2019-07-31 00:18 UTC, majastrz commented
>         "billingPeriodId": {

This is potentially an SDK breaking change. (When users update the current SDK to one generated from this Swagger, their code won't compile if they are referencing properties that got removed.) What's the plan to deal with that?

---
Refers to: specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-05-01/consumption.json:1269 in 71e2dcb. [](commit_id = 71e2dcbd4d0f5e6367ed7a6ec72f77356da1f487, deletion_comment = True)

2019-07-31 22:40 UTC, majastrz approved these changes
Signed off from ARM side.

2019-08-01 01:34 UTC, santoshsinha100 commented
Can some one do this review on priority. Its waiting for an approval

2019-08-01 02:23 UTC, majastrz commented
> Can some one do this review on priority. Its waiting for an approval

I'm confused by this. Normally a person from the SDK team is assigned to a PR like this and they finish the review from the SDK side once ARM (me this week) signs off. I'll send an email to a contact I know internally (I don't know her GitHub name to just @ mention here.)

2019-08-01 02:25 UTC, majastrz commented
If you reach out to me directly via Teams (alias is same as my github name), I can add you to the mail thread.

2019-08-01 05:06 UTC, yungezz reviewed
looks good, some minor issue in samples. @santoshsinha100 could you pls resolve conflict? then I'll go to approve and merge the PR.

2019-08-03 02:50 UTC, santoshsinha100 commented on specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-05-01/examples/AggregatedCostByManagementGroup.json
> +          "usageEnd": "2018-10-31T00:00:00.0000000Z",
Hi I am unable to resolve the conflict in readme.md file. UI doesn't allow me to resolve.  Looking at the conflict, I will go with "### Tag: package-2019-05" not the preview one. Will it be possible to get this resolved at your end .

2019-08-05 05:30 UTC, yungezz commented
@santoshsinha100 pls look at the resolved readme.md file. pls update the tag `package-preview-2019-05` to `package-2019-05` at https://github.com/Azure/azure-rest-api-specs/pull/6620/files#diff-19989b3082cb3c89e63e9903a79a80b6R40 to

2019-08-05 05:30 UTC, yungezz requested changes
pls review change in readme.md for conflict resolving, and update tag name per need.

2019-08-05 18:50 UTC, ms-premp approved these changes
Thanks @yungezz. Your ReadMe changes looks good.

2019-08-06 05:58 UTC, yungezz approved these changes

2019-08-06 05:59 UTC, merged