[SRP] Add new API ListBlobServices
Azure/azure-rest-api-specs pull request #6657
Opened 2019-07-17 21:13 UTC by zfchen95

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-07-17 21:14 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-07-17 21:14 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-07-17 21:15 UTC, AutorestCI commented
# Automation for azure-sdk-for-java

2019-07-17 21:33 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-07-19 21:42 UTC, zfchen95 commented
@yungezz Sorry I have to close the previous one because I added too many commits after the git pull rebase. I saw some of the tests are failed for this PR. But I couldn't find out the issue from the error log. Was it because I added a new API that breaks the existing sdk? Any other issue you would notice?

2019-07-19 21:43 UTC, zfchen95 commented
The PR was signed off by ARM team in the private repo https://github.com/Azure/azure-rest-api-specs-pr/pull/777

2019-07-29 18:31 UTC, amarzavery requested changes

2019-07-29 18:31 UTC, amarzavery commented on specification/storage/resource-manager/Microsoft.Storage/stable/2019-04-01/blob.json
> +        "operationId": "BlobServices_List",
Please add `"x-ms-pageable": { "nextLinkName": null }` extension to the list operation. It is also done for many other operations like [StorageAccounts_List](https://github.com/Azure/azure-rest-api-specs/blob/c63f7d5f37c4c3be5c065544574b5b32c1ad52aa/specification/storage/resource-manager/Microsoft.Storage/stable/2019-04-01/storage.json#L323)

2019-07-29 18:33 UTC, amarzavery commented
Please fix the CI failures for model validation and lint diff

2019-07-29 22:27 UTC, amarzavery approved these changes

2019-07-29 22:27 UTC, merged