[Hub Generated] Review request for Microsoft.Capacity to add version preview/2019-04-01
Azure/azure-rest-api-specs pull request #6731
Opened 2019-07-26 00:06 UTC by gautam714

If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/gautam714/azure-rest-api-specs/dev-reservations-Microsoft.Capacity-2019-04-01_includeterm...master/).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2019-07-26 00:08 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-07-26 00:09 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-07-26 00:10 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-07-26 04:33 UTC, nschonni commented
Model validation issues fixed in #6732. If you pull those fixes in here, let me know an I'll close that one

2019-07-26 15:55 UTC, gautam714 commented
> Model validation issues fixed in #6732. If you pull those fixes in here, let me know an I'll close that one

I have pulled the fix. All validations are passing now. Could you please approve and merge?

2019-07-26 15:57 UTC, nschonni commented
Sorry, i'm not an MS employee. I think there are instructions on the PR template for escalating internally

2019-07-26 18:30 UTC, daviwil commented
@openapibot sdkautomation rebuild

2019-07-27 08:38 UTC, Juliehzl commented
@NullMDR Can you have a look at SDK problem?

2019-07-29 02:23 UTC, NullMDR commented
@openapibot sdkautomation rebuild

2019-07-29 03:38 UTC, NullMDR commented
@Juliehzl This should be a bug in sdk automation. I'll check it later.

2019-07-29 08:09 UTC, NullMDR commented
@openapibot sdkautomation rebuild

2019-07-30 00:26 UTC, gautam714 commented
Can somebody please take a look from ARM side? @Juliehzl : please assign someone.

2019-07-31 01:56 UTC, majastrz commented on specification/reservations/resource-manager/Microsoft.Capacity/preview/2019-04-01/reservations.json
> +          "$ref": "#/definitions/ReservationTerm"
>ReservationTerm [](start = 33, length = 15)

You are adding a new property non-readonly property to a stable API version. This is considered a breaking change. You should introduce this change in a new API version.

2019-07-31 01:58 UTC, majastrz requested changes
You are adding a new property non-readonly property to a stable API version. This is considered a breaking change. You should introduce this change in a new API version.

2019-07-31 19:38 UTC, majastrz commented
> You are adding a new property non-readonly property to a stable API version. This is considered a breaking change. You should introduce this change in a new API version.

When I was tracing usages through in the Swagger I mistook response for the body of a PUT, which led to me to conclude that it wasn’t read-only. This was also confirmed by the RP owners.

2019-07-31 19:38 UTC, majastrz approved these changes
Signed off from ARM side.

2019-08-01 01:10 UTC, Juliehzl approved these changes

2019-08-01 01:10 UTC, merged