Move to stable version
Azure/azure-rest-api-specs pull request #6997
Opened 2019-08-19 22:55 UTC by LTA-Thinking

Moved from a preview version to a stable version. Added a new example, cleaned up some existing examples, and modified some descriptions text. VS's auto formatter changed the indents in the json files making it look like every line changed.

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-08-19 22:55 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-08-19 22:56 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-08-19 23:03 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-08-20 03:46 UTC, nschonni commented on specification/healthcareapis/resource-manager/readme.md
> +### Tag: package-2018-08-preview
```suggestion
### Tag: package-2019-09-16
```

2019-08-20 06:59 UTC, michaeljqzq commented on specification/healthcareapis/resource-manager/readme.md
> +   - $(this-folder)/Microsoft.HealthcareApis/stable/2019-09-16/healthcare-apis.json
format error

2019-08-21 18:49 UTC, poadhika commented
@nschonni @michaeljqzq  I saw the label WaitForArmFeedback. Is there any action that we need to take from our side? We have a GA deadline on 9-16. We need to complete this work before that timeframe. Any help would be mush appreciated.

2019-08-23 05:39 UTC, michaeljqzq commented
@poadhika ARM team will review the PR, normally need no more than a week

2019-08-23 05:41 UTC, michaeljqzq commented
@openapibot sdkautomation rebuild

2019-08-23 05:47 UTC, poadhika commented
@michaeljqzq Thank you for your response. We have a GA deadline of September 16. How can we expedite this process?

2019-08-27 17:29 UTC, anthony-c-martin requested changes

2019-08-28 02:42 UTC, michaeljqzq approved these changes

2019-08-28 09:14 UTC, yungezz commented
hi @anthony-c-martin could you pls change review state from "request change" to "approve" so we can go ahead to merge?

2019-08-28 16:12 UTC, anthony-c-martin approved these changes

2019-08-29 16:07 UTC, poadhika commented
@michaeljqzq, @nschonni : Can you please merge the PR?

2019-08-30 02:58 UTC, merged