[Do Not Merge]Putsubscription api
Azure/azure-rest-api-specs pull request #7000
Opened 2019-08-20 02:01 UTC by navysingla

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-08-20 02:02 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-08-20 02:04 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-08-20 02:37 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-08-20 08:01 UTC, Juliehzl commented
@navysingla You don't want to merge this PR, right? I add [DoNotMerge] label for your PR. And before reviewing, can you try to fix errors in CI checks first?

2019-08-22 23:58 UTC, KrisBash requested changes
Please see comments. Feel free to reach out with any questions

2019-08-22 23:58 UTC, KrisBash commented on specification/subscription/resource-manager/Microsoft.Subscription/preview/2019-03-01-preview/subscriptions.json
> +          "202": {
The 202 pattern is fine, but generally 201 is preferred for resource create. https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#asynchronous-operations

2019-08-28 06:09 UTC, yungezz commented
hi @navysingla are you still on this PR? Could you pls address comments? Is it ok to close if you're not ready for reviewing?

2019-08-28 06:22 UTC, navysingla commented
I will work on them tomorrow

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Yunge Zhu <notifications@github.com>
Sent: Tuesday, August 27, 2019 11:10:26 PM
To: Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com>
Cc: Navy Singla <Navy.Singla@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [Azure/azure-rest-api-specs] [Do Not Merge]Putsubscription api (#7000)


hi @navysingla<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnavysingla&data=02%7C01%7CNavy.Singla%40microsoft.com%7Cf851ca94772a4539cef508d72b7e6baa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637025694281473540&sdata=2Si0Lgq%2BiX3J35KQdcvW775efugEVnxEW7KnkTU%2FYq8%3D&reserved=0> are you still on this PR? Could you pls address comments? Is it ok to close if you're not ready for reviewing?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F7000%3Femail_source%3Dnotifications%26email_token%3DALLQV2DVXD6LDMK7243DG7DQGYJFFA5CNFSM4INLPEU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5J77SQ%23issuecomment-525598666&data=02%7C01%7CNavy.Singla%40microsoft.com%7Cf851ca94772a4539cef508d72b7e6baa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637025694281473540&sdata=7LnHx2UWmJgxSCL4lZIEzeUGSKUiw%2Fhsf2X4ngSgcvQ%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALLQV2FU7YQSWWKYRQ7TP53QGYJFFANCNFSM4INLPEUQ&data=02%7C01%7CNavy.Singla%40microsoft.com%7Cf851ca94772a4539cef508d72b7e6baa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637025694281483538&sdata=E98Ww%2Bo5mSvvXYCLTO0vBZMrsH9Q0P5RnN1fWWNmT1I%3D&reserved=0>.

2019-09-26 07:52 UTC, yungezz commented
hi @navysingla ping for update? Is it ok to close it for now since no update in 29 days?

2019-10-08 03:30 UTC, yungezz commented
hi @Juliehzl, could you pls follow up on this PR?

2020-07-24 14:34 UTC, akning-ms commented
Hi @navysingla, can we close this PR as it is idle for a long time.

2020-07-27 23:34 UTC, ravbhatnagar commented
Removing ARM labels for a 1 year old PR.

2020-09-23 07:24 UTC, Juliehzl commented
Hi  @navysingla, do you still need the PR? If yes, please fix CI error and remove donotmerge.

2020-10-19 02:36 UTC, Juliehzl commented
close the PR because there is no response for a long time. If you are ready for review, feel free to reopen it.

2020-10-19 02:36 UTC, closed without merging