[Hub Generated] Review request for Microsoft.Aadiam to add version stable/2018-01-01
Azure/azure-rest-api-specs pull request #7051
Opened 2019-08-28 00:13 UTC by jssmomo

If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/jssmomo/azure-rest-api-specs/dev-azureactivedirectory-Microsoft.Aadiam-2018-01-01...master/).

### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2019-08-28 02:00 UTC, ArcturusZhang commented on specification/azureactivedirectory/resource-manager/readme.md
> +  - Microsoft.Aadiam/stable/2018-01-01/azureactivedirectory.json
You should put the swagger files `metrics_API.json` and `metricDefinitions_API.json` in this section

2019-08-28 02:05 UTC, ArcturusZhang requested changes
Please fix the errors that CI reports

2019-08-28 23:38 UTC, jssmomo commented
> Please fix the errors that CI reports

Hi ArcturusZhang, can you help me fix the issues? Most of the issues are similar but I could not figure out what could be the root cause. The error is:

scripts/multiapi.ts(95,40): error TS2345: Argument of type 'Set<string>' is not assignable to parameter of type 'Iterable<any>'.

2019-08-29 04:30 UTC, ArcturusZhang commented
> > Please fix the errors that CI reports
> 
> Hi ArcturusZhang, can you help me fix the issues? Most of the issues are similar but I could not figure out what could be the root cause. The error is:
> 
> scripts/multiapi.ts(95,40): error TS2345: Argument of type 'Set' is not assignable to parameter of type 'Iterable'.

That is caused by a bug introduced by typescript update, which is resolved now.
As for the failure on SDK python, I will try to consult the SDK owner of python

2019-08-30 01:37 UTC, ArcturusZhang commented
Hi @zikalino could you please help us check the failure on SDK python check?

2019-09-01 21:03 UTC, jssmomo commented
> Hi @zikalino could you please help us check the failure on SDK python check?

Hi @ArcturusZhang I fixed the validation. Can you let me know what is the next steps?

2019-09-02 02:17 UTC, ArcturusZhang commented
> > Hi @zikalino could you please help us check the failure on SDK python check?
> 
> Hi @ArcturusZhang I fixed the validation. Can you let me know what is the next steps?

Now we just need waiting for feedback from the ARM team, I will write an email to inform them of this pr

2019-09-06 18:54 UTC, jssmomo commented
Some more context: the added Metrics & MetricDefinitions APIs are the Tenant-Level equivalent of the existing Monitoring APIs. The schema and parameters are highly similar to the existing Monitoring APIs

2019-09-09 17:00 UTC, KrisBash commented
@jssmomo - do you want to move this to the private github repo? My understanding from discussion with the Insights team is that this is a prototype that will not ship publicly.

2019-09-09 22:31 UTC, jssmomo commented
> @jssmomo - do you want to move this to the private github repo? My understanding from discussion with the Insights team is that this is a prototype that will not ship publicly.

I think it make sense. One question I have before creating PR in private repo is that for our RP, we didn't work with private repo when we creating the specs. So should I also include the older APIs in the PR?

2019-09-20 01:59 UTC, ArcturusZhang commented
Hi @jssmomo will there be more update to this pr? If not, I am going to close this pr for now.

2019-09-21 00:01 UTC, jssmomo commented
> Hi @jssmomo will there be more update to this pr? If not, I am going to close this pr for now.

Hi @ArcturusZhang, please let me confirm with Kris. I'll let you know the update early next week.

2019-09-25 23:42 UTC, jssmomo commented
Closing the PR as I created one in Private repo:
https://github.com/Azure/azure-rest-api-specs-pr/pull/935

2019-09-25 23:42 UTC, closed without merging