Add Cosmos DB PrivateEndpointConnection and PrivateLink Swagger
Azure/azure-rest-api-specs pull request #7087
Opened 2019-08-30 18:43 UTC by ayanMSFT

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-08-30 18:44 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-08-30 18:45 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-08-30 19:17 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-08-31 13:06 UTC, anthony-c-martin requested changes

2019-08-31 13:06 UTC, anthony-c-martin commented on specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2015-04-08/cosmos-db.json
> +          "$ref": "#/definitions/Resource"
Again, I think you'll want to extend ProxyResource here, and not Resource.

2019-08-31 13:06 UTC, anthony-c-martin commented on specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2015-04-08/examples/CosmosDBPrivateLinkResourceListGet.json
> +    "api-version": "2015-04-08"
So you're not releasing a preview version of this resource prior to GA? Just want to make sure you're aware of the implications of releasing it with a stable api version. See https://armwiki.azurewebsites.net/api_contracts/APIDeprecationPolicy.html for some more info on this.

2019-08-31 13:06 UTC, anthony-c-martin commented on specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2015-04-08/examples/CosmosDBPrivateEndpointConnectionGet.json
> +    "subscriptionId": "subid",
[nit] Examples should resemble real data as closely as possible - please use a dummy guid for "subscriptionId"

2019-09-03 18:08 UTC, ayanMSFT commented on specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2015-04-08/cosmos-db.json
> +      "get": {
we are implementing that API in Cosmos DB RP. Should I wait for it to be deployed before updating the swagger, and updating this PR?

2019-09-06 02:39 UTC, KrisBash reviewed
There appear to be some blocking issues outstanding.

2019-09-06 02:39 UTC, KrisBash commented on specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2015-04-08/cosmos-db.json
> +      "get": {
@ayanMSFT  per review process, we want to see the swagger before exposing the API in the RP. The best way to do that is to flag the PR as doNotMerge, get it reviewed, and then ship the API, and finally merge the signed off PR

2019-09-06 17:05 UTC, ayanMSFT commented
I will send another PR with these proposed API changes after following the review process

2019-09-06 17:05 UTC, closed without merging