[DO NOT MERGE] Compute 2019-07-01 version
Azure/azure-rest-api-specs pull request #7094
Opened 2019-08-31 01:59 UTC by hyonholee

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-08-31 02:03 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-08-31 02:08 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-08-31 03:02 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-09-11 18:37 UTC, hyonholee commented
@zikalino Could you check why model validation fails in this PR?  Thanks

2019-09-26 19:01 UTC, hyonholee commented
@zikalino  the validation error says "Model definition 'DiskEncryptionSet' must have the properties 'name', 'id' and 'type' in its hierarchy and these properties must be marked as readonly."  But 'DiskEncryptionSet' has only id property which is set by a client in request body.

2019-10-15 19:04 UTC, hyonholee commented
These validation failures are expected.

Potential new ARM errors

========================

R2020 - RequiredPropertiesMissingInResourceModel

Model definition 'DiskEncryptionSetParameters' must have the properties 'name', 'id' and 'type' in its hierarchy and these properties must be marked as readonly.

  at specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json:6879



R3016 - DefinitionsPropertiesNamesCamelCase

Property named: 'diskIOPSReadWrite', for definition: 'DataDisk' must follow camelCase style. Example: 'diskIopsReadWrite'.

  at specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json:7113



R3016 - DefinitionsPropertiesNamesCamelCase

Property named: 'diskIOPSReadWrite', for definition: 'VirtualMachineScaleSetDataDisk' must follow camelCase style. Example: 'diskIopsReadWrite'.

  at specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json:8420

2019-10-15 22:39 UTC, hyonholee commented
@zikalino Hi, we finalized our Swagger spec from our side.  Could you review this PR?  The failed validation errors are expected.

2019-10-17 01:37 UTC, zikalino commented
@hyonholee so we need to disable these validation errors

2019-10-17 05:47 UTC, qiaozha commented
@hyonholee   For errors in LintDiff, if you'd like to suppress these validation errors, you may refer to specification/compute/resource-manager/readme.md of this repo and add them to the suppress part.

2019-10-18 23:07 UTC, KrisBash requested changes
All swagger API specs should have a "default" response with a response body aligned to standard error contract. Can we at least add that in new/changed APIs?

2019-10-18 23:07 UTC, KrisBash commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +        "responses": {
Missing "default" response, which should be on all API responses. See[ here for an example. ](https://github.com/Azure/azure-rest-api-specs/blob/b51344bc3d2022a2ecacd5297a6ad1553418dd51/specification/batch/resource-manager/Microsoft.Batch/stable/2019-08-01/BatchManagement.json#L105)

2019-10-18 23:07 UTC, KrisBash commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +        "responses": {
These should all have "default" response too. Let's at least get the new APIs standarized in this fashion.

2019-10-18 23:07 UTC, KrisBash commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/disk.json
> +        "responses": {
Same comments on "default" throughout changed apis

2019-10-19 22:13 UTC, hyonholee commented
@KrisBash   I added default responses to the new APIs.

2019-10-19 22:22 UTC, KrisBash approved these changes
LGTM thanks

2019-10-20 00:28 UTC, zikalino approved these changes

2019-10-20 23:55 UTC, zikalino approved these changes

2019-10-20 23:55 UTC, merged