add ta v3.0-preview.1
Azure/azure-rest-api-specs pull request #7133
Opened 2019-09-05 17:24 UTC by HanLiMS

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-09-05 17:26 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-09-05 17:26 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-09-05 18:06 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-09-05 19:01 UTC, bazzdg commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "description" : "The API returns a list of pii entities (\\\"SSN\\\", \\\"Bank Account\\\", \\\"Goverment ID\\\" etc) in a given document. See the <a href=\"https://docs.microsoft.com/en-us/a
add in the description what PII stands for: Personally Identifiable Information (PII) although it is fine if in the summary it is simplky the acronym

2019-09-05 19:02 UTC, bazzdg commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "summary" : "Well-known entities.",
Could we possibly improve this summary. Possibly "Extract well known entities from text." or something along those lines

2019-09-05 19:04 UTC, bazzdg commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "summary" : "Sentiment",
Could we expand these summaries to be a little more descriptive

2019-09-05 19:06 UTC, bazzdg commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +          "description" : "(optional) This value indicates which model be used for scoring .",
we may want to work on making this a little more descriptive or add alink to see where the versions are where that is ready

2019-09-05 21:22 UTC, assafi requested changes
First pass. Please see comments.

2019-09-05 21:22 UTC, assafi commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +          "description" : "(Optional) if showStats=true was specified in the request this field will contain information about the \r\n            document payload."
We should probably group the statistics item under a new type. Not sure why this only has a description field.

2019-09-05 21:22 UTC, assafi commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "name" : {
Some folks weren't happy with the `name` field. Could you please gather feedback from the PMs for alternatives.

2019-09-05 21:22 UTC, assafi commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "wikipediaLanguage" : {
I think we may want to change this to be more generic to support other data sources as well. 
For example: have a `dataSourceLanguage`, `dataSourceId`, etc. and a `dataSource` with a `Wikipedia` value.

2019-09-05 21:22 UTC, assafi commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +          "description" : "(optional) If a well-known item with Wikipedia link is recognized,\r\n            a decimal number denoting the confidence level of the Wikipedia info will be returned."
Format description.

2019-09-05 21:22 UTC, assafi commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +  "x-servers" : [ {
This should probably be removed.

2019-09-06 02:14 UTC, ArcturusZhang commented
Hi @HanLiMS if you want to release SDK for this new RP, you should update the readme files correspondingly.

2019-09-06 21:23 UTC, suhas92 commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +          "required" : false,
By default, OpenAPI keeps every parameter as optional. So, adding a `required: false` on a query parameter is not a required.

2019-09-09 06:45 UTC, ArcturusZhang requested changes
Please update the readme files correspondingly.

2019-09-11 23:50 UTC, johanste commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +      },
Invalid json?

2019-09-11 23:56 UTC, johanste commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +    "hostTemplate": "{Endpoint}/text/analytics/v2.1-preview",
v3.0-preview?

2019-09-23 16:53 UTC, assafi requested changes
A bit more comments following the last few discussions.

2019-09-23 16:53 UTC, assafi commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +          "description" : "(optional) This value indicates which model will be used for scoring. If a model-version is not specified, the API should default to the latest, non-preview version. ",
According to the API discussion this should be `model-version` everywhere.

2019-09-23 16:53 UTC, assafi commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "operationId" : "56f30ceeeda5650db055a3c6",
Use operation name as ID

2019-09-23 16:53 UTC, assafi commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "innerError": {
`innererror` instead of `innerError`

2019-09-23 16:53 UTC, assafi commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +            "$ref" : "#/definitions/ErrorResponse"
This is missing the document `id` field.

2019-10-11 01:42 UTC, ArcturusZhang commented
Hi @HanLiMS it has been a quite long time since last update on this pr. Will there be more update to this pr? Otherwise I will close this pr for now, you can submit another pr when this service is ready

2019-10-11 18:49 UTC, assafi commented
@ArcturusZhang We have an API review later next week. We are planning to complete this PR soon after.

2019-10-23 23:08 UTC, assafi requested changes
model-version comments

2019-10-23 23:08 UTC, assafi commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +          "description" : "if model-version=true was specified in the request this field will indicate which model is used for scoring."
model-version is not set to true..

2019-10-23 23:08 UTC, assafi commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +          "description" : "if model-version=true was specified in the request this field will indicate which model is used for scoring."
Also, we should always return this, regardless if the value was specified or not in the input.

2019-10-23 23:08 UTC, assafi commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +            "examples" : {
No example contains model-version in the output

2019-10-29 02:16 UTC, ArcturusZhang commented
Seems there is a new json file not referenced in readme, which causes Avocado failure

2019-10-30 21:15 UTC, mssfang commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "operationId" : "/entities/recognition/pii",
Please use an appropriate name for method name. It shows up in the generated Java code:
```Java
Mono<SimpleResponse<Object>> /entities/recognition/general(@HostParam("Endpoint") String endpoint, @QueryParam("model-version") String modelVersion, @QueryParam("showStats") Boolean showStats, @BodyParam("application/json; charset=utf-8") MultiLanguageBatchInput multiLanguageBatchInput);
```
Might be `RecognitionPII` could be a better name. A better naming pattern is to capitalize the first letter of word and no space between words.

2019-10-30 21:16 UTC, mssfang commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "operationId" : "/entities/linking",
Use an appropriate name for the operationId. Same as above comment.

2019-10-30 21:16 UTC, mssfang commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "operationId" : "/keyPhrases",
Use an appropriate name for the operationId. Same as above comment.
```suggestion
        "operationId" : "keyPhrases",
```

2019-10-30 21:16 UTC, mssfang commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "operationId" : "/languages",
```suggestion
        "operationId" : "languages",
```

2019-10-30 21:17 UTC, mssfang commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "operationId" : "/sentiment",
```suggestion
        "operationId" : "sentiment",
```

2019-10-30 21:17 UTC, mssfang commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "operationId" : "/entities/recognition/general",
Use an appropriate name for the operationId. Same as above comment.

2019-11-04 23:44 UTC, kristapratico commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "detectedLanguage"
This needs to be "detectedLanguages" so that the correct variables get set.

2019-11-04 23:44 UTC, kristapratico commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "detectedLanguage" : {
Same here - "detectedLanguages"

2019-11-14 22:48 UTC, assafi commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-Preview.1/TextAnalytics.json
> +        "warnings" : {
Should we use an error object instead of a string here?

2019-11-14 22:48 UTC, assafi approved these changes
Approved with one comment regarding warnings.

2019-11-15 01:44 UTC, ArcturusZhang commented
For spellcheck CI, you should change the word spellchecking reported as "Unknown word", or you should append these new words to the `custom-words.txt` file.
For the Avocado CI, you should reference your json file in the readme. This should resolve the error.
For the ModelValidation CI, it seems you have some errors in your examples, missing required parameters, etc.
Please fix these CI. If you do not have permission to check those logs, let me know. 
Thanks

2019-11-15 01:45 UTC, ArcturusZhang commented
And for now, you can ignore the SDK java CI  error. Maybe it only fails by its own.

2019-11-18 02:33 UTC, ArcturusZhang commented
Hi @raych1 could you please help us on identifying the errors in `ModelValidation`?

2019-11-18 06:04 UTC, raych1 commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-preview.1/TextAnalytics.json
> +      "example": {
Can you remove this example part since it has x-ms-example to cover already?

2019-11-18 06:04 UTC, raych1 commented on specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-preview.1/TextAnalytics.json
> +      "example": {
Can you remove this example part since it has x-ms-example to cover already?

2019-11-18 06:08 UTC, raych1 commented
@HanLiMS , can you remove the example part in swagger since it's covered in x-ms-examples already? There's a bug in modelvalidation would check the non-required parameter for example within swagger file. cc: @ArcturusZhang

2019-11-18 06:57 UTC, HanLiMS reviewed
> @HanLiMS , can you remove the example part in swagger since it's covered in x-ms-examples already? There's a bug in modelvalidation would check the non-required parameter for example within swagger file. cc: @ArcturusZhang

Hi I updated according to your suggestion but still could not pass the validations. Any more suggestions? 

Thanks!

2019-11-20 06:35 UTC, ArcturusZhang approved these changes

2019-11-20 06:35 UTC, merged