Changed swagger to fit the new return value from actions controller
Azure/azure-rest-api-specs pull request #7171
Opened 2019-09-10 15:44 UTC by YuvalShilo-Microsoft

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-09-10 15:46 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-09-10 15:47 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-09-10 15:59 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-09-11 07:29 UTC, shschwar reviewed
Looks great. 
NIT - Could please just update the trigger URI comment to be more accurate.
from: "The uri for the action to trigger " --> to "Logic App Callback URL".

2019-09-11 11:09 UTC, nirgfani commented on specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2019-01-01-preview/SecurityInsights.json
>            "200": {
Shouldn't the ref in the put use ActionRequest?

2019-09-12 20:30 UTC, KrisBash requested changes
This looks like a breaking change within api version

2019-09-15 10:33 UTC, YuvalShilo-Microsoft commented on specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2019-01-01-preview/SecurityInsights.json
> +        "workflowId": {
Our product is still in preview, that's why we are doing these changes now..
we don't think there should be a new API version.

2019-09-19 13:53 UTC, KrisBash approved these changes
Signing off after offline discussion

2019-09-20 03:11 UTC, merged