Document update. Commit on behalf of Don(v-donglo2@microsoft.com).
Azure/azure-rest-api-specs pull request #719
Opened 2016-11-11 23:22 UTC by NonStatic2014

Update swagger with refined wording to prepare for new document web site.

2016-11-11 23:46 UTC, BryanLa commented on arm-machinelearning/2016-05-01-preview/swagger/webservices.json
> +            "description": "Success. This respoonse is returned for an update web service operation. The response payload is identical to the response payload that is returned by the GET operation. T
Typo in "respoonse"

2016-11-11 23:47 UTC, NonStatic2014 commented on arm-machinelearning/2016-05-01-preview/swagger/webservices.json
> +            "description": "Success. This respoonse is returned for an update web service operation. The response payload is identical to the response payload that is returned by the GET operation. T
Good catch!

2016-11-11 23:48 UTC, BryanLa commented on arm-machinelearning/2016-05-01-preview/swagger/webservices.json
> +            "description": "Created. This response is returned for a create web service operation. The response includes the Provisioning State and the Azure-AsyncOperation header. To get the progres
"For more information" is duplicated

2016-11-11 23:49 UTC, NonStatic2014 commented on arm-machinelearning/2016-05-01-preview/swagger/webservices.json
> +            "description": "Created. This response is returned for a create web service operation. The response includes the Provisioning State and the Azure-AsyncOperation header. To get the progres
They are different response code. That's why we write twice.

2016-11-11 23:50 UTC, BryanLa commented on arm-machinelearning/2016-05-01-preview/swagger/webservices.json
> +            "description": "Success. The response includes a paginated array of web service objects and a URI to the next set of results, if any. For the more infomartion the limits of the number of
Typo in "infomartion"

2016-11-11 23:52 UTC, BryanLa commented on arm-machinelearning/2016-05-01-preview/swagger/webservices.json
> +          "description": "When set to true, indicates that the Web Service is read-only and can no longer be updated or patched, only removed. Default, is false. Note: Once set to true, you cannot ch
Do you want "web service", for consistency?

2016-11-11 23:53 UTC, BryanLa commented on arm-machinelearning/2016-05-01-preview/swagger/webservices.json
> +          "description": "Specifies the storage account that Azure Machine Learning uses to store information about the web service. Only the name of the storage account is returned from calls to GET
Typo in "assests"

2016-11-11 23:54 UTC, NonStatic2014 commented on arm-machinelearning/2016-05-01-preview/swagger/webservices.json
> +          "description": "When set to true, indicates that the Web Service is read-only and can no longer be updated or patched, only removed. Default, is false. Note: Once set to true, you cannot ch
Will change it to lower case.

2016-11-11 23:55 UTC, BryanLa commented on arm-machinelearning/2016-05-01-preview/swagger/webservices.json
> +          "description": "Specifies the Azure Rerource Manager ID of the commitment plan associated with the web service."
Typo in "Rerource"

2016-11-11 23:56 UTC, BryanLa reviewed
Completed review of descriptions, but SDK team will need to review schema changes.

2016-11-12 00:16 UTC, BryanLa approved these changes
@amarzavery - the description changes are done; can you sign off on the other changes and merge?

2016-11-13 22:13 UTC, amarzavery requested changes

2016-11-13 22:13 UTC, amarzavery commented on arm-machinelearning/2016-05-01-preview/swagger/webservices.json
> +      "required": true
Please apply the extension `"x-ms-parameter-location": "method"`, for "ResourceGroupNameParameter" and "WebServiceNameParameter". By default parameters defined in the global parameters section will be properties of the client in the generated code. You would not want resourceGroupName and webServiceName as properties of the client as the customer would like to use the same client for making requests against different resource groups or webservices. Changing the property of the client everytime is inconvenient. Hence please apply the above mentioned extension to these two parameters.

2016-11-13 22:13 UTC, amarzavery commented on arm-machinelearning/2016-05-01-preview/swagger/webservices.json
> +          "description": "Read Only: The date and time when the web service was created.",
@BryanLa - I do not like this aspect of documentation. Why would you want the spec author to duplicate information in the description? The documentation tool should pickup `"readOnly": true` and update the documentation accordingly.

2016-11-14 17:02 UTC, BryanLa commented on arm-machinelearning/2016-05-01-preview/swagger/webservices.json
> +          "description": "Read Only: The date and time when the web service was created.",
I mentioned this in the email thread as well, but I agree. I've filed a DocFx tool bug to the VSC team.

2016-11-14 17:05 UTC, BryanLa commented on arm-machinelearning/2016-05-01-preview/swagger/webservices.json
> +          "description": "Read Only: The date and time when the web service was created.",
I mentioned this in the email thread as well, but I agree. I've filed a DocFx tool bug to the VSC team.

2016-11-15 01:54 UTC, amarzavery approved these changes

2016-11-15 01:54 UTC, merged

2016-11-15 01:56 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR719)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/589

2016-11-15 01:56 UTC, AutorestCI commented
No modification for NodeJS

2016-11-15 01:56 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR719)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/885