Add extension API for VMScaleset VMs
Azure/azure-rest-api-specs pull request #7407
Opened 2019-10-06 22:39 UTC by sds6

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-10-06 22:42 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-10-06 22:46 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-10-06 23:01 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-10-07 22:19 UTC, hyonholee requested changes

2019-10-07 22:19 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +    "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}/virtualMachines/{instanceId}/extensions/vmExtensionName": {
URL is wrong.   Should be {vmExntensionName}, instead of just vmExtensionName

2019-10-07 22:19 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +        "operationId": "VirtualMachineScaleSetVMs_CreateOrUpdate",
It should be VirtualMachineScaleSetVMExtensions_CreateOrUpdate

2019-10-07 22:19 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +        "description": "The operation to create or update the extension.",
create or update the VMSS VM extension.

2019-10-07 22:19 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +        "operationId": "VirtualMachineScaleSetVMs_Update",
same as above

2019-10-07 22:19 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +        "description": "The operation to update the extension.",
same as above

2019-10-07 22:19 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +        "operationId": "VirtualMachineScaleSetVMs__Delete",
same as above

2019-10-07 22:19 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +        "description": "The operation to delete the extension.",
same as above

2019-10-07 22:19 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +        "operationId": "VirtualMachineScaleSetVMs_Get",
same as above

2019-10-07 22:19 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +        "description": "The operation to get the extension.",
same as above

2019-10-07 22:19 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +        "x-ms-long-running-operation": true
add example file

2019-10-07 22:19 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +        "x-ms-long-running-operation": true
add example file

2019-10-07 22:19 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +            }
add example file

2019-10-07 22:19 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +        "x-ms-long-running-operation": true
add example file

2019-10-10 05:14 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +    "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}/virtualMachines/{instanceId}/extensions/{vmExtensionName}":
/ is missing before subscriptions

2019-10-10 06:19 UTC, danielli90 commented on specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/compute.json
> +    "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}/virtualMachines/{instanceId}/extensions/{vmExtensionName}":
this one caused Semantic Error. The path should start with "/", such as "/subscriptions/{subscriptionId}/..."

2019-10-11 20:34 UTC, huangpf commented
Sign off on behalf of the team

2019-10-11 22:39 UTC, huangpf approved these changes

2019-10-11 22:40 UTC, merged