Tesha/fqdn filtering
Azure/azure-rest-api-specs pull request #7427
Opened 2019-10-08 17:08 UTC by tejasshah7

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-10-08 17:10 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-10-08 17:52 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-10-08 18:01 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-10-08 21:51 UTC, anton-evseev requested changes
Just to be sure: are those two new properties settable by the customer? Or are they read-only?

2019-10-08 21:56 UTC, tejasshah7 commented on specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/azureFirewall.json
> +        "translatedFqdn": {
Sure moved both fields.

2019-10-08 21:56 UTC, tejasshah7 commented on specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/azureFirewall.json
> +        "destinationFqdns": {
Done.

2019-10-08 21:57 UTC, tejasshah7 commented
> Just to be sure: are those two new properties settable by the customer? Or are they read-only?

These can be set by customers.

2019-10-08 22:06 UTC, anton-evseev requested changes
You've updated order in examples, I was talking about spec file

2019-10-08 22:09 UTC, tejasshah7 commented
> You've updated order in examples, I was talking about spec file

Sorry my bad. Updated the spec file now.

2019-10-08 22:23 UTC, anton-evseev approved these changes

2019-10-09 17:24 UTC, KrisBash approved these changes
LGTM

2019-10-09 19:35 UTC, sergey-shandar approved these changes

2019-10-09 19:35 UTC, merged