Add skipActionRuleSet to appgw waf definition
Azure/azure-rest-api-specs pull request #7457
Opened 2019-10-10 22:19 UTC by jshaker

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-10-10 22:20 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-10-10 22:20 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-10-10 22:31 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-10-10 23:06 UTC, number213 commented
Please rebase your branch, there are a lot of unrelated commits here

2019-10-11 09:31 UTC, lirenhe commented
@jshaker  could you take a look at the error for spell check?

2019-10-11 18:47 UTC, jshaker commented
@number213 addressed commits
@lirenhe addressed spell check

2019-10-12 00:27 UTC, anton-evseev approved these changes
Can you also add examples for those properties?

2019-10-14 03:36 UTC, lirenhe approved these changes

2019-10-16 17:50 UTC, KrisBash approved these changes
LGTM

2019-10-16 20:51 UTC, anton-evseev requested changes

2019-10-16 20:51 UTC, number213 commented on specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/examples/WafPolicyGet.json
> +              "skippedManagedRulesets": [
```suggestion
              "skippedManagedRuleSets": [
```

2019-10-17 03:46 UTC, lirenhe commented
@jshaker, please fix the problem for model validation.

2019-10-18 23:00 UTC, jshaker commented
These changes are being pushed to a later release cycle

2019-10-18 23:00 UTC, closed without merging