Add new API version for Server AAD Admin
Azure/azure-rest-api-specs pull request #7652
Opened 2019-10-28 21:21 UTC by amolagar5

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-10-28 21:21 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=7652) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=7652) before we can accept your contribution.<br/><br/>:x: amolagar5 [sign now](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=7652)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-rest-api-specs?pullRequest=7652) it.</sub>

2019-10-28 21:27 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-10-28 21:32 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-10-29 02:50 UTC, lirenhe commented
@amolagar5 , could you take a look at the tool check error? It seems "$ref": "#/definitions/ProxyResource" is not defined.

2019-10-31 03:28 UTC, lirenhe commented
@amolagar5 , I still see a lot of check error, fix take a look at them and do the proper fix.  And let me know if you have any questions.

2019-10-31 18:39 UTC, amolagar5 commented
Thanks @lirenhe  I will take a look and update the request.

2019-11-01 22:02 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-11-02 01:20 UTC, amolagar5 commented
@lirenhe , can you please help me figure out why checks are failing. I keep getting something like this. 
INFO:swaggertosdk.autorest_tools:  Error: '$.paths["/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/administrators/{administratorName}"].put.tags' has incompatible values (---

INFO:swaggertosdk.autorest_tools:- ServerAdministrators

INFO:swaggertosdk.autorest_tools:, ---

INFO:swaggertosdk.autorest_tools:- Administrators

INFO:swaggertosdk.autorest_tools:).

2019-11-04 05:14 UTC, lirenhe commented
@amolagar, could you first fix the problem in Avocado and ModelValidation check? This may help to solve the problem for autorest.

2019-11-05 02:25 UTC, amolagar5 commented
@lirenhe thanks Renhe for taking a look, Looks like swaggers for 2014-04-01 and 2018-06-01-preview have to be exactly same for create or update. Any idea why that is needed. ?

2019-11-05 02:59 UTC, lirenhe commented
> @lirenhe thanks Renhe for taking a look, Looks like swaggers for 2014-04-01 and 2018-06-01-preview have to be exactly same for create or update. Any idea why that is needed. ?

Not quite sure about this. What item do you think is 'not needed'?

2019-11-06 04:34 UTC, lirenhe commented
@amolagar, there are a couple of failures in prettier check, could you also fix the code style issue?

2019-11-06 17:31 UTC, amolagar5 commented
@lirenhe how do I fix these prettier check failures, it only says check fails. Does not say why and how to fix them. Can you please share more details on what to fix and how to run tool locally or on git to find more information.

2019-11-08 14:55 UTC, amolagar5 commented
@lirenhe , can you please take a look when possible, I fixed prettier check and now its complaining about prettier check on files I am deleting and also some breaking change.

2019-11-14 02:25 UTC, lirenhe commented
> @lirenhe , can you please take a look when possible, I fixed prettier check and now its complaining about prettier check on files I am deleting and also some breaking change.

We will take a look at those errors.

2019-11-14 03:48 UTC, amolagar commented
Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Renhe Li <notifications@github.com>
Sent: Wednesday, November 13, 2019 6:25:36 PM
To: Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com>
Cc: Amol Agarwal-SQL <Amol.Agarwal@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [Azure/azure-rest-api-specs] Add new API version for Server AAD Admin (#7652)


@lirenhe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flirenhe&data=02%7C01%7CAmol.Agarwal%40microsoft.com%7Cc9591ed3e3304be4dcd908d768a9efaa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637092951400497304&sdata=UG0qcDJ9mylvv798cNqcOeeWOPbu%2F6l6xV7StwWv5tg%3D&reserved=0> , can you please take a look when possible, I fixed prettier check and now its complaining about prettier check on files I am deleting and also some breaking change.

We will take a look at those errors.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F7652%3Femail_source%3Dnotifications%26email_token%3DAHCRXN2DJPFIW5KNMGDKJNLQTSZKBA5CNFSM4JGAITVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEALJLA%23issuecomment-553694380&data=02%7C01%7CAmol.Agarwal%40microsoft.com%7Cc9591ed3e3304be4dcd908d768a9efaa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637092951400497304&sdata=wfxpviJHwP2k4JW96XQo2x%2BfHnasYdIbDwiYfAKNvhA%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHCRXN6FDHWRIA2U5RRK57DQTSZKBANCNFSM4JGAITVA&data=02%7C01%7CAmol.Agarwal%40microsoft.com%7Cc9591ed3e3304be4dcd908d768a9efaa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637092951400507295&sdata=dCo3jWqZQ0uyXyZuBmFwq9Pi05oRMdCQsOiN%2FC3BGVw%3D&reserved=0>.

2019-11-15 01:29 UTC, qiaozha commented
for breakingchange error, the .azure-pipeline-preproduction/package-lock.json file in your branch is still the old version please merge newest Azure:master into your branch. This breakingchange error should be gone.

2019-11-15 17:25 UTC, amolagar5 commented
Thanks @qiaozha , Merge fixed it, only pretty check is left which is on a file that is being deleted. Can you please review and sign off.

2019-11-18 01:38 UTC, qiaozha commented
> Thanks @qiaozha , Merge fixed it, only pretty check is left which is on a file that is being deleted. Can you please review and sign off.

@NullMDR  please take a look at this pretty check error

2019-11-18 05:34 UTC, NullMDR commented
Sorry there is a bug in prettier check. I'll try to fix it.

2019-11-18 05:59 UTC, NullMDR commented
/azp run

2019-11-18 06:28 UTC, NullMDR commented
@qiaozha @amolagar5 Fixed.

2019-11-18 19:08 UTC, lirenhe approved these changes

2019-11-18 23:36 UTC, jaredmoo requested changes

2019-11-18 23:36 UTC, jaredmoo commented on specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/ServerAzureADAdministrators.json
> +            "name": "administratorName",
This should have `enum` . See https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/Microsoft.Sql/preview/2017-03-01-preview/managedInstanceAdministrators.json

2019-11-18 23:36 UTC, jaredmoo commented on specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/ServerAzureADAdministrators.json
> +    "AdministratorListResult": {
For compatibility this should be ServerAdministratorListResult

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/sql/resource-manager/Microsoft.Sql/stable/2014-04-01/serverAzureADAdministrators.json#L258

2019-11-19 21:11 UTC, jaredmoo approved these changes

2019-11-19 22:14 UTC, amolagar5 commented
@lirenhe whom should I ask for merge now. Is it ARM team. ?

2019-11-20 18:37 UTC, ryansbenson commented on specification/sql/resource-manager/Microsoft.Sql/stable/2014-04-01/serverAzureADAdministrators.json
> -{
Have you gone through the deprecation process for these APIs?

https://armwiki.azurewebsites.net/api_contracts/APIDeprecationPolicy.html

2019-11-20 18:37 UTC, ryansbenson commented on specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/ServerAzureADAdministrators.json
> +    "title": "SqlManagementClient",
Title should be human readable

2019-11-20 18:37 UTC, ryansbenson commented on specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/ServerAzureADAdministrators.json
> +    "SqlVirtualMachineContainerNameParameter": {
unused

2019-11-20 18:37 UTC, ryansbenson commented on specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/ServerAzureADAdministrators.json
> +    "SqlVirtualMachineInstanceNameParameter": {
unused

2019-11-20 18:37 UTC, ryansbenson commented on specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/ServerAzureADAdministrators.json
> +    "VirtualClusterNameParameter": {
unused

2019-11-20 18:37 UTC, ryansbenson commented on specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/ServerAzureADAdministrators.json
> +    "BlobAuditingPolicyNameParameter": {
unused

2019-11-20 18:37 UTC, ryansbenson commented on specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/ServerAzureADAdministrators.json
> +    "ManagedInstanceNameParameter": {
unused

2019-11-20 18:37 UTC, ryansbenson commented on specification/sql/resource-manager/Microsoft.Sql/preview/2018-06-01-preview/ServerAzureADAdministrators.json
> +    "DatabaseNameParameter": {
unused

2019-11-20 18:50 UTC, jaredmoo commented on specification/sql/resource-manager/readme.md
> -- Microsoft.Sql/stable/2014-04-01/serverAzureADAdministrators.json
Should not remove

2019-11-20 18:50 UTC, jaredmoo commented on specification/sql/resource-manager/readme.md
> -- Microsoft.Sql/stable/2014-04-01/serverAzureADAdministrators.json
Should not remove

2019-11-20 21:06 UTC, amolagar5 commented
@ryansbenson added old files back, for title. - @jaredmoo  said its generic one for all SQL, unused params are generated by automation and not worth removing manually.

2019-11-22 22:55 UTC, ryansbenson approved these changes
Approved from ARMs side

2019-11-22 23:00 UTC, amolagar5 commented
@lirenhe , can you please merge. thanks @ryansbenson  for signing off.

2019-11-27 02:50 UTC, lirenhe commented
@amolagar5, I am unable to merge it because of the conflicts. Please help to resolve the conflicts.

2019-11-27 18:02 UTC, amolagar5 commented
@lirenhe , Sure. Merge complete, pls try again.

2019-11-28 02:29 UTC, merged

2019-11-28 17:54 UTC, amolagar commented
Thanks Renhe

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Renhe Li <notifications@github.com>
Sent: Wednesday, November 27, 2019 6:29:11 PM
To: Azure/azure-rest-api-specs <azure-rest-api-specs@noreply.github.com>
Cc: Amol Agarwal-SQL <Amol.Agarwal@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [Azure/azure-rest-api-specs] Add new API version for Server AAD Admin (#7652)


Merged #7652<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F7652&data=02%7C01%7CAmol.Agarwal%40microsoft.com%7Cf666709973ce48fbdd7f08d773aac178%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637105049540158682&sdata=VUu11neNohpHdb2w4NMgU%2BHdHGO5iykYmtKGmW1nrcE%3D&reserved=0> into master.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F7652%3Femail_source%3Dnotifications%26email_token%3DAHCRXN2N5TOO3DINGWR4XSLQV4UHPA5CNFSM4JGAITVKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOVEQLNNY%23event-2837493431&data=02%7C01%7CAmol.Agarwal%40microsoft.com%7Cf666709973ce48fbdd7f08d773aac178%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637105049540158682&sdata=zscw1ihWD1e4rPWEBOZjGevxIlL00jVyz38TQO4NwMc%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHCRXN4DDDWOGYBGTOBHWHDQV4UHPANCNFSM4JGAITVA&data=02%7C01%7CAmol.Agarwal%40microsoft.com%7Cf666709973ce48fbdd7f08d773aac178%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637105049540168649&sdata=o2O6dpatkoyfbvLXhiUGvQPpllbV3CiMFrooD7Mg3Gw%3D&reserved=0>.