[Datafactory] Add reportStatusOnCallBack property to webhook activity
Azure/azure-rest-api-specs pull request #7682
Opened 2019-10-31 19:52 UTC by LijuanZ

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [X] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-10-31 19:52 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-10-31 19:53 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-10-31 19:58 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-11-01 01:57 UTC, zhangyd2015 commented
@haricr can you review this change?

2019-11-01 01:59 UTC, zhangyd2015 approved these changes

2019-11-01 06:23 UTC, jackmagic313 reviewed
Does this property support expression? If so then it needs to be object type.

2019-11-01 06:25 UTC, jackmagic313 approved these changes

2019-11-01 18:42 UTC, LijuanZ commented
> Does this property support expression? If so then it needs to be object type.
@jackmagic313 Currently we don't support parameterization for this property yet, but I think there is no harm to make it parameterizable, so I've updated type to be object

2019-11-01 21:42 UTC, pilor requested changes

2019-11-01 21:42 UTC, pilor commented on specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Pipeline.json
> +        "reportStatusOnCallBack": {
Adding writable properties is typically a breaking change that requires a new api-version.  Here are the API versioning standard for ARM:  https://microsoft.sharepoint.com/:w:/t/azureresourcemanagerteam/EWXsAQ1yx25KkyYCeeWGUgwBSBxEdUDEbHi6FZ__U8EOQw?e=xEcppo

2019-11-01 21:58 UTC, pilor approved these changes

2019-11-04 01:59 UTC, ChenTanyi approved these changes

2019-11-04 01:59 UTC, merged