Santosh nov 25 2019 microsoft.subscription 2019 10 01 preview
Azure/azure-rest-api-specs pull request #7846
Opened 2019-11-26 03:47 UTC by santoshsinha100

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2019-11-26 03:48 UTC, AutorestCI commented
# Automation for azure-sdk-for-python

2019-11-26 03:49 UTC, AutorestCI commented
# Automation for azure-sdk-for-go

2019-11-28 07:37 UTC, ArcturusZhang commented
Do not forget to update the readme files for those language you want to generate SDK for.

2019-12-11 16:14 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-12-13 04:46 UTC, anthony-c-martin requested changes

2019-12-13 04:46 UTC, anthony-c-martin commented on specification/subscription/resource-manager/Microsoft.Subscription/preview/2019-10-01-preview/examples/GetOperationStatus.json
> +        "Location": "/subscriptions/44069e2b-39d3-44b2-93c0-7d2c70e7a02a/providers/Microsoft.Subscription/PurchaseSupportStatus/83aa47df-e3e9-49ff-877b-94304bf3d3ad?api-version=2019-10-01-preview",
[nit] OperationStatus

2019-12-13 04:46 UTC, anthony-c-martin commented on specification/subscription/resource-manager/Microsoft.Subscription/preview/2019-10-01-preview/subscriptions.json
> +        "prodirect_support"
What does 'prodirect' mean - will that be obvious to API users or does it need a description?

2019-12-13 04:46 UTC, anthony-c-martin commented on specification/subscription/resource-manager/Microsoft.Subscription/preview/2019-10-01-preview/subscriptions.json
> +        "basic_support",
@ArcturusZhang can you confirm that underscores are OK for SDK generation?

2019-12-13 04:46 UTC, anthony-c-martin commented on specification/subscription/resource-manager/Microsoft.Subscription/preview/2019-10-01-preview/subscriptions.json
> +    "SupportPlanName": {
`SupportPlanProperties`? Since this technically describes an object containing the support plan type.

2019-12-13 04:46 UTC, anthony-c-martin commented on specification/subscription/resource-manager/Microsoft.Subscription/preview/2019-10-01-preview/subscriptions.json
> +    "/subscriptions/{subscriptionId}/providers/Microsoft.Subscription/PurchaseSupport": {
Technically this can be used to purchase, cancel and convert - can we call it something more generic - `configureSupport` for example?

2019-12-13 04:46 UTC, anthony-c-martin commented on specification/subscription/resource-manager/Microsoft.Subscription/preview/2019-10-01-preview/subscriptions.json
> +    "/subscriptions/{subscriptionId}/providers/Microsoft.Subscription/SupportPlan/default": {
Just to confirm - can a subscription have multiple support plans, or just one (named default)?

2019-12-13 04:46 UTC, anthony-c-martin commented on specification/subscription/resource-manager/Microsoft.Subscription/preview/2019-10-01-preview/subscriptions.json
> +        "parameters": [
This API might feel more intuitive if it were a PUT (create or update) and a DELETE (delete) on the supportPlan resource. What's the reason to model it as a POST?

2019-12-13 04:46 UTC, anthony-c-martin commented on specification/subscription/resource-manager/Microsoft.Subscription/preview/2019-10-01-preview/subscriptions.json
> +    "/subscriptions/{subscriptionId}/providers/Microsoft.Subscription/OperationStatus/{Id}": {
I'm not sure whether you need to model this - does it make sense for customers to be able to call it directly, or only within the context of an async operatin? The generated SDKs will be able to track async operations without adding this definition.

2020-01-06 23:59 UTC, sanjaiganesh commented
@santoshsinha100 please address the comments.

2020-01-08 19:30 UTC, AutorestCI commented
/azp run automation - sdk

2020-01-15 04:30 UTC, ArcturusZhang commented
Hi @santoshsinha100 do we have any updates on this PR?
And you may need to do a rebase or merge to resolve the conflicts

2020-02-03 07:54 UTC, ArcturusZhang commented
Close due to not receiving any update from author

2020-02-03 07:54 UTC, closed without merging