enable datafactory cli generation
Azure/azure-rest-api-specs pull request #7942
Opened 2019-12-11 01:16 UTC by zikalino

2019-12-11 01:16 UTC, AutorestCI commented
/azp run automation - sdk

2019-12-11 01:43 UTC, mmyyrroonn approved these changes

2019-12-11 06:42 UTC, AutorestCI commented
/azp run automation - sdk

2019-12-11 16:12 UTC, azuresdkci commented
Can one of the admins verify this patch?

2019-12-13 01:26 UTC, mmyyrroonn approved these changes

2019-12-16 01:58 UTC, AutorestCI commented
/azp run automation - sdk

2019-12-16 02:01 UTC, AutorestCI commented
/azp run automation - sdk

2019-12-16 03:00 UTC, AutorestCI commented
/azp run automation - sdk

2019-12-16 09:04 UTC, MyronFanQiu commented
@zikalino Do we still need this PR?

2019-12-19 03:39 UTC, mmyyrroonn requested changes

2019-12-19 03:39 UTC, MyronFanQiu commented on specification/datafactory/resource-manager/test/test_cli_mgmt_datafactory.py
> +import mock
Sorry. We should remove these files.

2019-12-20 02:29 UTC, MyronFanQiu commented
@zikalino Since this is a small changes and you included extra files and you're too busy. 😄  I would close it first. Feel free to open a new one~

2020-01-02 05:42 UTC, AutorestCI commented
/azp run automation - sdk

2020-01-02 05:43 UTC, AutorestCI commented
/azp run automation - sdk

2020-01-16 05:50 UTC, mmyyrroonn approved these changes

2020-01-16 05:58 UTC, merged