Diagnostic contract update for the 2019-12-01-preview api version
Azure/azure-rest-api-specs pull request #8072
Opened 2020-01-06 20:19 UTC by promoisha

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [x] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [x] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [x] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [x] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [x] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2020-01-06 20:20 UTC, AutorestCI commented
/azp run automation - sdk

2020-01-06 23:07 UTC, solankisamir commented on specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2019-12-01-preview/definitions.json
> +        "httpCorrelationProtocol": {
>httpCorrelationProtocol [](start = 9, length = 23)

need to update the examples

2020-01-06 23:07 UTC, solankisamir requested changes
Need to update the examples

2020-01-07 13:33 UTC, akning-ms commented
Hi @qiaozha  Can you help take a look the lint & breakchange fail?

2020-01-09 00:55 UTC, ryansbenson reviewed
approved from ARMs side

2020-01-09 14:41 UTC, qiaozha commented
> Hi @qiaozha Can you help take a look the lint & breakchange fail?

@promoisha  your branch is behind Azure:master. Can you rebase it with the newest Azure:master and see if the problem still exists?

2020-01-09 18:08 UTC, solankisamir approved these changes
looks good

2020-01-09 18:09 UTC, solankisamir commented
> > Hi @qiaozha Can you help take a look the lint & breakchange fail?
> 
> @promoisha your branch is behind Azure:master. Can you rebase it with the newest Azure:master and see if the problem still exists?

@qiaozha this is a forked branch off master. We will rebase the forked branch when we are ready to merge to master

2020-01-09 18:09 UTC, merged