Added Support for IPv6 Circuit Connection Configuration.
Azure/azure-rest-api-specs pull request #8145
Opened 2020-01-14 09:32 UTC by amwate

### Latest improvements:
Below changes to ExpressRouteCircuitConfig are to provide the support for IPv6 properties. 
The support was added to NRP in the September release. Although the feature was not published or GA'd.

The below configurations would add a node IPv6CircuitConnectionProperties to the existing expressRouteCircuitConnection object. 

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2020-01-14 09:32 UTC, AutorestCI commented
/azp run automation - sdk

2020-01-14 09:32 UTC, AutorestCI commented
/azp run automation - sdk

2020-01-14 09:39 UTC, AutorestCI commented
/azp run automation - sdk

2020-01-14 09:40 UTC, AutorestCI commented
/azp run automation - sdk

2020-01-14 12:04 UTC, anton-evseev requested changes
Please address `ModelValidation` errors
https://dev.azure.com/azure-sdk/public/_build/results?buildId=233338&view=logs&jobId=8d2f9c49-cd83-5a9d-f3fe-2fd651afa742

2020-01-14 12:04 UTC, number213 commented on specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/expressRouteCircuit.json
> +    "Ipv6CircuitConnectionConfig": {
Please add `description`

2020-01-14 12:04 UTC, number213 commented on specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/expressRouteCircuit.json
> +    "Ipv6CircuitConnectionConfig": {
Please add `description`

2020-01-14 12:38 UTC, AutorestCI commented
/azp run automation - sdk

2020-01-14 12:38 UTC, amwate commented on specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/expressRouteCircuit.json
> +    "Ipv6CircuitConnectionConfig": {
Added

2020-01-14 12:38 UTC, amwate commented on specification/network/resource-manager/Microsoft.Network/stable/2019-11-01/expressRouteCircuit.json
> +    "Ipv6CircuitConnectionConfig": {
Added

2020-01-14 20:38 UTC, MikhailTryakhov commented
Hey @amwate, we are close to release our monthly branch. In case you won't solve all the failed jobs/get ARM approval - your PR would be closed around midnight today.

2020-01-16 11:56 UTC, AutorestCI commented
/azp run automation - sdk

2020-01-16 12:02 UTC, v-shhatt reviewed
reviewed.. please fix errors

2020-01-16 12:33 UTC, number213 commented
`network-december-release` has been already merged to meep tight deadlines. If your PR is urgent, please retarget to `master`

2020-01-16 13:15 UTC, AutorestCI commented
/azp run automation - sdk

2020-01-16 13:16 UTC, amwate commented
> `network-december-release` has been already merged to meep tight deadlines. If your PR is urgent, please retarget to `master`

It is not urgent. We can retarget it to network-january-release when it is pulled.

2020-01-16 13:17 UTC, amwate commented
> Hey @amwate, we are close to release our monthly branch. In case you won't solve all the failed jobs/get ARM approval - your PR would be closed around midnight today.

Sure no problem. We can targe this in the next release.

2020-01-17 18:39 UTC, MikhailTryakhov commented
Closing per latest comment

2020-01-17 18:39 UTC, closed without merging