Fixing open id connect provider list secrects operation ID.
Azure/azure-rest-api-specs pull request #8262
Opened 2020-01-30 12:21 UTC by trchen

Fixing casing to align with previous casing for spec generation.

2020-01-30 12:21 UTC, AutorestCI commented
/azp run automation - sdk

2020-01-30 13:53 UTC, AutorestCI commented
/azp run automation - sdk

2020-01-30 19:40 UTC, allenjzhang approved these changes

2020-01-30 19:54 UTC, solankisamir requested changes
please don't merge this, this is a breaking change in the clients.
We need to take it in next api-version

2020-01-30 19:56 UTC, solankisamir approved these changes
My bad, I see this is submitted for the newer api-version, so this is fine.

2020-02-05 06:17 UTC, allenjzhang commented
/azp run

2020-02-05 17:41 UTC, merged