ApiManagement - namedValue secrets and createContracts with required properties
Azure/azure-rest-api-specs pull request #8341
Opened 2020-02-07 23:31 UTC by vfedonkin

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2020-02-07 23:31 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-07 23:32 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-07 23:32 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-07 23:47 UTC, solankisamir commented on specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2019-12-01-preview/definitions.json
> +    "OpenidConnectProviderCreateContract": {
>OpenidConnectProviderCreateContract [](start = 5, length = 35)

maybe we can have `OpenIDConnectProvider` 
[https://auth0.com/docs/protocols/oidc](https://auth0.com/docs/protocols/oidc)

2020-02-07 23:47 UTC, solankisamir commented on specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2019-12-01-preview/definitions.json
> +          "description": "OpenId Connect Provider contract properties."
>OpenId [](start = 26, length = 6)

rename to `OpenID`

2020-02-07 23:47 UTC, solankisamir commented on specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2019-12-01-preview/definitions.json
> +      "description": "OpenId Connect Provider details."
>Connect [](start = 29, length = 7)

create contract

2020-02-07 23:48 UTC, solankisamir commented
>         }

we dont return `clientSecret` in GET... then why have it

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2019-12-01-preview/definitions.json:2956 in 544e8d3. [](commit_id = 544e8d33af37343a60f17b0cf821eb0c8db859e4, deletion_comment = False)

2020-02-07 23:51 UTC, solankisamir commented on specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2019-12-01-preview/definitions.json
> +      "description": "Client or app secret used in IdentityProviders, Aad, OpenID or OAuth."
>Client or app secret used in IdentityProviders, Aad, OpenID or OAuth. [](start = 22, length = 69)

fix description. This is secret value of the NamedValue entity.

2020-02-08 00:02 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-08 00:02 UTC, vfedonkin commented on specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2019-12-01-preview/definitions.json
> +          "description": "OpenId Connect Provider contract properties."
Done

2020-02-08 00:02 UTC, vfedonkin commented on specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2019-12-01-preview/definitions.json
> +      "description": "OpenId Connect Provider details."
Done

2020-02-10 18:58 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-10 19:02 UTC, vfedonkin commented
@solankisamir , ClientSecret removed from Get. Could you please look again?

2020-02-11 22:07 UTC, majastrz commented
>         "clientSecret": {

Can you add x-ms-secret: true to mark it as a secret?

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2019-12-01-preview/definitions.json:2277 in 1535884. [](commit_id = 1535884bbeebf583cc597ecc473f5919d2114440, deletion_comment = False)

2020-02-11 22:08 UTC, majastrz commented
>         "clientSecret": {

Please do this on any property that accepts a secret value.

---
In reply to: [584879568](https://github.com/Azure/azure-rest-api-specs/pull/8341#issuecomment-584879568) [](ancestors = 584879568)

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2019-12-01-preview/definitions.json:2277 in 1535884. [](commit_id = 1535884bbeebf583cc597ecc473f5919d2114440, deletion_comment = False)

2020-02-11 22:10 UTC, majastrz requested changes
Can you add the x-ms-secret: true annotation to designate secret properties. I'll be able to sign off from ARM side after you make the change.

2020-02-12 00:17 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-12 00:31 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-12 01:00 UTC, majastrz approved these changes
Signed off from ARM side.

2020-02-12 01:29 UTC, solankisamir commented
>         }

why does this contract have `value`

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2019-12-01-preview/definitions.json:3713 in 3ffd5be. [](commit_id = 3ffd5bebe959ea88cce759bb3908e5a7db02d251, deletion_comment = False)

2020-02-12 01:30 UTC, solankisamir commented
>               "$ref": "./definitions.json#/definitions/NamedValueContract"

we should have a `createcontract` for this entity too.

---
Refers to: specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2019-12-01-preview/apimnamedvalues.json:221 in 3ffd5be. [](commit_id = 3ffd5bebe959ea88cce759bb3908e5a7db02d251, deletion_comment = False)

2020-02-12 01:46 UTC, vfedonkin commented
@solankisamir , NamedValues don't always contains the secrets. We return 'value' property on GET and LIST in case "isSecret" property == false

2020-02-12 01:56 UTC, solankisamir commented
@vitaliy.fedonkin@gmail.com  I think we should have consistent experience, so that customer doesn't have to think whether GET will return him secrets or not.

---
In reply to: [584976201](https://github.com/Azure/azure-rest-api-specs/pull/8341#issuecomment-584976201) [](ancestors = 584976201)

2020-02-12 02:13 UTC, vfedonkin commented
@solankisamir , you mean removing "isSecret" property and consider all NamedValues as secrets? Yep, I will do it.

2020-02-12 07:03 UTC, erich-wang commented
@solankisamir, @vfedonkin , please let me know when you have agreement and all concerns have been addressed, then I can merge this PR, thanks.

2020-02-12 18:39 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-12 18:40 UTC, vfedonkin commented
@solankisamir , namedValues are changed. Could you please validate?

2020-02-12 22:40 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-12 23:02 UTC, solankisamir commented on specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2019-12-01-preview/examples/ApiManagementUpdateNamedValue.json
>            "secret": true
>true [](start = 20, length = 4)

we wont change the secretvalue from `false` to `true` :)

2020-02-12 23:03 UTC, solankisamir approved these changes
:shipit:

2020-02-12 23:06 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-12 23:41 UTC, vfedonkin commented
@erich-wang , the PR is ready for merge, thank you.

2020-02-13 05:36 UTC, merged