[Hub Generated] Review request for Microsoft.Insights to add version preview/2020-02-10-preview
Azure/azure-rest-api-specs pull request #8383
Opened 2020-02-13 01:38 UTC by aarongas

If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/aarongas/azure-rest-api-specs/dev-applicationinsights-Microsoft.Insights-2020-02-10-preview...master/).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2020-02-13 01:39 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-20 01:16 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-26 19:09 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-02-27 21:50 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-27 22:19 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-27 22:36 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-05 23:33 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-05 23:46 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-06 00:04 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-07 01:00 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-07 01:00 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-07 01:08 UTC, sanjaiganesh requested changes

2020-03-07 01:25 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-07 01:26 UTC, aarongas commented on specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2020-02-10-preview/WebTestResults_API.json
> +          "nextLinkName": null
fixed.

2020-03-07 01:26 UTC, aarongas commented on specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2020-02-10-preview/WebTestResults_API.json
> +    "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/microsoft.insights/webtests/{webTestName}/gettestresultfile": {
fixed

2020-03-07 01:26 UTC, aarongas commented on specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2020-02-10-preview/WebTestResults_API.json
> +        "operationId": "gettestresultfile",
fixed

2020-03-07 01:26 UTC, aarongas commented on specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2020-02-10-preview/WebTestResults_API.json
> +            "value": "webtestresult",
fixed

2020-03-07 01:27 UTC, aarongas commented on specification/applicationinsights/resource-manager/Microsoft.Insights/preview/2020-02-10-preview/WebTestResults_API.json
> +          "type": "string"
I would like to leave as string for now.

2020-03-09 19:02 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-09 19:19 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-09 19:30 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-09 20:34 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-10 00:22 UTC, AutorestCI commented
/azp run automation - sdk

2020-05-04 18:31 UTC, sanjaiganesh approved these changes

2020-05-07 17:18 UTC, zikalino approved these changes

2020-05-07 17:18 UTC, merged