[DevSpaces]: Add hostEndpointType to controller resource document
Azure/azure-rest-api-specs pull request #8387
Opened 2020-02-13 06:13 UTC by rakeshvanga

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2020-02-13 06:13 UTC, AutorestCI commented
You don't have permission to trigger SDK Automation.
Please add yourself to ***Azure*** group from opensource portal if you are MSFT employee,
or please ask reviewer to add comment *** /openapibot sdkautomation ***.
Please ask tih@microsoft.com (or NullMDR in github) for additional help.

2020-02-13 19:05 UTC, sanar-microsoft commented on specification/devspaces/resource-manager/Microsoft.DevSpaces/stable/2019-04-01/devspaces.json
> +          "readOnly": true,
This is not supposed to be readonly, right?

2020-02-13 19:17 UTC, sanar-microsoft approved these changes
LGTM

2020-02-14 03:17 UTC, NullMDR commented
/azp run automation - sdk

2020-02-14 23:09 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-14 23:09 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-14 23:09 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-14 23:09 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-14 23:14 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-14 23:14 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-14 23:14 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-14 23:14 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-21 00:33 UTC, rakeshvanga commented
@NullMDR, can you re-run the azure pipeline. it doesn't seem to be related to my changes.

2020-02-21 02:43 UTC, NullMDR commented
/azp run automation - sdk

2020-02-21 03:03 UTC, NullMDR commented
@rakeshvanga Back to green now

2020-02-21 20:08 UTC, rakeshvanga commented
@NullMDR, Thanks for re-running the pipeline. I would wait for the ARM to approve and merge the changes.

2020-02-26 19:08 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-03-02 18:42 UTC, rakeshvanga commented
Ping...
Can some one look into merging this change?

2020-03-03 22:22 UTC, pilor commented on specification/devspaces/resource-manager/Microsoft.DevSpaces/stable/2019-04-01/devspaces.json
> +        "hostEndpointType": {
>"hostEndpointType" [](start = 8, length = 18)

An addition of a mutable property should involve a new api-version.  See the "breaking changes" doc here: [https://armwiki.azurewebsites.net/api_contracts/Intro.html](https://armwiki.azurewebsites.net/api_contracts/Intro.html)

2020-03-03 22:23 UTC, pilor requested changes
1 comment

2020-03-04 02:08 UTC, NullMDR commented
/azp run

2020-03-09 16:39 UTC, rakeshvanga commented
Would update the version for arm spec in a different PR.

2020-03-09 16:39 UTC, closed without merging