[Hub Generated] Review request for Microsoft.AppPlatform to add version preview/2019-05-01-preview
Azure/azure-rest-api-specs pull request #8550
Opened 2020-02-28 00:32 UTC by metacpp

If you are a MSFT employee you can view your [work branch via this link](https://portal.azure-devex-tools.com/branch/metacpp/azure-rest-api-specs/steeltoe-appplatform-2019-05-01-preview...master/).

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/azure-rest-api-specs#basics) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.

2020-02-28 00:32 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-28 00:33 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-28 00:33 UTC, AutorestCI commented
/azp run automation - sdk

2020-02-28 00:35 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-02-29 12:40 UTC, bowen5 requested changes

2020-02-29 12:40 UTC, bowen5 commented on specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2019-05-01-preview/appplatform.json
> +        "description": "You can directly pass \"{value[i].value}\" attribute (in the response) to all deployment CRUD operations.",
Suppose should be "deployment creation operations" instead of "CRUD"? I think we don't support update runtime version today.

2020-02-29 12:40 UTC, bowen5 commented on specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2019-05-01-preview/appplatform.json
> +            "Deleting"
Are they related by your change? If not would you please undo? Let me check how are they introduced.

2020-03-10 21:00 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-10 21:02 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-10 21:06 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-10 21:10 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-10 21:12 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-20 06:52 UTC, ArcturusZhang commented
Please let me know this is ready to merge.

2020-05-07 08:26 UTC, ArcturusZhang commented
Hi @metacpp any updates?

2020-05-21 07:42 UTC, ArcturusZhang commented
Hi @metacpp do we have any update?

2020-07-08 03:07 UTC, ArcturusZhang commented
Closing this PR since no response for quite a long time. 
@metacpp please feel free to reopen when you get back, thank you

2020-07-08 19:07 UTC, metacpp commented
@ArcturusZhang : please don't delete the remote branch, thanks.

2020-07-09 05:19 UTC, ArcturusZhang commented
> @ArcturusZhang : please don't delete the remote branch, thanks.

No problem and since it is in your fork, I actually do not have the permission to delete

2020-08-21 05:38 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-21 05:38 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-21 05:42 UTC, metacpp commented
@ArcturusZhang : can you help on the PR ?

2020-08-21 05:54 UTC, AutorestCI commented
/azp run automation - sdk

2020-08-24 12:36 UTC, bowen5 approved these changes

2020-08-25 02:12 UTC, merged