HybridDataManagere - adding API version 2019-06-01 and examples
Azure/azure-rest-api-specs pull request #8676
Opened 2020-03-11 10:39 UTC by prtank

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2020-03-11 10:54 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-11 11:04 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-03-12 04:18 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-19 18:13 UTC, markcowl commented
@prtank  per the checklist above, this PR needs arm feedback.  Adding appropriate label

2020-04-02 00:18 UTC, majastrz approved these changes
Diffing with 2016-06-01 shows only a small change. When adding a new API, please make the first commit an unmodified copy of the previous API version at the folder of the new API version. This makes reviews very easy because then we simply diff first commit with last and get the actual delta.

Otherwise, changes look good from ARM side. Signing off...

2020-04-03 01:09 UTC, markcowl requested changes
A few minor changes in comments, otherwise, LGTM

2020-04-03 01:09 UTC, markcowl commented on specification/hybriddatamanager/resource-manager/Microsoft.HybridData/stable/2019-06-01/hybriddata.json
> +            "description": "The data store/repository object.",
Completed request for Create/Update.

2020-04-03 01:09 UTC, markcowl commented on specification/hybriddatamanager/resource-manager/Microsoft.HybridData/stable/2019-06-01/hybriddata.json
> +            "description": "The list of job definitions in that resource.OK",
```suggestion
            "description": "The list of job definitions in the resource.",
```

2020-04-03 17:09 UTC, AutorestCI commented
/azp run automation - sdk

2020-04-03 17:19 UTC, AutorestCI commented
/azp run automation - sdk

2020-04-03 19:24 UTC, markcowl approved these changes

2020-04-03 19:28 UTC, merged