Adding PublicNetworkAccess, InfrastructureEncryption as Server Create property for PostgreSQL/MySQL/MariaDB
Azure/azure-rest-api-specs pull request #8709
Opened 2020-03-13 22:51 UTC by ramnov

Adding PublicNetworkAccess, InfrastructureEncryption as Server Create property for PostgreSQL/MySQL/MariaDB

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2020-03-13 23:14 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-03-16 02:10 UTC, lirenhe approved these changes

2020-03-16 17:42 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-16 18:41 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-17 02:38 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-17 02:39 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-17 02:39 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-17 02:46 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-17 20:05 UTC, anthony-c-martin commented on specification/mariadb/resource-manager/Microsoft.DBforMariaDB/stable/2018-06-01/mariadb.json
> +        "publicNetworkAccess": {
This is typically regarded as a breaking change to a GA API. Why not publish a new API version?

2020-03-17 20:05 UTC, anthony-c-martin commented on specification/mariadb/resource-manager/Microsoft.DBforMariaDB/stable/2018-06-01/mariadb.json
> +            "publicNetworkAccess": {
This is typically regarded as a breaking change to a GA API. Why not publish a new API version?

2020-03-17 20:06 UTC, anthony-c-martin commented on specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2017-12-01/mysql.json
> +        "infrastructureEncryption": {
This looks again like a breaking change.

2020-03-17 20:06 UTC, anthony-c-martin commented on specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2017-12-01/mysql.json
> +        "identity": {
Possible breaking change.

2020-03-17 20:06 UTC, anthony-c-martin commented on specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2017-12-01/mysql.json
> +        "identity": {
Possible breaking change.

2020-03-17 20:06 UTC, anthony-c-martin commented on specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2017-12-01/mysql.json
> +            "publicNetworkAccess": {
Possible breaking change.

2020-03-17 20:06 UTC, anthony-c-martin requested changes
There are multiple breaking changes in this PR. What is the motivation?

2020-03-18 18:42 UTC, anthony-c-martin commented
Discussed offline - these changes have already been partially signed off on, and we're adding properties that were previously missed.

2020-03-18 18:54 UTC, anthony-c-martin approved these changes

2020-03-18 23:54 UTC, merged