Service fabric add APIs
Azure/azure-rest-api-specs pull request #875
Opened 2017-01-20 19:36 UTC by msjeffreychen

2017-01-23 20:32 UTC, amarzavery requested changes
please provide good descriptions for the operation and model definitions. All the model properties do not have descriptions at all. If the spec, does not have meaningful and accurate descriptions, the PR will not be accepted. Moving forward this is a must. Customer facing rest api docs are generated from the spec. Hence good descriptions are very important.

2017-01-23 20:32 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +            "description": "The upgrade of the start cluster",
Parameters supplied to start upgrading the cluster.

2017-01-23 20:32 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +            "description": "The description of the update cluster upgrade",
same as above. Please update the description everywhere accordingly.

2017-01-23 20:32 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +              "type": "string"
Is the entire response body just a string? Can you provide an example in the description about how the responseBody will look like?

2017-01-23 20:32 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +            "description": "The force remove",
Please provide better descriptions. Automated descriptions dont help the customer. REST API documentation is autogenerated from the spec and published to docs.microsoft.com website where every one can see.

2017-01-23 20:32 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +        "CodeFilePath": {
Are you sure that the properties on the wire are actually PascalCase? Usually the convention is camelCase, hence wanted to confirm.

2017-01-23 20:32 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +        "CodeFilePath": {
missing description for properties

2017-01-23 20:32 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +          "type": "string"
do you accept relative or absolute file paths or both? Can you please indicate that in the description?

2017-01-23 20:32 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +        "CodeVersion": {
should both the properties of this object be enums?

2017-01-23 20:32 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +        "ConfigVersion": {
missing description for model properties

2017-01-23 20:32 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +        "MaxPercentDeltaUnhealthyNodes": {
any min/max value constraints? Since the property name has percent in it, i assume 0-100. Can you please update the constraints?

2017-01-23 20:32 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +        "UpgradeKind": {
enum?

2017-01-23 21:05 UTC, msjeffreychen commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +              "type": "string"
There is no content in the response, except an "Ok". To get details of an upgrade, one will need to call UpgradeProgresses_Get.

2017-01-23 21:16 UTC, msjeffreychen commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +        "CodeFilePath": {
Yes, it is correct. We have used this style in all other APIs body.

2017-01-23 21:32 UTC, msjeffreychen commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +        "CodeVersion": {
It will be string, it looks like 1.0.0

2017-01-23 22:23 UTC, msjeffreychen commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +        "UpgradeKind": {
The field is a reserved field for future use. It is not being used today.

2017-01-27 19:22 UTC, msjeffreychen commented
Updated.

2017-01-31 18:46 UTC, msjeffreychen commented
Ping.

2017-02-01 19:24 UTC, amarzavery approved these changes

2017-02-01 19:27 UTC, amarzavery requested changes
missing descriptions for model properties. Please update them everywhere in the spec. We wont repeat this all the time.

2017-02-01 19:27 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +        "ConsiderWarningAsError": {
missing descriptions for model properties.

2017-02-01 19:27 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +        "ConfigVersion": {
missing descriptions for model properties.

2017-02-01 19:27 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +        "RollingUpgradeMode": {
missing descriptions for model properties.

2017-02-01 19:27 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +        "RollingUpgradeMode": {
missing descriptions for model properties.

2017-02-01 19:27 UTC, amarzavery commented on servicefabric/2016-01-28/swagger/servicefabric.json
> +      "properties": {
missing descriptions for model properties.

2017-02-09 18:33 UTC, gladiacxtylish commented
Updated.

2017-02-09 22:07 UTC, msjeffreychen commented
Updated

2017-02-16 19:50 UTC, msjeffreychen commented
Ping.

2017-02-17 05:37 UTC, amarzavery commented
@msjeffreychen - Do you see the general comment made about missing description in the swagger spec everywhere. No point pinging until the comments are not resolved.

2017-02-17 06:05 UTC, msjeffreychen commented
@amarzavery I have already added model comments, if you check line 5215.

2017-02-17 17:20 UTC, amarzavery approved these changes

2017-02-17 17:20 UTC, merged

2017-02-17 17:24 UTC, AutorestCI commented
No modification for Python

2017-02-17 17:24 UTC, AutorestCI commented
No modification for Ruby

2017-02-17 17:24 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-node.svg?branch=RestAPI-PR875)](https://travis-ci.org/AutorestCI/azure-sdk-for-node) https://github.com/Azure/azure-sdk-for-node/pull/2067