[HDInsight] Add two new APIs: listhosts and restart node
Azure/azure-rest-api-specs pull request #8794
Opened 2020-03-21 07:19 UTC by aim-for-better

Add two new APIs: listhosts and restart node

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2020-03-21 07:19 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-21 07:31 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-21 07:40 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-03-23 03:28 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-23 03:54 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-23 06:21 UTC, raych1 commented
/azp run

2020-03-23 06:56 UTC, raych1 commented
@aim-for-better , here's the detail log for model validation failures. In the example file of `RestartVirtualMachinesOperation.json`, the parameter of `hosts` should be array of string instead of array of object.

```
inner:
             [ { code: 'INVALID_TYPE',
                 params: [ 'string', 'object' ],
                 message: 'Expected type string but found type object',
                 path: [ 1 ],
                 title:
                  '{"path":["definitions","RestartHostsParameters","items"],"position":{"line":158,"column":16},"url":"D:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\hdinsight\\\\resource-manager\\\\Microsoft.HDInsight\\\\stable\\\\2018-06-01-preview\\\\virtualMachines.json","directives":{}}' },
               { code: 'INVALID_TYPE',
                 params: [ 'null', 'object' ],
                 message: 'Expected type null but found type object',
                 path: [ 1 ],
                 title:
                  '{"path":["definitions","RestartHostsParameters","items"],"position":{"line":158,"column":16},"url":"D:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\hdinsight\\\\resource-manager\\\\Microsoft.HDInsight\\\\stable\\\\2018-06-01-preview\\\\virtualMachines.json","directives":{}}' } ] }

2020-03-23 07:55 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-23 10:02 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-24 18:54 UTC, pilor commented on specification/hdinsight/resource-manager/Microsoft.HDInsight/stable/2018-06-01-preview/virtualMachines.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HDInsight/clusters/{clusterName}/listHosts": {
>listHosts [](start = 125, length = 9)

this should be a POST call

2020-03-24 18:56 UTC, pilor commented on specification/hdinsight/resource-manager/Microsoft.HDInsight/stable/2018-06-01-preview/virtualMachines.json
> +      "description": "The list of roles where script will be executed."
>The list of roles where script will be executed [](start = 22, length = 47)

is this description accurate?

2020-03-24 18:56 UTC, pilor requested changes
:clock1:

2020-03-25 07:53 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-25 07:54 UTC, aim-for-better commented on specification/hdinsight/resource-manager/Microsoft.HDInsight/stable/2018-06-01-preview/virtualMachines.json
> +      "description": "The list of roles where script will be executed."
> > The list of roles where script will be executed [](start = 22, length = 47)
> 
> is this description accurate?

Updated

2020-03-25 07:54 UTC, aim-for-better commented on specification/hdinsight/resource-manager/Microsoft.HDInsight/stable/2018-06-01-preview/virtualMachines.json
> +      "description": "The list of roles where script will be executed."
> > The list of roles where script will be executed [](start = 22, length = 47)
> 
> is this description accurate?

Updated

2020-03-25 07:55 UTC, aim-for-better commented on specification/hdinsight/resource-manager/Microsoft.HDInsight/stable/2018-06-01-preview/virtualMachines.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HDInsight/clusters/{clusterName}/listHosts": {
> > listHosts [](start = 125, length = 9)
> 
> this should be a POST call

waiting me to check with backend team

2020-03-28 07:13 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-28 07:14 UTC, aim-for-better commented on specification/hdinsight/resource-manager/Microsoft.HDInsight/stable/2018-06-01-preview/virtualMachines.json
> +    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.HDInsight/clusters/{clusterName}/listHosts": {
> > listHosts [](start = 125, length = 9)
> 
> this should be a POST call

Updated to post

2020-03-30 17:59 UTC, pilor approved these changes

2020-04-29 07:21 UTC, aim-for-better commented
> RestartHostsP

fixed.

> @aim-for-better , here's the detail log for model validation failures. In the example file of `RestartVirtualMachinesOperation.json`, the parameter of `hosts` should be array of string instead of array of object.
> 
> ```
> inner:
>              [ { code: 'INVALID_TYPE',
>                  params: [ 'string', 'object' ],
>                  message: 'Expected type string but found type object',
>                  path: [ 1 ],
>                  title:
>                   '{"path":["definitions","RestartHostsParameters","items"],"position":{"line":158,"column":16},"url":"D:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\hdinsight\\\\resource-manager\\\\Microsoft.HDInsight\\\\stable\\\\2018-06-01-preview\\\\virtualMachines.json","directives":{}}' },
>                { code: 'INVALID_TYPE',
>                  params: [ 'null', 'object' ],
>                  message: 'Expected type null but found type object',
>                  path: [ 1 ],
>                  title:
>                   '{"path":["definitions","RestartHostsParameters","items"],"position":{"line":158,"column":16},"url":"D:\\\\git\\\\github\\\\azure-rest-api-specs\\\\specification\\\\hdinsight\\\\resource-manager\\\\Microsoft.HDInsight\\\\stable\\\\2018-06-01-preview\\\\virtualMachines.json","directives":{}}' } ] }
> ```

fixed. Now all ci checks have passed

2020-04-29 07:27 UTC, merged