SLB changes for new backend pool addresses format.
Azure/azure-rest-api-specs pull request #8826
Opened 2020-03-24 21:48 UTC by ninzavivek

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2020-03-24 21:48 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-24 21:54 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-03-25 15:32 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-25 16:21 UTC, anton-evseev requested changes
LGTM except a few nitpicks

2020-03-25 16:21 UTC, number213 commented on specification/network/resource-manager/Microsoft.Network/stable/2020-03-01/loadBalancer.json
> +          "LBBackendAddressPoolListWithBackendAddressesPoolType": {
Please make this a human-readable description

2020-03-25 16:21 UTC, number213 commented on specification/network/resource-manager/Microsoft.Network/stable/2020-03-01/loadBalancer.json
> +      "description": "Properties of the loadbalancer backend addresses."
```suggestion
      "description": "Properties of the load balancer backend addresses."
```

2020-03-25 16:21 UTC, number213 commented on specification/network/resource-manager/Microsoft.Network/stable/2020-03-01/loadBalancer.json
> +          "description": "IP Address belonging to the virtual network referenced above.",
```suggestion
          "description": "IP Address belonging to the referenced virtual network.",
```

2020-03-25 16:21 UTC, number213 commented on specification/network/resource-manager/Microsoft.Network/stable/2020-03-01/loadBalancer.json
> +      "description": "Loadbalancer backend addresses."
```suggestion
      "description": "Load balancer backend addresses."
```

2020-03-25 16:38 UTC, AutorestCI commented
/azp run automation - sdk

2020-03-26 07:13 UTC, lirenhe commented
@ninzavivek, I saw this is still in draft mode, please let us know when it is ready for SDK/ARM review.

2020-03-26 12:25 UTC, AutorestCI commented
/azp run automation - sdk

2020-04-01 17:46 UTC, AutorestCI commented
/azp run automation - sdk

2020-04-01 18:05 UTC, AutorestCI commented
/azp run automation - sdk

2020-04-01 18:24 UTC, AutorestCI commented
/azp run automation - sdk

2020-04-01 18:43 UTC, AutorestCI commented
/azp run automation - sdk

2020-04-09 10:09 UTC, number213 commented
Closed in favor of https://github.com/Azure/azure-rest-api-specs/pull/8993

2020-04-09 10:09 UTC, closed without merging