Microsoft.Commerce: Ratecard updates
Azure/azure-rest-api-specs pull request #884
Opened 2017-01-27 06:34 UTC by pargall

- Moved Meter Region and Tags to MeterInfo
- Updated Offer Terms to acurately repersent the response

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [ x] The title of the PR is clear and informative.
- [ x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [x ] If applicable, the PR references the bug/issue that it fixes.
- [x ] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ x] My spec meets the review criteria:
  - [x ] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x ] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [x ] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

2017-01-27 06:34 UTC, azurecla commented
Hi __@pargall__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (pearga). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2017-02-02 07:48 UTC, sarangan12 commented
@pargall 

1. Line 160: Under UsageSample, the format of the SubscriptionId is marked as uuid. Is it really a uuid? Could you please provide justification for the usage of uuid here?

2. In the consumes and produces section, you have marked both application/json and text/json. Why? Wouldn't application/json be sufficient?

2017-02-02 18:41 UTC, sarangan12 commented
@pargall 

Definitions MonetaryCredit-MonetaryCommitment-RecurringCharge, they are not used anywhere. Why are they defined?

2017-02-03 20:59 UTC, pargall commented
Regarding the MonetaryCredit, MonetaryCommitment and, RecurringCharge. These can all be included in the OfferTerms of the ResourceRateCardInfo.  Let me know if there is a better way to represent that in swagger.

2017-02-03 21:03 UTC, pargall commented on arm-commerce/2015-06-01-preview/swagger/commerce.json
> +            "format": "uuid"
This is a list of Meter ids for which the monetary credit can not be applied against, these will be correlated with the MeterId in the MeterInfo object which is also a uuid.

2017-02-03 21:17 UTC, pargall commented
1. Re Line 160,  That section is owned by a separate team, so I'm not sure about that section. As far as I know all Azure Subscriptions ids are guids.

2. Regarding, The produces and consumes.  I am not sure the history behind that section, presumably application/json would be sufficient. Since the api supports both MIME types is there any issue leaving it as is?

2017-02-06 19:32 UTC, amarzavery requested changes

2017-02-06 19:32 UTC, amarzavery commented on arm-commerce/2015-06-01-preview/swagger/commerce.json
> +            "required": true,
Is the api-version "2015-06-01-preview" still the same? When are you guys planning to move out of preview?

2017-02-06 19:32 UTC, amarzavery commented on arm-commerce/2015-06-01-preview/swagger/commerce.json
> +          ]
Please use the extension ["x-ms-enum"](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-extensions.md#x-ms-enum).

2017-02-06 22:29 UTC, azurecla commented
Hi __@pargall__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (pearga). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

2017-02-06 23:19 UTC, amarzavery commented
Hi @pargall - Can you please provide examples for request and response using the extension x-ms-examples. This will help us validate the examples against the swagger spec and it will also form the basis for customer facing REST API documentation on docs.microsoft.com website.

You can more info about the extension and an example swagger spec over [here](https://github.com/Azure/adx-documentation-pr/blob/master/tools/tools.md#swagger-model-validation).

2017-02-08 00:10 UTC, pargall commented on arm-commerce/2015-06-01-preview/swagger/commerce.json
> +            "required": true,
Yes, this is describing that version of the api.  We do have a new version out,  but I wanted to correct the existing spec before I created the new one.

There is still some churn around the UsageAggregates API that needs to be worked out prior to leaving preview.

2017-02-13 17:31 UTC, pargall commented
@amarzavery I added the basic case to the x-ms-examples

2017-02-13 17:51 UTC, amarzavery approved these changes

2017-02-13 17:51 UTC, merged

2017-02-13 17:55 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby.svg?branch=RestAPI-PR884)](https://travis-ci.org/AutorestCI/azure-sdk-for-ruby) https://github.com/Azure/azure-sdk-for-ruby/pull/687

2017-02-13 17:55 UTC, AutorestCI commented
[![Build Status](https://travis-ci.org/AutorestCI/azure-sdk-for-python.svg?branch=RestAPI-PR884)](https://travis-ci.org/AutorestCI/azure-sdk-for-python) https://github.com/Azure/azure-sdk-for-python/pull/992

2017-02-13 17:55 UTC, AutorestCI commented
No modification for NodeJS