Update NH swagger to make hub a sub resource
Azure/azure-rest-api-specs pull request #8922
Opened 2020-04-02 14:45 UTC by varvusc

Regarding bug: https://dev.azure.com/msmobilecenter/NotificationHub/_workitems/edit/78678
Have moved Sku parameter from "Resource" to "NamespaceResource".

2020-04-02 14:45 UTC, AutorestCI commented
/azp run automation - sdk

2020-04-02 14:47 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-04-03 07:31 UTC, AutorestCI commented
/azp run automation - sdk

2020-04-03 07:31 UTC, AutorestCI commented
/azp run automation - sdk

2020-04-03 16:12 UTC, stankovski commented
@marstr  @markcowl can you please review the PR and advise what should be done about Python breaking change? Is is an FYI or do we need to do anything in this PR?

2020-04-03 16:44 UTC, marstr requested changes
Instead of using this PR to restructure which parameters are sent over the wire by the SDKs, we should use it to update the documentation to say that SKU will be ignored when applied to Hubs.

2020-04-03 16:45 UTC, marstr commented
@stankovski, I just took a look and this is a real breaking change for most (all?) of the SDK, not just Python. While this is a bug in our Swagger, the fix would be more painful than the problem.

We should remember this when we're considering adding a new API Version in the future.

2020-04-03 16:52 UTC, closed without merging