[Microsoft.ApiManagement][2019-12-01] Gateway hostname configuration protocol settings
Azure/azure-rest-api-specs pull request #8938
Opened 2020-04-03 21:38 UTC by maksimkim

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2020-04-03 21:38 UTC, AutorestCI commented
/azp run automation - sdk

2020-04-03 21:38 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-04-03 21:42 UTC, solankisamir approved these changes

2020-04-07 19:22 UTC, KrisBash requested changes
Please see one comment

2020-04-07 19:22 UTC, KrisBash commented on specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2019-12-01/definitions.json
> +        },
Adding these within an API version can cause undesired effects as customers use mixed SDK versions where only latest can deserialize these properties. Additionally, Azure Policy becomes unpredictable if properties customers use in policy evaluations are added within an API version. Can they be added in a new version?

2020-07-27 23:50 UTC, ravbhatnagar commented
@solankisamir - please let us know if this PR is still relevant and re-add the ARM review label. removing from now due to no activity for several months.

2020-07-29 17:45 UTC, closed without merging

2020-07-29 17:45 UTC, AutorestCI commented
/azp run automation - sdk

2020-07-29 18:28 UTC, solankisamir commented
@ravbhatnagar we have put the changes into new PR https://github.com/Azure/azure-rest-api-specs/pull/10292