add IgnoreResourceCheck query parameter to subscriptions to be cancelled
Azure/azure-rest-api-specs pull request #9043
Opened 2020-04-13 22:35 UTC by szaher

### Changes:
add IgnoreResourceCheck query parameter to subscriptions to be cancelled.
Allow sdk users to cancel azure subscriptions even if subscription has resources deployed in it.

Issue: #10814 

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [-] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [-] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [-] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).
Signed-off-by: Saad Zaher <eng.szaher@gmail.com>

2020-04-13 22:35 UTC, AutorestCI commented
You don't have permission to trigger SDK Automation.
Please add yourself to ***Azure*** group from opensource portal if you are MSFT employee,
or please ask reviewer to add comment *** /openapibot sdkautomation ***.
Please ask tih@microsoft.com (or NullMDR in github) for additional help.

2020-04-13 22:35 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=9043) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=9043) before we can accept your contribution.<br/><br/>:x: szaher [sign now](https://cla.opensource.microsoft.com/Azure/azure-rest-api-specs?pullRequest=9043)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-rest-api-specs?pullRequest=9043) it.</sub>

2020-04-13 23:10 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-04-16 15:31 UTC, szaher commented
@markcowl Do I need to do anything else?

2020-06-15 23:42 UTC, markcowl approved these changes

2020-06-15 23:43 UTC, markcowl commented
/azp run

2020-06-15 23:55 UTC, markcowl commented
/azp run

2020-06-16 00:33 UTC, markcowl requested changes

2020-06-16 00:33 UTC, markcowl commented on specification/subscription/resource-manager/Microsoft.Subscription/preview/2019-03-01-preview/subscriptions.json
> +      "description": "Ignore existing resources in the subscription to be cancelled."
need x-ms-parameter-location (as in parameter below), per lintDiff error

2020-06-16 00:33 UTC, markcowl commented on specification/subscription/resource-manager/Microsoft.Subscription/preview/2019-10-01-preview/subscriptions.json
> +      "required": false,
need x-ms-parameter-loaction tag, per LintDiff error

2020-06-16 00:33 UTC, markcowl commented on specification/subscription/resource-manager/Microsoft.Subscription/stable/2020-01-01/subscriptions.json
> +      "description": "Ignore existing resources in the subscription to be cancelled."
same

2020-06-16 00:34 UTC, markcowl commented
@szaher also need to fix model validation error

2020-07-22 22:12 UTC, markcowl commented
@szaher Closing for lack of response.  If you would still like to merge this PR, please re-open

2020-07-22 22:12 UTC, closed without merging