Adding ExtensionsTimeBudget to new Api Version
Azure/azure-rest-api-specs pull request #9319
Opened 2020-05-04 19:13 UTC by kamusta-msft

Squashed commits:

[f0151eb78] updated with extensionsTimeBudget

### Latest improvements:
<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i><br>
### Contribution checklist:
- [ ] I have reviewed the [documentation](https://github.com/Azure/adx-documentation-pr/wiki/Overall-basic-flow) for the workflow.
- [ ] [Validation tools](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-checklist.md#validation-tools-for-swagger-checklist) were run on swagger spec(s) and have all been fixed in this PR.
- [ ] The [OpenAPI Hub](https://aka.ms/openapiportal) was used for checking validation status and next steps.
### ARM API Review Checklist
- [ ] Service team MUST add the "WaitForARMFeedback" label if the management plane API changes fall into one of the below categories. 
- adding/removing APIs.
- adding/removing properties.
- adding/removing API-version. 
- adding a new service in Azure.

Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.
- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://armwiki.azurewebsites.net/rp_onboarding/ResourceProviderOnboardingAPIRevieworkflow.html).

2020-05-04 19:14 UTC, AutorestCI commented
/azp run automation - sdk

2020-05-04 19:31 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-05-05 16:48 UTC, AutorestCI commented
/azp run automation - sdk

2020-05-06 00:09 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/examples/CreateAScaleSetWithExtensionsTimeBudget.json
> +﻿{
You need add the link of this example file to compute.json file similar to below:

"$ref": "./examples/CreateAnAvailabilitySet.json"

2020-05-06 00:10 UTC, hyonholee commented on specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/examples/CreateAVmInWithExtensionsTimeBudget.json
> +﻿{
You need add the link of this example file to compute.json file similar to below:
"$ref": "./examples/CreateAnAvailabilitySet

2020-05-06 00:11 UTC, hyonholee requested changes
Please add the links of new example files to compute.json.

2020-05-11 02:48 UTC, ArcturusZhang commented
Since this PR is not targeting master branch but a dev branch of compute (I assume), I will then merge this PR as long as @hyonholee approves.

2020-05-12 19:00 UTC, AutorestCI commented
/azp run automation - sdk

2020-05-18 02:26 UTC, ArcturusZhang commented
Hi @kamusta-msft @hyonholee any updates?

2020-05-19 18:37 UTC, AutorestCI commented
/azp run automation - sdk

2020-05-19 19:29 UTC, AutorestCI commented
/azp run automation - sdk

2020-05-19 21:16 UTC, AutorestCI commented
/azp run automation - sdk

2020-05-19 21:43 UTC, AutorestCI commented
/azp run automation - sdk

2020-05-28 17:42 UTC, hyonholee commented
Please resolve the conflict

2020-05-28 21:33 UTC, AutorestCI commented
/azp run automation - sdk

2020-06-01 23:17 UTC, AutorestCI commented
/azp run automation - sdk

2020-06-03 18:56 UTC, hyonholee commented
@ravbhatnagar Could you review this PR?

2020-06-05 21:53 UTC, pilor approved these changes
:shipit:

2020-06-08 02:25 UTC, ArcturusZhang commented
Hi @hyonholee could you please approve? I would merge this once you approved this, thanks!

2020-06-08 02:25 UTC, ArcturusZhang approved these changes

2020-06-08 16:29 UTC, Sandido commented on specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/examples/CreateAVmInWithExtensionsTimeBudget.json
> +{
Since you're adding this file, the name CreateAVmInWithExtensionsTimeBudget seems odd. Unless this is a standard naming schema, remove 'In'.

2020-06-08 16:38 UTC, Sandido requested changes
See my comment about removing the 'In' string from the file name.

2020-06-09 22:24 UTC, AutorestCI commented
/azp run automation - sdk

2020-06-10 01:59 UTC, hyonholee approved these changes

2020-06-10 02:50 UTC, ArcturusZhang commented
/azp run

2020-06-10 04:51 UTC, merged

2020-06-12 15:09 UTC, Sandido commented
@kamusta-msft , now that this Swagger PR has been merged, you can create a PR in the relevant SDK repository with the autogenerated SDK and at least 1 test added. Please reach out to me if you're not sure how to proceed.