Delete LBBackendAddressPoolWithBackendAddressesPutWithNICIPConfigurat…
Azure/azure-rest-api-specs pull request #9719
Opened 2020-06-04 20:39 UTC by erichrt

…ion.json

We do not support NIC based PUTs for this REST call

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

2020-06-04 20:39 UTC, AutorestCI commented
/azp run automation - sdk

2020-06-04 20:40 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-06-04 20:41 UTC, erichrt commented
@anavinahar, @ninzavivek as FYI

2020-06-05 02:00 UTC, MyronFanQiu commented
@erichrt Hi. We cannot just delete one example without changing swagger definition.

2020-06-08 20:21 UTC, erichrt commented
Hi @MyronFanQiu we need to delete this example as the PUT operation does not support NIC IP configurations but the schema of the Backend Address Pool does thus we are not updating the spec. I will set up a short 15 minute sync for us to discuss.

2020-06-09 01:12 UTC, AutorestCI commented
/azp run automation - sdk

2020-06-09 01:12 UTC, erichrt commented
@MyronFanQiu updated with latest commit

2020-06-09 02:39 UTC, MyronFanQiu commented
@erichrt well. emmm. Looks like we cannot directly remove one example. You may need to fix this one with other changes together to pass the CI.

2020-06-09 06:08 UTC, gmainar approved these changes

2020-06-09 06:10 UTC, gmainar requested changes

2020-06-09 06:10 UTC, gmainar commented on specification/network/resource-manager/Microsoft.Network/stable/2020-04-01/loadBalancer.json
>            },
we may need to remove this comma

2020-06-10 12:20 UTC, closed without merging