[T2] keyvault - enable t2 generation
Azure/azure-rest-api-specs pull request #9750
Opened 2020-06-07 06:51 UTC by zikalino

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

2020-06-07 06:51 UTC, AutorestCI commented
/azp run automation - sdk

2020-06-07 06:54 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-06-08 17:36 UTC, heaths requested changes
I'm confused by this change. We have track 2 code in azure-sdk-for-python currently, which is where the track 2 Key Vault is developed and from where it is built and published. What is this other repo? It doesn't appear to even exist.

/cc @chlowell

2020-06-09 04:49 UTC, zikalino commented
@heaths from now on track1 mgmt packages will be published via release/v3 branch, while track2 to master branch.
this pr enables automation for track2

2020-06-09 06:20 UTC, heaths approved these changes
Approving to unblock and assuming this is working authoring, but I'm still confused since there's no actual azure-sdk-for-python-track2 repo. Is that just some moniker - an alias of sorts configured elsewhere?

2020-06-09 08:58 UTC, fengzhou-msft approved these changes

2020-06-11 03:25 UTC, merged