updated confluent readme for input files
Azure/azure-rest-api-specs pull request #9835
Opened 2020-06-13 20:41 UTC by ankisho

<i>MSFT employees can try out our new experience at <b>[OpenAPI Hub](https://aka.ms/openapiportal) </b> - one location for using our validation tools and finding your workflow. 
</i>

### Contribution checklist:
- [ ] I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow.
- [ ] [Validation tools](https://aka.ms/swaggertools) were run on swagger spec(s) and have all been fixed in this PR. [How to fix?](https://aka.ms/ci-fix)

If any further question about AME onboarding or validation tools, please view the [FAQ](https://aka.ms/faqinprreview).

### ARM API Review Checklist
- [ ] Service team MUST add the "**WaitForARMFeedback**" label if the management plane API changes fall into one of the below categories. 
  - adding/removing APIs.
  - adding/removing properties.
  - adding/removing API-version. 
  - adding a new service in Azure.

<i>Failure to comply may result in delays for manifest application. Note this does not apply to data plane APIs.</i>

- [ ] If you are blocked on ARM review and want to get the PR merged urgently, please get the ARM oncall for reviews (RP Manifest Approvers team under Azure Resource Manager service) from IcM and reach out to them. 
Please follow the link to find more details on [API review process](https://aka.ms/SwaggerPRReview).

2020-06-13 20:41 UTC, AutorestCI commented
/azp run automation - sdk

2020-06-13 20:56 UTC, azuresdkci commented
Can one of the admins verify this patch?

2020-06-15 16:24 UTC, AutorestCI commented
/azp run automation - sdk

2020-06-16 12:46 UTC, ankisho commented
@erich-wang : Could you please review this PR ?

2020-06-17 07:25 UTC, erich-wang commented
@ankisho , the lable `WaitForARMFeedbak` was added to ask arm review board to review. Adding pattern to existing parameter is kind of break change for customers, has the change been deployed to production?

2020-06-17 11:15 UTC, AutorestCI commented
/azp run automation - sdk

2020-06-17 11:20 UTC, ankisho commented
> @ankisho , the lable `WaitForARMFeedbak` was added to ask arm review board to review. Adding pattern to existing parameter is kind of break change for customers, has the change been deployed to production?

This PR has changes related to removing phone number property. This is breaking change.
right now, this RP is on production but it is not come under private preview yet. This RP is not being used by any of azure end-user. I'm doing internal testing using this RP and Private preview is scheduled for 31st July 2020. I've one more PR with similar changeswith RPaaS team: [https://github.com/Azure/azure-rest-api-specs-pr/pull/1449](url)

2020-06-17 15:40 UTC, AutorestCI commented
/azp run automation - sdk

2020-06-18 20:06 UTC, ankisho commented
@erich-wang : Could you please review this PR?

2020-06-19 07:14 UTC, ankisho commented
Could you please help me to review this PR? @erich-wang

2020-06-19 21:23 UTC, chiragg4u requested changes
There are breaking changes in this PR. Please take one of the options
1.	confirm if there is no customers for this version
2.	update the API version
3.	follow Azure Breaking changes approval request form as defined @ [Breaking Change Process](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes)

2020-06-19 21:27 UTC, ankisho commented on specification/confluent/resource-manager/Microsoft.Confluent/preview/2020-03-01-preview/confluent.json
> -          "pattern": "^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$",
This change is required as we had discussion with ISV Confluent. We & confluent ISV are decided that phone number is not required for this RP and requested to remove this.

2020-06-19 21:28 UTC, ankisho commented
> There are breaking changes in this PR. Please take one of the options
> 
> 1. confirm if there is no customers for this version
> 2. update the API version
> 3. follow Azure Breaking changes approval request form as defined @ [Breaking Change Process](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37673/Retirements-and-Breaking-Changes)

This PR has changes related to removing phone number property. This is breaking change.
right now, this RP is in production behind hidden feature flag but it does not come under private preview yet. This RP is not being used by any of azure end-user. I'm doing internal testing using this RP and Private preview is scheduled for 31st July 2020. 
I've one more PR with similar changes with RPaaS team: https://github.com/Azure/azure-rest-api-specs-pr/pull/1449

@chiragg4u

2020-06-20 01:24 UTC, chiragg4u approved these changes
Approving based as the feature is under testing.

2020-06-20 10:05 UTC, ankisho commented
> Approving based as the feature is under testing.

thanks

2020-06-22 21:23 UTC, ankisho commented
@erich-wang : Could you please prioritize the merge of this PR? This is blocking the ARM template generation task.

2020-06-27 05:21 UTC, erich-wang approved these changes

2020-06-27 05:22 UTC, erich-wang commented
@akning-ms, could you please force merge this PR?

2020-06-27 11:58 UTC, ankisho commented
> @akning-ms, could you please force merge this PR?

@erich-wang @akning-ms : I have a question about this swagger json. we are currently on private preview stage of RP development. since this repo is a public repo, should we merge this swagger to public repo before public private stage?

2020-06-28 05:59 UTC, akning-ms commented
Hi @ankisho, Normally, for private review. you can just submit PR in azure-rest-api-specs-pr(private repo). but looks your preview version 2020-03-01-preview was already in public repo, this PR is just kind of fix. so you can continue your merge for this version if you want. so let us know your thoughts

2020-06-30 10:02 UTC, AutorestCI commented
/azp run automation - sdk

2020-06-30 10:07 UTC, ankisho commented
> Hi @ankisho, Normally, for private review. you can just submit PR in azure-rest-api-specs-pr(private repo). but looks your preview version 2020-03-01-preview was already in public repo, this PR is just kind of fix. so you can continue your merge for this version if you want. so let us know your thoughts

Hi @akning-ms , i've some updates regarding this. 
since, confluent RP is going for private preview phase now(july 2020 end). we have decided that it'd be good if we can expose the confluent RP schema spec to public from Public preview or GA phase. Hence, i've updated this PR to remove the confluent spec from this public repo. Kindly review.

2020-07-01 08:19 UTC, merged