Traffic Manager 2017-03-01 spec
Azure/azure-rest-api-specs pull request #993
Opened 2017-03-06 14:03 UTC by vladca

This checklist is used to make sure that common issues in a pull request are addressed. This will expedite the process of getting your pull request merged and avoid extra work on your part to fix issues discovered during the review process. 

### PR information
- [x ] The title of the PR is clear and informative.
- [ x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x ] Except for special cases involving multiple contributors, the PR is started from a fork of the main repository, not a branch.
- [ x] If applicable, the PR references the bug/issue that it fixes.
- [ x] Swagger files are correctly named (e.g. the `api-version` in the path should match the `api-version` in the spec).

### Quality of Swagger
- [x ] I have read the [contribution guidelines](https://github.com/Azure/azure-rest-api-specs/blob/master/.github/CONTRIBUTING.md).
- [ x] My spec meets the review criteria:
  - [ x] The spec conforms to the [Swagger 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
  - [x ] Validation errors from the [Linter extension for VS Code](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/linter.md) have all been fixed for this spec. (**Note:** for large, previously checked in specs, there will likely be many errors shown. Please contact our team so we can set a timeframe for fixing these errors if your PR is not going to address them).
  - [ x] The spec follows the patterns described in the [Swagger good patterns](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-good-patterns.md) document unless the service API makes this impossible.

2017-03-06 14:03 UTC, msftclas commented
@vladca,
Thanks for having already signed the Contribution License Agreement. Your agreement has not been validated yet. We will now review your pull request.
_Thanks,
Microsoft Pull Request Bot_

2017-03-06 14:05 UTC, vladca commented
It's not really helpful for diffing that we add a new file of each API version. Perhaps I should have committed the 2015-11-01 file in the 2017-03-01 folder and then change it to make it easier. Sorry about that. I will highlight the changes for reviewers

2017-03-06 14:06 UTC, vladca commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +    "version": "2017-03-01"
Changed

2017-03-06 14:06 UTC, vladca commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +    "/providers/Microsoft.Network/trafficManagerGeographicHierarchies/default": {
Added new

2017-03-06 14:07 UTC, vladca commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +        "geoMapping": {
Added new

2017-03-06 14:07 UTC, vladca commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +    "Region": {
Added new

2017-03-06 14:08 UTC, vladca commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +    "TrafficManagerGeographicHierarchy": {
Added new

2017-03-07 18:08 UTC, sarangan12 commented
I am starting my review of this swagger. I will update the details shortly

2017-03-07 20:29 UTC, sarangan12 requested changes

2017-03-07 20:29 UTC, sarangan12 commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +    "TrafficManagerGeographicHierarchy": {
This is a TrackedResource i.e. extends Resource (using allOf). There must be a Patch operation for this tracked resource that atleast updates the tags. Could you add it?

2017-03-07 20:29 UTC, sarangan12 commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +        "nameAvailable": {
It is not recommended to use type: boolean. Instead, the recommended approach is to use string enums with allowed set of values defined. Could you modify it?

2017-03-07 20:29 UTC, sarangan12 commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +        "operationId": "Profiles_ListAllInResourceGroup",
The recommended naming convention is "Profiles_ListByResourceGroup". Can this be changed?

2017-03-07 20:29 UTC, sarangan12 commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +        "operationId": "Endpoints_Get",
Does this name sound right? Endpoint**s**_Get or Endpoint_Get?

2017-03-07 20:29 UTC, sarangan12 commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +        "operationId": "Endpoints_CreateOrUpdate",
Same here. All the operations deal with a single endpoint. But the names are misleading as Endpoints. Can I actually create or update multiple endpoints?

2017-03-07 20:29 UTC, sarangan12 commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +        "responses": {
For all the responses, there is no default response. I agree that in the absence of a default response, autorest would use the standard cloud exception. But, we are actually recommending RPs to provide a default error response if possible. Please try to add a default response for all the responses.

2017-03-07 20:29 UTC, sarangan12 commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +             "description": ""
Empty description here and in the next response. Please fix it.

2017-03-07 20:29 UTC, sarangan12 commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +             "description": ""
WHat is the schema that is returned?

2017-03-07 20:29 UTC, sarangan12 commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +             "description": "",
Empty description

2017-03-07 20:29 UTC, sarangan12 commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +             "description": ""
Empty description and no schema????

2017-03-10 13:16 UTC, ms-alguerra commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +    "version": "2017-03-01"
I believe this is a namespace broad operation and currently this operation is implemented by NRP team (although I am not sure if they expose it in Swagger)

2017-03-10 13:19 UTC, ms-alguerra commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +    "TrafficManagerGeographicHierarchy": {
I believe this operation is exposed as proxy-only in the manifest. Will removing the allOf bit be enough to fix it?

2017-03-10 13:23 UTC, ms-alguerra commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +        "operationId": "Endpoints_Get",
I believe the reason for this is consistency with the URI naming (plural is used there across RPs):

/subscriptions/{subscriptionId}/providers/Microsoft.Network/trafficmanagerprofiles

2017-03-10 13:23 UTC, ms-alguerra commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +        "operationId": "Endpoints_CreateOrUpdate",
Same comment about consistency with URI definition

2017-03-10 13:30 UTC, ms-alguerra commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +             "description": ""
Will do

2017-03-10 13:31 UTC, ms-alguerra commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +             "description": "",
Will fix

2017-03-10 13:31 UTC, ms-alguerra commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +        "operationId": "Profiles_ListAllInResourceGroup",
Will fix

2017-03-10 13:31 UTC, ms-alguerra commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +        "nameAvailable": {
That will require server side change so it is not as straight forward. For now it is a won't fix.

2017-03-10 13:32 UTC, ms-alguerra commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +    "Resource": {
Will do

2017-03-10 13:36 UTC, ms-alguerra commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +        "responses": {
Will do using dns spec as a template.

2017-03-10 13:54 UTC, ms-alguerra commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +             "description": ""
I haven't seen many teams adding schema for delete operation results. I will add one anyways.

2017-03-13 17:03 UTC, sarangan12 commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +    "version": "2017-03-01"
No changes required here.

2017-03-13 17:04 UTC, sarangan12 commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +    "TrafficManagerGeographicHierarchy": {
Since this is a proxy resource, no change required here,

2017-03-13 18:16 UTC, vladca commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +    "TrafficManagerGeographicHierarchy": {
This is a proxy resource and read-only, PUT and PATCH are not supported on it at all

2017-03-14 11:43 UTC, vladca commented on arm-trafficmanager/2017-03-01/swagger/trafficmanager.json
> +  ],
I've verified that we don't support text/json and will remove the entry

2017-03-14 23:16 UTC, sarangan12 approved these changes

2017-03-14 23:16 UTC, merged

2017-03-14 23:20 UTC, AutorestCI commented
No modification for Ruby

2017-03-14 23:20 UTC, AutorestCI commented
No modification for Python

2017-03-14 23:20 UTC, AutorestCI commented
No modification for NodeJS